### ISSUE TITLE
The discussion of language data types needs to have a section for functions/lambdas

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1000]
AFAICT, nowhere is it documented that variables that refer to functions or lambdas support introspection. That is, attributes such as `body`, `def`, or `src`. This is a very useful introspection feature and needs to be documented. For example, from a debugging session where I was trying to understand an "arity mismatch" error involving the prompt function:

```
> put $chain:gitstatus:get-response[def]
▶ "[]{\n        echo \"running read-upto\" >>/tmp/x\n        try {\n            read-upto $rs < $state[stdout]\n        } except {\n        echo \"read-upto threw exception\" >>/tmp/x\n            put ''\n        }\n        echo \"read-upto done\" >>/tmp/x\n    }"
```

Functions and lambdas should be documented in the section about [data types](https://elv.sh/ref/language.html#data-types).

**Comment by zzamboni** [comment]
Congrats on creating the thousandth issue! 🥇

**Comment by krader1961** [comment]
Closing since commit 8988d6e5f resolves this issue. See also, issue #1122 and #1123.
