### ISSUE TITLE
Support a system-wide library search path

### ISSUE THREAD

**Issue by alerque** [elves/elvish#1004]
I'm not familiar with Elvish, but I am creating distro packages for a program that provides a completions file for it. Where should I install such a file such that it would be found at runtime by Elvish?

For example other shell provide this information like this:

```sh
$ pkg-config --variable=completionsdir bash-completion
/usr/share/bash-completion/completions

$ pkg-config --variable=completionsdir fish
/usr/local/share/fish/vendor_completions.d
```

For bash you stick a file with the same name as the program in that directory and it will start completions for all users. For fish you stick a file `program.fish` in that directory.

Zsh doesn't provide a `zsh.pc` file, you just have to know that a file called `_program` goes in `/usr/share/zsh/site-functions/`.

The upstream program I am packaging builds a `program.elv` file. Where should I put it?

Besides just answering this question directly I think it would be useful to provide a `elvish.pc` file that can be installed so that `pkg-config` can answer questions like this.

**Comment by SolitudeSF** [comment]
elvish doesn't have system-wide configuration

**Comment by alerque** [comment]
Okay. Then what is a user expected to do with a `program.elv` file in order to avail themselves of completions for *Program*?

**Comment by SolitudeSF** [comment]
import it manually. elvish has package manager that can reduce friction with installing third party modules. https://elv.sh/ref/epm.html

**Comment by zzamboni** [comment]
@alerque I guess so few programs offer Elvish integration that this has not been a high priority until now. I see two possibilities:

- Provide some instructions like those from [direnv](https://direnv.net/docs/hook.html), which help the user create a `~/.elvish/lib/direnv.elv` file, which then gets loaded by the user using `use direnv` to load the integration.
- Instruct the user to use `epm` (as mentioned by @SolitudeSF) to install an Elvish module that does the integration. This module may live in a separate or in the same repository as your main code (but the whole repo gets cloned, so a separate repo for the Elvish module might make sense).

Both of these achieve the goal of installing a library under `~/.elvish/lib/`, which is where Elvish loads libraries from.

The topic of system-wide Elvish config has come up before, there's some discussion in #383 but I don't know if this is within @xiaq's short-term plans.

**Comment by alerque** [comment]
> elvish doesn't have system-wide configuration

It should. _Not_ having any system-wide configuration is basically a rude cold shoulder to almost every *nix distro in existence. Not 100% of them, but maybe 98%. You're basically cutting yourself off at the knees by not letting distro packagers take care of all the heavy lifting to ease adoption of your program.

> import it manually

Installing things into a user's home directory is not an option for distro packages. The best we can do is echo some message or write some file in the hopes that people follow the manual instructions. It's just a bad way to fly.

I understand as developers of a system like this using distro packages doesn't fit _YOUR_ use cases at all. But if ease and breadth of adoption means anything to you think about regular user use cases ... where the more out of the box support the better the experience will be.

**Comment by xiaq** [comment]
Elvish should support a system-wide search path for libraries. XDG's system data directory can be used for this purpose.

I reworded the issue by the proposed solution.

**Comment by krader1961** [comment]
The devil is in the details. Presumably a module in the user's *~/.elvish/lib* directory takes precedence over a module of the same name in the system-wide directory when doing a simple "use mod-name". It should also be possible to force loading the system wide module. There should probably be a var added to the `builtin:` namespace that defines the root of the elvish system wide directory. Something like `$elvish-data-dir` or `$elvish-global-dir` which can be used ala "use mod-name from $elvish-global-dir". The var would also be useful to locate other system-wide file resources such as message translations (it's never too soon to think about i18n and L10n).

**Comment by alerque** [comment]
> Presumably a module in the user's _~/.elvish/lib_ directory takes precedence over a module of the same name in the system-wide directory

Yes of course, this is pretty normative. The system sets up an out-of-the-box experience that matches the rest of the system. The user gets to override that in their user config however they like.

> It should also be possible to force loading the system wide module.

I don't know about this. The system config shouldn't be able to force override the user if that's what you mean. If you just mean the user can choose to load the system module wouldn't that happen anyway if they didn't have a similar module in their user path? Of more concern might be how does a user tell the system _not_ to load something it otherwise would be default.

> There should probably be a var added to the `builtin:` namespace that defines the root of the elvish system wide directory. Something like `$elvish-data-dir` or `$elvish-global-dir` which can be used ala "use mod-name from $elvish-global-dir".

I'm not an Elvish or Go person, so these devilish details are on your folks! I just need a place to install upstream app's provided modules in distro packages!

> The var would also be useful to locate other system-wide file resources such as message translations (it's never too soon to think about i18n and L10n).

Amen to that. Shells tend to have some of the worst i18n/l10n. Some of that is legacy, some of it is the tight coupling between input commands and output content. But the sooner you start thinking about how to handle that the better.

Perhaps an issue should be opened for that right away to brainstorm.

**Comment by xiaq** [comment]
Trying to all the possible library search paths when `use`ing a module is sufficient now; flexibility can be considered when valid use cases appear.

I18n/l10n is now #1007.

**Comment by krader1961** [comment]
Note that fish also has `$fish_function_path` and `$fish_complete_path` vars that are predefined to contain the directories fish will search for autoloaded functions and completion scripts. Elvish equivalents would be useful for introspection even if they were initially marked read-only.
