### ISSUE TITLE
Reuse doc examples as unit tests

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1008]
Examples in `elvdoc` have a lot of overlap with unit tests (in some cases they are almost identical), so it makes sense to reuse them.

Not all examples are suitable for use as unit tests, there should also be some way to exclude individual examples.

Python's [doctest](https://docs.python.org/3/library/doctest.html) is a prior art.

**Comment by krader1961** [comment]
I think this is a good idea. It will help ensure the examples in the documentation reflect the actual behavior. That is, help avoid "bit rot" in the documentation. It should not be viewed as an alternative to non-documentation based unit tests. Even if a documentation example does something simple like verify `math:pow 2 inf` results in infinity being output there should still be an explicit, non documentation based, test of that behavior.

**Comment by xiaq** [comment]
Transcript tests are now enabled for most .elv files.
