### ISSUE TITLE
Allow styled display (again) in edit:complex-candidate

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#1011]
At some point the `&style` option to `edit:complex-candidate` was deleted, and the `&display` option does not allow a `ui:text` object (the output of `styled`) as its value. It would be nice to either have the `&style` option back or (preferably) allow `ui:text` objects as the value to the `&display` option.

**Comment by rsteube** [comment]
Quite desirable as colored descriptions (similar to fish) is a bit more readable.

**Comment by zzamboni** [comment]
Gentle ping on this bug. I just noticed that in fact `&display` is documented as accepting a styled object, even though it does not (https://elv.sh/ref/edit.html#editcomplex-candidate):
> The &display option controls how the candidate is shown in the UI. It can be a string or a styled text. If it is empty, $stem is used.

**Comment by rsteube** [comment]
@xiaq nice!  works fine but is there a way to interpret strings instead of splitting things up like [this](https://github.com/rsteube/carapace/pull/384/files#diff-73ad75eee819fee59957725cf0c74c7b8458cd61881bf6db1f222685738ee54dR16)?
![2022-01-03-22274_1276x773_scrot](https://user-images.githubusercontent.com/9090290/147982844-e227b273-6652-4ae1-82c2-e621881b30b9.png)

**Comment by zzamboni** [comment]
Thanks for this! Now the `comp:decorate` function supports the `&style` argument again :) https://github.com/zzamboni/elvish-completions/commit/8e27f28b183c7b2ced1a2fe01e5599b6f5050fb8

**Comment by xiaq** [comment]
> @xiaq nice! works fine but is there a way to interpret strings instead of splitting things up like [this](https://github.com/rsteube/carapace/pull/384/files#diff-73ad75eee819fee59957725cf0c74c7b8458cd61881bf6db1f222685738ee54dR16)?

Do you mean interpolating strings? That is intentionally unsupported and what you are doing looks fine to me.

**Comment by rsteube** [comment]
@xiaq  Yes,  probably better this way anyway as it saves me trouble of having to escape brackets and such.
