### ISSUE TITLE
Can't override a builtin inside a module

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1016]
Consider this:

```
⬥ cat ~/.elvish/lib/foo.elv
fn nop [@_]{ put nop! }
fn bar { nop }
⬥ use foo
⬥ foo:bar
⬥
```
 I _expected_ `foo:bar` to put `nop!`, since the declared `nop` function would override the builtin.

In the interactive namespace, this does not happen. Any function defined will override a builtin of the same name. (The given example is of course silly. But I got bit by a similar occurrence.)

**Comment by krader1961** [comment]
I can confirm this and the difference in behavior between interactive and non-interactive situations surprises me as well. Note that it does not matter if you use `use`. It is sufficient to put the relevant statements in a file named *e.elv*:

```
fn nop [@_]{ put nop! }
fn bar { put b1; resolve nop; nop; put b2 }
bar
```

Then tell elvish to run it:

```
$ elvish ./e.elv
▶ b1
▶ '$nop~'
▶ b2
```

It seems like interactive and non-interactive modes should behave the same with respect to being able to override, or not, builtin commands.

**Comment by hanche** [comment]
Thanks for checking that out. Same result with `-take e.elv`. But then you have the new `nop` in interactive use afterwards. This prompted another experiment:

```
⬥ cat > nop.elv
nop
⬥
⬥ fn nop [@_]{ put nop! }
⬥ nop
⮕ nop!
⬥ -source nop.elv
⮕ nop!
```
That's expected behaviour. So the problem is _only_ with a function being defined in a script, then used in that same script.

 So what about values in the builtin namespace other than functions?

```
⬥ put $value-out-indicator
⮕ '⮕ '
⬥ cat > x.elv
value-out-indicator = '> '
put $value-out-indicator
⬥ -source x.elv
⮕ '> '
⬥ put $value-out-indicator
> '> '
```
I'll leave the interpretation of that to others, but the third-from last line of the transcript doesn't look right to me.

At the risk of stating the obvious: It is _essential_ that scripts be able to override primitives, for otherwise, the introduction of a new primitive can easily break existing scripts out there.

**Comment by krader1961** [comment]
> At the risk of stating the obvious: It is essential that scripts be able to override primitives...

Agreed. It's useful to be able to augment builtins like `cd` via Elvish functions. It's also true that being able to do so carries some risk. In shells, like fish, where `test` is a builtin it's not unusual for people to shoot themselves in the foot by defining a `test` function that does not delegate to the builtin. Note that you can, sort of, override a builtin by assigning to its associated global var. This works:

```
nop~ = [@_]{ put nop! }
fn bar { put b1; resolve nop; nop; put b2 }
bar
```

**However,** if you add a `builtin:nop` to that lambda it creates an infinite recursion. Also, this begs the question of how to wrap builtins in other namespaces (`re:`, `math:`) while still being to delegate to the builtin. Should it even be possible to do so? And if not then how to justify special treatment of `builtin:`?

**Comment by krader1961** [comment]
This is no longer a problem. At least, I can no longer reproduce the problem so the issue should probably be closed.
