### ISSUE TITLE
Rename the `store:` module to `hist:` or fold it into `edit:`?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1020]
I was working on a trivial documentation cleanup change and noticed the `store:` module [reference](https://elv.sh/ref/store.html). It seems to me it should be named `hist:` or `history:` to better reflect the purpose of the module. The current name appears to have been influenced by the choice to use Go package [bbolt](https://pkg.go.dev/go.etcd.io/bbolt/?tab=doc) which implements a key/value "store" model.

On the other hand, note that [`edit:command-history`](https://elv.sh/ref/edit.html#editcommand-history) exists as a means of enumerating the command history. The fact the example is no longer valid isn't the point. What is important is that the `edit:` namespace provides mechanisms for interacting with the interactive command history. So, should the facilities in the `store:` module be moved to the `edit:` module? Should the `store:` module be renamed and `edit:command-history` moved into it? Status quo? Something else?

**Comment by krader1961** [comment]
From the [0.13 release notes](https://elv.sh/blog/0.13-release-notes.html):

> The `edit:history:list` function has been removed. There is no replacement yet.

See also, issue #409 and #884 which suggests @xiaq is leaning towards a new module, separate from `edit`, for managing command history. So this might be a duplicate of #884. However, I'm not a fan of calling the new module `fuser` or `fused` :smile:

**Comment by xiaq** [comment]
The intention is that it will eventually expose everything supported by the Elvish store but little work has been done.

I filed #1032 and am closing this.

**Comment by xiaq** [comment]
Re folding into `edit:`: it is now only used by the editor, but it should be possible to use the store independently of the interactive editor.
