### ISSUE TITLE
The bundled "narrow" module isn't documented

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1021]
While working on a change to fill in some gaps in the documentation I noticed that the bundled [narrow](https://github.com/elves/elvish/blob/master/pkg/eval/bundled/narrow.elv.go) module is undocumented except in the [0.10 release notes](https://elv.sh/blog/0.10-release-notes.html).

**Comment by krader1961** [comment]
The bundled [binding](https://github.com/elves/elvish/blob/master/pkg/eval/bundled/binding.elv.go) module is also undocumented.

**Comment by zzamboni** [comment]
I believe the `narrow` module is no longer supported nor necessary after https://github.com/elves/elvish/commit/cf709ddf69c1daf6df6638c3a8386b9b9c0406f0 and the introduction of `edit:listing:start-custom`.

@xiaq maybe it should be removed altogether?

**Comment by hanche** [comment]
It doesn't work, either. Maybe that's what @zzamboni meant by “no longer supported”?
```
⬥ use narrow
Exception: variable $edit:narrow:up~ not found
Traceback:
  [bundled narrow], line 113:
    -bind Up        $edit:narrow:up~
  [tty 61], line 1:
    use narrow
```

**Comment by zzamboni** [comment]
Right, I think "deprecated" was the word I was looking for 😉 I see the same error.

**Comment by zzamboni** [comment]
I think the `binding` module is the one that provides basic support for vi-like keybindings. Maybe it should be renamed?

**Comment by krader1961** [comment]
The [0.13 release notes](https://elv.sh/blog/0.13-release-notes.html) documented the removal of `edit:narrow` and `edit:-narrow-read` so it appears the bundled elvish code was simply overlooked. I'll open a PR to remove it.

That still leaves the question of what to do with the bundled `binding` module.
