### ISSUE TITLE
Document `to-lines` and `from-lines`

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1023]
The `to-lines` and `from-lines` commands are not documented. It's not clear where `from-lines` is useful but `to-lines` is needed when piping value stream output to an external command. Which, by definition, only handles a byte stream. For example,

```
> { put a b c } | to-lines | grep '[ac]'
a
c
```

Without the `to-lines` the grep will not receive any data.

**Comment by hanche** [comment]
It seems that `from-lines` can be useful if you wish to separate byte input from structured input.

⬥ { put a; echo b; put c; echo d } | { from-lines; put ---; all }
⮕ b
⮕ d
⮕ ---
⮕ a
⮕ c

**Comment by krader1961** [comment]
From the forthcoming 0.14 release notes:

> -   The `all` command no longer preserves byte inputs as is; instead it turns
>     them into values, one each line. It also accepts an optional list argument,
>     consistent with other value-taking commands.

```
~> { put a; echo b; put c; echo d } | all
▶ a
▶ b
▶ c
▶ d
```

Of course, if you don't want the values of the two streams interleaved then you would still want to use `from-lines` as in @hanche's comment.
