### ISSUE TITLE
Expand the store: module to wrap all store operations

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1032]
The `store:` module should support everything exposed by the internal [Store interface](https://github.com/elves/elvish/blob/a4875de822a23fde03a47bb86b1973bc86c999cc/pkg/store/store.go#L13). Not necessarily exactly the same functions but functionality that is on par.

**Comment by krader1961** [comment]
It is not clear why a `store:` module is warranted. The "store interface" is very low level. Also, is there any current, or anticipated, context where that API is involved in anything other than interactive commands? If no then why shouldn't a higher level abstraction to the interactive command history be implemented rather than the low level "store" API?

**Comment by xiaq** [comment]
It is not clear to me how the high-level API you have in mind you is like.

The store API is also for more than command line history.

**Comment by zzamboni** [comment]
It would be nice to re-expose the shared-var functionality.

**Comment by krader1961** [comment]
> It is not clear to me how the high-level API you have in mind you is like.

I don't know what an Elvish API for command/navigation history would look like. I've only recently started using Elvish as my primary interactive shell. But `fish`, which is what I migrated from, provided a `history` command. That made it easy to do operations I sometimes find useful such as enumerating the N-most  recent `git` commands I executed as in this example:

```
> history search -R -5 --show-time="%a %m-%d %R  " git                                                   3.3  s
Thu 05-21 15:14  git tag -l
Thu 05-21 15:14  git checkout v1.3.4
Thu 05-21 16:34  git status
Sat 05-23 21:03  history -20 git
Sat 05-23 21:04  history search -R -20 --show-time="%a %m-%d %R  " git
```

Note that I don't actually type that command. I have a function named `h` which runs that command with any optional arguments.

Also, the fish `history` command provides a mechanism for merging the global command history with the local (i.e., this session) command history. It's not entirely clear how the Elvish interactive command history works or how to achieve similar behavior.

> The store API is also for more than command line history.

Understood, but a) at the moment it appears to be used only for command and navigation history, and b) it's not clear that the internal store API is appropriate for an Elvish shared key:val store.

**Comment by krader1961** [comment]
> It would be nice to re-expose the shared-var functionality.

@zzamboni, Note that the fish shell that I switched from has a "universal" variable type that I believe is similar to the shared var functionality you desire. In the three years I contributed to the fish shell I observed that shared/universal shell vars caused far more problems than they solved. That does not mean a shared var implementation in Elvish via a `store:` module (i.e., API) would suffer the same problems. Only that I've also used several programming languages/environments, such as [MUMPS](https://en.wikipedia.org/wiki/MUMPS), that provided a shared store mechanism. I advise against implementing anything like the mechanism provided by those languages. Which is to say this requires a lot of careful thought. For example, what if the backing file for the shared store is on a shared/network file system? What tools should be provided to examine or manipulate the shared store? What is a transaction and should it be implicit or explicit? ACID? Etcetera.

**Comment by zzamboni** [comment]
@krader1961 fully agree with you - shared storage mechanisms are not easy to get right.

Still, it would be nice if Elvish had a built-in mechanism for persisting simple pieces data, without a module having to figure out how and where to store it :)
