### ISSUE TITLE
The interactive editor is not aware you can run `builtin:cd` without doing `use builtin`

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1044]
I was reviewing commit 8af76083 which implies you must do `use builtin` to explicitly use it as a namespace prefix. Which prompted me to do an experiment. This works and changes my CWD to */tmp*:

```
$ elvish -norc
$ builtin:cd /tmp
```

However, the `builtin:cd` command was colored red by the editor which suggests it is not a valid command. Once you do `use builtin` that command is colored green. The `edit` module is aware that the `builtin` module is consulted implicitly when resolving commands but is not aware that using it as an explicit namespace prefix works even if `use builtin` has not been run.

**Comment by krader1961** [comment]
My opinion is that the current ability to do `builtin:cd` without first doing `use builtin` is a misfeature. Any explicit use of the `builtin:` namespace should require using it. Only unqualified builtin references should be allowed without `use builtin`.

**Comment by xiaq** [comment]
The highlighting issue has been fixed and I filed #1227 for removing support for referencing variables in `builtin` without `use builtin`.
