### ISSUE TITLE
Documenting unreleased significant changes

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1045]
I noticed that the recently introduced `order` command was not documented in the pending [0.14.0 release notes](https://github.com/elves/elvish/blob/master/website/blog/0.14.0-release-notes.md). There are probably other changes that also need to be documented in that document which are missing. Would it make sense to require every significant user visible change to include an update to that document? That would help reduce the likelihood of a significant user visible change not being documented. Too, it would make it easier for people building from the `master` branch to review what is in the pipeline. At least if the blog article for the next release was also included in the *website/blog/index.toml* document.

**Comment by krader1961** [comment]
Note that this issue is really about establishing a pattern wherein significant user visible changes are not merged until they include an appropriate update to the pending blog article for the next minor or major release. This is not about `order` not being in the 0.14.0 release notes blog article. That simply happened to be the trigger that caused me to open this issue.

**Comment by xiaq** [comment]
Yes, that's my intention, but I keep forgetting doing that.

I documented the expectation of updating the release notes in the contributor's manual.

**Comment by xiaq** [comment]
Closing this now that `order` was added to the release notes and the expectation is now also documented.
