### ISSUE TITLE
Document ns

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1046]
The `ns` command is currently undocumented.

As far as I understand it, it takes one argument (a map) and it creates an anonymous namespace implementing the same mapping. This can then be assigned to `name:` and then used as any other namespace.

Example:
```
⬥ fn store [&value=$nil]{
  fn get { put $value }
  fn set [v]{ value = $v }
  ns [&get~=$get~ &set~=$set~]
  }
⬥ foo: = (store)
⬥ foo:get
⮕ $nil
⬥ foo:set thing
⬥ foo:get
⮕ thing
```

Another example:
```
⬥ fn foo [nsp:]{ nsp:bar }
⬥ foo (ns [&bar~={ put foobar }])
⮕ foobar
```

Evidently, some restrictions apply:
```
⬥ ns [&$true=T]
Exception: key must be string
[tty 35], line 1: ns [&$true=T]
```

**Comment by xiaq** [comment]
This is now documented: https://elv.sh/ref/builtin.html#ns
