### ISSUE TITLE
Search command history using token split

### ISSUE THREAD

**Issue by href** [elves/elvish#1051]
One thing I miss in elvish is a way to search through my history in a more fuzzy fashion (like fzf).

Take the following command history:
```
git clone foobar
git -q clone baz
```

If I search for `git clone`, only the first item will be in the results list. Instead, I would much prefer it if my input was split into tokens, which would then be evaluated with a logical `and`.

I'd like it if `git clone` would return both commands, because each command has both `git` *and* `clone` in its string. That of course implies that my input would be split into tokens by whitespace.

Can this be accomplished at the moment (with some script or so), or is this something that could be added? I almost never want to search for explicit white-space, so the current system to me is often less then ideal.

**Comment by krader1961** [comment]
After switching from fish to elvish a few weeks ago I found myself wishing the mode entered by `edit:histlist:start` (as bound to [ctrl-R]) would behave as @href proposes. I had never used [ctrl-R] when my primary interactive shells were ksh and then zsh. When I switched to fish approximately five years ago it didn't support [ctrl-R] and its native fuzzy command matching was good enough for me so I never explored how [ctrl-R] works in bash and zsh.

Now that I'm using elvish I find, like @href, that the behavior of the [ctrl-R] binding is suboptimal. It is better than the bash native behavior but still lacking. I too wish that it had fuzzy matching behavior. Exactly how it should behave is an open question. What if the user types non-alphanum chars? Should that trigger switching to a literal match? Should it employ a fuzzy match using tokenizing based on the recently documented ["small words"](https://elv.sh/ref/edit.html#word-types) concept? Something else?

P.S., The current behavior is not documented. Specifically with respect to the bindings for toggling case sensitivity or deduplication of entries. It's also not documented what deduplication does and why disabling it should be an option. My investigation suggests it should always be enabled and disabling deduplication by pressing [ctrl-D] is not useful. The sole point of disabling duplication detection appears to be to make it clear in the [ctrl-R] list that a given statement matching what has been typed  has been executed more than once. That is not useful, IMHO.

**Comment by krader1961** [comment]
See also the other issues that mention fzf behavior: https://github.com/elves/elvish/issues?q=is%3Aissue+fzf+

**Comment by href** [comment]
I got pretty close to the behaviour I want with `fzf` and a shortcut:

```
fn unique {
    perl -ne'print unless $h{$_}++' /dev/stdin
}

fn history {
    edit:current-command = (all [(edit:command-history)] | each [cmd]{ print $cmd[cmd]"\n" } | unique | fzf --no-sort --tac)
}

edit:insert:binding[Ctrl-R] = {
    history </dev/tty </dev/tty >/dev/tty 2>&1
}
```

The only thing that's missing: The order of the command history is from old to new. Because I like to have newer commands before older commands I need to revert that order with `--tac` in fzf.

This leads to lots of redraws in the UI before the whole command list is loaded (something that does not happen without `--tac`).

It would be nice if the command history could also be printed in inverse order, maybe with a flag. Is that possible?

**Comment by zzamboni** [comment]
@href that's pretty nice! I think you can simplify the code a bit, I got the same effect with the following code (e.g. you don't need to call `perl`, and you had a double input redirect in the call to `history`):
```
fn history {
  h=[&]
  err = ?(edit:current-command = (edit:command-history | each [cmd]{
        if (not (has-key $h $cmd[cmd])) { print $cmd[cmd]"\000" }
  } | fzf --no-sort --tac --read0))
}

edit:insert:binding[Ctrl-R] = { history </dev/tty >/dev/tty 2>&1 }
```

**Comment by zzamboni** [comment]
BTW I tried using `order` to reverse the order, which works but then it takes a while to start, particularly if you have a very long command history like I do :)

**Comment by href** [comment]
Thanks. Saw the same effect with my history :)

Also I think your version doesn't sort out duplicates I think? The hashmap is never updated. Incidentally I did first try it with a hashmap, but found the perl appraoch to be significantly faster.

**Comment by zzamboni** [comment]
Duh - I had forgotten to update the hash :) I have edited my comment accordingly.

And Wow, you are right about the perl version being faster. By a lot:
```
[~]=> -time { private:get_history_perl > /dev/null }
256.395136ms
[~]=> -time { private:get_history_elvish > /dev/null }
1.828225893s
```

BTW is your call to perl missing a `-0` to use the null separators?

Here's my current code:

```
fn get_history_elvish {
  h = [&]
  edit:command-history |
      each [cmd]{
        if (not (has-key $h $cmd[cmd])) {
          print $cmd[cmd]"\000"
          h[$cmd[cmd]] = $true
        }
  }
}

fn get_history_perl {
  edit:command-history | each [cmd]{
        print $cmd[cmd]"\000"
    } | perl -n0e'print unless $h{$_}++'
}

fn history [&hist_fn=$get_history_elvish~]{
  err = ?(edit:current-command = ($hist_fn | fzf --no-sort --tac --read0))
}

edit:insert:binding[Ctrl-R] = { history </dev/tty >/dev/tty 2>&1 }
```

**Comment by href** [comment]
Yeah, sorry I forgot to add the `-0` on GitHub.

**Comment by xiaq** [comment]
Yes, it will be desirable to change the default matching algorithm to match each token individually.

Verbatim matching can be still be done by quoting the text to match, akin to how search engines work.

**Comment by xiaq** [comment]
It'd be best to reuse Elvish's expression syntax for this.

* Multiple expressions are implicitly AND-ed: `foo bar` matches items that include both `foo` and `bar`.

* To include whitespaces in the match, just quote it: `"foo bar"` matches items that include `foo bar`.

* In future, when the command history gets more metadata, use the key-value syntax to match metadata fields: `&timestamp=2021-01-01` matches items from 2021-01-01.
