### ISSUE TITLE
Implement edit:key-reader to show what a keypress sends and how to bind it

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1058]
There was a short discussion on Gitter/IRC/IM today about figuring out how to bind a key to a specific action. I pointed out that the fish shell provides the `fish_key_reader` utility which will show the chars received in response to a key press and **more importantly** the appropriate statement to bind that key to an action. It would be nice if elvish provided similar functionality. In fact, I think we can do slightly better by making it a builtin of the `edit:` namespace which shows any existing binding as well as the statement required to create a binding to that key. @hanche proposed naming the command `edit:key-reader`.

P.S., The discussion began because the delete/backspace key sent the "del" (0x7F) char and it wasn't obvious whether the symbolic name `Delete` or `Backspace` should be used in binding the key. The symbolic names are not documented. While most of them are, more or less, self-evident their meanings need to be documented. Especially since some, like `Backspace` and `Delete`, do not have a self-evident meaning.

**Comment by xiaq** [comment]
Closing in favor of #1180.
