### ISSUE TITLE
New hook `edit:after-prompt`

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#1060]
The existing `edit:before-readline` and `edit:after-readline` are executed at the very beginning of a new command line (before the prompt), and after the user presses Enter on a complete command to execute it. I would like to propose a new hook `edit:after-prompt` which gets executed after the prompt is drawn and before the start of the command:
```
[before-readline]prompt[after-prompt] command
[after-readline]
```
This can be used to, for example, emit special escape sequences to notify the terminal emulator about where a new command starts (e.g. iTerm2).

This can be achieved at the moment by extending the prompt function itself, but I think a hook would have the following advantages:

- Guarantee that the hooks are executed only once, regardless of how many times the prompt is updated. This is at the moment hard to do, requiring logic in both `edit:prompt` and `edit:after-readline` to keep state and determine when the prompt function is being called for the first time.
- Makes it easier for modules to add code to the hook without having to redefine the `edit:prompt` function, potentially conflicting with themes, other modules, or user configuration.
- Is in line with existing `edit:` hooks.

**Comment by krader1961** [comment]
> This can be used to, for example, emit special escape sequences to notify the terminal emulator about where a new command starts (e.g. iTerm2).

Doesn't the zero-width styled segment proposal in #1039 address this need? If the prompt width changes, thus changing where the command begins, and the proposed `after-prompt` isn't run again wouldn't that confuse the terminal?

**Comment by zzamboni** [comment]
@krader1961 in this particular case, you are correct. In fact, at the moment this is how [iterm2.elv](https://github.com/zzamboni/elvish-modules/blob/master/iterm2.org) works.

(side comment: unfortunately iTerm2 does not seem to handle redrawn prompts gracefully, and even if the codes are re-emitted, it still captures the command wrong if the prompt changes length in the middle of typing. But this is an iTerm2 bug and not related to Evish)

Even if the hook gets executed when the prompt is redrawn (maybe: re-execute it only when the prompt length changes?), I still think it's more elegant for modules to add code to a hook variable than to have to modify the prompt function.

**Comment by zzamboni** [comment]
One more point for this: iTerm2 now supports (at my request, see https://gitlab.com/gnachman/iterm2/-/issues/8996) changing the length of the prompt on the fly. However, this does not work at the moment due to a combination of factors:

- Prompt functions cannot emit raw escape codes at the moment (see #1038). Because of this, the "end of prompt" codes for iTerm have to be printed with a redirect to `/dev/tty` so that they get to iTerm2.
- However, when refreshing the prompt as the user types the command, the prompt function is called without moving the cursor from its current position (e.g. at the end of the command the user is typing), before redrawing it in the correct position.

This means that with the current  behavior, and in the latest iTerm2 nightly, https://github.com/zzamboni/elvish-modules/blob/master/iterm2.org no longer captures the commands correctly.

Having a hook that get executed after the prompt is drawn (therefore the cursor will be in the correct position) would solve this problem.

@xiaq any thoughts?

**Comment by xiaq** [comment]
I don't see why zero-width segment doesn't solve your problem - can you elaborate? The purpose of zero-width segment is to have a safe-ish API for putting arbitrary escape sequences into the prompt, as long as they don't move the cursor.

The idea of a post-prompt hook doesn't fit into how Elvish's rendering system works. It assumes that at each refresh, Elvish first writes the prompt, and then the rest of the UI. That is not the case; Elvish renders everything first onto an internal buffer, and then compares the buffer with the current state, and updates whatever has changed. You cannot hook procedures into this process, but you can add zero-width segments to the internal buffer.

**Comment by zzamboni** [comment]
@xiaq thanks for the explanation. I think zero-width segments solve the problem of emitting the escape codes. However, this still requires modifying the prompt function to print those segments. In the case of an external library like `iterm2`, this is possible but adds the "complication" (in quotes because it's not really a big problem) of making sure you call the `iterm2:init` function *after* your prompt function has been initialized.

So, assuming the existence of zero-width segments my argument for the hook is one of user/developer experience 🙂 

How about this: whatever is output by the "post-prompt" hook functions simply gets appended to the output from `edit:prompt`, and rendered exactly as if the prompt function had produced that output. I believe this would respect the rendering model you explained, while still allowing third-party libraries to add output into the prompt.

Given that so far I know of exactly one use case for a library that would like to do this (`iterm2.elv`), my desired priority would be to have the zero-width segment from #1039. As soon as the next version of iTerm2 is released, the `iterm2` module will break without the ability to emit the escape codes as part of the prompt function.

**Comment by krader1961** [comment]
Rather than implement this hook perhaps `edit:prompt` and `edit:rprompt` should support being defined in terms of...

1) A simple string for a purely static prompt. For example, `edit:prompt = 'elvish > '` rather than `edit:prompt = []{ print 'elvish > ' }`. This isn't really needed but would be trivial to support as a convenience and would be useful in writing interactive unit tests.

1) A single lambda that emits a sequence of simple strings or styled segments. This is the current behavior.

1) A list of lambdas each of which emits a sequence of simple strings or styled segments. This would be roughly equivalent to the original `edit:after-prompt` proposal but folding the existing .

In each of the above a simple string is interpreted so that SGR sequences are turned into the equivalent styled segments just like today. If you don't want that interpretation to occur you have to wrap the bytes in a zero-width segment (see issue #1039).

Augmenting the current prompt variables in this fashion would obviate the need to introduce yet another variable and having to explain how `edit:prompt` and `edit:after-prompt` interact. It also means we don't need to also introduce a `edit:after-rprompt` for symmetry. And most importantly, this makes it easier (or at least clearer) to build a prompt using a chained sequence of discrete functions. **In fact, it would allow elvish to execute each lambda in the list of functions that compose the prompt to be executed in parallel.**

**Comment by zzamboni** [comment]
@krader1961 I like this idea, it generalizes the concept quite nicely.

@xiaq I'd love to see what you think about this.

In the context of iTerm2 terminal integration, the following issues continue to be highest priority for me:

- #1039 would enable proper support for variable-length prompts in Elvish when capturing commands;
- #1059 so that exit status can be reported correctly

**Comment by zzamboni** [comment]
@krader1961 after some more thought, I'm not so sure your proposal has the same benefit as having a separate variable - namely, that the hooks can be set or modified without messing with the prompt definition. At the moment, adding behavior after the prompt function requires the following steps (as currently done by [iterm2.elv](https://github.com/zzamboni/elvish-modules/blob/master/iterm2.org#shell-integration):

1. Save the current value of `$edit:prompt` in a variable
2. Redefine `$edit:prompt` as a function that calls the original (as saved), followed by any desired custom behavior.

With a separate variable `$edit:after-prompt`, this gets reduces to a single step:

1. Add the extra behavior in `$edit:after-prompt`.

With the generalized idea you proposed, it's actually more complicated:

1. If `$edit:prompt` is a string, convert it to a function that prints the string.
2. If `$edit:prompt` is a function, convert it to a list which contains the function.
3. Add the new elements to the end of the list.

I still think it's potentially a nice idea, but it doesn't solve the same problem ;)

**Comment by krader1961** [comment]
If the user wants to use any plugins that extend the prompt it is the user's responsibility to use the third form: a list of lambdas. If the user defines the prompt as a simple string or lambda it is not the responsibility of a prompt plugin to transform it into a list. In that case the user accepts that they cannot use a plugin to extend their prompt.

> Furthermore, having a separate variable makes it easy to modify the "extra behavior", which is not easy to do in any of the other two schemes (i.e. you don't know where the extra stuff starts).

I can't grok that. Anyone who wants to take advantage of plugins like your iTerm support module has to use the third form: a list of lambdas. In which case the plugin just does `edit:prompt = [$@edit:prompt plugin-fn~]`. Too, your `edit:after-prompt` can only be used for functions that promise not to change the visible prompt and are thus, implicitly, always treated as zero-width segments.

**Comment by zzamboni** [comment]
I agree, in any case it's the user's responsibility to do the right thing.

In any case, as I said before, I think the most useful feature will be the zero-width segment ability.

**Comment by xiaq** [comment]
I am leaning towards rejecting this proposal.

As far as I can see, there is really just one case for this after-prompt hook now: inserting iTerm's "prompt ends here" escape sequences. The current approach of wrapping `edit:prompt` feels slightly hacky, but it isn't too bad. This proposal would be more compelling if there are more use cases for it.

At the same time, prompt "frameworks" will have their own mechanism of defining prompts in terms of an array *anyway*, rendering this API unnecessary.

**Comment by zzamboni** [comment]
@xiaq this is fine with me, I agree it's a fairly narrow use case.

I'm closing this, feel free to focus on #1039 😉
