### ISSUE TITLE
Improve unit test coverage to 85% before 0.15.0 release

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1062]

**Comment by xiaq** [comment]
Test coverage has not reached 85% yet but 0.15.0 is scheduled to be released soon, so I'm retrospectively amending the scope and keeping this closed.

**Comment by krader1961** [comment]
FWIW, I don't understand why the title of this issue was changed. As I write this the current master branch (at commit 141a6d49558e663f976f6154effb4a6e51c7c93d) has 87.6% coverage as reported by `go tool cover -func=cover`. It is true that https://codecov.io/gh/elves/elvish reports 82.2% coverage, but that is because it incorrectly handles statements such as `import` and `var`; i.e., it considers such statements as not covered even though the compiler ensures they are "executed" at compilation time.

**Comment by xiaq** [comment]
Hmm there is indeed a weird discrepancy, but re

> it incorrectly handles statements such as import and var; i.e., it considers such statements as not covered even though the compiler ensures they are "executed" at compilation time.

I wonder how did you draw that conclusion? If you open any file in codecov the `import` lines are shown without any coloring, indicating that it is ignored for coverage; see this one for example: https://codecov.io/gh/elves/elvish/src/master/pkg/tt/tt.go

If import lines are always considered uncovered, no file with an import line would have 100% coverage in codecov; yet this file shows 100% coverage.

**Comment by xiaq** [comment]
It seems that the difference is in how `if` branches that were never executed is counted. Codecov will not only count the branch body as uncovered, but also the branch condition; for example here: https://codecov.io/gh/elves/elvish/src/master/pkg/cli/addons/histwalk/histwalk.go#L119. Codecov shows the line containing the branch condition as yellow and doesn't consider it to be covered in its coverage calculation.

Indeed, if I manually include the "yellow" lines in the coverage calculation I get a number much closer to the 87.6% that `go tool cover` outputs. Currently for all of `pkg/`, Codecov is showing:

* 11,193 total lines
* 9,201 green lines (fully covered)
* 434 yellow lines (condition lines that never evaluate to `true`)

The coverage number codecov reports by default only includes green lines, which is 9201/11193 = 82.2%. If I include the yellow lines, it's (9201+434)/11193 = 86.1%. It's still not exactly 87.6% but the difference is much smaller now.

Overall I find codecov's more strict calculation to be better. If a branch condition never evaluates to `true`, the condition line should indeed be considered uncovered even if it is executed.

**Comment by xiaq** [comment]
It seems that the remaining difference can be accounted for by two factors:

* Codecov shows aggregated coverage from 3 OS'es, Linux, macOS and Windows, whereas a local test coverage report will only include one OS. One of the few files in the Elvish codebase that has 0 coverage is a Windows-specific file (https://codecov.io/gh/elves/elvish/src/master/pkg/cli/term/reader_windows.go).

* The `.codecov.yml` file used to exclude some files. I have removed those excludes now that cross-package coverages are included.

**Comment by xiaq** [comment]
Removing the excludes actually made the coverage a lot worse, so I added them back. :)
