### ISSUE TITLE
Improve the printing of “job job … & finished”

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1067]
In the below transcript, I had finished typing `echo ` (including the trailing space) when the background sleep finished. Then I typed `foo`.

```
⬥ elvish -norc
~> sleep 1 &
~> echo job sleep 1 & finished
        foo
```

Note that the prompt and the first part of the command are not replicated, but otherwise the `foo` is properly aligned. I think there is much room for improvement there.

Also, if some other job is running in the foreground, messages about background jobs can mess up the output of the foreground job. Personally, I would prefer to wait for the prompt before receiving such notices. But on this, others might disagree, so perhaps make that an option.

These are my suggestions, then:

1. Create a flag, say `$bg-job-notifications-wait-for-prompt` (or better, find a shorter name). If the flag is set, notifications about background jobs are delayed until the current foreground job is finished, and printed just before the prompt is printed.

2. In any case, if a background job notification arrives while the editor is active, print the notification _above_ the prompt, in the same manner as happens with any output from functions called from within the editor.

**Comment by krader1961** [comment]
> I would prefer to wait for the prompt before receiving such notices. But on this, others might disagree, so perhaps make that an option.

I don't think this should be configurable. Printing information about the state of background jobs should only be done when a new prompt is shown -- not when a prompt is updated while typing a command. I know that bash has `set -b` to display the background status immediately when it changes. That is a misfeature in my opinion. It's also a feature that only made sense when serial terminals (e.g., a real VT100) were the most common means of interacting with an OS. I don't see any reason to implement features that were only relevant more than a decade, if not two decades, ago.

**Comment by hanche** [comment]
At least we agree that background state information should not be printed when a job is running in the foreground! And I am perfectly happy with not having that being configurable. However, I think having such information printed while you're typing a command is okay, _provided_ the information appears above the prompt, with the prompt, current command, and cursor position being properly maintained, of course. That might be a bit disruptive if you're in the middle of typing a complex command, but I think I would prefer that to having to wait for the next prompt. The mechanism for doing this is already there: Consider what happens if you run `echo foo` in the minibuffer.

In fact, I would propose a bolder approach: Expose an interface to the user, let's call it `notify` for the sake of discussion (probably not the best name): This function would queue its argument(s) in a notification queue, to be printed before the next prompt. Optionally(?), if the user is editing a command while this is called (in a different thread presumably), the notification could be inserted above the prompt, say, with the string `[notification]` prepended. Then we could add a hook to be called when the status of background changes. The default value of the hook would create a suitable message and call `notify`.

This may seem overkill, but I think it could be useful if you have a long running elvish function running in the background. It could use this mechanism to inform the user of important event.

**Comment by krader1961** [comment]
@hanche, The problem as I see it is job status changes are asynchronous versus displaying output synchronously as a result of what I'm typing; e.g., in the mini buffer. If the job status change is displayed a millisecond before I press [enter] it is likely I won't see or grok the job notification. What you're proposing would require an explicit acknowledgement of the notification AFAICT to be reliable. The core problem is that whatever command I'm about to execute is likely to replace the job notification with other text. Consider just running an external editor, or a command like `cat a-file`.

Obviously displaying the job notification only when a new prompt is about to be written doesn't 100% eliminate the problem but it should be good enough. It is very unlikely that after running a command and being presented with a new prompt anyone will execute a new command that mutates the screen before they can read the job notification that is displayed just above the new prompt.

**Comment by xiaq** [comment]
There are two cases:

* Background job completes while a foreground job is running. I think the most reasonable behavior is to print this only at the next prompt.

* Background job completes while the editor is active. Elvish in fact has a [notification mechanism](https://github.com/elves/elvish/blob/d27cee0724a0cdf3ddc95beb721853daa214dd99/pkg/cli/app.go#L40) exactly cases like this.

Moreover, this message should probably be always hidden in non-interactive mode.
