### ISSUE TITLE
Missing parse-time deprecation warnings for imported modules

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1072]
When a file uses a trailing backslash for continuation in a file and that file is executed via `-take` or `use`, no deprecation warning occurs, even if the shell was run with `-show-deprecations`. The warning is shown in interactive use, however.

**Comment by xiaq** [comment]
In fact all the compile-time deprecation warnings are missing too...

**Comment by xiaq** [comment]
Scratch that; compile-time deprecation still work. The original title was correct...

**Comment by xiaq** [comment]
The fix is cherry-picked onto the `v0.14-release` branch and will appear in the bugfix release v0.14.1.
