### ISSUE TITLE
Should `re` module document using `(?i)` for case-insensitive matches?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1090]
I found myself converting this command from my pre-elvish login shell:

```
expr "$LANG" : ".*\.[Uu][Tt][Ff].*"
```

Looking at the [`re` module](http://elv.sh/ref/re.html) documentation I didn't see an obvious way to rewrite that without the character classes so that a case-insensitive match would still occur. It took me a few minutes to find that the Go regex engine supports `(?i)` as a regex flag to cause case-insensitive matches. I think case-insensitive matches are needed often enough to warrant explicit mention of how to do so in the Elvish `re` module documentation. That is, without requiring the user to dig through the Go regex documentation. Also, the phrase "syntax of regular expressions" in the `re` module documentation should be a link to https://godoc.org/regexp/syntax. Or, possibly https://github.com/google/re2/wiki/Syntax but that seems to be less useful since it is harder to read.

**Comment by xiaq** [comment]
I'll change the link to point to regexp/syntax instead.
