### ISSUE TITLE
Magic var $-exports- is undocumented

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1110]
The magic `$-exports-` var is mentioned in the [0.12 release notes](https://elv.sh/blog/0.12-release-notes.html) but is otherwise undocumented. The documentation of this var should note that it can only be used in *~/.elvish/rc.elv*. Note that `put $-exports-` from an interactive prompt will fail while the same statement in *~/.elvish/rc.elv* will succeed. Also, the var is a map where each key should be a string ending in a tilde that represents the command to be made available as if it were a builtin and each value is the lambda/function to run when the key is used as a command. For example, if you put this in your *~/.elvish/rc.elv*:

```
fn hello { put hello }
-exports- = [&a1~=$hello~ &b2~=$hello~]
```

You can then use all three commands interactively:

```
> hello
▶ hello
> a1
▶ hello
> b2
▶ hello
> resolve b2
▶ '$b2~'
```

**Comment by hanche** [comment]
You can export non-functions using this mechanism too. For example, I have code in my `tc.elv` that checks if we are running under iTerm, and if so does

```
use iterm
-exports-[iterm:] = $iterm:
```
Works like a charm.

**Comment by krader1961** [comment]
@hanche, Good point that the exports map can contain types other than functions; such as variables. I explicitly excluded non-functions in my opening comment because it seemed to me the primary, and possibly sole, purpose of the `$-exports-` mechanism was to support introducing functions defined in modules into the interactive namespace. If that is true then the implementation should constrain its input to that use case. If that is false then the documentation needs to explain how non-function types, such as a namespace reference, are handled and why they might be useful. 

Having said that, @hanche, I don't grok the point of your example. The `-exports-` assignment doesn't seem to serve any purpose beyond what the `use iterm` serves. Is that leftover from an older version of Elvish or am I missing the point of your example?

**Comment by hanche** [comment]
The point of my example is this: The `use` statement is conditional: `if (…) { use iterm; … }`. Due to lexical scoping, `iterm:` is confined within the function body of the conditional.

**Comment by krader1961** [comment]
@hanche, I just opened #1116 complaining that the following does not make the "unix" namespace available interactively before I read your latest comment:

```
if $platform:is-unix {
  use unix
  unix:umask = 0o027
}
```

I can confirm that adding `-exports-[unix:] = $unix:` to that block "fixes" my issue. TBD is whether that is the preferable mechanism for resolving that issue. Regardless, your example should be supported and documented as such.

**Comment by krader1961** [comment]
Also, note that the example by @hanche fails if `$-export-` has not been explicitly populated, with at a minimum an empty map, by the user's init scripts. You'll see a "compilation error: variable $-exports- not found" exception in that case. The code that implements assigning to `-exports-` should probably silently instantiate an empty map if the var has not previously been assigned a map.

Also, doing `-exports- = $true` in my *~/.elvish/rc.elv* results in the cryptic `Exception: assoc is not supported` exception.

**Comment by krader1961** [comment]
I'm closing this issue since the recent deprecation of `$-exports-` in the upcoming 0.15 release, in favor of the new `edit:add-var` and `edit:add-vars` commands, makes this issue moot.
