### ISSUE TITLE
Document lvalue

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1112]
There are some error messages that reference the concept of lvalue, but it is not documented yet.

Also document the possible syntax of lvalues. Other than a lone variable name (`foo`) or rest variable (`@foo`), it is also possible to use a braced list in the position of lvalues (e.g. `{foo bar}`).

**Comment by krader1961** [comment]
A comment I made regarding existing Elvish exceptions that use the term "lvalue" resulted in this issue being opened. Nonetheless, I realize that documenting this term (or an equivalent) is going to be challenging. Results of a "google" search include useless (the [Wikipedia](https://en.wikipedia.org/wiki/Value_(computer_science)#lrvalue) article) and tautological (an [IBM support article](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbclx01/lvalue.htm)) definitions. The only decent definitions I found were all C/C++ specific such as [this one](https://www.geeksforgeeks.org/lvalue-and-rvalue-in-c-language/).

**Comment by xiaq** [comment]
As of 46dedae9fa9a9aadd9bd4ed1d68befc23c0a33b4, lvalue is documented as part of [ordinary assignment](https://elv.sh/ref/language.html#ordinary-assignment).
