### ISSUE TITLE
`eval` command behavior and documentation

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1115]
The [documentation](https://elv.sh/ref/builtin.html#eval) for the recently introduced `eval` command would benefit from some changes. First, it needs an example for how it can be used as a replacement for the `-source` command. Second, the note that it "cannot affect the current namespace" is true but misleading as it can affect the namespace specified by the `&ns` option which many people will consider the "current namespace" for the statements being `eval`'d.

I have a util.elv module. It does not contain a `x` variable. Yet I can introduce a `x` var into the `util:` namespace using `eval`:

```
> put $util:x
Exception: variable $util:x not found
[tty 1], line 1: put $util:x
> eval &ns=$util: 'put $x'
Exception: compilation error: variable $x not found
[eval 6], line 1: put $x
[tty 10], line 1: eval &ns=$util: 'put $x'
> eval &ns=$util: 'x = wtf; put $x'
▶ wtf
> eval &ns=$util: 'put $x'
▶ wtf
> put $util:x
▶ wtf
```

It is true I can't embed that eval into a function in the `util` module since it will complain during compilation (i.e., when doing `use`) that  either `$util:` or `$x` does not exist depending on what I try to do. Also, and perhaps more confusingly, I can't simply do `util:x = wtf` at an interactive prompt even though doing this indirectly via `eval` (see above) does work:

```
> util:x = wtf
Exception: new variables can only be created in local scope
[tty 4], line 1: util:x = wtf
```

**Comment by xiaq** [comment]
It seems that the issues have been addressed now, closing.
