### ISSUE TITLE
How to conditionally `use` a module interactively

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1116]
I like to automatically `use` all the modules I'm likely to need in my interactive Elvish shells. For example, from my *~/.elvish/rc.elv*:

```
# Standard elvish modules we always want to be readily available.
use builtin
use epm
use math
use platform
use re
use readline-binding
use str
use unix
```

The problem is the `use unix` fails on Windows. If I instead do this then the unix namespace isn't available until I type `use unix` interactively:

```
if $platform:is-unix {
  use unix
  unix:umask = 0o027
}
```

It would be nice if I could do something like

a) `use &ignore-missing unix`, or

b) `use &up unix` to force the import to occur in the outer scope.

**Comment by krader1961** [comment]
See this [comment](https://github.com/elves/elvish/issues/1110#issuecomment-675296985) regarding how to use the undocumented `-exports-` variable to provide the behavior I expect. TBD is whether that is the preferred means of resolving this issue even if the `-exports-` mechanism is documented.

**Comment by hanche** [comment]
FWIW, I just realised that the following works:
`nop (and $platform:is-unix (use unix))`
The extra `nop` is just to suppress the resulting `$true` value.

**Comment by krader1961** [comment]
That is clever @hanche. It almost rises to the level of being an entry in a obfuscated Elvish contest :smile: Which is to say, if anyone were to use it I would hope they include a clarifying comment.

**Comment by krader1961** [comment]
The straightforward solution to my question, now that `edit:add-var` is available, is adding this to my `rc.elv`:

```
# This will conditionally import the `unix` module into the interactive
# namespace so that we don't get an exception when running on MS Windows
# (which doesn't provide the builtin `unix` module).
if $platform:is-unix {
  use unix
  edit:add-var unix: $unix:
}
```

TBD is how to document this so it is discoverable.
