### ISSUE TITLE
lazy loading for command completion scripts

### ISSUE THREAD

**Issue by rsteube** [elves/elvish#1130]
With an increasing amount of completion scripts (`edit:completion:arg-completer`) shell startup time is affected considerably.
ZSH solved this by [only looking at the first line](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files) and loading the file when needed (first `TAB`).

Is there a similar concept for elvish?

**Comment by zzamboni** [comment]
I don't think this exists out of the box, but it should be possible to build it into the completer function and read the appropriate files automatically. One impediment is that there is no convention for where the completion files would be stored, so that would need to be agreed upon.

**Comment by zzamboni** [comment]
(Note: the new `use-mod` command would be perfect for dynamically loading completions)

**Comment by krader1961** [comment]
The fish shell has a notion of auto-loaded functions and completion scripts. It's not clear how that would work for functions given the Elvish concept of modules, or even that auto-loading modules/functions is needed. But as the number of completion scripts increases it becomes increasingly important to defer loading them until needed.

**Comment by rsteube** [comment]
related #1004

**Comment by rsteube** [comment]
setting a tempory completion function that replaces itself with the correct completion and invokes it works for me (15secs down to more or less instant):
```elvish
carapace --list | each [c]{
    edit:completion:arg-completer[$c] = [@arg]{
        carapace $c > /tmp/carapace_$c; -source /tmp/carapace_$c
        $edit:completion:arg-completer[$c] $@arg
    }
}
```

**Comment by zzamboni** [comment]
Nice.

What is `carapace`?

**Comment by rsteube** [comment]
https://github.com/rsteube/carapace-bin

did some work on a completion script generator for [lab](https://github.com/zaquestion/lab) and used that to create some completion scripts

**Comment by rsteube** [comment]
closing this as i'm quite happy with the current solution so there is not necessarily a need to actually alter elvish itself
