### ISSUE TITLE
Add something like a `printf` builtin

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1132]
I was asked to publish my `cmd-duration` module to make it easy to include a human friendly command duration in the left or right prompt. That caused me to realize my current implementation needed some improvements. One of which was to replace whole units with fractional units to one decimal point. That is, rather than "1 m" (for one minute) it might display "1.3 m" (for 1.3 minutes). That, however, requires using the external `printf` command for reliable results. Notwithstanding the generally excellent automatic conversion of float64 values to strings. I've noticed this deficiency before in my use of Elvish but generally worked around it -- often by calling the external `printf`. I've concluded this capability should be a builtin.

We almost certainly do not want to slavishly implement the [POSIX printf command](https://pubs.opengroup.org/onlinepubs/007908799/xcu/printf.html). Whether such a builtin should be named `builtin:printf`, `builtin:sprint`, or `str:printf` is an open question. Too, whether we want to simply expose the Go stdlib `fmt.Sprint` function or provide a more constrained wrapper around it is TBD.

**Comment by krader1961** [comment]
If we retain the builtin `print` (see issue #1065) a backward compatible solution that does not introduce yet another builtin command is to add a `&fmt` option to the `print` builtin. If it is not set (thus nil) there is no format and the legacy behavior is used. Otherwise it acts, more or less, like the legacy `printf` command.

Obviously the above observation applies to the `echo` builtin; but adding a `&fmt` option to `echo` makes me slightly queasy for irrational reasons.

**Comment by uranusjr** [comment]
Another possibility is to have a `str:format`. `printf` can be done with `echo (str:format $template $arg...)`.

**Comment by krader1961** [comment]
@uranusjr, What happens when the format, or data, includes a `\n` (newline) character? Should `str:format` output to the value channel without regard to whether the format includes a newline character? Consider what happens in a legacy POSIX shell:

```
> e:printf "%s\n%s\n" a b
a
b
```

I agree that `str:format` would resolve this issue when combined with the builtin `echo` and `print` commands (assuming `str:format` wrote to the value stream) if embedded newlines were ignored; i.e., `str:format` emitted a single value even if the format included an explicit newline. However, I can't help but think this situation is common enough that there should probably be a simpler, more straightforward, means of emitting formatted output to the byte stream rather than the value stream.

**Comment by krader1961** [comment]
Note that a trivial wrapper around something like the Go `fmt.Sprintf` function won't work. That's because formatting verbs such as `%x` and `%d` require an integer type which Elvish doesn't have. Too, even `%f` requires an actual float type (e.g., `float64`) which means doing `printf "%f\n" 3.14` will fail since `3.14` is a string in that context. You would have to write `printf "%f\n" (float64 3.14)`.

The aforementioned problems can be solved by using the `fmt.Formatter` interface. That, however, requires aliasing the builtin `float64` type to an Elvish specific type that implements that interface. As well as aliasing the `string` type to one that implements the `fmt.Formatter` interface. Ugh! Aliasing `string` values is easy to do in the `printf` (or equivalent) command. Too, one could argue that exposing the Go `float64` type was a mistake and an Elvish specific floating point type should have been used. Although, here again, we can dynamically alias `float64` inside the `printf` implementation rather than change most of the existing `float64` uses to an Elvish type alias. Other Elvish types would be dynamically converted to strings (using `vals.ToString`) before doing the actual formatting.

The proposal above to use dynamic type punting is expensive. But it is certain to be far less expensive than invoking the external POSIX `printf` command. And is also going to be more portable and less likely to result in unexpected results.
