### ISSUE TITLE
Modify how the test framework displays expected versus actual values

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1136]
I was working on issue #1019 and deliberately introduced a bug to verify the tests fail. That resulted in borderline unreadable error messages due to putting the error message, wanted values, and expected values on the same line. For example,

```
    glob_test.go:111: Glob("/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d**") => [/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dX /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dXY], want [/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dX /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dXY]
```

Readability of that error would be greatly improved if each datum was printed on a separate line. Something like this:

```
    glob_test.go:111: Glob("/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d**")
Expect: [/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dX /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dXY]
Actual: [/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2 /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g/X /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dX /private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/dXY]
```

Note that I deliberately mislabeled the two values because I think printing the expected value before the actual value is preferable and I couldn't be bothered to actually swap the values in my example. :smile:

**Comment by xiaq** [comment]
https://pkg.go.dev/github.com/google/go-cmp/cmp#Diff can be used to provide a very readable diff for nested data structures.

**Comment by krader1961** [comment]
The `go-cmp` package looks interesting but it's far from obvious that using it will result in a better experience than my proposal which leverages the related capabilities of modern CLI tools like the `less` pager. I would need to see an example of the `go-cmp` output for the example in my first comment to make even a preliminary conclusion. However, I'm willing to bet $20USD that using the `go-cmp` package in this context is not better, and possibly worse, than my proposal for changing how the changing the output to span more than one line. 😸

**Comment by xiaq** [comment]
If you follow https://pkg.go.dev/github.com/google/go-cmp/cmp#Diff, there is an example with output.

**Comment by krader1961** [comment]
@xiaq: I might owe you $20USD 😅 I took a minute to look at the example you linked to. If that is representative of what we can expect by using that function to display unexpected differences in Elvish unit tests it might be better than my more simplistic proposal. However, comparing the expected to actual value of a failure should be exceedingly rare once a unit test is proven reliable and merged. So it's unclear if the "diff" style output is easier to interpret than my proposal for "expected" versus "actual" flat strings. I think we need to try both approaches for a handful of representative test errors (including the one in my original problem statement).

**Comment by xiaq** [comment]
Well, this is what `cmp.Diff` outputs from the example in your original comment:

```go
diff (-want+got):
  []string{
  	strings.Join({
  		"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht",
  		"est.428317376/d1",
- 		"/e/f/g/X",
  	}, ""),
  	strings.Join({
  		"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht",
  		"est.428317376/d1/e",
- 		"/f/g",
  	}, ""),
  	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht"...,
  	strings.Join({
  		"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht",
  		"est.428317376/d1/e",
+ 		"/f/g",
  	}, ""),
  	strings.Join({
  		"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht",
  		"est.428317376/d",
- 		"2",
+ 		"1",
  		"/e/f/g/X",
  	}, ""),
- 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g",
- 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f",
- 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e",
- 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d1",
  	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht"...,
+ 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e",
+ 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f",
+ 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g",
+ 	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvishtest.428317376/d2/e/f/g/X",
  	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht"...,
  	"/private/var/folders/6t/t624jkmx7cbb9t35vzvjwj180000gn/T/elvisht"...,
  }
```

Even without considering its ability to do deep structural diffing, the way it formats slice elements on separate lines is already a pretty big plus.

Also note how it could diff string contents by splitting them into segments (see the first element).

**Comment by krader1961** [comment]
> Also note how it could diff string contents by splitting them into segments (see the first element).

Yeah, that's pretty cool. Okay, I'm sold. If you haven't already started working on integrating the `go-cmp` package into the Elvish unit test framework I'm happy to do so. My, much simpler, proposal would make sense if that package wasn't available given that I wouldn't have bothered to implement `go-cmp` just for this issue. However, it makes sense to take advantage of such a great tool to make future Elvish development easier.

**Comment by xiaq** [comment]
I gave it a go. This was slightly more complicated since `cmp.Diff` has some requirements on the structs it compares, but the fix wasn't too cumbersome or intrusive.

**Comment by krader1961** [comment]
> This was slightly more complicated since cmp.Diff has some requirements on the structs it compares, but the fix wasn't too cumbersome or intrusive.

The need to either make some private structure members public or configure `cmp.Diff` to ignore private members was something that concerned me. Looking at your change I agree it makes sense to make some formerly private struct members public since those structures are not part of the public Elvish API.  I'm glad, @xiaq, you went ahead and implemented this change because I would have been worried about your reaction to anyone else (e.g., myself) changing the visibility of those structure members. 😄
