### ISSUE TITLE
Provide a safe API for mutating the interactive top-level namespace

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1138]
There is now a magic `$-exports-` variable that can be assigned in `rc.elv` to export a dynamic interactive namespace. However, this doesn't work outside `rc.elv`.

There is a fundamental tension between the safety guarantees of a static namespace and the need for a dynamic namespace in a REPL. However, they can be reconciled by treating the REPL's namespace not as a single namespace that gets mutated dynamically, but at a series of static namespaces at each iteration. For example, when the REPL executes `x = 100` (assuming that `x` wasn't defined before), instead of thinking that this adds a new `x` symbol into the REPL namespace, think of it's creating another namespace that is almost the same as the current one, with the addition of a new `x` symbol.

A general API for "mutating" the REPL namespace can thus be defined in terms of two functions:

* `edit:add-var $name $init-value?` adds a variable in the REPL namespace, overwriting any existing one. It also supports an optional initial value.

* `edit:del-var $name` deletes a variable in the REPL namespace.

**Comment by krader1961** [comment]
See also issue #1110 which seems to be the impetus for this issue.

**Comment by krader1961** [comment]
There should also be a way to refer to the REPL namespace just as you can refer to the `builtin:` namespace. See #1166.

**Comment by krader1961** [comment]
Note that `keys $edit:` does not include vars (or commands) added by changing `$-exports-` or using the recently introduced `edit:add-var` command. Which speaks to a concern expressed by someone else (@hhanche?) about whether this command should be in the `edit:` namespace rather than a new `repl:`namespace.

**Comment by xiaq** [comment]
> Note that `keys $edit:` does not include vars (or commands) added by changing `$-exports-` or using the recently introduced `edit:add-var` command.

The edit: namespace and the interactive namespace are distinct

> Which speaks to a concern expressed by someone else (@hhanche?) about whether this command should be in the `edit:` namespace rather than a new `repl:`namespace.

If there is a repl: namespace, it will also be distinct from the interactive namespace.
