### ISSUE TITLE
Represent the namespace internally as a slice instead of map

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1139]
Since namespaces in Elvish are static, all the variable names can be collected in a symbol table and translated to indices. Representing the namespace as a slice instead of a map has two advantages:

* Slice access is much faster than map access;
* It will make accidental dynamic mutations of the namespaces much harder (e.g. #1137).

**Comment by krader1961** [comment]
The term `symbol box` is unknown to me and Google isn't much help regardless of the other terms I include in my search. Where can I learn more about what you're referring to?

As far as making "accidental dynamic mutations of the namespaces much harder" I don't see how that could be true. I'm all for changing the internal representation of namespaces if it makes the implementation faster. But, even if that claim were true I would consider it indicative of a deeper problem that is probably not best solved by the proposed change.

**Comment by xiaq** [comment]
Oh, that was a typo. I meant "symbol table".

Re the part about making accidental mutations harder, it's a relatively minor implementation detail that is not worthwhile dwelling on - I only mentioned it because #1137 is relevant.

**Comment by krader1961** [comment]
Using a list as a symbol table representation is certainly reasonable. At least for a typical compiler. It isn't, however, obvious how that works for the pseudo "interactive" namespace.
