### ISSUE TITLE
argument completion for aliased commands

### ISSUE THREAD

**Issue by rsteube** [elves/elvish#1146]
When aliasing a command accoding to [ui-recipes](https://elv.sh/learn/cookbook.html#ui-recipes) the completion is still called for the original command.
The completion should be replaced as well:

```
fn ls [@a]{ e:exa $@a }
edit:completion:arg-completer[ls] = [@args]{
  args[0] = 'exa'
  $edit:completion:arg-completer[exa] $@args
}
```

**Comment by zzamboni** [comment]
I'm not sure I understand the issue. If you redefine `ls` to something else, of course the completer will still be called for `ls` (assuming it has a custom completer). If you want to call the `exa` completer for `ls`, then what you suggested is necessary (BTW I'm not sure you need to assign `args[0]`, just calling the completer should be fine)
```
fn ls [@a]{ e:exa $@a}
edit:completion:arg-completer[ls] = $edit:completion:arg-completer[exa]
```

**Comment by rsteube** [comment]
yeah, that works as well - was worried  i messed that up in the completion scripts, but it's fine
