### ISSUE TITLE
What are the rules for option (command flag) recognition?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1152]
The discussion in issue #952 caused me to notice this behavior:

```
> range 1&step=2 6
▶ (float64 1)
▶ (float64 3)
▶ (float64 5)
```

Why is the `&step` option recognized as an option even though the ampersand does not occur after a whitespace boundary? Is this desirable? Would it be better to parse that as command argument `1&step=2` rather than as argument `1` and option `&step=2`? If nothing else this subtlety needs to be documented by https://elv.sh/ref/language.html#arguments-and-options

**Comment by krader1961** [comment]
@hanche, Good point about ampersand not being legal in a bare word which naturally leads to the current semantics. Still, it bothers me since it allows you to write `a_func &opt1=v1&opt2&opt3=v3 arg1`. Sure, no one is going to write it like that (I hope) rather than `a_func &opt1=v1 &opt2 &opt3=v3 arg1` (i.e., with whitespace between the options). Of course, most languages allow formatting equivalent code in more than one way and typically some of those are considered "good" and some "bad" ways to format the code.

On balance the simplicity of the current semantics is probably best even though it allows people to write hard to read statements. In particular, we don't want to allow ampersands in bare words in some cases but not others.

It would be nice if we had an `elvishfmt` command that mimicked `gofmt` and which could be used to enforce whitespace before the ampersand that introduces an option. The question is whether the Elvish compiler should enforce that restriction.

**Comment by hanche** [comment]
I think the case for not allowing `a_func &opt1=v1&opt2&opt3=v3 arg1` is quite strong: In elvish, the lack of whitespace between different “things” on the command line indicates concatenation, and that makes no sense in this case. So it should be considered an error.

**Comment by krader1961** [comment]
For your amusement, the first (very lame) obfuscated Elvish contest entry:

```
> fn a [&o1=1&o2=2&o3=false @rest]{ put $o1 $o2 $o3 $rest }
> a&o1=11&o2=22&o3 a b c
▶ 11
▶ 22
▶ $true
▶ [a b c]
```

**Comment by xiaq** [comment]
This is in a sense a POSIX baggage - POSIX sh uses `&` as the indicator for background jobs, and it does not need to be preceeded by whitespaces (`echo a&` works in POSIX sh and Elvish). As a result Elvish recognizes `&` as a metacharacter everywhere, so it will terminate barewords and other key-value pairs to start a new key-value pair.

It can be made a conditional metacharacter like `~`, thus always requiring preceding whitespaces, but I'm not bothered enough by `a_func&opt1=v1&opt2&opt3=v3` to make the parser more complex. I'll just document this.

**Comment by krader1961** [comment]
> I'll just document this.

Fair enough; although, I would hope it includes a caveat that omitting the whitespace isn't recommended since whitespace might be required in the future if someone decides to make the parsing of ampersands more context aware.
