### ISSUE TITLE
Distinct result when searching history

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#116]
In history mode, the duplicated results seem useless.

**Comment by xiaq** [comment]
Indeed.

A warning ahead: If you are going to implement this, do the duplicate removal when searching, not when storing. An untampered history is useful with history listing (#63), for instance.

**Comment by xiaq** [comment]
The easiest way to implement this has something to do with storing though. We add a `duplicateWithLater` field to the history table. When storing a history item, we search for all items with the same content and set their `duplicateWithLater` to true.

When searching back through history, we skip items with `duplicateWithLater = true`. When listing the history, we simply ignore this flag.

**Comment by xiaq** [comment]
The current implementation is wrong.

It works by maintaining a `lastAmongDup` field. When a new history item is inserted, it has `lastAmongDup = 1` and all duplicate items have their `lastAmongDup` set to 0. When searching through history, we use `where lastAmongDup = 1`.

A problem arises when there are concurrent sessions. To start with, the history shown to the user is the history in the database before the session starts, plus the current session history. Commands input in other sessions after this session starts are not shown.

Now suppose that there is an `ls` entry in the database, and now you start two sessions, A and B. In sesson A you input `ls`, which resets the `lastAmongDup` flag of the `ls` entry in the database . Now in session B you will never see `ls`.
