### ISSUE TITLE
Simplistic builtins to read text files

### ISSUE THREAD

**Issue by uranusjr** [elves/elvish#1168]
With `-source` deprecated, there is now not a builtin way to read from the file system. This is a problem on Windows, where there is not an external command to do this (`type` is a built-in). There are good third-party commands out there (e.g. `bat`), but they are generally not in default `$path`, creating a chicken-egg problem—you need to run code to make those commands available, but then those commands can’t be used in the code that initialises them.

The proposal is to have some builtin functions that do basic file I/O that can be used to bootstrap more sophiscated utilities. The most useful from the top of my head is an equivalent to `cat`, and something that can do POSIX `test` stuff is probably also handy, although I can imagine simulating most of if by hacky `try` constructs.

**Comment by xiaq** [comment]
`slurp < filename` does this.
