### ISSUE TITLE
Selecting nothing on file manager improvement suggestion

### ISSUE THREAD

**Issue by chengxuncc** [elves/elvish#1169]
Way to reproduce:
- CTRL+N
- Choose an empty directory and hit →
- Hit ENTER
- `[space]''` will append to termial

Improvement: not append `[space]''` when selecting nothing.

**Comment by krader1961** [comment]
Note that the problem doesn't just involve empty directories. Start with an empty command line and use navigation mode to select a filename. A space is prepended so now the command line begins with a space which means it won't be added to the command history.

**Comment by krader1961** [comment]
FYI, The fix for both problems is trivial (see `func navInsertSelected`). I'll create a pull-request as soon as I have added unit tests. Something that is more difficult than I expected due to the opacity of APIs like `TestTTY`.
