### ISSUE TITLE
Weird Chinese character display

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#117]
![image](https://cloud.githubusercontent.com/assets/227180/13015066/05babad4-d1f2-11e5-87da-820e580f98c2.png)

Env:
Debian testing
KDE 5.4.3
Konsole

Have no idea about this situation...

**Comment by xiaq** [comment]
Confirmed. Also:

![screenshot_2016-02-12_19-03-11](https://cloud.githubusercontent.com/assets/582021/13015790/501f3528-d1bb-11e5-9270-3bf6a95ab9a3.png)

什么 is completely missing.

A tip: you can debug the terminal output by uncommenting the logging code in `edit/writer.go` (search `Logger`) and giving elvish the `-debuglog=outputfile` switch at startup. Open another terminal to `tail -f outputfile`.

**Comment by xiaq** [comment]
This has to do with the delta algorithm. If you do `le:binding[insert][Ctrl-R]=redraw`, and press Ctrl-R to force a redraw after typing a Chinese character, it looks fine.
