### ISSUE TITLE
prompts should support type float64 as well as string

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1186]
Sorry, @zzamboni, but while reviewing my commit history I also noticed one of your changes:

https://github.com/elves/elvish/commit/a062be0c052332afdcd821f4a95289cf92d76bf2

To reproduce the problem that change in the documentation addresses start an interactive Elvish shell and type these statements:

```
> n = 1
> edit:prompt = { sleep 2; put $n; n = (+ $n 1); put ': ' }
```

The change in that commit "fixes" the problem with the documentation but introduces an ambiguity since it mixes byte and value output in the prompt function. The order in which byte and value streams are processed is currently undefined. Thus, replacing the first `put` with `to-string`, "fixes" the problem but there is no guarantee that the number, written to the byte stream, will appear before the `": "` string that is written to the value stream. The proper fix is to change the prompt rendition code to support implicit coercion of any data type (including float64) that has a `String` method so that prompt functions can consistently write to the value stream.

**Comment by zzamboni** [comment]
@krader1961 I agree that it would be nice that the prompt code automatically converts other types to string.

However, your explanation of the ambiguity is incorrect. `to-string` writes the string to the value stream, not to the byte stream, so the documentation fix still outputs only to the value stream.

**Comment by krader1961** [comment]
> However, your explanation of the ambiguity is incorrect. to-string writes the string to the value stream, not to the byte stream, so the fixed example still outputs only to the value stream.

Yeah, I realized that after I went to bed and it occurred to me I had conflated `to-string` with `to-lines`. Nonetheless, I think everyone would agree that coercion to a string should happen implicitly in the context of rendering a prompt. The question is whether it should be done only for specific types such as `float64` or should be done for any non-string data type. It looks like the the `Text.Concat` and `Text.RConcat` methods are the appropriate place to add the conversion for `float64` (and possibly any non-string type not already handled).

**Comment by krader1961** [comment]
After thinking about this some more, and working on a fix, I've decided that `float64` should be special-cased rather than implicitly converting to a string any data type not otherwise explicitly handled by the `Concat` and `RConcat` methods. Doing so is obviously fragile since the addition of other data types (see issue #241) that should be implicitly converted will also need to be special-cased in these methods. If, and when, that happens we can explore introducing a new interface for a "convert to string only in contexts like rendering a prompt" API.
