### ISSUE TITLE
Test coverage does not count lines executed by a test in a different package

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1187]
While working on issue #1186 I was perplexed that `make coverage` showed no executions of these methods:

https://github.com/elves/elvish/blob/6f3b8a787b8b8eb98e1436316f0d4cc1d00e4604/pkg/ui/text.go#L64-L86

Despite the fact that adding debugging print statements (or `panic()` calls) showed those methods were being run during test coverage. This [article](https://www.ory.sh/golang-go-code-coverage-accurate/) explains why that incorrect coverage occurs.

It is my opinion that indirect coverage is meaningful, and the default Go toolchain behavior is incorrect (i.e. undesirable), for this project. Will there be corner cases that are incorrectly considered to be covered via an indirect test? Maybe. Nonetheless, I don't think that adding explicit unit tests of the uncovered functions is more valuable than implicit tests from other packages. It's more useful to assume that indirect execution during a unit test (i.e., from a different package) is meaningful for this project's test coverage metrics.

**Comment by krader1961** [comment]
I also have a discussion opened at [codecov.io](https://community.codecov.io/t/codecov-incorrectly-considers-implicitly-executed-go-statements-as-being-not-executed/2363/2) to explore whether

a) this project can be configured to produce more accurate coverage metrics for its Go code on codecov.io, or

b) the codecov.io treatment of Go code is currently broken. That is, too pessimistic due to not distinguishing statements always "executed" by the compiler (e.g., 'import(...)` blocks) versus statements executed at run-time.

**Comment by xiaq** [comment]
There are valid reasons both for counting and not counting lines that are covered by tests in a different coverage.

If you think of each package as an individually reusable library, then the fact that the tests of *another library* exercise some lines in this library should not give you a free pass for not writing unit tests.

However, if you think of packages as just a way of grouping and organizing files in a large project, then a line should be considered covered as long as any test in this project exercises it.

The situation in the Elvish codebase seems to be somewhere in between, so a hybrid solution (if possible) would be ideal:

* The top-level directories under `pkg` are on the end of individually reusable libraries; for example, the `edit` and `eval` packages are two very different libraries, and if a test against `edit` exercises a line in `eval`, that line should **not** be considered covered.

* On the other hand, when I think about how to group the files within (say) `eval` into packages, I'm merely using packages as a way to organize code. I think of all code in `eval` and its subdirectories as one library. So if a test in `eval/foo` exercises a line in `eval/bar`, I **do** want to consider that line covered.

**Comment by krader1961** [comment]
> The situation in the Elvish codebase seems to be somewhere in between

Yes, but it is much closer to your second proposition, it seems to me. Yes, some bits of the code, like the web UI, should not be considered as exercising other bits of the code. However, AFAICT, that is not a significant source of differences in the coverage metrics. Even if those bits of the project skewed the coverage metrics it's not clear they do so sufficiently to justify complicating computing the coverage metrics. 

Note that we're talking about, as I write this, a 2% coverage difference on macOS between the value reported by `go tool -cover` without and with this change (86.3% => 88.3%). Using the suggested hybrid approach results in a 0.2% increase in coverage (86.3% => 86.5%) but still shows that *pkg/ui/text.go* coverage is unchanged.

Note that the example in my opening comment involves code in *pkg/edit* that indirectly, yet explicitly, executes code in *pkg/ui* which is not correctly reflected in the coverage metrics using the current, or proposed hybrid, implementation. Whereas my change, as I write this, does correctly reflect those invocations.

**Comment by krader1961** [comment]
I took a deeper dive into the difference in overall coverage as a result of my proposed change. I did so by manually running `go tool cover -func=cover` with and without my proposed change and comparing the results. The results are below. As you can see a lot of the change is due to code that has no explicit unit test but is implicitly tested via integration tests. Such as the functions in *pkg/sys/termios.go*. There are a few packages which had improved coverage that I don't yet understand. For example, *pkg/parse/parseutil/parseutil.go*. Yet others, such as the improved coverage of *pkg/testutil/must.go* are obviously due to indirect execution by other tests that, it seems to me, should be counted as exercising that code. Overall I don't see any reason to think my proposal produces inflated coverage that cannot be justified.

```
pkg/cli/addons/histwalk/histwalk.go:128:@walk                 70.0  90.0  20.0
pkg/cli/addons/navigation/navigation.go:53:@Handle            81.8  90.9   9.1
pkg/cli/addons/navigation/navigation.go:165:@SelectedName     80.0  90.0  10.0
pkg/cli/term/buffer.go:92:@TrimToLines                        83.3  91.7   8.4
pkg/cli/term/buffer_builder.go:119:@WriteSpaces                0.0 100.0 100.0
pkg/cli/term/buffer_builder.go:128:@MarkLines                 75.0 100.0  25.0
pkg/cli/term/setup.go:14:@Setup                                0.0 100.0 100.0
pkg/cli/term/setup.go:19:@SetupGlobal                          0.0 100.0 100.0
pkg/cli/term/setup.go:24:@Sanitize                             0.0 100.0 100.0
pkg/cli/term/setup_unix.go:14:@setup                          81.0  85.7   4.7
pkg/cli/term/setup_unix.go:54:@setupGlobal                     0.0 100.0 100.0
pkg/cli/term/setup_unix.go:58:@sanitize                        0.0 100.0 100.0
pkg/daemon/client.go:47:@SockPath                              0.0 100.0 100.0
pkg/eval/builtin_special.go:261:@use                          76.5  82.4   5.9
pkg/eval/compile_effect.go:616:@exec                          80.0 100.0  20.0
pkg/eval/eval.go:218:@InstallDaemonClient                      0.0 100.0 100.0
pkg/eval/eval.go:224:@InstallModule                            0.0 100.0 100.0
pkg/eval/eval.go:235:@SetArgs                                  0.0  75.0  75.0
pkg/eval/eval.go:260:@Eval                                    69.2  92.3  23.1
pkg/eval/frame.go:47:@SetLocal                                 0.0 100.0 100.0
pkg/eval/frame.go:161:@PipeOutput                              0.0 100.0 100.0
pkg/eval/mods/daemon/daemon.go:18:@Ns                          0.0  69.2  69.2
pkg/eval/mods/store/store.go:8:@Ns                             0.0 100.0 100.0
pkg/eval/ns.go:52:@HasName                                     0.0 100.0 100.0
pkg/eval/ns.go:59:@PopName                                     0.0 100.0 100.0
pkg/eval/port_helper.go:21:@PortsFromFiles                     0.0 100.0 100.0
pkg/eval/process_unix.go:15:@putSelfInFg                       0.0  40.0  40.0
pkg/eval/purely_eval.go:13:@PurelyEvalCompound                 0.0 100.0 100.0
pkg/eval/purely_eval.go:17:@PurelyEvalPartialCompound         92.6  96.3   3.7
pkg/eval/vals/concat.go:30:@Error                              0.0 100.0 100.0
pkg/eval/vals/conversion.go:32:@Error                          0.0 100.0 100.0
pkg/eval/vals/conversion.go:41:@Error                          0.0 100.0 100.0
pkg/eval/vals/conversion.go:115:@elvToFloat                   90.0 100.0  10.0
pkg/eval/vals/index.go:41:@Index                              81.8  90.9   9.1
pkg/eval/vals/iterate.go:29:@Iterate                          81.8 100.0  18.2
pkg/eval/vals/repr_helpers.go:20:@WriteElem                   85.7 100.0  14.3
pkg/eval/vals/repr_helpers.go:35:@String                      83.3 100.0  16.7
pkg/eval/vars/element.go:118:@HeadOfElement                    0.0 100.0 100.0
pkg/fsutil/gethome.go:17:@GetHome                             33.3  83.3  50.0
pkg/fsutil/search.go:14:@DontSearch                            0.0 100.0 100.0
pkg/glob/glob.go:29:@Glob                                     61.5  69.2   7.7
pkg/glob/glob.go:182:@matchElement                            93.5  96.8   3.3
pkg/glob/glob.go:246:@matchFixedLength                        81.2  87.5   6.3
pkg/glob/pattern.go:41:@Match                                 33.3 100.0  66.7
pkg/logutil/logutil.go:20:@GetLogger                           0.0 100.0 100.0
pkg/parse/parse.go:720:@exitusCapture                         85.7 100.0  14.3
pkg/parse/parseutil/parseutil.go:12:@FindLeafNode              0.0  85.7  85.7
pkg/parse/parseutil/parseutil.go:27:@Wordify                   0.0 100.0 100.0
pkg/parse/parseutil/parseutil.go:32:@wordifyInner              0.0 100.0 100.0
pkg/parse/parseutil/parseutil.go:46:@isCompound                0.0 100.0 100.0
pkg/parse/quote.go:59:@rtohex                                  0.0  87.5  87.5
pkg/parse/quote.go:73:@quoteDouble                            52.6  73.7  21.1
pkg/store/cmd.go:70:@IterateCmds                               0.0 100.0 100.0
pkg/store/cmd.go:84:@Cmds                                      0.0 100.0 100.0
pkg/store/cmd.go:93:@CmdsWithSeq                               0.0 100.0 100.0
pkg/store/dir.go:104:@Swap                                     0.0 100.0 100.0
pkg/sys/isatty_unix.go:10:@IsATTY                              0.0 100.0 100.0
pkg/sys/select_unix.go:11:@Select                             66.7 100.0  33.3
pkg/sys/signals_unix.go:11:@NotifySignals                      0.0 100.0 100.0
pkg/sys/termios.go:20:@TermiosForFd                            0.0 100.0 100.0
pkg/sys/termios.go:26:@ApplyToFd                               0.0 100.0 100.0
pkg/sys/termios.go:31:@Copy                                    0.0 100.0 100.0
pkg/sys/termios.go:37:@SetVTime                                0.0 100.0 100.0
pkg/sys/termios.go:42:@SetVMin                                 0.0 100.0 100.0
pkg/sys/termios.go:47:@SetICanon                               0.0 100.0 100.0
pkg/sys/termios.go:52:@SetIExten                               0.0 100.0 100.0
pkg/sys/termios.go:57:@SetEcho                                 0.0 100.0 100.0
pkg/sys/termios.go:62:@SetICRNL                                0.0 100.0 100.0
pkg/sys/termios_64bitflag.go:8:@setFlag                        0.0 100.0 100.0
pkg/sys/winsize_unix.go:20:@GetWinsize                         0.0  80.0  80.0
pkg/testutil/must.go:9:@MustPipe                               0.0  75.0  75.0
pkg/testutil/must.go:17:@MustReadAllAndClose                   0.0  80.0  80.0
pkg/testutil/must.go:27:@MustMkdirAll                          0.0  75.0  75.0
pkg/testutil/must.go:37:@MustCreateEmpty                       0.0  80.0  80.0
pkg/testutil/must.go:48:@MustWriteFile                         0.0  66.7  66.7
pkg/testutil/must.go:56:@MustChdir                             0.0  66.7  66.7
pkg/testutil/must.go:70:@Must                                  0.0  50.0  50.0
pkg/testutil/testdir.go:55:@InTempHome                         0.0 100.0 100.0
pkg/tt/tt.go:111:@Match                                        0.0 100.0 100.0
pkg/tt/tt.go:122:@matchOne                                    66.7 100.0  33.3
pkg/tt/tt.go:151:@call                                        81.8 100.0  18.2
pkg/ui/color.go:99:@parseColor                                92.3 100.0   7.7
pkg/ui/styling.go:182:@parseOneStyling                        93.8 100.0   6.2
pkg/ui/text.go:65:@Concat                                      0.0 100.0 100.0
pkg/ui/text.go:79:@RConcat                                     0.0  66.7  66.7
pkg/ui/text.go:196:@String                                     0.0 100.0 100.0
pkg/ui/text_segment.go:91:@Concat                              0.0  80.0  80.0
pkg/ui/text_segment.go:108:@RConcat                            0.0  66.7  66.7
pkg/ui/text_segment.go:149:@VTString                          75.0 100.0  25.0
al:@(statements)                                              86.3  88.3   2.0
```

**Comment by krader1961** [comment]
The sole invocation of `pkg/parse/parseutil/parseutil.go:12:@FindLeafNode` (one of the functions that went from zero to non-zero coverage) is from *pkg/edit/complete/complete.go*. Ideally there would be an explicit unit test of `FindLeafNode()`. But it seems to me the indirect execution by *pkg/edit/complete/complete.go* is sufficient to consider the former to have been "covered" (to some extent) since the test of the `Complete()` function that called `FindLeafNode()` is likely to fail if `Complete()` behaved unexpectedly.

**Comment by krader1961** [comment]
> Yes, some bits of the code, like the web UI, should not be considered as exercising other bits of the code. However, AFAICT, that is not a significant source of differences in the coverage metrics.

I modified my proposed change to limit cross-package coverage to just those in the *pkg/...* tree. That made no difference to the overall coverage. We might want to use that modification to protect against future changes to tertiary packages (*cmd/...*, *website/...*) that might skew the core elvish coverage but doing so makes no difference today and is unlikely to make a difference in the future.

**Comment by xiaq** [comment]
OK, I am convinced that calculating coverage for the whole project is a reasonable approach.
