### ISSUE TITLE
or special command results in unexpected logic

### ISSUE THREAD

**Issue by dangerousHobo** [elves/elvish#1193]
Maybe I'm using the builtin `or` command wrong but something here does not seem right.

I can write the following to test if a file exist:

```
> if (test ! -e /tmp/abc1) { echo "does not exist" } else { echo "exist" }
does not exist
> if (test ! -e /tmp/abc2) { echo "does not exist" } else { echo "exist" }
does not exist
```

So the condition is evaluating to true. If I combine this with an `or` to make a single statement:

```
> if (or (test ! -e /tmp/abc1) (test ! -e /tmp/abc2)) { echo "does not exist" } else { echo "exist" }
exist
```

Both conditions evaluate to true, but the `or` appears to think they both evaluated to false.

I think it'd partial simplify to this:

```
> if (or $true $true) { echo "does not exist" } else { echo "exist" }
does not exist
```

What am I missing here? Am I using the `or` command wrong?

**Comment by dangerousHobo** [comment]
I see what was going on. The `test` command is exiting with a 1 and would cause an exception but its not caught or shown.

If I tell elvish to ignore the exception, things work as expected:

```
> if (or ?(test ! -e /tmp/abc1) ?(test ! -e /tmp/abc2)) { echo "does not exist" } else { echo "exist" }
does not exist
```

**Comment by zzamboni** [comment]
This is because in Elvish, a non-zero exit code is considered an exception, which interrupts execution:

```
[~]|> test -e /foo
Exception: test exited with 1
[tty 138], line 1: test -e /foo
[~]|> if (test -e /foo) { echo true } else { echo false }
Exception: test exited with 1
[tty 140], line 1: if (test -e /foo) { echo true } else { echo false }
[~]|> or (test -e /foo)
Exception: test exited with 1
[tty 141], line 1: or (test -e /foo)
```

The solution, as you have discovered, is to use `?(...)`, which returns the exit code while "swallowing" the exception. 

This is documented: https://elv.sh/learn/unique-semantics.html#predicates-and-if
