### ISSUE TITLE
Shut down the old Matrix room

### ISSUE THREAD

**Issue by notramo** [elves/elvish#1194]
**Gitter is now natively bridging Matrix** (as first steps on the roadmap of making Matrix the backbone of Gitter, and blending the Gitter and Matrix ecosystem together). There is now a native Gitter - Matrix bridge at gitter.im, which **provides beautiful native-feeling bridging experience**.
https://matrix.org/blog/2020/12/07/gitter-now-speaks-matrix
This means that the old bridge is not needed, and will only cause confusion and **may destroy the room**.
Currently, there are 3 Elvish rooms on Matrix.
- **Native bridged** at gitter.im (now preferred) [#elves_elvish:gitter.im](https://matrix.to/#/#elves_elvish:gitter.im)
- **Old Gitter bridge** at matrix.org (will be shut down by matrix.org team) [#gitter_elves=2Felvish:matrix.org](https://matrix.to/#/#gitter_elves=2Felvish:matrix.org)
- **Manualy created** room with mesajor bridge: [#elvish:matrix.org](https://matrix.to/#/#elvish:matrix.org)

The old Gitter bridge at matrix.org will be shut down automatically, but you should shut down [#elvish:matrix.org](https://matrix.to/#/#elvish:matrix.org), and bring the bridge into [#elves_elvish:gitter.im](https://matrix.to/#/#elves_elvish:gitter.im)

**Comment by xiaq** [comment]
The manually created room `#elvish:matrix.org` is no longer bridged with the rest of the IM channels. Instead, the matterbridge instance is now configured to just bridge between Gitter, IRC and Telegram. Matrix users can just use the native bridge. I'll update the website too.

**Comment by notramo** [comment]
@xiaq
Is #elvish:matrix.org still needed?
I see it's not listed in the directory, but if someone knows the address, they can still join it.
You can remove the alias and deprecate the room with [@room-deprecation-bot:systemtest.tk](https://matrix.to/#/@room-deprecation-bot:systemtest.tk).

The displayed text of the matrix link at elv.sh still shows #elvish:matrix.org, but correctly points to https://matrix.to/#/#elves_elvish:gitter.im

**Comment by xiaq** [comment]
> You can remove the alias and deprecate the room with @room-deprecation-bot:systemtest.tk.

That's just a bot that says that the room is deprecated, right? :) I saw you tried to use it in the room without success. Given that the room already says that it's deprecated in the description and not many people use the Matrix room anyway I feel it's not worth bothering.

> The displayed text of the matrix link at elv.sh still shows #elvish:matrix.org, but correctly points to https://matrix.to/#/#elves_elvish:gitter.im

Thanks for catching that, fixing.
