### ISSUE TITLE
"end of history" should appear only once

### ISSUE THREAD

**Issue by adam-devel** [elves/elvish#1198]
![Screenshot from 2020-12-20 20-57-32](https://user-images.githubusercontent.com/70688335/102723602-5c76fa80-4309-11eb-8ed0-2e2cbf3d0221.png)
I've noticed that, when i type part of a used command then press "up" several time until reaching the end of the history, the shell keeps writing "end of history"

**Comment by xiaq** [comment]
This is intentional; if you keep pressing Up at the end of history you will get feedback every time.

**Comment by adam-devel** [comment]
i understand that, but what is the intention behind this unrequired verbosity, wouldn't elvish be better without it repeating it, or at least repeat it under the prompt rather than on top of it?
wouldn't it be better to ignore further events after the first message, as long as long as the input is the same

**Comment by xiaq** [comment]
Consider this:

1. The user enters history mode, and keeps pressing Up until they reach the end of history. They see an "end of history" message, and they now know that this is the end of history and will stop pressing.
2. The user does something else.
3. The user now enters history mode again, and keeps pressing Up until they reach the end of history.

If the same message is suppressed, the user gets no feedback this time that they have reached the end of history.
