### ISSUE TITLE
Bogus color blocks in navigation mode on termux

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#120]
![screenshot_2016-02-12-21-44-19](https://cloud.githubusercontent.com/assets/582021/13019813/f222c932-d1d1-11e5-8b3d-d87b9aff87b1.png)

**Comment by fornwall** [comment]
Hi, let me know if this seems to be a bug with the terminal emulation in Termux!

**Comment by xiaq** [comment]
@fornwall Sure. Nice to see you here :)

**Comment by xiaq** [comment]
Termux bug: https://github.com/termux/termux-app/issues/51

**Comment by xiaq** [comment]
Not termux bug. Should use '\e[0m' before erasing.
