### ISSUE TITLE
Recent changes broke a `use` trick

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1204]
See issue #1202 for background. This issue documents a related panic unrelated to the use of the experimental `-source` command introduced by changes starting with commit 6419f4524a1a5217e5d29fdc9ff0b6d4ca13b1a7. This failure occurs when using a module import trick popularized by @hanche on Gitter. Create a *~/.elvish/rc.elv* with these lines:

```
use platform

# This is a clever way to conditionally import the `unix` module into the
# interactive namespace so that we don't get a startup exception when running
# on MS Windows.
nop (and $platform:is-unix (use unix))

-exports- = [&]
if $platform:is-unix {
  # -exports-[unix:] = $unix:  # not needed due to `use` trick above
  -exports-[umask] = $unix:umask
}
```

You should see a panic similar to this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x136f026]

goroutine 13793 [running]:
github.com/elves/elvish/pkg/eval.(*Ns).lookup(0x0, 0xc00042d385, 0x5, 0x1453420)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/ns.go:68 +0x26
github.com/elves/elvish/pkg/eval.(*Ns).indexInner(...)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/ns.go:60
github.com/elves/elvish/pkg/eval.deref(0xc0008565b0, 0xc0004c44b0, 0x10755cf, 0x142cae0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/var_ref.go:137 +0xf5
github.com/elves/elvish/pkg/eval.variableOp.exec(0x137f, 0x138a, 0x0, 0xc00042d380, 0xa, 0
xc0004c44b0, 0xc0008565b0, 0x203000, 0x203000, 0x203000, ...)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_value.go:320 +0x4d
github.com/elves/elvish/pkg/eval.compoundOp.exec(0x137f, 0x138a, 0x0, 0xc0004c6190, 0x1, 0
x1, 0xc0008565b0, 0x1473b40, 0x145ef01, 0xc00082cb40, ...)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_value.go:75 +0x69
github.com/elves/elvish/pkg/eval.seqValuesOp.exec(0x137f, 0x138a, 0xc0004c6180, 0x1, 0x1,
0xc0008565b0, 0xc000843180, 0xc00005caf0, 0x109bd32, 0xc00032de60, ...)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_value.go:620 +0xb3
github.com/elves/elvish/pkg/eval.(*assignOp).exec(0xc0004b1840, 0xc0008565b0, 0xc00005ce38
, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_lvalue.go:110 +0x232
github.com/elves/elvish/pkg/eval.(*formOp).exec(0xc0004bb080, 0xc0008565b0, 0x0, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:388 +0x862
github.com/elves/elvish/pkg/eval.(*pipelineOp).exec.func1(0x152b780, 0xc0004bb080, 0xc0008
565b0, 0xc000010738, 0xc0007808e0, 0xc0003f8e00)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:150 +0x3f
created by github.com/elves/elvish/pkg/eval.(*pipelineOp).exec
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:149 +0x225
```

A debug print in `pkg/eval/var_ref.go@deref` shows that its `variable.Get().(*Ns)` call is returning nil for the `ns` pointer and true for `ok` when `subName` is "umask". Resulting in the nil pointer being dereferenced by the `ns.indexInner(subName)` call.

**Comment by krader1961** [comment]
The recent changes also breaks the more straightforward approach:

```
use platform
if ($platform:is-unix) {
    use unix
}
# ... more initialization
if $platform:is-unix {
    -exports-[umask] = $unix:umask
}
```

That doesn't result in a panic but does report `compilation error: variable $unix:umask not found`. So this change seems to make it impossible to conditionally import and use a module. At least when it is a builtin, pre-defined, module.

**Comment by krader1961** [comment]
See also issue #1116 where I ask how to conditionally `use` a module interactively (such as the `unix` module). That issue resulted in me using the import trick suggested by @hanche. That trick was broken by the recent changes to how namespaces are managed.

**Comment by hanche** [comment]
I don't have any opportunity to test the new version now myself right now, but out of curiosity: Does the following work with the new version?

```
nop (foo = bar)
echo $foo
```

assuming `$foo` was not defined before, of course.

**Comment by hanche** [comment]
I suddenly had a spare moment to try what I asked above. It works just fine without crashing.

**Comment by xiaq** [comment]
Hmm, this is a very subtle bug where the arguments of special commands (in this case `and`) are compiled twice, and only the result of the first compilation is evaluated.

In `nop (and $platform:is-unix (use unix))`, the `use unix` form is compiled twice since it's part of an argument of `and`. This causes there to be two `$unix:` variables, the second one shadowing the first. However, since only the first instance of `use unix` is executed, the `unix:` module is only stored in the first shadowed `$unix:` variable, leaving the second `$unix:` variable nil.
