### ISSUE TITLE
`dir-history` should not be in the builtin: namespace

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1205]
Using the `dir-history` builtin in a non-interactive Elvish program results in this error:

```
Exception: store not connected
/Users/krader/x, line 1: dir-history
```

Since directory history, like command history, is only relevant in interactive context the command should be in the `edit:` namespace rather than `builtin:`. What probably makes more sense is to move `dir-history` and `edit:command-history` to a `store:` namespace. That way, if we ever decide to make the interactive history accessible by a non-interactive Elvish shell there won't be any problems due to `edit:` only being available in interactive shells. Also, we're likely to want to introduce more commands and/or variables for efficiently interacting with the interactive history store. Such as by enumerating the history from a non-interactive shell for analysis, backup, etc.

**Comment by krader1961** [comment]
@xiaq: Since I've been working on issue #568 it occurs to me this should be addressed sooner rather than later. My inclination is to introduce a `store:` namespace since it's API is only loosely coupled to the `edit:` namespace. It should be possible to use the "store" commands without the shell actually being interactive -- even if we don't support that today. See also #1299, but even if `use edit` is allowed in a non-interactive shell it still seems to me better to separate the concept of interactive REPL mode and accessing the interactive store.

**Comment by xiaq** [comment]
> @xiaq: Since I've been working on issue #568 it occurs to me this should be addressed sooner rather than later. My inclination is to introduce a `store:` namespace since it's API is only loosely coupled to the `edit:` namespace. It should be possible to use the "store" commands without the shell actually being interactive -- even if we don't support that today. See also #1299, but even if `use edit` is allowed in a non-interactive shell it still seems to me better to separate the concept of interactive REPL mode and accessing the interactive store.

Seems you arrived at the same motivation for opening #1032 after all. :)

**Comment by krader1961** [comment]
Yes, this is essentially a duplicate of #1032 but with a clearer explanation for why it is needed. :smile:
