### ISSUE TITLE
$args is empty in script example

### ISSUE THREAD

**Issue by href** [elves/elvish#1207]
Some of my scripts stopped working after updating to the latest Elvish master. I can't say what my previous version was, so I don't know when this was introduced.

It seems like `$args` is always empty. See the example from the [docs](https://elv.sh/ref/builtin.html#args):
```elvish
~> echo 'put $args' > args.elv
~> elvish args.elv foo -bar
```

This should output `▶ [foo -bar]`, but it outputs `[]`

**Comment by zzamboni** [comment]
I can reproduce this.
```
[~]|> elvish -buildinfo
Version: v0.14.0-209-g0e0a0485
Go version: go1.15.6
Reproducible build: true
```

**Comment by href** [comment]
Thank you 👍
