### ISSUE TITLE
Overwriting functions in the builtin namespace

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1211]
I can overwrite the function `builtin:return` in this way:

```
⬥ return~ = { echo 'NOBODY expects the Spanish Inquisition!' }
⬥ builtin:return
NOBODY expects the Spanish Inquisition!
```

This does not happen if I use `fn return { … }` instead. It also does not happen if I run `fn return { }` and then perform the above assignment. (This is not surprising, really.)

The same thing happens with at least some other functions; maybe all of them. But testing is painful because of all the side effects of mutating the builtin namespace.

**Comment by hanche** [comment]
Oh, wait: I just discovered that this is documented behaviour. Still arguably a bug, but at least it is already known.

**Comment by xiaq** [comment]
Documented yes, desirable no. I don't think there is a valid use case for overriding builtins, so I'll make these read-only.
