### ISSUE TITLE
Only the first "use" of a module imports the module correctly, subsequent uses import an empty namespace

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1212]
Honestly, I had a hard time coming up with a descriptive title for this issue. Look here:

```
⬥ cat one.elv
echo Loading one
use ./two
keys $two:
nop $two:two~
⬥ cat two.elv
echo Loading two
fn two [@_]{ }
⬥ cat bug.elv
use ./one
use ./two
nop $two:two~
⬥ ./elvish -buildinfo
Version: stable-63-g02d9252b
Go version: go1.15.6
Reproducible build: true
⬥ ./elvish -norc bug.elv
Loading one
Loading two
▶ two~
Exception: variable $two:two~ not found
/Volumes/solid/pkg/gopkg/src/github.com/elves/elvish/bug.elv, line 3: nop $two:two~
Exception: ./elvish exited with 2
[tty 28], line 1: ./elvish -norc bug.elv
```

(**Edited** to avoid messing with your init files while confirming the bug.)

Note that the line `keys $two:` in `one.elv` produces the expected output `two~`

If I comment out the line `use one` from `bug.elv`, no error results.

In case it is relevant, this is on macOS 11.1 (Big Sur).

**Comment by xiaq** [comment]
The problem is that only the first `use` of a module imports the module correctly; subsequent `use`s imports an empty namespace.
