### ISSUE TITLE
Bug: Path not resolving correctly on Windows 10

### ISSUE THREAD

**Issue by tgrelka** [elves/elvish#1231]
I have a `rc.elv` in my `.elvish` folder in Windows 10 containing one line:
```
eval (starship init elvish)
```

When I start the shell, I get an error:
```
Exception: exec: "/c/Users/Tim": file does not exist
Traceback:
  [eval 1], line 1:
    eval (/c/Users/Tim Grelka/scoop/apps/starship/current/starship.exe init elvish --print-full-init | slurp)
  C:\Users\Tim Grelka\.elvish\rc.elv, line 1:
    eval (starship init elvish)
```

Note how the exception says “/c/Users/**Tim**” does not exist, instead of “Tim Grelka”.

It seems like elvish has a problem with paths containing spaces, at least for the `eval` command - the database with command history and everything else works just fine.

**Comment by xiaq** [comment]
This seems to be a bug of `startship` in that its output does not properly quote paths that contain spaces.
