### ISSUE TITLE
Increase test coverage to 88% before 0.16.0 release

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1234]

**Comment by krader1961** [comment]
I was curious why the existing unit tests did not have sufficient coverage to satisfy this issue. That resulted in me noticing that `IsExecutable()` in *pkg/fsutil/search.go* is unused. Not just in a unit test but unused by the elvish program. That function is theoretically useful. Especially in the context of issues like #1135. TBD is whether to retain and use it.
