### ISSUE TITLE
Broken symlink causes wildcard matching to fail

### ISSUE THREAD

**Issue by muesli** [elves/elvish#1240]
I have a directory with two files in it:

```
file1
file2
```

`file1` is a symlink pointing to a file that doesn't exist anymore.
`file2` is a regular file.

`ls file*` now fails: `Exception: wildcard has no match`

Fixing the symlink of `file`1 resolves the issue.

**Comment by hanche** [comment]
As @krader1961 has mentioned in chat, this issue and #1236 are probably related.

**Comment by krader1961** [comment]
I just tried an experiment with several files and directories, including a dead symlink, in a test dir. Running `put *` **does not throw an error**. It simply stops enumerating files when it reaches the dead symlink. Note that `put d*` does throw an exception. Which suggests there might be a second problem with wildcard expansion; or at least the need to unify some code for consistent behavior.

**Comment by clonejo** [comment]
One example where this bug hits hard is a git-annex repo where not all files are locally available. Those files are then represented by dangling symlinks. Normally you could do move operations on those symlinks just fine, but not having wildcards available makes it a hassle.
