### ISSUE TITLE
Incorrect results when combining braced list with wildcard

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1245]
```
~> touch xy.{u v w} xz.w
~> put x*
⮕ xy.u
⮕ xy.v
⮕ xy.w
⮕ xz.w
~> put x*.{u v w}
⮕ xy.w
⮕ xz.w
⮕ xy.w
⮕ xz.w
⮕ xy.w
⮕ xz.w
```

The cause of the problem is probably thus: the internal glob data structure is being inadvertently shared between the expanded `x*.u`, `x*.v` and `x*.w`, and since the last one was last evaluated it overwrote the previous two data structures.

**Comment by hanche** [comment]
I'd like to see this bug squashed sooner rather than later. It bit me again today. And it ruins the semantics of perfectly reasonable code, making it a serious bug in my opinion.
