### ISSUE TITLE
x~ cannot be set to $nil

### ISSUE THREAD

**Issue by gergelyk** [elves/elvish#1248]
Since initial value of `x~` is `$nil`, I would assume that `$nil` can be assigned to this variable any time.
```
[~]─> var x~
[~]─> put $x~
▶ $nil
[~]─> set x~ = $nil
Exception: wrong type: need nil, got nil
[tty 3], line 1: set x~ = $nil
[~]─>
```

**Comment by krader1961** [comment]
The confusing error message is a known issue, see #744. While it is true it is initalized to `$nil` when you declare the var without giving it a value you can't actually use it:

```
> var x~
> x
Exception: bad value: command must be callable or string containing slash, but is nil
[tty 55], line 1: x
```

A var name ending in a tilde is a function (or command if you prefer) and must be a lambda. You also can't assign a string to it:

```
> x~ = echo
Exception: wrong type: need nil, got string
[tty 56], line 1: x~ = echo
```

**Comment by xiaq** [comment]
@gergelyk Thanks, this is an interesting edge case. Maybe the initial value for `$x~` should be changed to `$nop~`...

**Comment by gergelyk** [comment]
@krader1961, even though `x~` set to `$nil` is not callable, it is still usable. E.g. I can imagine:

```
var callback~
# some code here which may set `callback~`
# some code here which may clear `callback~`
if (is $callback~ $nil) { echo "Nothing to do!" } else { $callback~ }
```

**Comment by krader1961** [comment]
@gergelyk, That's an interesting use case. I'm inclined to agree with @xiaq's proposal that the initial value be changed to `$nop~` rather than special-case `$nil`. If you need to distinguish between code that might assign`$nop~` and an uninitialized state you can always use a unique sentinel value:

```
> var none~ = { }
> var callback~ = $none~
# some code here which may set `callback~`
# some code here which may clear `callback~`
if (is $callback~ $none~) { echo "Nothing to do!" } else { $callback~ }
```

**Comment by gergelyk** [comment]
Yup, I agree. Proposal of @xiaq sounds reasonable.
