### ISSUE TITLE
Built-in namespaces not introspectable

### ISSUE THREAD

**Issue by gergelyk** [elves/elvish#1249]
Should we expect built-in namespaces to be introspectable? I have found none of these working:

```
put (keys $builtin)
put (keys $locals)
put (keys $up)
put (keys $builtin:builtin)
```

**Comment by zzamboni** [comment]
*Style note:* Your example shows a useless-use-of-`put` - you can just run the `keys` commands to the same effect.

The `builtin:` namespace can be introspected if you `use` it first:
```
[~]|> use builtin
[~]|> keys $builtin:
▶ fg~
▶ path-ext~
▶ put~
▶ +~
...
```

The `locals`, `up` and `$builtin:builtin` namespaces do not exist in Elvish AFAIK.

**Comment by gergelyk** [comment]
Thank you, @zzamboni. I confirm, it works very well for builtin.

[Here](https://elv.sh/ref/language.html#scoping-rule) is where I have read about `local` and `up`. They are called namespaces too. `locals` is a typo of mine, but I'm still not sure how to introspect `local`.

Regarding `$builtin:builtin` - if `builtin` is a built-in namespace, I would expect to find it in `builtin` too. This is why I gave a try. It is not necessarily needed though.

**Comment by zzamboni** [comment]
@gergelyk I see - I remember now reading about `local:` and `up:`, but I have never used them as well. I assume because they are "magic" namespaces, they are probably not resolvable all the time.

@xiaq any thoughts about this?

**Comment by krader1961** [comment]
> Regarding $builtin:builtin - if builtin is a built-in namespace, I would expect to find it in builtin too.

While namespaces can be nested `builtin:` isn't a member of `builtin:`. I don't see how that would be useful. You also won't find `math:` (or any of the other bundled modules) inside the `builtin:` namespace.

The `local:` and `up:` namespaces are special lexical scopes. See https://elv.sh/ref/language.html#pre-defined-modules. I don't see any reason it couldn't be made possible to introspect them but it's not clear what the use cases would be. See also issues #668, #999 and #1026.

**Comment by xiaq** [comment]
> Regarding `$builtin:builtin` - if `builtin` is a built-in namespace, I would expect to find it in `builtin` too. This is why I gave a try. It is not necessarily needed though.

I think what led you to this conclusion is that that `$builtin:foo` now works without requiring `use builtin`; I will change that, which is tracked in #1227.

In any case the original issue has been resolved, and the issue with other special namespaces are listed in @krader1961's comment. Closing.

**Comment by gergelyk** [comment]
@krader1961, my initial motivation was to improve python integration. I was thinking of something like:

```
fn py [code]{

# collect local variables from outer scope
vars = [&greeting=hello &name=john]

full_code = "import json, sys
locals().update(json.loads(sys.stdin.read()))
"$code"
"

echo (to-json [$vars]) | python -c $full_code
}

###############################################################################

var greeting = hello
var name = john

py "print(f'{greeting.title()} {name.title()}!')"
```
