### ISSUE TITLE
signaled broken pipe

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#125]
After executing `git log` in `elvish`, it says `signaled broken pipe`

**Comment by xiaq** [comment]
This is not a bug. If you do this in zsh or bash and run `echo $?` afterwards you get 141, which is 128 + `SIGPIPE`.

**Comment by xiaq** [comment]
When the reading process of a pipe (the pager) exits before the writing end, the latter is sent a `SIGPIPE` when it attempts to write. This is expected behavior.

On a side note, if you scroll to the bottom, thus allowing `git log` to write all output, you will not see this error.
