### ISSUE TITLE
Capture output and error at the same time

### ISSUE THREAD

**Issue by gergelyk** [elves/elvish#1250]
Inspired by the [docs](https://elv.sh/ref/language.html#exception-capture) I tried:

```
output = [(error = ?(ls /non/existing/dir))]
```

This raises arity mismatch error though. Is this intended?
```
Exception: arity mismatch: assignment right-hand-side must be 1 value, but is 0 values
```

I just wonder what can be the use case of this construct.

**Comment by SolitudeSF** [comment]
works on my machine with master

**Comment by gergelyk** [comment]
My mistake. I confirm. It works fine.

**Comment by gergelyk** [comment]
On the other hand, this gives arity error

```
[~]─> output = (error = ?(fail "booo"))
Exception: arity mismatch: assignment right-hand-side must be 1 value, but is 0 values
[tty 1], line 1: output = (error = ?(fail "booo"))
```

elvish version: 0.15.0
