### ISSUE TITLE
Request: Support for z/zoxide

### ISSUE THREAD

**Issue by jacostag** [elves/elvish#1251]
It will be nice to be able to use a z helper like this one https://github.com/ajeetdsouza/zoxide

**Comment by krader1961** [comment]
Have you tried Elvish's [location mode](https://elv.sh/learn/cookbook.html)? While I agree that in principal it should be possible to use tools like fzf and zoxide with Elvish I think integrating the best ideas from those tools into Elvish itself is probably a better use of the limited developer resources.

**Comment by zzamboni** [comment]
@jacostag I second what @krader1961 said. I use location mode all the time, and I find it an extremely efficient way of moving around. You can even change directories in the middle of typing a command if you like, and it also keeps a ranking of directories so it offers your most-used ones first. You can also configure the [matcher](https://elv.sh/ref/edit.html#matcher) to use according to your preferences.

Having said that, it's entirely possible to define your own functions backed by external utilities. I don't know `z`, but for a while I was using a custom command-history chooser based on `fzf`, defined using the following code:

```
fn get_history_perl {
  edit:command-history | each [cmd]{
        print $cmd[cmd]"\000"
    } | perl -n0e'print unless $h{$_}++'
}

fn fzf-select {
  fzf --no-sort --tac --read0 --layout=reverse --info=hidden
}

fn history [&hist_fn=$get_history_perl~]{
  err = ?(edit:current-command = ($hist_fn | fzf-select))
}

edit:insert:binding[Ctrl-R] = { history </dev/tty >/dev/tty 2>&1 }
```

You could easily create a similar setup for choosing location, using the output of `dir-history` instead to produce the choices.

**Comment by zzamboni** [comment]
BTW I don't think this feature request belongs to Elvish, as it provides already equivalent functionality, and all the facilities needed to implement it if needed. However, if you put something together, I'd encourage you to publish it on github and submit a PR to the https://github.com/elves/awesome-elvish repository so that others can find it.

**Comment by jacostag** [comment]
Thank you, I like the idea of integrating functionality on elvish directly. Location mode and history mode are already awesome.
I also opened a ticket with zoxide...
I did check some issues trying to support a different shell. On of the best approaches and less intrusives was to use alias.
I just discovered elvish 3 days ago, and I am trying to learn the differences (much more used to ksh, bash and zsh)

The propose alias are this:
#alias:new z [a] {if $(echo $a | empty?) == $true { cd ~ } {echo $a | each { if $it == '-' { cd - } {cd $(zoxide query -- $it | str trim)}}}}
#alias:new zi [a] {echo $(do -i {zoxide query -i $a} | str trim) | each { cd $it }}
#alias:new za [a:block] {zoxide add $a}
#alias:new zq [a] {zoxide query -- $a}
#alias:new zl [] {zoxide query --list}
#alias:new zqi [a] {echo $(do -i {zoxide query -i $a | str trim }) | each { cd $it }}
#alias:new zr [a] {zoxide remove $a}
#alias:new zri [a] {zoxide remove -i $a}

In case that anyone is interested, of course these aliases do not work yet, I have to rewrite them in proper elvish.

Regards

**Comment by ajeetdsouza** [comment]
Hey, I just discovered this issue, so I thought I'd comment here. zoxide v0.6.0 officially supports Elvish.
