### ISSUE TITLE
str:to-upper only takes 1 argument. 

### ISSUE THREAD

**Issue by supreetsingh10** [elves/elvish#1276]
```
~> use str
~> str:to-upper hello there 
Exception: arity mismatch: arguments here must be 1 value, but is 2 values
[tty 2], line 1: str:to-upper hello there 

```

What I think is that it would be better if it can take more than 1 argument.

**Comment by xiaq** [comment]
Well, it is intentional that each function should just do one thing, and what `str:to-upper` does is turning one string to upper case.

To turn multiple strings into upper case, use `each`:

```
put hello there | each [x]{ str:to-upper $x }
```

To concatenate strings and turn them into upper case, use `str:join`:

```
str:to-upper (str:join '' [hello there])
```

**Comment by supreetsingh10** [comment]
Thank you for clearing this out.
