### ISSUE TITLE
`count` now outputs a `num` which breaks common uses of `eq` and `not-eq`

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1288]
While investigating issue #1287 I noticed that the expression in this line was unexpectedly evaluating to true even when I passed a single argument to the script:

```
if (not-eq (count $args) 1) {
```

You can reproduce with these simpler, standalone, examples:

```
> eq 1 (num 1)
▶ $false
> not-eq 1 (num 1)
▶ $true
```

**Comment by krader1961** [comment]
Note that the explicit numeric comparison commands work as expected with the new number system:

```
> == 1 (num 1)
▶ $true
> != 1 (num 1)
▶ $false
```

**Comment by hanche** [comment]
Is it a bug, or is it a feature? Quoth the doc:

> Determine whether all `$values` are structurally equivalent. 

I'd say that the string 1 and the number `(num 1)` are not structurally equivalent, and that one should use `==` and friends to compare numbers.

Whether I am right or not, this needs to be documented better. Also the docs for `eq` should make reference to `==`.

**Comment by krader1961** [comment]
Part of the problem is "structurally equivalent" isn't defined and it's not clear that everyone will have the same intuitive definition. Of course, what really caused the breakage wasn't a change in behavior of `eq` and `not-eq` it's that `count` now outputs a `num` rather than a string. I guess the question is whether `eq` and `not-eq` should coerce a num to a string when comparing the value to a string. That solution, however, creates some ambiguities and may be worse than the current, slightly surprising, behavior. Consider `eq 1 (num 1) (float64 1)` where the comparison of the second and third arguments are clearly not structurally equivalent even though they are numerically equivalent.

**Comment by hanche** [comment]
> Part of the problem is "structurally equivalent" isn't defined and it's not clear that everyone will have the same intuitive definition.

Agreed. Your example is a great illustration: It is not clear to me that `eq 1 (num 1)` should produce a different result than `eq (float64 1) (num 1)`. And should the latter produce the same as `eq 1.0 1`? And if we admit that `eq 1 (num 1)` should return `$true`, what about `eq 01 1`?

Overall, it seems safest to me to keep the current, strict behaviour of `eq` and to document clearly that only `==` will yield the expected result when applied to numbers and number-like strings.

However, users might possibly wish to compare lists `[1 2 3]` and `[1 (num 2) (float64 3)]` with a `$true` result (and similarly for maps). One could achieve that by giving `eq` an option `&numeric`, for example.

**Comment by xiaq** [comment]
This is the intended behavior; I've clarified that in the doc of `eq`. It's an unfortunate backward-incompatible change.
