### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by scateu** [elves/elvish#129]
I just added a testing homebrew support for elvish.

`/usr/local/Library/Formula/elvish.rb`

```
class Elvish < Formula
  desc "elvish"
  homepage "https://github.com/elves/elvish"
  url "https://dl.elvish.io/elvish-osx"
  version "0.0-prebuilt-3f4cf9"
#  sha256 "ab37b773a8db181b1bd031f6d02b1eaacd3cb4731869a1c03dc98304393f4cf9"

  def install
    bin.install "elvish-osx" => "elvish"
  end

  test do
    system "false"
  end
end
```

**Comment by xiaq** [comment]
Are homebrew formulas typically maintained in the upstream repository?

**Comment by scateu** [comment]
Don't know.

**Comment by vendion** [comment]
It looks like this is the procedure to adding a new formula to homebrew [Add a new formula for foo version 2.3.4 from $URL](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md#add-a-new-formula-for-foo-version-234-from-url).  In short it looks like you do need to file a PR to the upstream Homebrew repo.

**Comment by xiaq** [comment]
According to http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x, it is possible to keep the formula in the upstream repository (namely this one). I will accept PR if any of you write one.

**Comment by lastomato** [comment]
I will take a look during the weekend, @xiaq @scateu.

**Comment by lastomato** [comment]
Actually, there is no tags yet as the work is still on its pretty early stage, I think that packaging WIP code doesn't make too much sense. I am going leave this ticket open for now.

**Comment by gaoyifan** [comment]
https://github.com/Homebrew/homebrew-core/pull/4724#event-786968662
