### ISSUE TITLE
Parsing filenames with trailing newlines

### ISSUE THREAD

**Issue by ykonstant1** [elves/elvish#1294]
Hello!  I am playing with the online elvish shell, and tried testing the following commands:
```touch "Hello World\n\n"```
```ls (find . -name "*\n")```
This fails since, as the docs mention, the paren invocation strips a trailing newline.  The docs suggest ```slurp``` to avoid this behavior.  So I tried
```ls (find . -name "*\n" | slurp)```
but unfortunately, this also fails, although the newlines do pass properly to ```ls```.

How can elvish parse filenames like the above properly?

**Comment by zzamboni** [comment]
Honestly, the easiest would be to avoid newline characters in filenames - they are all sorts of trouble in any shell.

Having said that, this is achievable by using `slurp`, but not by itself. The thing is that `slurp` swallows the whole output, including the final newline. You can see this if you run the command by itself, notice there are three `\n` at the end:
```
> find . -name "*\n" | slurp
▶ "./hello\n\n\n"
```
To overcome this, we can use `find`'s `-print0` option, which uses a NUL character as the separator. This will happen both between records, and at the end, as can be seen if we create a second file:
```
> touch "bye\n\n"
> ls
bye\n\n  hello\n\n
> find . -name "*\n" -print0 | slurp
▶ "./bye\n\n\x00./hello\n\n\x00"
```
So now we can work on this by splitting the string on the NULL character, and passing the results to `ls`. One last tweak: we remove the last character of the string returned by `slurp` to eliminate an empty element at the end:
```
> str:split "\x00" (find . -name "*\n" -print0 | slurp)
▶ "./bye\n\n"
▶ "./hello\n\n"
▶ ''
> str:split "\x00" (find . -name "*\n" -print0 | slurp)[0:-1]
▶ "./bye\n\n"
▶ "./hello\n\n"
> ls (str:split "\x00" (find . -name "*\n" -print0 | slurp)[0:-1])
./bye\n\n  ./hello\n\n
```

**Comment by zzamboni** [comment]
BTW I think this type of question is better suited for the forum (see "Join the Community" at https://elv.sh/) rather than GitHub issues.

**Comment by ykonstant1** [comment]
Thank you for the information, it was very illuminating!

**Comment by zzamboni** [comment]
You're very welcome, and welcome to Elvish!

**Comment by krader1961** [comment]
@ykonstant1: In addition to the excellent comments by @zzamboni I will point you to a proposal for disallowing newlines (and other "magic" characters) from file names on UNIX: https://dwheeler.com/essays/fixing-unix-linux-filenames.html. POSIX shells not only do not handle newlines correctly, at least not without a huge amount of effort, they also do not handle file names containing spaces or tabs without significant, careful, effort by the person writing the script. Elvish, at least, limits the catastrophic corner case to just one of three of the problematic chars in a POSIX shell :smile:

**Comment by ykonstant1** [comment]
@krader1961 I have read the proposal, and I agree completely with the spirit.  However, file names in all major OSs are, tragically, also file manager display names.  It is what non-technical people see as "the file's title".

I am a reseacher and expositor.  In my field, filenames with special characters abound: a researcher downloads a paper from arxiv, say 4040.9592.pdf.  They open it, grab the title and authors (and thus  commas, periods, newlines, spaces, hyphens, tex code and high unicode) and paste it in the file name.  It is a widespread practice.  Same for writers, middle managers in non-tech companies and so on.

And *crucially*, from their perspective, it is absolutely the right thing to do!  They are modifying the *display name* of a document to make it easier to identify on their desktop or file manager.  

Being prevented by the system, as in Wheeler's proposal, would be the best compromise in my opinion.  But it is still an unfortunate compromise resulting from desktop environments using the file name as their display name.

Sorry for hijacking the issue to write this, but I think it is an important and overlooked point by many developers.

**Comment by krader1961** [comment]
The original question has been answered and the issue has been quiet for two weeks. Close it? Unless, of course, you have a proposal for how Elvish can handle the filename with an embedded newline case better than it does today. Alternatively, a suggestion for how the documentation could be improved.
