### ISSUE TITLE
bug: command with prefix blank space not be stored in history

### ISSUE THREAD

**Issue by badpooh** [elves/elvish#1296]
```elvish
~> echo 1
1
->  echo 2 # warn: there is a space in front
2
->     echo 3 # warn: there is a TAB(\t) in front
3
-> # press [CTRL] + R
 HISTORY (dedup on)  
 1 echo 1
```
If command have blank space, it's not going to store in history.

**Comment by krader1961** [comment]
Works as expected for me using Elvish built from a recent commit. What does `elvish -buildinfo` output?

**Comment by badpooh** [comment]
Forgot to provide version info.
```bash
~> elvish -buildinfo
Version: v0.15.0
Go version: go1.15.7
Reproducible build: true
```

**Comment by krader1961** [comment]
While v0.15.0 is the most recent published release it is old in Elvish time. :smile: However, I see I misunderstood your original problem statement. I thought you were saying you saw the command lines prefixed by a space in your command history. I now realize you are surprised that a leading space has that effect. I agree with you. This is already under discussion in issue #524 which makes this a duplicate of that issue; although, the subject line of that issue could be improved to make the relationship to command lines prefixed with a space clearer.

**Comment by badpooh** [comment]
Okay, this actually is a feature, surprise.
