### ISSUE TITLE
Tune database to reduce disk writes

### ISSUE THREAD

**Issue by ppwwyyxx** [elves/elvish#130]
One can see 400K/s actual disk write in `iotop`, if constantly entering `ls` in elvish. This is likely caused by sqlite.

**Comment by xiaq** [comment]
True, the database needs tuning.

**Comment by xiaq** [comment]
Now that all database accesses are done in the daemon process (which also is using BoltDB instead of SQLite now), this doesn't seem to be a problem anymore.
