### ISSUE TITLE
Module `math` needs to deal with the new numeric system

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1300]
A recent IRC discussion noted that the `math` module doesn't gracefully handle the newly introduced number system that has types in addition to float64 and string (convertible to float64):

```
> math:max 42
▶ (num 42.0)
> math:max (num 42)
Exception: wrong type of argument 0: must be number
[tty 10], line 1: math:max (num 42)
```

Which leads me to the comment I wrote as [feedback](https://github.com/elves/elvish/pull/1298/commits/bdefdf7bd6180138f92b9afa35b9bd9725cae90d#r627878818) to a related pull-request:

> It seems to me this function (and some of the code in the math module) should be using ScanToGo() rather than an explicit switch size.(type). However, at the present time ScanToGo is not sufficiently general and doesn't support commonly used Go types like int64.

In the context of the `math` module this could be handled two ways. First, generalize the calling context to recognize that a value must be representable by a Go `float64` where that is the type signature in the Go function that corresponds to an Elvish command. That is, an implicit conversion to a float64, or exception if the conversion fails. Similarly for the other Go types -- which includes minimum/maximum errors.

P.S., The current error text contains this:

> Exception: wrong type of argument 0: must be number

It should also tell us what type was seen in addition to what was expected.

**Comment by xiaq** [comment]
There are two things I planned but forgot to implementation for the number system: (1) the implicit conversion of other number types to `float64`; (2) rewriting some functions in `math:` to handle handle different number types, not just `float64`. The commit I just pushed address 1; I'll close the issue after 2 is also addressed.

**Comment by hanche** [comment]
Good!

On the wishlist is a `powmod` function: One that computes a power modulo some integer for unlimited precision integer arguments (a.k.a. bignums). With it, one can start implementing public key cryptography in elvish.

**Comment by krader1961** [comment]
@xiaq, I was tempted to close this because, AFAICT, it looks like most of the  relevant `math` module functions now handle the Elvish `vals.Num` type. However, there are still math builtins, such as `math:atanh` which are directly mapped to the Go math function and therefore do not accept Elvish numeric types that are not a `float64`. Those Elvish commands still require a shim function that handles non-float64 types.

**Comment by xiaq** [comment]
> However, there are still math builtins, such as `math:atanh` which are directly mapped to the Go math function and therefore do not accept Elvish numeric types that are not a `float64`. Those Elvish commands still require a shim function that handles non-float64 types.

Not sure what this is referring to; they already accept all num types (and convert them to `float64`).

**Comment by krader1961** [comment]
> Not sure what this is referring to; they already accept all num types (and convert them to float64).

I, stupidly, overlooked the fact that the conversion of Elvish command arguments handles Go stdlib functions (e.g., `math.Atanh`) as well as Elvish commands written in Go. Thus there is no need for a shim function. /facepalm
