### ISSUE TITLE
Conversion of non-nums to nums

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1313]
While investigating #1312 I wrote a reproducer that didn't depend on `ssh`; only on builtins. That caused me to notice that `num $true` throws `Exception: wrong type of argument 0: must be number`. Similarly, `exit $true` throws `Exception: wrong type of argument 0: must be integer`. The "wrong type" portion of the exception message should include the type of invalid value. But that isn't the core problem.

Note that I was not explicitly doing the above. Instead I was using the output of `== 0 (% $args[0] (randint 1 10))`, which returns a bool, as the input to the two commands. I wanted some elvish invocations to randomly fail. I eventually ended up with this:

```
elvish -c 'exit (if (== 0 (% $args[0] (randint 1 10))) { put 1 } else { put 0 })' $n
```

But that is unnecessarily verbose. It  seems reasonable to use the long established convention that false is equivalent to zero and true is equivalent to one.

**Comment by xiaq** [comment]
> But that is unnecessarily verbose. It seems reasonable to use the long established convention that false is equivalent to zero and true is equivalent to one.

I prefer Go's design choices of not doing implicit conversion between bools and numbers. I find this conversion only more often problematic than useful. So no, sorry.

Also, I think your example is slightly more succinctly written as:

```
if (== 0 (% $args[0] (randint 1 10))) { exit 1 } else { exit 0 }
```
