### ISSUE TITLE
Make math:floor exactness-preserving

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1331]
The five functions `math:floor`, `math:ceil`, `math:round`, `math:round-to-even`, and `math:trunc` all return inexact integers. An option `&exact` to return an exact integer instead, would be most welcome. The main rationale for this is that one can then use the result as an index, where a float is not allowed. Example:

```
⬥ math:trunc -1.2
⮕ (num -1.0)
⬥ math:trunc -1.2 &exact
⮕ (num -1)
```

**Comment by krader1961** [comment]
I think it would be better to augment the places which accept a number (such as a list index), and which require it to be an integer, to automatically perform the conversion if the value is an integer.

**Comment by hanche** [comment]
> … better to augment the places which accept a number (such as a list index) …

That's viable option, and worth doing in any case, I think.

But the particular functions under discussion here inherently produce integers, and in many cases you really want to treat them as _exact_ integers. But not always: After all, if `$x` is very close to an integer, it makes a difference to `floor $x` which side of that integer `$x` falls.

But perhaps, to get a bit more philosophical, my trouble is with the conflation of inexactness and being a float. In real life, not all floats are inexact!

As it currently stands, the `math` module is all about floating point numbers, being just a port of similar functions from go, I think. Which makes me wonder if the module is misnamed. Not all math is about floats! Perhaps I'll start saying `use math float` instead, so I can use the `float:` prefix.

All this is a roundabout way to suggest that perhaps we need exact versions of `floor`, `ceil` and friends, perhaps in a module of their own.

**Comment by krader1961** [comment]
> But perhaps, to get a bit more philosophical, my trouble is with the conflation of inexactness and being a float. In real life, not all floats are inexact!

Right, and the current behavior is a regression. Prior to the introduction of the new number system this worked at commit 5eec2c0:

```
> put [1 2 3 4][(float64 2.0)]
▶ 3
```

It now fails:

```
> put [1 2 3 4][(float64 2.0)]
Exception: index must must be integer
[tty 34], line 1: put [1 2 3 4][(float64 2.0)]
```

Your other points are cogent and I'm pretty sure @xiaq already intends to address them. See this [comment](https://github.com/elves/elvish/issues/1300#issuecomment-835809435) in issue #1300.

**Comment by xiaq** [comment]
The thing here is that `floor` should actually be exactness-preserving. Floor of exact rationals should be exact integers. Floor of (inexact) floats should remain inexact.

**Comment by xiaq** [comment]
Oh, I actually left a TODO in the code. I think I just didn't implement it because Go's big.Rat doesn't support it out of the box, but it isn't hard to implement.
