### ISSUE TITLE
epm:install doesn't work

### ISSUE THREAD

**Issue by 72siddharth** [elves/elvish#1334]
Installed elvish just a day ago, and came across epm.
When I try to install a package, epm says its already installed but when I try to use the package it says the module doesn't exist. The directory for the modules also does not exist.
```
~> use epm
~> epm:install github.com/zzamboni/elvish-modules
=> Package github.com/zzamboni/elvish-modules is already installed.
~> use github.com/zzamboni/elvish-modules/alias
Exception: no such module: github.com/zzamboni/elvish-modules/alias
[tty 2], line 1: use github.com/zzamboni/elvish-modules/alias
```
When I try to install a non-existent package it still says the module is already installed
```
~> epm:install random-non-existent-package
=> Package random-non-existent-package is already installed.
```
Os - Garuda Linux Soaring
Elvish Version - v0.15.0

**Comment by xiaq** [comment]
Can you paste the output of

```
echo $-lib-dir
test -e $-lib-dir/random-non-existent-package
```

**Comment by 72siddharth** [comment]
```
~> echo $-lib-dir
compilation error: 5-14 in [tty]: variable $-lib-dir not found
compilation error: variable $-lib-dir not found
[tty 1], line 1: echo $-lib-dir
~> test -e $-lib-dir/random-non-existent-package
compilation error: 8-17 in [tty]: variable $-lib-dir not found
compilation error: variable $-lib-dir not found
[tty 2], line 1: test -e $-lib-dir/random-non-existent-package
```

**Comment by xiaq** [comment]
Oops. Replace $-lib-dir with $epm:-lib-dir, what's the output?

**Comment by 72siddharth** [comment]
```
~> echo $epm:-lib-dir
compilation error: 5-18 in [tty]: variable $epm:-lib-dir not found
compilation error: variable $epm:-lib-dir not found
[tty 3], line 1: echo $epm:-lib-dir

~> test -e $epm:-lib-dir/random-non-existent-package
compilation error: 8-21 in [tty]: variable $epm:-lib-dir not found
compilation error: variable $epm:-lib-dir not found
[tty 4], line 1: test -e $epm:-lib-dir/random-non-existent-package
```
I'm guessing this should've returned './elvish/lib'? So does this mean I need to explicitly set the value for lib-dir?

**Comment by xiaq** [comment]
Hmm, do "use epm" first before running those commands?

**Comment by 72siddharth** [comment]
Oh well, my bad.
```
~> echo $epm:-lib-dir
/home/sid/.elvish/lib

~> test -e $epm:-lib-dir/random-non-existent-package
0.0064
```

**Comment by xiaq** [comment]
Hmm so the `test` command on your system seems to be off, it's certainly not the standard UNIX test command and that's the cause of the problem. Maybe you built a test program and put it somewhere in your PATH?

epm should be changed to use https://elv.sh/ref/path.html#pathis-dir though, and that'd also avoid such problems.

**Comment by 72siddharth** [comment]
sorry about the test command, completely forgot about it. This is with the standard test command
```
~> test -e $epm:-lib-dir/random-non-existent-package
Exception: test exited with 1
[tty 26], line 1: test -e $epm:-lib-dir/random-non-existent-package
```

**Comment by xiaq** [comment]
Did you remove your own test command from PATH? If so epm:install should work as expected from now on.

**Comment by 72siddharth** [comment]
Ah yes. It works now, thank you.
