### ISSUE TITLE
Create docset for elvish

### ISSUE THREAD

**Issue by shomodj** [elves/elvish#1336]
This would be nice addition to the current documentation, [docset](https://kapeli.com/docsets#dashDocset) is not proprietary format and can be viewed in [zeal](https://zealdocs.org/)

The main benefit of this is that documentation is offline and searchable, also some people (mostly me :) prefer to have their documentation in one central place.

**Comment by xiaq** [comment]
WIP: https://apps.xiaq.me/Elvish.tgz

I'll clean up this a bit (need to remove the top banner and ToC in the HTML) and this will eventually be integrated into the CI.

**Comment by shomodj** [comment]
I created a feed for it at 

https://gist.githubusercontent.com/shomodj/6f50c7464e3fe934e6ef8edfc178ee7f/raw/c7bd4060a86950ccbbcd11e36b202d2e79029afd/Elvish.xml

And added it to Zeal

![Screenshot from 2021-06-12 07-34-08](https://user-images.githubusercontent.com/304768/121767564-cb167180-cb50-11eb-81e7-7dfa1882e935.png)


Few things I noticed:
- icon for elvish is missing
- from `+` to `<s <=s ==s !=s >s >=s` titles are messed up with html encoding like `+%20%7B%23add%7D`

Thanks

**Comment by xiaq** [comment]
> * from `+` to `<s <=s ==s !=s >s >=s` titles are messed up with html encoding like `+%20%7B%23add%7D`

I'm not seeing that in Dash. But I changed some other stuff and re-uploaded; if you still see that, it should probably be considered a Zeal bug.

**Comment by krader1961** [comment]
FWIW, I downloaded Elvish.tgz and added it to my Dash docsets. I don't see the encoding artifact mentioned by @shomodj but the Elvish icon isn't displayed by Dash. Presumably the latter issue is just a matter of including the *website/favicons/favicon.ico* file at the appropriate location in the Dash docset. I did, however, notice a different problem. Links like `Elvish.docset/language.html#File`, for the reference to a "file object" from the documentation for `file:pipe`, does not take the user to the specified HTML anchor -- only to the start of the page.

**Comment by shomodj** [comment]
Updated docset, it looks better now, thx @xiaq 

![Screenshot from 2021-06-13 15-45-46](https://user-images.githubusercontent.com/304768/121812081-80831b00-cc5e-11eb-808b-8a0ca63f5a01.png)

**Comment by xiaq** [comment]
> I don't see the encoding artifact mentioned by @shomodj but the Elvish icon isn't displayed by Dash. Presumably the latter issue is just a matter of including the _website/favicons/favicon.ico_ file at the appropriate location in the Dash docset.

Icon added.

> I did, however, notice a different problem. Links like `Elvish.docset/language.html#File`, for the reference to a "file object" from the documentation for `file:pipe`, does not take the user to the specified HTML anchor -- only to the start of the page.

That's just because the link has been broken (it should be `#file`).

**Comment by krader1961** [comment]
> That's just because the link has been broken (it should be #file).

This is an example for explicit verification of such links in the documentation if feasible. 

Note that I did not explicitly look for a broken link. I simply navigated to a command that I knew was recently introduced and clicked on one of the associated links. Since I found one such occurrence by chance it seems reasonable to assume there are other broken links of this nature. Whether writing code to detect such mistakes is worthwhile is TBD.

**Comment by xiaq** [comment]
> This is an example for explicit verification of such links in the documentation if feasible.

Yeah, I've been meaning to add that as a CI task, but there doesn't seem to be any open-source solution that would work out of the box. Developing such a script wouldn't be too hard though, especially if the scope is constrained to checking relative links (so no need for arbitrary HTTP requests, just walking the generated HTML files is sufficient).

**Comment by xiaq** [comment]
Docsets are now built for each commit; a feed is available on https://elv.sh/ref.
