### ISSUE TITLE
I can't grep help message; help message in stderr

### ISSUE THREAD

**Issue by whoizit** [elves/elvish#1345]
grep not works for help message
```
elvish -h | rg daemon
```
works only this
```
elvish -h 2> /dev/stdout | grep daemon                                                                                                ± master
  -daemon
        run daemon instead of shell
        a file to write debug log to except for the daemon
        path to the daemon socket
```

It's totally incorrect behavior for linux

related issue
https://github.com/nadoo/glider/issues/129

**Comment by xiaq** [comment]
The help flag is `-help`. If you run `elvish -help` the output is written to stdout and can be greped.

But since you mentioned https://github.com/nadoo/glider/issues/129, I read through it and your aggressive behavior in that issue is not OK in this community. Don't do it.

**Comment by whoizit** [comment]
help message should not be posted if key (-h) is not exist

**Comment by whoizit** [comment]
it's not aggression, it's straightforwardness

**Comment by xiaq** [comment]
> help message should not be posted if key (-h) is not exist

Most programs do that.

> it's not aggression, it's straightforwardness

"Straightforwardness" is not an excuse for lack of basic civility.

I don't usually reprimand people, but for the benefit of the rest of this community, I'll document why I called your behavior aggressive:

In https://github.com/nadoo/glider/issues/129, which is essentially the same issue for a different project, the project author asked you what the behavior of other programs are. In https://github.com/nadoo/glider/issues/129#issuecomment-544471686, you replied with:

> I'm not understand what do you mean. You have no experience using Linux/Mac?".

It's clear that this question was **not** being asked in good faith. You were talking to someone who had created software that runs on Linux and Mac, so must have had some experience using Linux or Mac. The only way to understand this response is that you were implying that the author, despite having created software that runs on Linux and Mac, was stupid enough to miss something very basic about Linux and Mac software.

This kind of language is not OK. Don't do it here.

**Comment by whoizit** [comment]
problem still exist, grep not works with -h. print help in stderr - inadequate behavior
if you do not handle -h, you must specify that the -h key is incorrect

**Comment by whoizit** [comment]
I don't know what standards the Go lang community recommends we follow. GNU says to add at least --version and --help 

https://stackoverflow.com/questions/16820245/is-help-flag-a-posix-standard-recommendation
https://www.gnu.org/prep/standards/html_node/index.html

**Comment by zzamboni** [comment]
Both `--version` and `--help` are supported by Elvish.

**Comment by xiaq** [comment]
> problem still exist, grep not works with -h. print help in stderr - inadequate behavior

Print help in stderr when a flag is not supported is the behavior of most "classical" UNIX programs.

For example, the `grep` command itself doesn't support `-h`, and it prints usage to stderr when you do that.

BSD grep:

```
~> grep -h > /dev/null
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
```

GNU grep:

```
~> ggrep -h > /dev/null
Usage: ggrep [OPTION]... PATTERNS [FILE]...
Try 'ggrep --help' for more information.
```

> if you do not handle -h, you must specify that the -h key is incorrect

That's fair, it'd be nicer if `elvish -h` indicates that `-h` is an unsupported flag. But note that this behavior is not really universal; BSD grep shown above doesn't do this.

**Comment by xiaq** [comment]
be84cb0a866f01bf48353b375563adca972ec32e introduced explicitly handling for `-h`. `elvish -h` now indicates that the flag isn't supported.
