### ISSUE TITLE
how to use daemon mode?

### ISSUE THREAD

**Issue by whoizit** [elves/elvish#1346]
i can't find anything about -daemon on site. How to use it? I would expect that to work like `urxvtd` or `foot --server` - single process for multiple instances
I've start elvish without parameters and it shows two processes.
```
user     10050  0.0  0.0 1303764 9920 pts/6    SNl+ 08:53   0:00 elvish
user     10056  0.0  0.0 1154336 8812 ?        SNsl 08:53   0:00 /usr/bin/elvish -daemon -bin /usr/bin/elvish -db /home/user/.elvish/db -sock /home/user/tmp/elvish/sock
```
i've start another elvish and it shows one more elvish process. So I don't understand how it works.

**Comment by xiaq** [comment]
The daemon is only used for accessing Elvish’s database that keeps things like command history, and is started automatically. It does not work as a headless server.
