### ISSUE TITLE
Use "//go:embed" directive when our minimum supported Go is 1.16

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1351]
When Go 1.17 is released, and our minimum supported version becomes 1.16, we should replace the embedded Elvish source with the [`//go:embed`](https://golang.org/pkg/embed/) directive. Moving the embedded Elvish source into files with a *.elv* extension. That will make it easier to edit the embedded Elvish source and easier to spot where such instances are present.

**Comment by krader1961** [comment]
Closing since commit ab59ef90627389bdeb7c035f123968706dac1c03 implemented this idea. Thanks, @xiaq.

**Comment by mqudsi** [comment]
For anyone searching for a match to an error, I believe if you are not using go 1.16, you'll see this error:

> build src.elv.sh/cmd/elvish: cannot load embed: malformed module path "embed": missing dot in first path element

Upgrade and it'll go away.
