### ISSUE TITLE
Discord For Elvish in Order to Expand Community. 

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [elves/elvish#1352]
In order to generate a larger community and discussion around elvish, a proposed discord server with channels about announcements, FAQ's, and differing discussions would greatly help get the word out there. Discord has helped other projects like [tokio](https://discord.gg/AfFqZnE4) and [rust](https://discord.gg/rust-lang-community) foster a community. Elvish's has other community centers but the accessibility and popularity of discord make it the clear front runner.

**Comment by xiaq** [comment]
I haven't really used Discord and can't comment on its merits, but I'm a fan of letting people use their preferred IM app to access the community. I'll look into setting up a discord server and bridging with other IMs.

**Comment by krader1961** [comment]
> the accessibility and popularity of discord make it the clear front runner.

That is a bold assertion, @ChiefMateStarbuck. I've managed to avoid using Discord without feeling like I am not part of any particular project's community of users or developers. I looked at the [Rust home page](https://www.rust-lang.org/) and the only obvious community link is at the bottom of that page: [Ask a Question on the Users Forum](https://users.rust-lang.org/). How does that forum relate to the Discord link you provided? The [READ CONTRIBUTION GUIDE](https://rustc-dev-guide.rust-lang.org/getting-started.html) link does have, at the bottom of its page, this entry: "#contribute and #rustdoc on Discord". Which is the only mention of Discord I could readily find.

**Comment by xiaq** [comment]
> > the accessibility and popularity of discord make it the clear front runner.
> 
> That is a bold assertion, @ChiefMateStarbuck.

Please don't make this conversation unnecessarily confrontational. You can ask whether @ChiefMateStarbuck had evidence to back up that claim without concluding in advance that it is a "bold assertion". Maybe there is enough evidence to back up that claim, maybe there isn't. You can disagree respectfully. Other readers of this issue will draw their own conclusions.

FWIW, the Discord server is featured in the community tab of Rust's website (https://www.rust-lang.org/community).

Personally I find the question of whether Discord is the most popular chat app largely irrelevant. As long as *some* potential users and contributors use it (which is quite likely true), it's worthwhile to reach out to those folks.

**Comment by zzamboni** [comment]
I am in a few Discord communities. I'm not a big fan, but it's OK.

@xiaq: The main thing to consider is that a Discord server can have multiple channels, so I'm not sure how bridging would work. That said, a Discord could be a conduit to start attracting a larger community. It could start with a single channel that gets bridged to the existing ones, and over time grow to have more as needed.

**Comment by xiaq** [comment]
> @xiaq: The main thing to consider is that a Discord server can have multiple channels, so I'm not sure how bridging would work. That said, a Discord could be a conduit to start attracting a larger community. It could start with a single channel that gets bridged to the existing ones, and over time grow to have more as needed.

Yes, that's what I thought. If there's a need for more channels I'll create corresponding channels in other IMs too.

**Comment by xiaq** [comment]
I've set up a Discord guild (or "server") and bridged it to the existing IM platforms. You can join it via https://discord.gg/jrmuzRBU8D (also linked from the https://elv.sh homepage).
