### ISSUE TITLE
`go test -bench=. ./...` fails

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1355]
I ran `go test -bench=. ./...` and was surprised it failed. The most recent commit that successfully executes the benchmark tests is HEAD~284 (commit 5f0e4fc). Any newer commit fails thusly:

```
ok      src.elv.sh/pkg/edit/highlight   0.099s
?       src.elv.sh/pkg/env      [no test files]
goos: darwin
goarch: amd64
pkg: src.elv.sh/pkg/eval
cpu: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
BenchmarkEval_Empty-8                            3297529               363.4 ns/op
panic: runtime error: index out of range [1] with length 0

goroutine 8869 [running]:
src.elv.sh/pkg/eval.(*Frame).ValueOutput(...)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/frame.go:100
src.elv.sh/pkg/eval.(*goFn).Call(0xc000146150, 0xc000147260, 0x0, 0x0, 0x0, 0xc000352030, 0xc0001461
50, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/go_fn.go:237 +0x140c
src.elv.sh/pkg/eval.(*formOp).exec(0xc00011c4d0, 0xc000147260, 0x0, 0x0)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:377 +0x9a2
src.elv.sh/pkg/eval.(*pipelineOp).exec.func1(0x43d5b08, 0xc00011c4d0, 0xc000147260, 0x0, 0xc0001c600
0, 0xc000051b00, 0xc000290000)
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:122 +0x3f
created by src.elv.sh/pkg/eval.(*pipelineOp).exec
        /Users/krader/projects/3rd-party/elvish/pkg/eval/compile_effect.go:121 +0x22c
exit status 2
FAIL    src.elv.sh/pkg/eval     1.978s
PASS
```

I wonder how other open source projects leverage the Go benchmarking facility to regularly collect the information it provides and aggregate it into useful graphs and such.

**Comment by krader1961** [comment]
Googling for "go benchmark tracking" turns up some useful links such as https://pkg.go.dev/golang.org/x/perf/cmd/benchstat and https://blog.seriesci.com/monitoring-benchmarks-over-time-in-go/.

**Comment by krader1961** [comment]
See also https://pkg.go.dev/golang.org/x/perf/cmd for commands to capture and compare benchmark data.

**Comment by xiaq** [comment]
I've fixed the offending tests.

Collection of benchmark data can be done when performance becomes a priority.

**Comment by krader1961** [comment]
> Collection of benchmark data can be done when performance becomes a priority.

Focusing on performance may not be a priority but clearly Elvish users, and potential users, are expecting Elvish to have performance comparable to other shells. If we start tracking how changes affect the performance of existing benchmarks we will be more likely to exercise care when making a change that affects performance. Tracking benchmark results also provides incentive for implementing more benchmarks. The question is whether there is a lightweight mechanism, such as [seriesci](https://blog.seriesci.com/monitoring-benchmarks-over-time-in-go/), we can leverage today with minimal effort to start capturing this data.
