### ISSUE TITLE
Capture stdout and stderr into different variables

### ISSUE THREAD

**Issue by shomodj** [elves/elvish#1357]
It would be really nice if Elvish had this solved without using temp files, for example to catch `stdout` and `stderr` into separate vars

```sh
error_file=$(mktemp)
out=$(some_command 2>$error_file)
err=$(< $error_file)
rm $error_file
```

https://stackoverflow.com/questions/11027679/capture-stdout-and-stderr-into-different-variables

**Comment by zzamboni** [comment]
This can be achieved using pipe. For example, my [util:pipesplit](https://github.com/zzamboni/elvish-modules/blob/master/util.org#parallel-redirection-of-stdoutstderr-to-different-commands) function can be used as-is, like this:
```
|> var out
|> var err
|> util:pipesplit { echo stdout-test; echo stderr-test >&2 } { out = (cat) } { err = (cat) }
|> put $out $err
▶ stdout-test
▶ stderr-test
```

This is still convoluted, but it should be possible to wrap this in another function which simply returns two values, one for STDOUT and one for STDERR.

Of course, I agree it would be nice to have this as a builtin :)

**Comment by shomodj** [comment]
pasting @zzamboni latest code from chat, just in case anyone searches for this (future me:)

```elvish
fn capture [f]{
  var pout = (file:pipe)
  var perr = (file:pipe)
  var out err
  run-parallel {
    $f > $pout[w] 2> $perr[w]
    file:close $pout[w]
    file:close $perr[w]
  } {
    set out = (slurp < $pout[r])
    file:close $pout[r]
  } {
    set err = (slurp < $perr[r])
    file:close $perr[r]
  }
  put $out $err
}
```
