### ISSUE TITLE
How to use other modules in unit tests?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1364]
I was writing a unit test for the `unix:ulimit` command I'm working on. I wanted to construct, using Elvish syntax, a "big int" by doing `(math:pow 2 65)` within the test. I couldn't find a way to make that work. In fact, I can't find any other unit test that does anything similar. I couldn't find a single unit test that relied on one of the builtin modules other than the one being tested and the magic "builtin" module. I worked around not being able to use `math:pow` but it seems to me that either

a) all builtin modules should be available by default in unit tests, or

b) there should be a straightforward means for explicitly using a builtin module other than the one being tested.

The ability to use builtin modules like `re` and `math` is likely to become increasingly useful in writing unit tests. For example, the `unix:ulimit` test needs to validate the stdout byte stream of that command. That is currently impossible without hardcoding a fragile literal string for a `That().Prints()` test. And that is fragile even if the underlying syscall is stubbed which I want to avoid if at all possible.

**Comment by xiaq** [comment]
Add it as part of the evaler setup:

https://github.com/elves/elvish/blob/ebf02e3a9192d43ecd0b67f4ddbdb5230bd6e8d5/pkg/eval/mods/unix/umask_test.go#L16-L18

Change that to

```go
	setup := func(ev *eval.Evaler) {
		ev.AddGlobal(eval.NsBuilder{}.AddNs("unix", Ns).AddNs("math", math.Ns).Ns())
	}
```

You also don't need `math:pow` to construct a bigint; passing a big number to `num` (e.g. `num 100000000000000000000)` is sufficient.

**Comment by krader1961** [comment]
Thanks, @xiaq. I tried that last night without success. I must have had a typo in the `AddNs()` call that I didn't recognize because it was telling me `ulimit_test.go:17: got: variable $math:pow~ not found`. It's working now. I wanted to use `(math:pow 2 65)` to make the intent clearer than a large magic literal. I also need to use `re:match` because the test harness `.Prints()` method doesn't currently support `MatchingRegexp{}` as the wanted value and I don't want to complicate the change by implementing that capability.
