### ISSUE TITLE
Suggestion: (nested) indirect variable expansion

### ISSUE THREAD

**Issue by simonrouse9461** [elves/elvish#1365]
In Bash, variables can be evaluated indirectly with a dynamic name stored in another variable:
```bash
> a=1
> b=a
> echo ${!b}
1
```
Fish shell further allows nested indirect variable expansion:
```fish
> set a 1
> set b a
> set c b
> echo $$$c
1
```
However, Elvish not yet supports this feature. As a versatile shell language in its nature, Elvish is expected to be extremely flexible. So, I suggest to support indirect variable expansion by combining `$` with brace expansion and value capture. For example, `${foo ba{r z}}` can be expanded into `$foo $bar $baz`, and `$(echo foo; echo bar)` will be evaluated to `$foo $bar`. As a result, nested variable expansion becomes naturally possible like this: `${${$c}}`, or even for any combination like this: `${$foo[$idx] (echo $bar)}`.

**Comment by xiaq** [comment]
In Elvish this will be supported by indexing the local namespace, e.g. `echo $local:[b]`. That is tracked in #668.

**Comment by simonrouse9461** [comment]
> In Elvish this will be supported by indexing the local namespace, e.g. `echo $local:[b]`. That is tracked in #668.

@xiaq Does this feature exist in 0.15? Or it will be released along with 0.16?

**Comment by krader1961** [comment]
@simonrouse9461, The capability mentioned by @xiaq is not in the code base: either the 0.15.0 release or elvish built from head. It might be included in the 0.16.0 release but probably won't. If it is included it's likely to be a side-effect of fixing issue #1343.

**Comment by simonrouse9461** [comment]
@krader1961 I see. Thanks for the info!

**Comment by xiaq** [comment]
Closing this as a dup of #668.
