### ISSUE TITLE
Move cursor with ctrl-A and ctrl-E

### ISSUE THREAD

**Issue by simonrouse9461** [elves/elvish#1366]
Most of the interactive command line tools use ctrl-A and ctrl-E to move cursor to the beginning and the end of the input line respectively. Elvish doesn't seem to support this. Is there a reason why this is not supported? Or does Elvish have different key bindings for that?

**Comment by zzamboni** [comment]
`use readline-bindings`

**Comment by simonrouse9461** [comment]
@zzamboni I see. Thanks!

**Comment by simonrouse9461** [comment]
> `use readline-binding`

I found that this actually override the original ctrl+L. Is there a way to have custom bindings that only allow readline-style ctrl-A and ctrl-E without overriding ctrl-L, or bind directory history to some other keys?

**Comment by zzamboni** [comment]
You can reassign any keybindings you want after loading `readline-binding`, see documentation at https://elv.sh/ref/edit.html#keybindings.

For example, see the corresponding section of my config at https://github.com/zzamboni/dot-elvish/blob/master/rc.org#general-modules-and-settings

**Comment by zzamboni** [comment]
Also, for this kind of questions I'd suggest asking in the forum, rather than opening issues. See https://elv.sh/#-join-the-community
