### ISSUE TITLE
Support edit:undo and edit:redo

### ISSUE THREAD

**Issue by simonrouse9461** [elves/elvish#1367]
Recently, fish added support for undo and redo. I don't see a similar api in the "edit:" interface. I think it's a good feature to be added.

**Comment by krader1961** [comment]
Dup of issue #636?

**Comment by krader1961** [comment]
@simonrouse9461: Any reason this shouldn't be closed as a duplicate of issue #636?

**Comment by xiaq** [comment]
Closing as duplicate
