### ISSUE TITLE
Nonstandard number formatting

### ISSUE THREAD

**Issue by fennewald** [elves/elvish#1369]
Got this behavior while doing some weird file moving.

```
~/Downloads/backgrounds> ls
01.jpg	02.jpg	03.jpg	04.jpg	05.jpg	06.jpg	07.jpg	08.jpg	09.jpg	10.jpg
~/Downloads/backgrounds> range 1 11 | each [n]{ printf "%02d\n" $n } | each [n]{ mv $n'.jpg' (- $n 1)'.jpg' }
~/Downloads/backgrounds> ls
0.jpg  1.jpg  2.jpg  3.jpg  4.jpg  5.jpg  6.jpg  7.0.jpg  8.0.jpg  9.jpg
```

Version info:
Version: v0.16.0-dev.4717debfeca7f5e1da43828269514452565067b1
Go version: go1.16.5
Reproducible build: true

**Comment by zzamboni** [comment]
The subtraction produces a numeric type, you'd need to do the printf on
that number as well.

**Comment by fennewald** [comment]
I did some more digging, and it appears that numbers with a leading 0 are formatted as octal. Opening a separate issue.
