### ISSUE TITLE
Compile-time safety, statical analysis, types, assert, etc.

### ISSUE THREAD

**Issue by dumblob** [elves/elvish#1370]
Hi, newbie here.

I couldn't find much information about compile-time safety checking of the given Elvish program. Could you shed some light on that? The more detailed, the better.

Thanks!

**Comment by xiaq** [comment]
Names of local variables are statically checked: https://elv.sh/ref/language.html#variable-use

There isn't much else going on right now. Some kind of static type checking (in a very general sense of the word "type") is likely useful, but type-checking dynamic languages is far from a solved problem.
