### ISSUE TITLE
buildin cmd source  !

### ISSUE THREAD

**Issue by timeloveboy** [elves/elvish#1376]
neet to add buildin cmd
`source `

**Comment by xiaq** [comment]
Elvish intentionally doesn't have a `source` command.

If you want to use functions or variables from another file, use `use`: https://elv.sh/ref/language.html#modules.

If you want to evaluate a piece of code for side effect, use `eval`: https://elv.sh/ref/builtin.html#eval.

If you want to add symbols to the interactive REPL, use `edit:add-var`: https://elv.sh/ref/edit.html#editadd-var.

**Comment by krader1961** [comment]
@timeloveboy, If you still feel a `source` command is needed please provide a concrete example (or two) of how you would use a `source` command that cannot be handled by the mechanisms enumerated in the previous comment.

**Comment by rdw20170120** [comment]
I need this capability, to customize my Elvish shell to configure my PATH, to activate a Python virtual environment, to configure other tools, etc. If Elvish intentionally lacks a source command or equivalent, then how is such shell session configuration supposed to be achieved.

Please note that my (and many other's) use case involves putting all the relevant shell configuration into a code repository as part of a project. Therefore, it MUST NOT involve modifying the user's configuration (in XDG directories and files).

Can this be done in Elvish, or must I look for another shell?

**Comment by xiaq** [comment]
Closing this - see #453 for alternatives to `source` in Elvish.
