### ISSUE TITLE
[crash] fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by judaew** [elves/elvish#1389]
Elvish crashes after executing the binary file Build installed with [MacPorts](https://ports.macports.org/port/elvish/details/). Tested on macOS 11.5.2 x86_64, elvish v0.16.1.

```console
$ elvish
Cannot connect to daemon: daemon unreachable after waiting for 1s
Daemon-related functions will likely not work.
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2040ec9e]
```

[crash_elvish.txt](https://github.com/elves/elvish/files/7045739/crash_elvish.txt)

**Comment by stefanb** [comment]
It seems MacPorts builds with [go 1.17](https://ports.macports.org/port/go/) which is not yet ok for elvish 0.16.1

This could be fixed by https://github.com/elves/elvish/pull/1390 & making a new release.

**Comment by judaew** [comment]
Thanks, this PR fixes this issue for MacPorts.

**Comment by stefanb** [comment]
I'd suggest reopening this issue until PR #1390 is merged and release made

**Comment by judaew** [comment]
OK, done

**Comment by stefanb** [comment]
Yes.
I was expecting it to close automagically with the merge of PR with description "closes #...", but apparently this didn't happen.

**Comment by judaew** [comment]
@stefanb Thanks for fix!
