### ISSUE TITLE
Proper way to configure PATH in elvish?

### ISSUE THREAD

**Issue by vendion** [elves/elvish#139]
Normally I would launch Elvish from ZSH where ZSH has already set various environment variables and correctly configured my PATH and Elvish just uses these preset variables without any issue.

Trying to setup a _$HOME/.elvish/rc.elv_ file so elvish could be used as a standalone shell, instead of launching from another shell, and following the information in both the README and the wiki there seems to be some mix match going on.

The rc.elv file I'm testing with is as follows
```
~> cat .elvish/rc.elv
env:GOROOT="/usr/local/go"
env:GOPATH=$env:HOME"/gocode"
env:GOBIN=$env:GOPATH"/bin"
env:PATH=$env:GOROOT"/bin:"$env:HOME"/bin:"$env:GOBIN":/usr/local/bin:/usr/local/sbin:/usr/local/opt/ruby/bin:"$env:HOME"/.fzf/bin:"$env:PATH

fn tmux { /usr/local/bin/tmux -2 }
fn _ { sudo $@ }
```

After launching a new terminal window running elvish as the shell and checking the environment variables they seem to be correctly set
```
~> put $env:GOROOT
▶/usr/local/go
~> put $env:GOPATH
▶ /Users/vendion/gocode
~> put $env:PATH
▶ /usr/local/go/bin:/Users/vendion/bin:/Users/vendion/gocode/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/ruby/bin:/Users/vendion/.fzf/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

This seems to be all expected behaviour, but things start to get odd when I run `put-all $paths`
```
~> put-all $paths
▶ /usr/bin
▶ /bin
▶ /usr/sbin
▶ /sbin
```

That doesn't contain all the paths I defined in the _rc.elv_ file nor what is in `$env:PATH`.  Things get weirder when trying to launch a program that exists in a directory that is in `$env:PATH` but not in `$paths`.

```
~> which vim
/usr/local/bin/vim
~> vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2015 16:22:14)
Compiled by root@apple.com
...
~> /usr/local/bin/vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 16 2016 10:59:23)
MacOS X (unix) version
Included patches: 1-1301
Compiled by Homebrew
...
```

So even though commands like `which` is correctly working with what `$env:PATH` has set, as _/usr/local/bin/vim_ would be found before _/usr/bin/vim_, when executing commands it seems to use what is set in $paths not $env:PATH.  Is there something I overlooked to get `$env:PATH` and `$paths` to be in sync?

My environment:
OS: Mac OSX 10.11.3
Terminal: iTerm2 with one profile set to use ZSH for the `$SHELL` and another set to use elvish for the `$SHELL`.

**Comment by xiaq** [comment]
True, `$path` is only updated at startup (that is, before loading `rc.elv`) and doesn't sync with `$env:PATH`. The search mechanism uses `$path`, but it is `$env:PATH` that gets exported to external commands, which explains what you observed.

**Comment by xiaq** [comment]
One-way syncing has been implemented. The other direction (`$paths` -> `$env:PATH`) is not yet, but at least now assigning to `env:PATH` does what you mean.

I will implement the other direction in the coming weeks. The variables that expose elvish internals like `$paths` and `$le:binding` have some duplicate code, and now that I can see the pattern, I will first clean them up in a systemized manner.

**Comment by xiaq** [comment]
@vendion Two-way syncing has been implemented in 2ac73b4eba6d3b8ca39ee3666644cdd3c5daa24a. You can now either set `$env:PATH` to a string like `env:PATH=/bin:/sbin:/usr/bin` or set `$paths` to a list like `paths=[/bin /sbin /usr/bin]`. To append and prepend to the list, write `paths=[/a/b $@paths /c/d]` (there might be room for a better syntax).

`$env:PATH` and `$paths` are always kept in sync, and they correctly affects elvish as well as external commands run from elvish.

**Comment by xiaq** [comment]
Oops, `paths=[/a/b $@paths /c/d]` doesn't actually work. Tracking in #143.

**Comment by xiaq** [comment]
`paths=[/a/b $@paths /c/d]` now works.

**Comment by vendion** [comment]
I like being able to set the PATH via `$paths` that approach makes it feel more like ZSH, plus working with PATH as an array/list makes more sense than a long string in my opinion.
