### ISSUE TITLE
Version wasn't raised in 0.16.2 release

### ISSUE THREAD

**Issue by stefanb** [elves/elvish#1392]
With the release of 0.16.2 the version stayed the same:
https://github.com/elves/elvish/blob/980a391ba55679da164e546a320175adbf49e401/pkg/buildinfo/buildinfo.go#L19

Failing the check during elvish upgrade attempt in homebrew: https://github.com/Homebrew/homebrew-core/pull/84111

**Comment by xiaq** [comment]
Fixed in https://github.com/elves/elvish/commit/4fb12ee2b85801c324f100998ff8bc98f3acd524
