### ISSUE TITLE
keybinding w/ interactive fn makes elvish non-responsive

### ISSUE THREAD

**Issue by crinklywrappr** [elves/elvish#1397]
I wanted to make a [navi](https://github.com/denisidoro/navi) `widget`, but adding a keybinding for a fn seems to break elvish.  I'm probably doing something wrong, and it would be nice to get some direction.

```
fn call-navi []{
  navi --print
}

edit:insert:binding[Alt-h] = $call-navi~
```

**Comment by krader1961** [comment]
Please tell us how that broke Elvish? I did the same thing, but replaced the `navig --print` with a simple `put yes` and it did what I expected. That is, caused Elvish to report that the function wrote the value "yes". I suspect this is an [XY Problem](https://xyproblem.info/). What happens if you instead just run `navi --print` from an interactive shell prompt?

**Comment by krader1961** [comment]
@crinklywrappr, See https://github.com/elves/elvish/issues/1053#issuecomment-859223554 where I show how to use `fzf` to insert the output of that command into the command line.

**Comment by crinklywrappr** [comment]
@krader1961 it seems to work fine if the command being executed is non-interactive.

`navi --print` presents an interactive prompt.  Running the command normally works, but the interactive prompt isn't drawn when using the keybinding.

**Comment by krader1961** [comment]
@crinklywrappr, I think you mean something different than my understanding when you say "interactive prompt". The `fzf` command has an "interactive prompt". The key is having it write the desired value to the stdout byte stream and capturing that data as I showed in my `fzf` example I linked to. In your example you are not capture the output of `navi --print`.

**Comment by crinklywrappr** [comment]
Thanks @krader1961 

This works well enough for my needs!

```
fn call-navi []{
  answer = (navi --print)
  edit:insert-at-dot $answer
}

edit:insert:binding[Alt-h] = []{ call-navi >/dev/tty 2>&1 }
```

I don't think it's good enough to submit to `navi` as a PR.  The team seems to want a way to take segments of input and provide it as query parameter to navi eg `wget thing | untar<keybinding>` -> `wget thing | tar xvf`

I don't see a way to accomplish this in elvish, but I welcome your greater knowledge if you do!  🙂
