### ISSUE TITLE
Enforce type of function argument ending in tilde

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1402]
(I admit this is very minor. But hopefully fixing it is very quick and easy, too.)

It is often useful to name a function argument expected to be a function with a trailing tilde, so the function body can call it without the initial `$`. Contrived example:

```
⬥ fn foo [x~ y]{ x $y }
⬥ foo [z]{ put $z$z } bar
⮕ barbar
```

Elvish enforces the convention that variables with a name ending in `~` must have a function value:

```
⬥ var x~ = bar
Exception: wrong type: need nil, got string
```

So far, so good (except for the `need nil` part, but that is covered in a different issue). But this convention is not enforced for _function arguments_.

```
⬥ fn foo [x~]{ put $x~ }
⬥ foo bar
⮕ bar
```

For consistency's sake, and for better error reporting, I think this should also raise an exception like in the variable assignment case above.

**Comment by krader1961** [comment]
@hanche, Isn't this a duplicate of #1289 that you opened six months ago? I'm guessing you have been bitten more than once because the current Elvish implementation does not impose such a restriction. :smile: See also #1248.

**Comment by hanche** [comment]
@krader1961 Good grief, you're right!

I have from time to time searched the net for a solution to some vexing problem, only to end up at one of my own answer at a stackexchange site. It must be the same phenomenon at work.
