### ISSUE TITLE
cd generates an error

### ISSUE THREAD

**Issue by caedmon-kitty** [elves/elvish#1403]
Downloaded version 0.16.3 today.

host> cd
Exception: exec: "builtin:cd": executable file not found in $PATH
Traceback:
  /home/michael/.elvish/lib/local/elvish/dir.elv, line 80:
        builtin:cd $@dir
  [eval 7], line 2:
    fn cd [@_args]{ use local/elvish/dir; dir:cd $@_args }
  [tty 1], line 1:
    cd
host> which elvish
/home/caedmon/bin/elvish

The previous version 0.15.0 worked fine.

**Comment by xiaq** [comment]
You now need to `use builtin` before using the builtin namespace. Add that to the beginning of /home/michael/.elvish/lib/local/elvish/dir.elv.

**Comment by caedmon-kitty** [comment]
Thank you.  Sorry if I missed it in the documentation.

**Comment by krader1961** [comment]
@caedmon-kitty, FWIW, this was a relatively recent change made at my request for consistency with all the other builtin modules. See https://elv.sh/blog/0.16.0-release-notes.html.
