### ISSUE TITLE
A variant of “or” (and possibly “and”) that treats only nil values specially.

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1404]
Quoting myself from chat:

> I found myself wanting a variant of `or` that will only skip `$nil `values, not `$false`. The idea being that `$nil` typically means “no value”, whereas `$false` is a definite value that I might want to capture.
> 
> Think of it as an analogue of SQL's COALESCE function.
> 
> So, if we adopt the name from SQL,
> 
> `coalesce $nil $false (fail foo)`
> 
> should output `$false` (and not throw any exception).

Responses from @xiaq and @krader1961 amount to a cautious “maybe”, which is why I turned it into an issue.

Two minor questions:

- Should it be an option to `or`, as in `or $nil …`, instead of having its own name?
  One argument in favour that is that this would not be an ordinary function, but has to be treated specially, i.e., as language syntax. And the fewer keywords in the language, the better. So I think that is a reasonable suggestion. (Besides, it saves us the trouble of finding a suitable name.)
- Should we do the same for `and`?
  I can't for the life of me think of a use case, but that does not mean nobody would find it useful, and arguments of symmetry with `or` says we should.

The bigger question is whether the feature is worth the effort of implementing it. I honestly don't know. What I do know is that I only found myself wanting it now, after using elvish for quite some time. So it may not be used all that often, perhaps. OTOH, it seems sufficiently useful that people will reach for it more often if it is available. I leave it to others to code up an AI to find all (or most) instances in publicly available elvish code where this feature could have come in handy. 😉

**Comment by zzamboni** [comment]
This gets a cautious 👍 from me - I can see its usefulness but it's fairly limited, and can also lead to confusion.

The main use case that comes to mind is in assigning configurable default values to function options which require a boolean value. Since an option's default value cannot be a variable, I have found myself more than once writing code like this:

```
var default-opt-value = foo

fn some-func [&opt=$nil] {
   if (eq $opt $nil) {
    set opt = $default-opt-value
  }
...
```

For a real example, see the `allow-v` parameter in my [semver module](https://github.com/zzamboni/elvish-modules/blob/master/semver.org#parsing-and-validating-version-numbers).

**Comment by xiaq** [comment]
I suggested a counterpart to `and` but can't think of any use cases either.

I slightly prefer just adopting SQL's `coalesce` name - it's perfectly intuitive to me but that may be just because I write a lot of SQL in my day job :)

**Comment by xiaq** [comment]
No command named `coalesce` packaged by [Debian](https://dyn.manpages.debian.org/jump?q=coalesce) or [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=coalesce&apropos=0&sektion=0&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html).
