### ISSUE TITLE
Re-importing a module

### ISSUE THREAD

**Issue by dangerousHobo** [elves/elvish#1408]
I have a module that I'm using to setup a build environment. This module defines some global variables, some functions, and some command completion stuff. The work flow goes like so:

```sh
#in project directory, current shell is bash
./bin/elvish #enter elvish interactive shell
use ./source-me #load module to setup development environment
#run commands defined in module
```

During development and making changes to this module. I'd like to be able to just run `use ./source-me` to bring in the current changes. I [see this is not supported](https://elv.sh/ref/language.html#re-importing). Are there any changes to my work flow that would allow this? Long ago I was using `-source ./source-me.elv` to reload changes and that seemed to work without issue.

**Comment by krader1961** [comment]
@dangerousHobo: Have you considered using `exec elvish` to get a fresh shell in which you can `use ./source-me` again? Also, why not automatically import that module, if it exists, in your *rc.elv*? Then all you have to do is `exec elvish`.

**Comment by dangerousHobo** [comment]
Thanks for the replies. I'll go with `exec ./bin/elvish` followed by `use ./source-me`. The shell and module are contained in a project. One requirement is that the project repo contains everything needed to build the software, so having the user setup and use `rc.elv` is a non-starter.
