### ISSUE TITLE
Remove the local: and up: special namespaces

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1409]
These special namespaces don't behave like normal namespaces and require special support for introspection (e.g. #1343). It's simpler to just remove them, since they're not really essential anywhere. FWIW, `builtin:` also used to be a special namespace, and was demoted to a normal namespace that can be imported with `use builtin`.

The existence of `local:` also leads to some unnecessary usage - e.g. writing `$local:a` to ensure that the code is accessing the local `$a`. Since Elvish always resolves local variables first, `$local:a` can always be replaced with `$a`.

One valid use case for `local:` is shadowing variables - `local:a = foo` always creates a new variable, as opposed to `a = foo` which might be assigning `$a` from an outer scope. But `var a = foo` now does the same thing and is preferred.

The removal of `up:` does lead to some loss of functionality, since it could be used to access shadowed variables. However, this should be rare enough, and no other language I am aware of provides a mechanism to access shadowed variables, and they seem fine.

Timeline:

* Deprecate in 0.17.0
* Remove in master branch after branching of 0.17.x

I took a brief survey of uses of `local:` "in the wild" on GitHub and it seems that the majority of places are just using it to declare local variables; such uses are already handled by the [upgrader](https://go.elv.sh/u0.17), which will rewrite `local:a = x` to `var a = x` (stripping the `local:`), so I'll probably not include this migration in the upgrader.

**Comment by krader1961** [comment]
It occurred to me that you would be removing the `local:` namespace in light of introducing explicit variable declaration using `var`. I concur that the new syntax and semantics is preferable.

Regarding the `up:` namespace I assumed it was inspired by something like the TCL [`uplevel`](https://www.tcl.tk/man/tcl8.4/TclCmd/uplevel.html) command. But, yes, I can't really see much value in retaining the feature and thus it is reasonable to remove it. Also, shouldn't it be possible to achieve the same result by assigning the value of the enclosing lexical scope before defining a new local var with the same name?
