### ISSUE TITLE
"Exception: arity mismatch" error while variable declaration with assignment

### ISSUE THREAD

**Issue by EmilySeville7cfg** [elves/elvish#1418]
Elvish version: 0.13+ds1-2
OS version: Linux Mint 20.2 Cinnamon

I just typed example from [docs](https://elv.sh/learn/tour.html) in terminal:
```elvish
var foo = bar
```

and obtained `Exception: arity mismatch`.

**Comment by krader1961** [comment]
The `var` and `set` builtins were added in the 0.15.0 release. In the 0.13 release you're using they are just regular tokens (e.g., var names) so you have two var names and one value. Hence the arity mismatch.

**Comment by krader1961** [comment]
Try a current release of Elvish from https://elv.sh/get/

**Comment by EmilySeville7cfg** [comment]
Everything works fine. :)
