### ISSUE TITLE
Require "try" to be followed by an "except" or "finally" block

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#1424]
People might write `try { ... }` and expect that it would suppress exceptions, but it doesn't. The `try` itself doesn't really do anything, one needs an `except` to do that - `try { ... } except { }` does suppress exceptions.

JavaScript and Python (and possibly other languages) require `try` to be followed by an `except` or `finally` block. Elvish should do the same.

Elvish also supports an `else` block that is run if no exceptions were thrown. However, AFAICT it is only useful when combined with an `except` block; the behavior of `try { x } else { y }` is the same as just `x; y`.

**Comment by derekmahar** [comment]
Isn't `try { x } except { y } else { z }` equivalent to `try { x } except { y }; z`?

**Comment by xiaq** [comment]
> Isn't `try { x } except { y } else { z }` equivalent to `try { x } except { y }; z`?

Only when `y` also triggers an exception.

If `y` doesn't trigger any exception (which is probably more common), the first snippet only executes `z` when `x` doesn't throw an exception, while the second snippet always executes `z`.

**Comment by iandol** [comment]
Coming from MATLAB, a `try { }` by itself is equivalent to an empty catch block (i.e. it silently drops the exception), which is why I at least was surprised that `try { x }` was different to  `try { x } catch { }` — the `try { x }` syntax is a bit more concise when you don't care about the exception. But I suppose your consistency to major scripting languages is an important factor!

**Comment by krader1961** [comment]
I am ambivalent about the current, and proposed, behavior. It seems to me that either a bare `try` block should suppress exceptions or it should be syntactically invalid. In the latter case an explicit `except` clause should be required; regardless of whether a `finally` or `else` clause is present.
