### ISSUE TITLE
TOC section headings in the documentation should provide a link to that section

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1426]
The recent improvements to the Elvish web pages reminded me of a missing feature I fervently wish were implemented. To wit: Each section heading that appears in the TOC (table of contents) should provide a way to copy the relative link to that section heading. For example, hovering over the section heading for the definition of [exceptions](https://elv.sh/ref/language.html#exception) should provide a way to see/copy the URL to that section. This would make it significantly easier to figure out the appropriate link to use in documentation I'm writing.

Hopefully this is something that is easy to implement because the Pandoc tool used to generate the Elvish documentation already provides a mechanism for that behavior.

**Comment by xiaq** [comment]
> Hopefully this is something that is easy to implement because the Pandoc tool used to generate the Elvish documentation already provides a mechanism for that behavior.

I can't find that in Pandoc's documentation, do you mind pointing out what that mechanism is?

**Comment by krader1961** [comment]
Sorry, that was meant as a statement of hope -- not that I know Pandoc can do it. I skimmed the Pandoc dos and didn't see an obvious knob to generate such links. It may be necessary to manually add CSS and Javascript. I tried googling what I thought were likely terms but didn't find an answer but that likely just reflects my relative lack of advanced HTML/CSS knowledge.

**Comment by xiaq** [comment]
I see. Since pandoc's own website has those anchor links I did some digging and this is how it is done: https://github.com/jgm/pandoc-website/pull/50

**Comment by xiaq** [comment]
The licensing of the entire pandoc-website is unclear though. Pandoc is covered by GPLv2, so it's better to assume that the website code is also GPLv2. It's safer for me to reimplement this.

**Comment by krader1961** [comment]
LGTM. Much thanks for implementing this.
