### ISSUE TITLE
How should modules be documented and referred to?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1430]
I was working on an improvement to the `path` module documentation when I noticed something unexpected. Commit #41cbcfb1b181a4f15ed1b5a56247aa94f5c2e6db moved most of the documentation for the `re` module from its *re.md* file to the  corresponding *re.go* file. That changed how the vars and functions in that module are documented; i.e., by adding a `re:` prefix that wasn't previously present. I noticed this because the `@cf eval-symlinks` in the `path` module documentation no longer worked. So the real problem is that an earlier change modified how links to other parts of the documentation work but not all of the affected references were updated.

This seems like a good time to suggest a related change: Elvish URI fragments should include a separator char between the module name and its variable or function. So, for example, rather than `#resplit` it would instead be `#re:split` (or whatever makes more sense given the relevant standards).

**Comment by krader1961** [comment]
It appears that HTML anchor tag IDs can contain colons. See, for example, https://stackoverflow.com/questions/70579/what-are-valid-values-for-the-id-attribute-in-html. Changing how the HTML anchor IDs are written will, of course, invalidate existing URLs that use the current representation. Invaliding currently valid URLs should not be done lightly. However, in this case I think the improved clarity justifies the change. And doing so will still take the user to the desired web page -- just not positioned to the desired section of the document.

**Comment by zQueal** [comment]
cheat.sh might be a good way. You can color or not color, and everything is text formatted. Only dependency is curl, or another curl like utility.

    curl cheat.sh/lua/:list

to show a list of topics.

    curl cheat.sh/lua/Functions

show functions and simple examples, etc. Doing this you can basically copy and paste what's already available to a repo, and make it available to cheat.sh.

**Comment by krader1961** [comment]
@zQueal: Did you perhaps mean to add your comment to issue #1432?

**Comment by krader1961** [comment]
LGTM. Much thanks for tackling this.
