### ISSUE TITLE
RFC: Add a simpler control struct for executing a loop N times?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1433]
The only aspect of Elvish that still annoys me is writing simple loops to be executed *N* times. Go has a C like construct for this case:

```
for i := 0; i < 10; i++ {
	f(i)
}
```

While in Elvish that would be written thusly:

```
for i [(range 10)] {
    f(i)
}
```

The Elvish formulation is more succinct. But it's also considerably less efficient (especially for large values of *N*) since it requires instantiating a list then ranging over it. I'm not suggesting adding the Go syntax but it would be nice if there was an even simpler, more efficient, way to perform this common operation. The simplest, most Elvish, solution I can think of is to augment the builtin `range` command to accept an optional argument that takes a lambda. Thus allowing the above to be written like this:

```
range 10 {|i|
    f(i)
}
```

**Comment by shizhaojingszj** [comment]
Taking lambdas as arguments is generally a better idea to me. I'd like to learn these syntaxes if embeded to elvish shell.

**Comment by iandol** [comment]
Yes, I think this would be a great addition, I also have this shortcut in my rc.elv:

```
fn repeat-each {|n f|
	for i [(range $n)] { $f }
}
```

`repeat` makes more sense to me (in a common language meaning sense), but currently that command only copies a value X times. One idea would be to extend `repeat` so that it could also take functions:

```
⟨~⟩❯ repeat 3 (randint 10)
▶ (num 3)
▶ (num 3)
▶ (num 3)

⟨~⟩❯ repeat 10 { randint 10 }
▶ (num 7)
▶ (num 4)
▶ (num 9)
```

**Comment by krader1961** [comment]
> One idea would be to extend repeat so that it could also take functions

`range` is more general and if my idea were implemented it would be trivial to replace `repeat 4 NAN` with `range 4 {|_| put NAN }`. Using `range` in that way also makes it easy to use the current iteration count: `range 1 5 {|n| put 'iter#'$n }`.

**Comment by krader1961** [comment]
I don't know how easy it would be to implement but it would be nice if `range` could call a lambda that accepted one or zero arguments. That way you could write `range 4 { put NAN }` rather than `range 4 {|_| put NAN }` if you don't care about the current value.

**Comment by zQueal** [comment]
This seems like a much more natural approach to me. I love it.

**Comment by krader1961** [comment]
While refactoring the `range` implementation to support counting down (see issue #1436) I noticed that allowing an optional lambda would be most easily implemented by adding an option rather than another optional argument. In other words, implementing this would be easiest if the signature was `range $start? $end &step=0 &fn={|n| put $n}`.  It can certainly be implemented without requiring the `&fn` option prefix but that would greatly complicate the implementation. Opinions?

**Comment by iandol** [comment]
In general for interactive or casual use, the less syntax we have to type the better, so all other things being equal `range 0 5 { |n| echo $n }` is cleaner/simpler than `range 0 5 &fn={ |n| echo $n }` — but things are not equal in that implementation is easier for the latter. I would rather have this option than have nothing…

**Comment by hanche** [comment]
I think the optional lambda is the way to go. But I would name the option more suggestively: I propose `&map`, to clearly show that the function is mapped over the values in the range: `range 0 5 &map={ |n| * $n $n }` seems to make it clearer to the novice that you are producing squares.

**Comment by xiaq** [comment]
`range 10 &fn={|n| echo $n}` isn't that much shorter than `range 10 | each {|x| echo $x}`.

Personally I think the slightly verbose `range n | each {|x| ...}` form is fine, you don't need to add anything extra or require people to learn anything extra.

**Comment by iandol** [comment]
@hanche 
> seems to make it clearer to the novice that you are producing squares

As a causal programmer, the use of the term `map` is not immediately clearer 😅. It is the same IMO with `range` vs. `repeat`: common english meanings are clear (repeat is clearly a verb, range is a noun that can **also** be used as a verb). I think elvish should appeal to casual users, and syntax should be as general as possible. Perhaps it is a cultural sign of imperative vs. functional styles, or just a demonstration of my ignorance 😊

**Comment by hanche** [comment]
Haha, you have a point there. It seems that `each` is under-utilized. I myself don't use it half as much as I ought to, I think. How about adding an example to the documentation of `range`?

**Comment by krader1961** [comment]
Like @hanche I don't think of using `each` as often as I probably should. I'm inclined to agree that supporting something like `range n &fn={|x| ...}` isn't worthwhile even if, as I suspect, it would be marginally more efficient than the equivalent pipeline involving `each`. So consider this proposal withdrawn. I'll make a P.R. that includes an example and rationale in the `range` documentation after the P.R. for #1436 is merged.

**Comment by krader1961** [comment]
I think this is a good example why adding examples, and explanatory text, to the documentation can have significant benefits given that several of the long term Elvish users, including myself, didn't immediately recognize the `range n | each` form was the idiomatic equivalent to my proposal. My hope is that everyone lurking who might be hesitant to propose improvements to the documentation will take this issue as an example why they should at least open an issue or, even better, create an actual change to the documentation.

**Comment by zzamboni** [comment]
I agree that `each` would be the most idiomatic way to do this.

Since @krader1961's initial comment mentioned efficiency, I should point out that using `range ... | each` seems noticeably less efficient than `for x [(range ...)]` in terms of runtime:

```
|> @times = (range 10 | each {|i| time &on-end=[t]{ put $t } { var total = 0; for x [(range 10000)] { set total = (+ $total $x) } } })
|> / (+ $@times) (count $times)
▶ (num 0.47202234709999996)
|> @times = (range 10 | each {|i| time &on-end=[t]{ put $t } { var total = 0; range 10000 | each [x]{ set total = (+ $total $x) } } })
|> / (+ $@times) (count $times)
▶ (num 0.5455861848)
```

**Comment by krader1961** [comment]
@zzamboni: Try this version on your system. It eliminates the closure capture and cost of the math and assignment. It thus more accurately reflects the cost of each range+lambda construct:

```
#!/usr/bin/env elvish
use math
range 1 9 | each {|exp|
    var n = (math:pow 10 $exp)
    var @ts1 = (range 3 | each {|_| time &on-end=$put~ { for _ [(range $n)] { nop } } } | order)
    var t1 = $ts1[0]
    var @ts2 = (range 3 | each {|_| time &on-end=$put~ { range $n | each {|_| nop } } } | order)
    var t2 = $ts2[0]
    var delta_pct = (* 100.0 (- 1 (/ $t1 $t2)))
    printf "range 10^%d: for %11.6f, each %11.6f, delta %+5.1f%%\n" $exp $t1 $t2 $delta_pct
}
```

I would expect the small `$n` cases to favor the `for` construct while the large `$n` values might favor the `each` construct. Here is a representative run of the above program on my main macOS server:

```
range 10^1: for    0.000207, each    0.000175, delta -18.6%
range 10^2: for    0.001341, each    0.001197, delta -12.0%
range 10^3: for    0.012397, each    0.010498, delta -18.1%
range 10^4: for    0.124259, each    0.113158, delta  -9.8%
range 10^5: for    1.299611, each    1.193217, delta  -8.9%
range 10^6: for   12.642846, each   11.983693, delta  -5.5%
range 10^7: for  128.134012, each  121.910828, delta  -5.1%
range 10^8: for 1335.565923, each 1234.275465, delta  -8.2%
```

There is a lot of variability in the results for the small ranges but on my server the `each` construct is always faster. **Note:** The `for _ [(range $n)]` construct consumes between two and three orders more memory for large values of `$n` compared to the `each` construct. The 10^8 case causes my system to thrash due to swapping when using the `for` construct but not when using the `each` construct.

**Comment by krader1961** [comment]
> (I mean - "noticeably" in the tenths-of-a-second scale 😉 so irrelevant in most practical terms unless it's for very large ranges)

@zzamboni: Any performance difference, at least greater than microsecond magnitude, is significant for non-interactive uses. I have been dismissive of complaints about the speed of Elvish in the past but am now starting to think Elvish is mature enough that performance of core features deserves attention.

**Comment by krader1961** [comment]
I ran my [benchmark program](https://github.com/elves/elvish/issues/1433#issuecomment-980823289) again using an `elvish` binary that includes commit 64661d6b to improve the performance of a common case that doesn't require the overhead of a new goroutine. The results are, as expected, considerably faster. However, the `range $n | each {|_| ... }` case is now slower than the `for _ [(range $n)] { ... }` formulation. Which is surprising since the first formulation should, in theory, only require starting two goroutines. Which, when amortized over many values should have negligible cost; not the +20% (give or take) increase I observed:

```
range 10^1: for    0.000107, each    0.000127, delta +15.9%
range 10^2: for    0.000494, each    0.000490, delta  -0.8%
range 10^3: for    0.003536, each    0.004918, delta +28.1%
range 10^4: for    0.030460, each    0.039378, delta +22.6%
range 10^5: for    0.340794, each    0.404620, delta +15.8%
range 10^6: for    3.376859, each    4.143207, delta +18.5%
range 10^7: for   33.385901, each   40.489002, delta +17.5%
range 10^8: for  393.756029, each  459.855213, delta +14.4%
```

I haven't looked but I hope the difference isn't because the `each` implementation is starting a new goroutine for each value. If it is then we should evaluate whether the lambda passed to `each` needs to be run in a new goroutine for each value. If it does then we're back to wondering if the performance difference is so significant it warrants adding a `&fn` option to `range` in order to avoid that overhead.

**Comment by xiaq** [comment]
> I haven't looked but I hope the difference isn't because the `each` implementation is starting a new goroutine for each value. If it is then we should evaluate whether the lambda passed to `each` needs to be run in a new goroutine for each value. If it does then we're back to wondering if the performance difference is so significant it warrants adding a `&fn` option to `range` in order to avoid that overhead.

It's not. Maintaining performance parity between `for` and `each` is not a goal, at least not at the moment.

Also it seems this can now be closed since @krader1961 expressed on IM not to pursue this anymore.
