### ISSUE TITLE
Augment `range` to support counting down

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1436]
While pondering augmenting `range` to accept a lambda arg (issue #1433) it occurred to me there is no good reason the command has to be restricted to counting up. In other words, `range 5 0` should be equivalent to `range &step=-1 5 0` to produce the sequence 5, 4, 3, 2, 1. Obviously the argument (and `&step` option) sanity checks would need to be adjusted. Too, the documentation should replace the terms `low?` and `high` with something like `start?` and `end`.

TBD is whether the `end` value should be excluded or included when counting down. The former would be consistent with the current counting up behavior. While the latter feels more natural and is consistent with the `seq` command (at least on macOS).

**Comment by krader1961** [comment]
Looking at the [current implementation](https://github.com/elves/elvish/blob/388ac81a8c9bbcc2728da4678d7555554b6f9cf6/pkg/eval/builtin_fn_container.go#L190) for the `range` command I appreciate why the limitation to only count up exists as a consequence of the numerous numeric types. Nonetheless, it feels like an artificial limitation. The implementation will have to be more complicated to support both counting up and down but that seems like a reasonable tradeoff  to make the Elvish behavior more consistent and useful.

**Comment by xiaq** [comment]
Excluding the endpoint would be consistent internally.

`range` is already different from `seq` when counting up, it is not very helpful to make it consistent with `seq` when counting down.

**Comment by krader1961** [comment]
> range is already different from seq when counting up, it is not very helpful to make it consistent with seq when counting down.

That's the conclusion I also came to when I was wrapping up my refactoring last night. The consistenc also made rewriting the documentation a little easier. Just need to add a few more unit tests before creating a P.R.
