### ISSUE TITLE
Elvish Functions with Arguments?

### ISSUE THREAD

**Issue by zQueal** [elves/elvish#1441]
I'm attempting to replicate my old way of executing different applications given different arguments which doesn't seem to work;

```bash
fn command [x] {
	if ($x=='a'){
		echo ($E:INFO | program a)
	}
	if ($x=='b') {
		echo ($E:INFO | program b)
	}
}
```

Realistically I just want to be able to run `command a` or `command b` to execute `echo ($E:INFO | program a)` and `echo ($E:INFO | program b` respectively.

For example, I have 14 different functions which all pretty much query the same API. How would I go about rolling them all into the same function based on case?

So if I have;

    command1
    command2
    command3

How could I get;

    trigger c1 = command1
    trigger c2 = command2
    trigger c3 = command3

Maybe a case loop?

Any guidance on this?

**Comment by zQueal** [comment]
OK, so I realized my obvious stupidity with the first part;

```cmd
fn command [x]{
	echo ($E:INFO | program $x)
}
```

But my issues persist. I have 14 or so functions I'd like to roll into being called from one function name. Can't really crack that one.

**Comment by krader1961** [comment]
Your original function has some whitespace problems. You should be getting syntax errors when using it. However, the main problem with what you're trying to do are the lines that look like ` if ($x=='a')`. Elvish doesn't have infix conditionals. See https://elv.sh/ref/language.html#if. Try this instead:

```
fn command {|x|
	if (eq $x 'a') {
		# echo ($E:INFO | program a)
		echo option a
	}
	if (eq $x 'b') {
		# echo ($E:INFO | program b)
		echo option b
	}
}
```

Also, you probably don't need (or want) the `echo` unless you deliberately want to convert multiline output from `program` into a single line.

**Comment by zQueal** [comment]
Yes, I seem to be having a little trouble acclimating to the elvish syntax considering my limited background. For example, this logic is a little lost on me;

```cmd
if (eq $x 'a')
```

If I understand it correctly, it returns `$true` or `$false` depending on the value of `$x` and then proceeds with any if statement which returns `$true`? If that's true, then IMO, it's a bit different than other conditional statements I've dealt with in the past. Is there any advantages that you've noticed doing things this way vs the more traditional `if ($val==$int) { doSomething(); }` which simply triggers when `$val` is equal to `$int` and doesn't return `$true` or `$false` depending on the outcome?

**Comment by krader1961** [comment]
I'm not aware of any shell where your example is valid:

```
if ($val==$int) { doSomething(); }
```

I suspect you're thinking of the POSIX standard which codified the Bourne shell syntax:

```
if [$val==$int] { doSomething(); }
```

In which case note that the expression that follows `if` is a command and `[` is simply an alias for the `test` command (see `man test`). On you system run `ls -l '/bin/['`. You should see something like this:

```
-rwxr-xr-x 1 root wheel 35840 Sep 21  2020 '/bin/['*
```

Elvish recognizes that it is preferable to eliminate that syntactic sugar and simply rely on the command capture syntax (`(...)`) for consistency. If the command outputs values that, in aggregate, can be construed as `$true` then execute the `if` body.

**Comment by zQueal** [comment]
Yes, it appears that *nix and Bash has indoctrinated me into a POSIX way of thinking. I'm not sure if it's optimal, but I think I've gotten this figured out. At first, I ran into an issue because I need a range of between 1-3 arguments which have no specific type (int, str) and are only sometimes required. I first tried;

```cmd
fn command {|a x y|
```

And of course elvish expected those variables every time, and would throw an error when not supplied. I moved then to;

```cmd
fn command {|a @x|
```

And have opted to use `$x[0]` and `$x[1]` which seems to be working just fine. `$a` will always be supplied as that's how I tell the function how I want to proceed and `$x` depends on the supplied arguments.

Is this the only way to accomplish this? The best way? I appreciate the attention, by the way.

**Comment by krader1961** [comment]
There is nothing wrong with thinking in terms of the POSIX shell standard as implemented by `bash`, `ksh`, and `zsh`; among many other more or less POSIX compatible shells. The important point is to recognize that Elvish is, explicitly, not POSIX compliant. Therefore, any POSIX shell code you are converting to Elvish will require more than trivial changes to the syntax of the original code.

I don't understand what your most recent question about handling optional arguments has to do with your original question. Nonetheless, yes, optional arguments should be handled by a [rest argument](https://elv.sh/ref/language.html#function) in the signature of the function. The function can then decide what to do based on whether the optional arguments are present and, if so, the specific values of those optional args.

**Comment by iandol** [comment]
@zQueal — I think that the other confusion which I also faced is the idea of having the function first, i.e. `+ 1 1` is weird for me whereas `1 + 1` is obvious. This just depends on where you have learnt programming syntax, and `+ 1 1` is common for Lisp derived languages...

**Comment by zQueal** [comment]
> and + 1 1 is common for Lisp derived languages...

This too is a little difficult for me considering I got my start with Python, Perl and PHP. It's becoming easier, but it's a process.

**Comment by zQueal** [comment]
Funny enough, I've been using elvish under windows all this time. I transfered my `rc.elv` to a *nix environment to do some work, and wanted to make use of elvish. When running elvish under *nix, I got a ton of errors for using;

> fn command {|a @x|

and had to swap them all to 

> fn command [a @x]{

to work correctly under *nix. 🤔🤔🤔

**Comment by krader1961** [comment]
That's because on Windows you're using an `elvish` binary built with commit 20e98c747 (merged 2021-10-13) which introduced the `{|| }` syntax, while on your Unix system you're using an older binary that doesn't understand the new lambda syntax.

**Comment by zQueal** [comment]
Yup. That seems to have fixed it. Crazy! Newest Ubuntu using go1.13.
