### ISSUE TITLE
Typo in builtin reference for each function

### ISSUE THREAD

**Issue by ryanjafari** [elves/elvish#1446]
Hi, I'm new to elvish.

If I copy/paste the [first example](https://elv.sh/ref/builtin.html#each) for `each`:

`range 5 8 | each {|x| * $x $x }`

into my elvish shell, I get:

```
parse error: 18-19 in [tty]: should be ',' or '}'
parse error: 30-31 in [tty]: unexpected rune '}'
compilation error: 24-26 in [tty]: variable $x not found
```

[Elsewhere](https://elv.sh/ref/builtin.html#supplying-input), I can find:

```
put 10 100 | each [x]{ + 1 $x }
```

Which when copy/pasted into my shell, yields:

```
▶ (num 11)
▶ (num 101)
```

which is expected.

Do we have a typo here?

Ryan

**Comment by krader1961** [comment]
No typo, you're simply using an old version of Elvish that doesn't recognize the new syntax for lambdas. Try a current version from https://elv.sh/get/.

**Comment by ryanjafari** [comment]
Thanks! I installed using brew I guess that's the old version.

**Comment by xiaq** [comment]
The first version that supports the new syntax is 0.17.0, which is not released yet but will be this week.
