### ISSUE TITLE
Document how to create a TTY snapshot (i.e., a "ttyshot")

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1459]
The directions in the `README.md` file at https://github.com/elves/elvish/tree/master/website/ttyshot do not work.

I can't help but wonder if using a mechanism like https://asciinema.org/ might be preferable in the long term given that every "tty snapshot" is highly variable.

**Comment by xiaq** [comment]
Instructions are now fixed.

I'm aware of Asciinema (I have many Elvish recordings in https://asciinema.org/~xiaqqaix). However, it is an extra JS-heavy dependency, and it is not really necessary for static shots. IIRC it also doesn't handle small screens very well (but that may have changed).

I'm not sure what you mean by "every tty snapshot is highly variable" and how asciinema solves that problem?

**Comment by krader1961** [comment]
> Instructions are now fixed.

That's better but it seems to me that anyone reading those instructions will still have difficulty generating a "ttyshot". Partly because of the need to manually add any generated output, but also because "Put Elvish in the state you want, and press Alt-X" is still very ambiguous. Too, you don't actually document how to include the output of the example command(s) in the "ttyshot" file.

Also, it seems to me the "do not edit" comment should be in the output of the `bufToHTML` function and should say something like this (from the change I've been working on):

```
var bufHtmlPrefix = `<!-- DO NOT EDIT THIS FILE: See https://src.elv.sh/website/ttyshot -->`
```

> I'm not sure what you mean by "every tty snapshot is highly variable" and how asciinema solves that problem?

To be honest I  don't know, now, why I wrote "highly variable". Nonetheless, it still seems to me that using Asciinema is a more flexible, less problematic, easier to use, technology for generating these types of images. In no small part because it doesn't require the user to manually edit the generated "ttyshot" to include the output of the commands being illustrated. Given that you chastised me for manually editing some *website/ttyshot/**.html* files it seems odd that you are sanctioning doing so. In other words, the current mechanism seems to me to be suboptimal. Yes, Asciinema has its own problems, not least of which is the pacing of the input by the user, but I still think it is, overall, preferable to the current mechanism.

Note that if there is a `website/ttyshot/ttyshot.rc` that can be used when starting an interactive Elvish session via `elvish -rc website/ttyshot/ttyshot.rc`  that makes both the current, and Asciinma, approach easy without requiring the user to interactively configure the Elvish session in a manner that might be visible in the "ttyshot".

**Comment by xiaq** [comment]
You have some valid points, but I don't feel it's worth the effort to optimize the details for generating ttyshots. There aren't that many and they are not updated that frequently anyway. If you find them painful to working with, I can update them if you point out what needs to be changed.

It's probably worth revisiting if there are more of them, or more contributors work on docs that include them. But for now I'm satisfied with the current simple (maybe simplistic) system. The entire `website` toolchain is rather hacky in fact but it works well enough.

**Comment by krader1961** [comment]
> If you find them painful to working with, I can update them if you point out what needs to be changed.

FWIW, I think everyone, other than yourself, is going to find creating, or updating, ttyshot images painful using the current instructions. I think that using the asciinema mechanism is both easier to use and less likely to result in incorrect output given appropriate directions.

**Comment by krader1961** [comment]
FWIW, I now realize the phrase "highly variable" in my original comment referred to the fact that the ttyshot demos include a person's private history. Which itself is problematic. The private command and location history of an individual should not be evident in a "ttyshot". That, however, is a tough nut to crack given the current Elvish CLI and dependency on a daemon due to the semantics of the BoltDB used to store that information.
