### ISSUE TITLE
Is there an X-to-Elvish translation guide?

### ISSUE THREAD

**Issue by chipbuster** [elves/elvish#1461]
Hey there!

I picked up Elvish last night and spent a bunch of time translating my ZSH configs into my rc.elv. I'm very happy with how complete the documentation is, but I keep finding myself wanting to do something I'm familiar with from ZSH and having to go combing through the docs to find it. A few examples of the things I've wanted to do so far:

  - Wanting to use `source` to execute files, spending 10 minutes throwing searches around until finding [this comment](https://github.com/elves/elvish/issues/453#issuecomment-932996777) which answers my question perfectly.
  - Wanting to check if an external command exists, clicking to the [builtins reference page](https://elv.sh/ref/builtin.html), then scanning functions until spotting `has-external`.
  - Figuring out how to combine multiple boolean values using boolean operators (still not clear if I can do this without having to use `eq` and `$true`/`$false`)
  - How to execute two commands in a pipeline, with the second only firing if the first is successful (still have no idea how to do this).

I'm wondering if there's a "translation guide" available, official or not, for how to translate short idioms from e.g. bash/zsh into Elvish. For example, if I search `source` in this document, it might also have `.` "read and execute an elvish file" as things you want to do, and have [this comment's contents](https://github.com/elves/elvish/issues/453#issuecomment-932996777) as reasons you might want to do this, with the appropriate solutions.

Several google searches have pulled up nothing, but I might have just missed it. If it does not exist, would there be any interest in the creation of such a document?

**Comment by krader1961** [comment]
> How to execute two commands in a pipeline, with the second only firing if the first is successful (still have no idea how to do this).

I have no idea what you mean by this statement. I suspect you don't mean a pipeline such as `a | b` but the POSIX `||` operator which is not a pipeline constructor. A concrete example of what you mean would help.

**Comment by krader1961** [comment]
Also, note that Elvish is explicitly not a POSIX compatible shell. So many non-trivial statements meant to be run by shells like `bash`, `ksh`, or `zsh` will require non-trivial changes to work correctly under Elvish.

**Comment by chipbuster** [comment]
> I have no idea what you mean by this statement [...] A concrete example of what you mean would help.

Right, "pipeline" was wrong. I want to run the second command only if the first succeeds (or if the first fails). In my case, I was just attempting do something like `mkdir directory && cd directory`.

> Also, note that Elvish is explicitly not a POSIX compatible shell. So many non-trivial statements meant to be run by shells like bash, ksh, or zsh will require non-trivial changes to work correctly under Elvish.

Yes, that's fine. I wouldn't mind being told "this functionality doesn't exist" or "there's no one-liner for that, write a function instead." Right now, I'm holding several pages open, Ctrl-F-ing through them, then nervously wondering if I missed something when I don't find anything.

**Comment by krader1961** [comment]
> EDIT: It looks like what I want for && is a code chunk with semicolons, and I'd probably want to write a function for || using exception-handling.

Yes, you are on the right track with that insight. Also, I found your `mkdir directory && cd directory` example interesting since it might illustrate a deeper problem. If I wrote a POSIX script that needed to create a directory only if it didn't exist I would not predicate its creation on a subsequent `cd` command. I would instead do something like this:

```
set -x
[[ ! -d directory ]] || mkdir directory
cd directory
```

In other words, I want my script to fail if the directory doesn't exist and I can't create it or I can't chdir to it. Your version will silently fail if a non-directory file named `directory` already exists.

**Comment by krader1961** [comment]
@chipbuster, See my [blog post](https://www.skepticism.us/posts/2015/10/its-time-to-replace-zsh-with-a-saner-shell-because-unsetopt-multifuncdef-breaks-tab-completion/) for why I discourage everyone from using Zsh.

**Comment by xiaq** [comment]
The [quick tour](https://elv.sh/learn/tour.html) is supposed to be that doc, and I just expanded it to address all your questions. I also sneaked in "translate" in the doc, hopefully it will eventually show up if you Google "elvish translate bash".

**Comment by xiaq** [comment]
It seems that all your original questions are answered now, closing.

**Comment by chipbuster** [comment]
@xiaq and @krader1961 Thanks for the help! Seems I have some more reading to do; excited to see what elvish is capable of! :)
