### ISSUE TITLE
Pipelines.html still using legacy syntax.

### ISSUE THREAD

**Issue by iandol** [elves/elvish#1465]
The home page pipline section still uses legacy lambda syntax, should be:

```
curl https://api.github.com/repos/elves/elvish/issues |
from-json | all (one) |
each {|issue| echo $issue[number]: $issue[title] } |
head -n 11
```

`head -n 11` could also be replaced by `take 11`, but perhaps showing the interaction with external commands is more important...

**Comment by xiaq** [comment]
Yes, the use of `head` instead of `take` is intentional, to use interop with external commands.
