### ISSUE TITLE
One difference between a function and a lambda

### ISSUE THREAD

**Issue by s5unty** [elves/elvish#1467]
> Define a function with a given name.
> The function behaves in the same way to the lambda used to define it, except that it “captures” return.
> In other words, return will fall through lambdas not defined with fn, and continues until it exits a function defined with fn:

```ruby
# good
seq 2 | each {|x| echo "x"$x}

# good
var y = {|x| echo "y"$x}
seq 2 | each $y
```

```ruby
# not good
fn z {|x| echo "z"$x}
seq 2 | each z
# output
Exception: wrong type for arg #0: wrong type: need !!eval.Callable, got string

# not good
fn z {|x| echo "z"$x}
seq 2 | each $z
# output
compilation error: variable $z not found
```

Is it possible to reference a function directly in `each`?
If I'm missing any documentation, please give me a hint, thanks.

```
% elvish --version
0.18.0-dev.84b72af4ca3ff56233271807237126f4fbb3478c
```

**Comment by krader1961** [comment]
The behavior of `return` is documented [here](https://elv.sh/ref/language.html#exception-and-flow-commands) and [here](https://elv.sh/ref/builtin.html#return).

Your `seq 2 | each z` example needs to be written as `seq 2 | each $z~`. The bare-word `z` in your version is syntatically the same as `"z"`; i.e., `seq 2 | each "z"`. See also https://elv.sh/ref/language.html#variable-suffix.

**Comment by krader1961** [comment]
@s5unty: You responded favorably to my previous comment. Is there anything else the Elvish community can help you with in regard to this issue? Are there still aspects of the current behavior that confuses you? If not you should probably close this issue.
