### ISSUE TITLE
Parse error on rc.elv

### ISSUE THREAD

**Issue by Air4x** [elves/elvish#1471]
For some reason when I start elvish in an interactive mode it outputs an error when it tries to parse rc.elv. But if I copy-paste line per line the contents of the rc.elv file in the elvish's shell it works flawlessly.
Here are the contents of the rc.elv file
```
fn ls { |@a| exa $@a }
fn la { |@a| exa --all $@a }
fn lc { |@a| exa -1 $@a }
fn tree { |@a| exa --tree -L 2 $@a }
fn wget { |@a| wget --hsts-file=\"$E:XDG_CACHE_HOME/wget-hsts\" $@a }
eval (starship init elvish) 2> /dev/null
```
Here the output of `elvish -compileonly rc.elv`
```
Multiple parse errors:
  string not terminated
    /home/mario/.config/elvish/rc.elv, line 9:
      ^
  should be '}'
    /home/mario/.config/elvish/rc.elv, line 9:
      ^
```
But if I remove all the function definitions there is no error.

**Comment by krader1961** [comment]
The backslashes in your wget function aren't doing what you think. Just remove the `\"` sequences. See https://elv.sh/ref/language.html#bareword and https://elv.sh/ref/language.html#double-quoted-string.

Also, redirecting stderr to /dev/null is almost always a bad idea and not needed.

**Comment by krader1961** [comment]
FYI, your `wget` function has another problem: infinite recursion. That's because the `wget` command inside the function will resolve to the function, not the external command of the same name. Use `e:wget` to force using the external command.

**Comment by krader1961** [comment]
> But if I copy-paste line per line the contents of the rc.elv file in the elvish's shell it works flawlessly.

You did not copy/paste the wget function definition since it results in an incomplete statement:

```
0.000134 elvish> fn wget { |@a| wget --hsts-file=\"$E:XDG_CACHE_HOME/wget-hsts\" $@a }

```

Note the empty line rather than a new prompt after I pressed Enter which tells me the statement I typed was not complete.

**Comment by Air4x** [comment]
Now anything works as it should, thank you. About starship, there is a (closed) issue about this, but the proposed solution is to redirect stderr to /dev/null. For now, I decided to redirect to a file, at least I'll not lose errors.

**Comment by zzamboni** [comment]
FWIW, `starship` has not been upgraded for the Elvish 0.17 syntax changes. To avoid deprecation errors, you can use the following:

```
eval (starship init elvish --print-full-init | upgrade-scripts-for-0.17 -lambda | slurp)
```
