### ISSUE TITLE
How to source an elv file in the same directory as rc.elv?

### ISSUE THREAD

**Issue by ezh** [elves/elvish#1483]
I found a number of issues like https://github.com/elves/elvish/issues/453. Also, I tried to search across GitHub without success.

My case:
I have `rc.elv` with a group of declared functions that I'm using as commands in a console.
I decided to move those functions to a separate file because `rc.elv` is huge.
Now I have inside `~/.config/elvish`:
```
alias.elv  rc.elv
```
`use` is useless and I would like to do `eval (slurp < alias.elv)` or `eval (slurp < ./alias.elv)`
But I get `Exception: failed to open file ./alias.elv: open ./alias.elv: no such file or directory`

How to source file from the same directory where the current script (rc.elv) is located.

`use` loads `alias.elv` well but it is wouldn't export functions to the global scope.

**Comment by ezh** [comment]
I won't provide an absolute path because I would like to keep `rc.env` portable between machines.

**Comment by zzamboni** [comment]
The "Elvish" way to do this would be to store your extra file as a library, and then load it with `use`.

However, if you really want to keep the files in your main config dir, then you could load them with `use` and a relative path, like this:
```
use ./alias
```

**Comment by iandol** [comment]
And if you want your functions in the interactive editor scope, then use `edit:add-var` in your `alias.elv`:

```
edit:add-var ll~ {|@in| e:ls -alFGh $@in }
```

Or use zzamboni's alias module (though there are some limitations to its use)...

**Comment by ezh** [comment]
Thank you very much.

**Comment by ezh** [comment]
A small note for other guys with the same issue.
Please read https://github.com/elves/elvish/blob/master/pkg/edit/vars.go

**Comment by zzamboni** [comment]
I'm not completely sure what you are referring to in that file, but if it's the documentation for `edit:add-var`, you can find a more readable version in the Elvish docs: https://elv.sh/ref/edit.html#edit:add-var
