### ISSUE TITLE
comment after `^` triggers parse error

### ISSUE THREAD

**Issue by crinklywrappr** [elves/elvish#1498]
I had this code in a project

```elvish
if (or (re:match '.*{$' $line) ^ # ends with {
        (re:match '.*^$' $line) ^ # ends with ^
        (re:match '.*{\ *|[^|]*|$' $line)) { # ends with params
  put foo
}
```

it produced a parse error like

```
Exception: Multiple parse errors:
  should be ')'
   ...foobar.elv, line 260:
                 (re:match '.*^$' $line) ^ # ends with ^
  should be '}'
    ...foobar.elv, line 260:
                 (re:match '.*^$' $line) ^ # ends with ^
  should be '}'
    ...foobar.elv, line 260:
                 (re:match '.*^$' $line) ^ # ends with ^
  unexpected rune '^'
    ...foobar.elv, line 260:
                 (re:match '.*^$' $line) ^ # ends with ^
```

This was unexpected b/c of how comments _normally_ work.  Even if it's not technically a bug, it was surprising.

Removing the comments fixes the issue.

**Comment by krader1961** [comment]
From the [documentation](https://elv.sh/ref/language.html#lexical-elements):

> A line continuation: a ^ followed by a newline ("\n"), or a carriage return and newline ("\r\n").

It's modeled on the equivalent POSIX shell syntax of placing a backslash just before a newline to elide the newline. In other words, in a traditional POSIX shell you can't do this:

```
echo A\ # the echoed text continues on the next line
B
```

See, for example, https://superuser.com/questions/794963/in-a-linux-shell-why-does-backslash-newline-not-introduce-whitespace

**Comment by crinklywrappr** [comment]
I thought that might be the case.

Good thing elvish isn't posix compliant. Support could be added if xiaq wants to.

Consider this a feature request.

I'm cool either way.

**Comment by krader1961** [comment]
> Good thing elvish isn't posix compliant.

Yes, I think everyone who uses Elvish would agree its explicit non-POSIX compliance is a good thing. 😄 But my point was that there are reasons for the current behavior. Having said that, your proposal could, in theory, be implemented. However, it's not clear what that means for other variations; e.g., `echo a^b`. See issues #989 and #979 for context regarding the current behavior. Especially this [comment regarding using `^` elsewhere](https://github.com/elves/elvish/issues/979#issuecomment-619581918) in the future.

**Comment by crinklywrappr** [comment]
Good points!
