### ISSUE TITLE
on launch: "failed to spawn stub: search: not found"

### ISSUE THREAD

**Issue by aerth** [elves/elvish#151]
Since upgrading recently, every time elvish is launched it prints: ```failed to spawn stub: search: not found``` on launch

That is on NetBSD 7. On Debian wheezy, similar error occurs:
```
Warning: cannot connect to store: failed to initialize table cmd: database is locked
failed to spawn stub: search: not found
```
After rm -Rf ~/.elvish/*, ```failed to spawn stub: search: not found```

**Comment by xiaq** [comment]
Please refer to the updated [building section](https://github.com/elves/elvish#building-it-yourself) of README.

**Comment by xiaq** [comment]
To fix the first error, do `rmdir ~/.elvish/db.lock`. There used to be bugs that will leave the database locked when elvish exits, but hopefully they have been fixed.

**Comment by xiaq** [comment]
Also, NetBSD is likely also affected by #152.
