### ISSUE TITLE
`after-chdir` hook vs built-in file manager

### ISSUE THREAD

**Issue by gergelyk** [elves/elvish#1510]
`after-chdir` hook is not called when directory is changed by built-in file manager. I would suggest either calling it or creating separate hook for such event.

**Comment by xiaq** [comment]
This was fixed in https://github.com/elves/elvish/commit/46774d707845e78864671d1c6ed6358d624b8650, which is included in the latest 0.18.0 release.

Which version are you running?

**Comment by gergelyk** [comment]
I confirm. After migration to 0.18 it works fine.
