### ISSUE TITLE
Doc typo: `+ 1 2` returns an integer

### ISSUE THREAD

**Issue by alex-robbins** [elves/elvish#1513]
The Quick Tour, section [3.5 Numbers] says 
```
~> + 1 2
▶ (float64 3)
```

But actually:
```
~> + 1 2
▶ (num 3)
```

(Also, the syntax for showing floats seems to have changed; that page says e.g. `▶ (float64 1000)` but I'm seeing `▶ (num 1000.0)`.)

[3.5 Numbers]: https://elv.sh/learn/tour.html#numbers

**Comment by xiaq** [comment]
Thanks, this is some leftover from before the number system rewrite.
