### ISSUE TITLE
rest option

### ISSUE THREAD

**Issue by gergelyk** [elves/elvish#1522]
You may want to consider rest option that would (similarly to rest argument) accept all the options that are not declared. E.g.

```
fn example1 {|@&opts| put $opts}           # `$opts` would evaluate to map.
fn example2 {|@&opts| example1 $@opts}     # `$@opts` would pass options to example2
```

While rest argument corresponds to *args in Python, rest option would be similar to **kwargs.

This would make it possible to write a wrapper for any function.

**Comment by hanche** [comment]
Duplicate of #584?

**Comment by gergelyk** [comment]
iIndeed. Closing.
