### ISSUE TITLE
Command substitution failed with `hdiutil` on macOS

### ISSUE THREAD

**Issue by LdBeth** [elves/elvish#1523]
A typical command for mounting ramdisk on macOS with POSIX shell syntax would be:

    diskutil erasevolume HFS+ "Ramdisk" `hdiutil attach -nobrowse -nomount ram://4096`

Which would always work fine with bash or dash.
For which `hdiutil` returns a path like `/dev/disk2` to be consumed by `diskutil`.

For elvish, this command would fail with something like `Unable to find disk for /dev/disk2`:

    diskutil erasevolume HFS+ "Ramdisk" (hdiutil attach -nobrowse -nomount ram://4096)

more curiously, this function when called would loop forever:

```text
fn ramdisk {
var p = (hdiutil attach -nobrowse -nomount ram://4096)
while (not ?(test -b $p)) {
   sleep 5
}
}
```

Same issue would happen to fish.

I find however piping the returned path with xargs would make it work:

    hdiutil attach -nobrowse -nomount ram://4096 | xargs diskutil erasevolume HFS+ "Ramdisk"

**Comment by hanche** [comment]
That is because the output of the `hdiutil` command is not quite what it seems like at first glance:

```
⬥ put (hdiutil attach -nobrowse -nomount ram://4096)
⮕ "/dev/disk4          \t                               \t"
⬥
```

The corresponding command works in bash because bash will strip the whitespace, but not in elvish, because elvish merely splits stdin into lines with no further processing. You'll need to remove it using [`str:strip`](https://elv.sh/ref/str.html#str:trim):

```
⬥ hdiutil attach -nobrowse -nomount ram://4096 |
  str:trim (one) " \t" |
  diskutil erasevolume HFS+ Ramdisk (one)
Started erase on disk5
Unmounting disk
Erasing
Initialized /dev/rdisk5 as a 2 MB case-insensitive HFS Plus volume
Mounting disk
Finished erase on disk5 (Ramdisk)
```

**Comment by LdBeth** [comment]
I guessed it was because some of the invisible white space, but I didn't realized `put` can visualize this!
I think the problem now get solved.

PS. `man hdiutil` is a thousand more lines long, do you have some nifty trick on how to locating the subcommand description from the man page (i.e. `/attach` in `less` catches too many results)
