### ISSUE TITLE
possible regression at v0.15 when referencing some builtins

### ISSUE THREAD

**Issue by crinklywrappr** [elves/elvish#1524]
Prior to v0.15 I was able to do

```elvish
put $+~
```

Since then Elvish throws an error.  In v0.18:

```
parse error: 5-6 in [tty]: should be variable name
compilation error: 4-5 in [tty]: variable $ not found
parse error: should be variable name
[tty 1], line 1: put $+~
```

This still works for some builtins, though.

```elvish
$ put $each~
▶ <builtin each>
```

**Comment by krader1961** [comment]
The grammar was tightened up to avoid some ambiguities. Specifically, the definition of a [bareword](https://elv.sh/ref/language.html#bareword) was changed. Commit 80e944be, 2021-01-12, introduced the ability to use characters not allowed in a bareword in a variable name by quoting the string. For example,

```
> put $'+~'
▶ <builtin +>
> var '+foo^' = foobar
> put $'+foo^'
▶ foobar
```
```
