### ISSUE TITLE
Can't access the Fedora repo

### ISSUE THREAD

**Issue by ErickHoward** [elves/elvish#1526]
I have tried to install Elvish through the repository listed on the website however I can't connect to the repository. Pings and trying to access the server via Firefox do not work.

**Comment by krader1961** [comment]
As mentioned on the instant-messaging channels the stable distro releases of Fedora, Ubuntu, etc. are going to have extremely old versions of Elvish. Even if you can install Elvish using those distro's tools you are (almost) guaranteed to have an Elvish that is so distant from the current release that it is borderline unusable given the rapid evolution of Elvish. At this time installing Elvish from https://elv.sh/get/ is the only practical solution if you want an Elvish binary that matches the published documentation and is compatible with third-party modules such as found at https://github.com/elves/awesome-elvish. At least without building Elvish from source.

**Comment by ErickHoward** [comment]
Should the option be removed from the website then?
