### ISSUE TITLE
How can I use elvish's Ctrl-N to display a dot file?

### ISSUE THREAD

**Issue by Coordinate-Cat** [elves/elvish#1529]

**Comment by krader1961** [comment]
See https://elv.sh/ref/edit.html#edit:navigation:trigger-shown-hidden and the output of `pprint $edit:navigation:binding` which shows it is bound to Ctrl-H. This looks like something that could be better documented. 😄

**Comment by xiaq** [comment]
Nav mode now shows the more obscure bindings:

<img width="707" alt="截屏2022-11-26 16 59 42" src="https://user-images.githubusercontent.com/582021/204100236-f1d4e2db-91cb-430e-a116-0f5156192e57.png">
