### ISSUE TITLE
Autocomplete does not work correctly when dealing with directories with spaces

### ISSUE THREAD

**Issue by 2426021684** [elves/elvish#153]
Autocomplete does not work correctly when dealing with directories with spaces.

Steps to Reproduce:
1. Type start of directory with spaces
2. Press tab
3. Select the directory with spaces
4. Press enter

Actual Result:
```
~> cd Code/Recipe Parser/
args error
~>
```

Expected Result:
```
~> cd "Code/Recipe Parser/"
~/Code/Recipe Parser>
```

**Comment by xiaq** [comment]
I happen to be working on this recently :)
