### ISSUE TITLE
Setting temporary environment variable will leave a blank environment behind

### ISSUE THREAD

**Issue by tw4452852** [elves/elvish#1536]
```sh
~> env | grep TEST
Exception: grep exited with 1
[tty 120], line 1: env | grep TEST
~> { tmp E:TEST = 1; put $E:TEST }
▶ 1
~> env | grep TEST
TEST=
```

**Comment by krader1961** [comment]
This is a duplicate of #1448. Don't feel bad, @tw4452852, about opening a duplicate issue as this type of issue is difficult to search for and thus hard to know whether it has already been reported. It's better to have people open a new issue for a problem we already know about than not to tell us you observed unexpected behavior.

**Comment by tw4452852** [comment]
@krader1961 
Sorry for the duplication, it's my bad. I will close this one.

**Comment by krader1961** [comment]
> Sorry for the duplication, it's my bad. I will close this one.

No need to apologize. Like I said, these types of issues can be hard to find even when you make the effort to search for whether it has already been reported. I see you've created a possible fix which is fantastic. Hopefully @xiaq or myself will be able to review it soon.

**Comment by tw4452852** [comment]
@krader1961
Thanks for your kindness.
