### ISSUE TITLE
Is it good that blackhole var $_ can be redefined?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1538]
The [documentation](https://elv.sh/ref/builtin.html#_) implies the blackhole var cannot be redefined. But it can be redefined:

```
> set _ = abc
> put $_
▶ $nil
> var _ = def
> put $_
▶ def
```

Is this desirable? If it is then the documentation should be augmented. Personally, I don't think a `var _ =` statement should be allowed. Or, if allowed, it should be equivalent to `set _ =`. The documentation for [`var`](https://elv.sh/ref/language.html#var) hints that the current behavior is expected but is far too vague if we want to retain that behavior. Especially in light of the documentation for the [magic underscore var](https://elv.sh/ref/builtin.html#_) .

**Comment by hanche** [comment]
See also the discussion at #1141.

**Comment by krader1961** [comment]
Thanks for the pointer, @hanche. I had a vague feeling this had already been discussed but for some reason didn't find that issue when I checked. Closing this as a dup.
