### ISSUE TITLE
New tmp form doesn't work on multiple commands (tmp may only be used inside function)

### ISSUE THREAD

**Issue by hexsel** [elves/elvish#1542]
Running the following command is not allowed with the new tmp syntax:
```
> echo "A" ; tmp TXT = "B" echo $TXT

compilation error: 11-34 in [tty]: tmp may only be used inside a function
compilation error: tmp may only be used inside a function
[tty 11], line 1: echo "A" ; tmp TXT = "B" echo $TXT
```

The opposite order also doesn't work:
```
> tmp TXT = "B" echo "A" ; echo $TXT

compilation error: 0-23 in [tty]: tmp may only be used inside a function
compilation error: tmp may only be used inside a function
[tty 12], line 1: tmp TXT = "B" echo "A" ; echo $TXT
```

**Comment by krader1961** [comment]
See https://elv.sh/ref/language.html#tmp. Your first example should be written something like the following. Note I've introduced a TXT var for the first `echo` as I think that more clearly shows the expected behavior:

```
0.000234 elvish> var TXT = a
0.000261 elvish> echo $TXT
a
0.000258 elvish> { tmp TXT = b; echo $TXT }
b
0.000279 elvish> echo $TXT
a
```

**Comment by hexsel** [comment]
Maybe I'm misunderstanding something - my intent was actually to override some environment variable, so it looked a bit like this:
```
yarn build ; E:A=B E:C=D yarn deploy
```

What is the new recommended syntax?

**Comment by krader1961** [comment]
> What is the new recommended syntax? 

It's the same as my previous example:

```
yarn build
{ tmp E:A = B; tmp E:C = D; yarn deploy }
```

**Comment by mmlb** [comment]
I came across this while searching issues for this exact error message. I came across this because the 0.18 docs say to use `tmp` as a replacement for the old/deprecated behavior. From https://elv.sh/blog/0.18.0-release-notes.html#deprecated-features

> The legacy temporary assignment syntax (e.g. a=foo echo $a) is deprecated. Use the new tmp command instead (e.g. tmp a = foo; echo $a).

How are we to to do temporary variable assignment in 0.19? Having to do it in a function seems very odd for something that I'd think happens pretty regularly.

Happy to open a separate issue, but thought to chime in here first.

**Comment by krader1961** [comment]
@mmlb, What makes you think temporary assignments happen "pretty regularly"? My experience has been they are used rarely and almost always to temporarily change an env var, not a regular var. Note too that you don't have to define a function. A simple lambda to create a new scope is all that is needed. That's four extra characters (not counting the need for `tmp`): `{  }`.

**Comment by mmlb** [comment]
Hey @krader1961 you're right about the regular-var vs env-var, I was definitely thinking about temporary envvar overrides. I don't think the distinction matters for the issue at hand, as env vars are also affected, for example I regularly run `E:TERM=xterm-256color vagrant ssh -t provisioner` and similar uses of temporarily override an envvar. `tmp` still doesn't work here, with out some sort of function (or lambda).

I get it that its only a few extra characters, but it just feels weird. How often do you type a command, have it fail in some form, you then go back and add/tweak an envvar to the line? Now we're going to also wrap in `{ }` too? It feels cumbersome to me.

sidenote: this feels like a shift from favoring interactive use over to favoring scripted instead. Maybe its just me but elvish is still primarily an interactive shell to me, I've only got a couple of elvish scripts.

**Comment by krader1961** [comment]
@mmlb, You wrote

```
For example I regularly run E:TERM=xterm-256color vagrant ssh -t provisioner
```

Why? Are you running `vagrant` from inside a Tmux session and don't want the Tmux `TERM` value (e.g., `tmux-256colors`) to be used by the `vagrant` command? If that is the case under what conditions would you want the `vagrant` command to use the Tmux `TERM` value? Why not simply define a `vagrant` function that always temporarily sets `TERM` to your desired value then invokes `e:vagrant`?

**Comment by mmlb** [comment]
> > How often do you type a command, have it fail in some form, you then go back and add/tweak an envvar to the line?
> 
> Extremely rarely. Obviously, for you, it is more frequently. But, really, how often do you do this? Can you provide some real examples? There may be another way to address your use case(s).

Going back through history I'm at just shy of 1% of my commands match `grep '^E:'`. Things like:
```
E:DHCP_LEASE_TIME=1d ./tinkerbell 
E:DHCP_LEASE_TIME=240h ./tinkerbell 
E:DHCP_LEASE_TIME=30m ./tinkerbell 
```

> @mmlb, You wrote
> 
> ```
> For example I regularly run E:TERM=xterm-256color vagrant ssh -t provisioner
> ```
> 
> Why? Are you running `vagrant` from inside a Tmux session and don't want the Tmux `TERM` value (e.g., `tmux-256colors`) to be used by the `vagrant` command? If that is the case under what conditions would you want the `vagrant` command to use the Tmux `TERM` value? Why not simply define a `vagrant` function that always temporarily sets `TERM` to your desired value then run`e:vagrant`?

note this is just one example, the most recent and such fresh in my brain. I override TERM because I'm using kitty and the remote vagrant vm doesn't know about TERM=xterm-kitty. I find that overriding envvars is usually for immediate experimentation and wrapping in a script or updating rc file just doesn't really make sense.

**Comment by hexsel** [comment]
I also run a variety of DevOps-related commands, and I often have to specify things for tools via env vars - AWS_PROFILE, AWS_REGION, sometimes our ENV_NAME, TERM, etc. 

For some tools, it's a common form of parameter-passing, but I understand this may not be the primary goal of a more structured shell like Elvish.

**Comment by krader1961** [comment]
@mmlb, For you tinkerbell examples I would write a very simple function along these lines:

```
fn tinkerbell {|lease-time|
    tmp E:DHCP_LEASE_TIME = $lease-time
    ./tinkerbell
}
```

For your vagrant example I would probably use an abbreviation but a function would work too.

@hexsel and @mmlb, For those cases where there isn't enough regularity to the overrides to justify an abbreviation or function I would use the `env` command:

```
env A=B C=D yarn deploy
```

**Comment by krader1961** [comment]
Also, while `env` should be available on every UNIX platform Elvish runs on it is trivial to implement as an Elvish function. Which could allow specifying env vars with or without the `E:` namespace prefix in order to avoid the dissonance of being required to type `env A=B yarn deploy` rather than `env E:A=B yarn deploy`.

**Comment by krader1961** [comment]
@mmlb, you replied

> Going back through history I'm at just shy of 1% of my commands match grep '^E:'.

I would conclude you use that mechanism "rarely" but perhaps not "extremely rarely". I'm willing to bet that most of those temporary env var changes can be handled by my prior comment(s) to use a function or command abbreviation. And the remainder can be handled by the `env` command. So I am still not convinced the legacy temp var syntax should be reinstated.
