### ISSUE TITLE
the `exec` builtin should work on Windows

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1556]
The MSYS2 `bash` shell supports the `exec` builtin command on Windows. Elvish should also support it rather than throwing `Exception: not supported on Windows`. I often want to replace the current Elvish shell with a new one rather than launching a sub-shell. TBD is determining how the MSYS2 `bash` shell supports that capability and port it to Elvish.

**Comment by xiaq** [comment]
Windows doesn't have an API for replacing a current running process.

Cygwin's `exec` family syscall (which MSYS2 derives from) simply emulates the behavior of Unix's `exec` by exiting the parent process when the spawned process exits. You can observe this behavior by counting the number of `bash` processes when you run `exec bash`.

If you want to emulate such a behavior with Elvish, you can just do `elvish; exit`.

**Comment by krader1961** [comment]
I knew that the Windows API (at least as it existed two decades ago) only supports spawning a child process; i.e., it has no equivalent of `fork()`. I was hoping that in the intervening years it had been augmented to support a `SpawnWithReplacementOfCurrentProcess()` API. Still, it would be nice if `exec` on Windows implemented the hack described above so that users don't have to remember it doesn't work on Windows.

@xiaq, If I do the work any objecting to merging such a change?

**Comment by krader1961** [comment]
Ping? I still think that it makes sense to emulate `exec` on Windows using the hack employed by MSYS2 Bash. Doing so doesn't have any any significant downsides that I can see and eliminates a friction point. Honestly, if I happen to use `exec` on Windows I'm unlikely to care that the current Elvish process continues to exist until the exec'ed command exits.

**Comment by krader1961** [comment]
> Honestly, if I happen to use exec on Windows I'm unlikely to care that the current Elvish process continues to exist until the exec'ed command exits.

The only case I can think of where that isn't true is trying to install a new Elvish binary by exec'ing a new one from a different location so the reference by the current process to its binary is removed. Thus allowing the old binary file to be removed or overwritten. However, given that installing a new Elvish binary is already a PITA on Windows I don't see that as a good argument not to implement the `exec` hack.

**Comment by W1M0R** [comment]
If anyone is interested in contributing a PR, try this implementation (this is part of a [similar effort elsewhere](https://github.com/direnv/direnv/pull/1291)):

```go
// winExec is a windows approximation of the syscall.Exec function.
//
// In Unix environments, syscall.Exec replaces the current process with
// commandPath. Since we can't do that in Windows, we approximate that
// behaviour.
func winExec(commandPath string, args []string, env []string) error {
	// https://man7.org/linux/man-pages/man2/execve.2.html
	// In the execve and syscall.Exec interface, commandPath is also args[0].
	// Let's strip that from args for this function.
	if len(args) > 0 {
		args = args[1:]
	}

	cmd := exec.Command(commandPath, args...)
	cmd.Env = env

	// Set the standard input, output, and error to the current process
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		return err
	}

	if err := cmd.Wait(); err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			if status, ok := exitErr.Sys().(syscall.WaitStatus); ok {
				os.Exit(status.ExitStatus())
			}
		}
		os.Exit(1)
	}

	os.Exit(0)

	return nil
}
```
