### ISSUE TITLE
Add a &key option to the order command

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1570]
The [`order` command](https://elv.sh/ref/builtin.html#order) currently has the option `&less-than`, which should be a function to be called with two values from the list to be ordered in order to determine is the first is to be placed before the second.

In applications, the supplied function often needs to extract or compute a sort key from each of the two list item, and then compare the keys. This can lead to extra verbosity, code that is harder to read. and a (somewhat) higher risk of bugs.

> **Proposal:** Add an option `&key=$nil` to the `order` command. Its value should be a function of one argument, to be applied to each item in the list. Then the `less-than` comparison is applied to the resulting keys instead of the original values.

The proposal is inspired by the [Common Lisp `sort` functiuon](http://www.lispworks.com/documentation/HyperSpec/Body/f_sort_.htm#sort), which has such an option. It was recently discussed briefly in chat.

For reference, here is a simple elvish implementation of the proposal.

```
fn order {|&reverse=$false &less-than=$nil &key=$nil @args|
  use builtin
  set key = (coalesce $key $put~)
  set less-than = (coalesce $less-than {|a b| == -1 (compare $a $b)})
  builtin:order $@args &reverse=$reverse ^
    &less-than={|a b| $less-than ($key $a) ($key $b)}
}
```

Example usage:

```
⬥ var t = [[c 1] [a 3] [b 2]]
⬥ order $t &key={|x| put $x[1] }
⮕ [c 1]
⮕ [b 2]
⮕ [a 3]
```

**Comment by krader1961** [comment]
Other prior art is the Python `sorted` command: https://docs.python.org/3/howto/sorting.html. However, note this statement in that documentation:

> The value of the key parameter should be a function (or other callable) that takes a single argument and returns a key to use for sorting purposes. This technique is fast because the key function is called exactly once for each input record.

If the same optimization is done in Elvish then that clearly makes a `&key` option worthwhile, from a performance perspective, compared to an equivalent `&less-than` function. If that optimization is implemented then my opinion of adding a `&key` option goes from slightly opposed to greatly in favor of doing so.

P.S., I can't help proposing that `order` be renamed `sorted` at the same time. 😸

**Comment by hanche** [comment]
@krader1961 Yeah, I thought of that optimization too, but neglected to mention it, as I was in a rush to leave. Of course, it comes at a slight cost in space in order to save time, but that is probably not a strong argument against it. In any case,, that is easily resolved by writing a bit more go code, so the optimization is not applied when `$key` is `$nil`.

Below is an elvish implementation using this optimization. Incidentally, while testing it, I discovered that the documentation for `order` does not match the actual behaviour: If you explicitly give it the option `&less-than=$nil`, it raises an error.

```
fn order {|&reverse=$false &less-than=$nil &key=$nil @args|
  use builtin
  if $key {
    set less-than = (coalesce $less-than {|a b| == -1 (compare $a $b)})
    if (eq $args []) { all } else { put $@args } ^
    | each {|item| put [($key $item) $item]} ^
    | builtin:order &reverse=$reverse ^
      &less-than={|a b| $less-than $a[0] $b[0]} ^
    | each {|pair| put $pair[1]}
  } elif $less-than {
    builtin:order &reverse=$reverse &less-than=$less-than $@args
  } else {
    builtin:order &reverse=$reverse $@args
  }
}
```

**Comment by krader1961** [comment]
It turned out to be simpler than I expected to support `order &less-than=$nil`. It did take me a couple of hours to figure out due to unfamiliarity with the Go `reflect` package but the change itself turned out require just five new lines (plus eleven more for unit tests). I should also have an `order &key` option added in the next day or two. I'm hoping that benchmarks show it is significantly faster than using `&less-than`.

**Comment by krader1961** [comment]
My earlier benchmark results made the `&less-than` option performance appear better than it really is due to a bug in my benchmark. Below are the correct results. Note that, as expected, as the number of items sorted increases the "simple" (no sort options) and "key" variants scale linearly with the input while the "less-than" variant is a bit more than linear. For large inputs (e.g., 10^5 items) using `&key` is almost 50x faster than `&less-than`. But for even just 10 items `&key` is 4x faster. I'm actually surprised `&less-than` isn't worse.

```
Benchmarking 10^1 (10) strings:
simple       0.001740
key          0.001969
less-than    0.007779

Benchmarking 10^2 (100) strings:
simple       0.000527
key          0.007207
less-than    0.103583

Benchmarking 10^3 (1000) strings:
simple       0.002862
key          0.053202
less-than    1.454200

Benchmarking 10^4 (10000) strings:
simple       0.032566
key          0.569946
less-than   21.170543

Benchmarking 10^5 (100000) strings:
simple       0.341759
key          5.622884
less-than  260.840497
```

```
use file
use math
use path
use str

range 1 6 | each {|p|
    var n = (math:pow 10 $p)
    echo
    echo "Benchmarking 10^"$p" ("$n") strings:"
    var @l = (range $n | each {|x| put (randint (/ $n 2))" line "$x })

    time &on-end={|d| printf "%-10s %10.6f\n" simple $d } {
        order $l | to-lines > /tmp/simple
    }
    time &on-end={|d| printf "%-10s %10.6f\n" key $d } {
        order $l &key={|v| num (str:split " " $v &max=2 | take 1) } | to-lines > /tmp/key
    }
    time &on-end={|d| printf "%-10s %10.6f\n" less-than $d } {
        order &less-than={|a b|
            var a-key = (num (str:split " " $a &max=2 | take 1))
            var b-key = (num (str:split " " $b &max=2 | take 1))
            < $a-key $b-key
            } $l | to-lines > /tmp/less-than
    }
}
```

**Comment by krader1961** [comment]
I was waiting for my earlier change to support comparing boolean values to be merged before creating a pull-request for this feature. Now that comparing booleans is possible (see issue #1585) I'll proceed with creating a pull-request to resolve this issue.
