### ISSUE TITLE
Failing to connect dl.elv.sh

### ISSUE THREAD

**Issue by rakino** [elves/elvish#1589]
```
~ $ curl -v https://dl.elv.sh/linux-amd64/elvish-HEAD.tar.gz
*   Trying 172.93.189.248:443...
* Connected to dl.elv.sh (172.93.189.248) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 444 certificates in /run/current-system/profile/etc/ssl/certs
* GnuTLS ciphers: NORMAL:-ARCFOUR-128:-CTYPE-ALL:+CTYPE-X509:-VERS-SSL3.0
* ALPN: offers h2
* ALPN: offers http/1.1
* gnutls_handshake() failed: Internal error
* Closing connection 0
curl: (35) gnutls_handshake() failed: Internal error
```

Firefox: `SSL_ERROR_INTERNAL_ERROR_ALERT`
Chromium: `ERR_SSL_PROTOCOL_ERROR`

**Comment by rakino** [comment]
#1558

**Comment by krader1961** [comment]
Works for me both using curl and my browser. However, my system connected to 51.158.65.224 which is a swc.cloud server. Whereas `host 172.93.189.248` reports a NXDOMAIN error which makes sense since it is a private address. So apparently you're going though a local proxy that is causing problems.

**Comment by rakino** [comment]
@krader1961 Thank you!
