### ISSUE TITLE
There should be a `$platform:tty-name` variable

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1594]
While working on issue #1263 it occurred to me it would be good if users didn't have to do something like this to write portable code:

```
use platform
var tty-name
if $platform:is-unix {
    set tty-name = "/dev/tty"
} else if $platform:is-windows {
    set tty-name = "con:"
} else {
    fail "could not determine the tty device name"
}
```

I thought Go had a constant that defined the appropriate string for each supported platform but I can't find it. Regardless, this seems like something Elvish should provide via a `$platform:tty-name` variable.

**Comment by krader1961** [comment]
I looked at the Go source code and could not find a single mention of `CON:`. There are a handle of uses of `/dev/tty` but no constant that is exposed by the Go stdlib. That surprises me but I still believe adding a `platform:tty-name` variable will make it easier for a user to write portable Elvish code.

**Comment by iandol** [comment]
This should be fixed by https://github.com/elves/elvish/commit/34dab39da1ce2b443198dd191e99b87aef2617f8 ?

**Comment by krader1961** [comment]
@iandol, Good catch. I had forgotten I had opened this issue when I opened #1633. Closing this as resolved.
