### ISSUE TITLE
The `-cpuprofile` flag no longer works

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1605]
I was working on a fix for issue #1377 and was surprised that

1) the default `elvish` binary did not support the `-cpuprofile` flag, and

2) that building with `go build -o ./elvish ./cmd/withpprof/elvish` did not result in an Elvish binary that correctly handled the `-cpuprofile` flag. With, or without, my fix for handling the `exit` command.

The reason for both issues is commit 33a04f8dc, merged seven months ago, that refactored the code in response to the desire to minimize the size of the `elvish` binary for unusual situations. Such as using `elvish` as a shell in an embedded environment where every byte in the size of the binary matters. 

Issue #1 is because we now have to do something like `go build ./cmd/withpprof/elvish` rather than simply running `make get` (which, FWIW, I have never liked as a `make` target name).

Issue #2 is because the [defer](https://github.com/elves/elvish/blob/2986d29f34113823f39243715fe0fd70b6925681/pkg/pprof/pprof.go#L29) in the cpuprofile setup stops profiling when the [pprof `Run()`](https://github.com/elves/elvish/blob/2986d29f34113823f39243715fe0fd70b6925681/pkg/pprof/pprof.go#L21) function returns. Which is before anything useful to be profiled is executed.

On my macOS ARM system the `elvish` binary without pprof support is 9.5 MB, and with it the size is 9.8 MB. That is a 3.2% increase in size for profiling support. Performance metrics are extremely useful; especially in a relatively new shell like Elvish that is undergoing rapid development. A borderline insignificant increase in the size of the binary is worthwhile, IMHO, to make it easy to capture performance metrics that will help us figure out where it is most advantageous to make performance improvements.

**Comment by krader1961** [comment]
For those wondering about the rationale for commit 33a04f8: It was primarily in response to the [u-root](https://github.com/u-root) project wanting an easier way to build an Elvish binary that did not include support for the interactive history daemon. That project desired a shell written in Go whose binary was as small as possible. They had been using an old version of the source that they had edited by hand to eliminate the daemon. But users of that project were unhappy that the documented behavior of the current Elvish version was very different from the (old) version they provided. So we restructured the Elvish source to include a `cmd/nodaemon` build target so that the `u-root` project would have  way to depend on a current version of Elvish with minimal effort. As part of that work @xiaq decided to also make support for the `-cpuprofile` flag optional and not included in either the standard or no-daemon Elvish binary.

Rather than fix the `cmd/withpprof` build target I'm inclined to simply undo commit 33a04f8 and move profiling support back into the standard Elvish binary; which means it will also be part of the `cmd/nodaemon` target used by the `u-root` project. While this will increase the size of the Elvish binary the difference is small and shouldn't be a problem -- even for the `u-root` project. Too, the utility of always being able to get profiling data is going to be valuable as we begin focusing more on performance and less on changes to the syntax of Elvish.

**Comment by krader1961** [comment]
Should there should be separate `-cpuprofile` and `-memprofile` flags or a single `-profile` flag that enables both profiles with distinct file names using the `-profile` argument as a prefix? As I write this the change I am working on has distinct flags for consistency with the Go tools.

**Comment by krader1961** [comment]
> While this will increase the size of the Elvish binary the difference is small and shouldn't be a problem -- even for the u-root project.

I am also of the opinion that if the small (~3%) size increase is a problem for the u-root project then the `nodaemon` build should be modified to also explicitly exclude profiling support. That is, profiling should be enabled for standard Elvish builds.

**Comment by krader1961** [comment]
The discussion regarding P.R. #1606 makes it clear that simply moving profiling support back into the primary Elvish binary is not an acceptable solution. So the question is how to fix the problem in the current *cmd/withpprof/elvish* build target that causes it to not emit profiling data. Also, when fixing that problem support for a `-memprofile` option should be added.

**Comment by xiaq** [comment]
Regarding other points:

- Re `-memprofile`: there are two different types of memory profiles, `heap` and `allocs`. `heap` doesn't make sense as a global flag; I added support for `allocs` and the flag is called `-allocsprofile`.

- Re the name `nodaemon`: it describes the difference with the "default" variant in cmd/elvish. Renaming it "tiny" may become necessary in future if it sheds more components, but doesn't make so much sense now.
