### ISSUE TITLE
The `List` value type is rendered weird on the language ref HTML page

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1608]
The `List` value type is rendered incorrectly on the [language](https://elv.sh/ref/language.html#list) reference page because it has an anchor element with `id="toc-list"`. The incorrect rendering is because *website/style.css* defines a selector with that name:

```
#toc-list {
    margin-left: -0.6em;
}
```

Notice the unexpected outdenting:

<img width="279" alt="Screen Shot 2022-09-17 at 19 38 52" src="https://user-images.githubusercontent.com/7545917/190883207-bbf9484b-75f1-4fa7-9218-7c4591977e42.png">

The simplest fix is to change `## List` to `## Lists` in *website/ref/language.md*. However, that is inconsistent with the naming of the other value types which use the singular form. TBD is how best to fix this stylistic issue.

**Comment by xiaq** [comment]
Just changed the pandoc template to avoid the conflict.
