### ISSUE TITLE
`make get` failed with low go version (go1.15.5)

### ISSUE THREAD

**Issue by astraw99** [elves/elvish#1610]
When building elvish with `make get`, got this error:
```
make get
mkdir -p /home/dev/go/bin
go build -o /home/dev/go/bin/elvish ./cmd/elvish
pkg/edit/editor.go:9:2: package embed is not in GOROOT (/usr/lib/golang/src/embed)
make: *** [get] Error 1
```

After check, it is the go version too low (go1.15.5) lead this.

**Comment by xiaq** [comment]
Well, the Go version requirement is just above the build instruction.

Go 1.15.5 is very old, very few Go programs retain compatibility with it.

**Comment by xiaq** [comment]
d7c5e35d39304f302371b12827cc5e22001f99e9 updated the README so that it no longer directs the user to use `make get` at all.

**Comment by astraw99** [comment]
OK, just encounter the README updating...
But now, with the latest master code, try `go install ./cmd/elvish`, just got error:
```
pkg/edit/editor.go:9:2: package embed is not in GOROOT (/usr/lib/golang/src/embed)
```

So maybe it is better to add go version hints. What do you think?

**Comment by xiaq** [comment]
Well, `go install` is the standard for Go programs these days, and I don't control how it behaves. It's also unlikely for Go developers to add this type of version check to old versions of Go.
