### ISSUE TITLE
The `eq` command fails to correctly compare exception objects

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1632]
There was a recent discussion on the IM channels about how to deal with the exception raised by builtins like `break`, `continue`, and `return`. That caused me to notice that this fails to produce the expected, `true`, result:

```
elvish> var e = ?(break)
elvish> eq ?(break) $e
▶ $false
```

That is, obviously, a contrived and not particularly interesting example in isolation. But it illustrates that the `eq` command fails to correctly compare exception objects such as raised by the control flow builtins. Which makes it impossible for examples like this (again, contrived and simplified) to work as expected:

```
elvish> try { break } catch e { if (eq ?(break) $e) { put "break captured" } }
```

**Comment by hanche** [comment]
It seems relevant here to mention this issue:

Exception control: “try” should rethrow flow control exceptions #1396

After all, one reason for trying to compare exceptions is to recognize flow control exceptions happening in a `try` block so one can rethrow them.

**Comment by krader1961** [comment]
As @dzu pointed out on the IM channels the reason `eq` doesn't output `$true` is due to the inclusion of backtrace data you can otherwise only see using the `show` builtin. Whether `eq` should ignore the backtrace data is debatable. However, comparing exceptions using `eq` is useless, AFAICT, unless the backtrace data is ignored. Which includes exceptions created by the `fail` builtin; not just the special builtins like `break`, `continue` and `return`. The fact the backtrace data isn't exposed by `put` or `repr` also suggests that information isn't interesting with respect to deciding if two exception objects are equivalent (however, I wish they made it clearer the object was an exception rather than a simple map).

**Comment by krader1961** [comment]
I played around with capturing, and comparing, the output of `fail` and still believe that `eq` should exclude the backtrace data when comparing exception objects. It should, however, obviously still consider the exception pseudo-type in the comparison so that a simple map with the same content (excluding the backtrace) isn't treated as equal.

**Comment by dunsany** [comment]
I think that comparing exceptions with `eq` should behave just by comparing types of `reason` fields, as documented [here](https://elv.sh/ref/language.html#exception).

**Comment by hanche** [comment]
I agree with the two previous comments (I believe they don't contradict each other). There is always the [`is`](https://elv.sh/ref/builtin.html#is) function if you need a really strict check.

**Comment by krader1961** [comment]
I wrote this in my original problem statement:

> But it illustrates that the eq command fails to correctly compare exception objects such as raised by the control flow builtins.

That is an obviously very opinionated statement since including the backtrace data in the comparison is not wholly unreasonable. However, I stand by my statement. Including the backtrace data in the comparison effectively means the `eq` comparison will always output `$false` since it seems to me only the tautological comparison of `eq $e $e` (In an `try...catch e { }` block) would ever output `$true`.

**Comment by krader1961** [comment]
Note also this example that unexpectedly outputs `$false` because the two `break` commands are not in identical positions vis-a-vis the execution context:

```
elvish> eq ?(break) ?(break)
▶ $false
```

The inclusion of the backtrace in the exception comparison by the `eq` command is not useful in any context that I can imagine.

**Comment by dunsany** [comment]
> However, I stand by my statement.

It sounds like you're arguing. Who are you arguing with?

> Note also this example that unexpectedly outputs `$false`

Not unexpectedly, it's effectively the same example as in your first post in this issue, putting it in one line changes nothing.

**Comment by krader1961** [comment]
> It sounds like you're arguing. Who are you arguing with?

I'm arguing with myself and anyone who disagrees with my analysis. It seems like you, @dunsany, agrees that the  `eq` builtin should ignore the backtrace of exception objects. However, given your comment I am replying to it is not entirely clear that is true.

**Comment by dunsany** [comment]
I hoped that it would be. Backtrace data is not included in the documentation, so [this comment](https://github.com/elves/elvish/issues/1632#issuecomment-1362728729) means I agree with you that it should not be included in the comparison. It may be a nice thing to expose that data in the pseudo-map, and then documentation would change, of course, but that wouldn't change my mind about comparison. I also can't imagine any scenario where comparing backtrace data would be useful. Doing that would be effectively an identity check, and we have a separate function for that - `is`.

**Comment by krader1961** [comment]
@dunsany, The [comment](https://github.com/elves/elvish/issues/1632#issuecomment-1362728729) you linked to says "eq should work simply by comparing types of reason fields". I am fairly certain you meant to write that the comparison should include the type of the exception as well as the actual value while ignoring the traceback data. I am probably being pedantic with this commen, and I think we are in agreement, but I feel precision is important. Otherwise someone may think you meant that all exceptions generated by the `fail` builtin are equal regardless of their value.

**Comment by dunsany** [comment]
You are right, of course. There were just two words too much:

> I think that comparing exceptions with eq should work simply by comparing ~~types of~~ reason fields as documented [here](https://elv.sh/ref/language.html#exception).

**Comment by xiaq** [comment]
The reason is that exceptions also have stack traces that are not exposed to Elvish, but participate in equality tests. You can use `eq $e1[reason] $e2[reason]` as a workaround.

**Comment by xiaq** [comment]
Actually, `eq $e1[reason] $e2[reason]` is not a workaround but rather the intended way to compare that two exceptions have the same reason. The actual issue here is that the stack traces are not exposed.

**Comment by krader1961** [comment]
> Actually, eq $e1[reason] $e2[reason] is not a workaround but rather the intended way to compare that two exceptions have the same reason.

I still feel this should be the default behavior when doing `eq $e1 $e2` as including the stack trace in the equality test is never useful, and as the discussion in this issue shows, is a confusing and a source of bugs.

**Comment by xiaq** [comment]
> > Actually, eq $e1[reason] $e2[reason] is not a workaround but rather the intended way to compare that two exceptions have the same reason.
> 
> I still feel this should be the default behavior when doing `eq $e1 $e2` as including the stack trace in the equality test is never useful, and as the discussion in this issue shows, is a confusing and a source of bugs.

It was confusing because printing the exception object didn't indicate that it contains the stack trace.

**Comment by SigmaBonder** [comment]
> > I still feel this should be the default behavior when doing `eq $e1 $e2` as including the stack trace in the equality test is never useful, and as the discussion in this issue shows, is a confusing and a source of bugs.
> 
> It was confusing because printing the exception object didn't indicate that it contains the stack trace.

So that would leave "never useful" and "source of bugs" on the table, which I'm inclined to agree with. What are your thoughts on the matter? What would be wrong with `eq` comparing anything but the stack traces and `is` behaving as usual?

**Comment by dunsany** [comment]
> > I still feel this should be the default behavior when doing `eq $e1 $e2` as including the stack trace in the equality test is never useful, and as the discussion in this issue shows, is a confusing and a source of bugs.
> 
> It was confusing because printing the exception object didn't indicate that it contains the stack trace.

So that would leave "never useful" and "source of bugs" on the table, which I'm inclined to agree with. What are your thoughts on the matter? What would be wrong with `eq` comparing anything but the stack traces and `is` behaving as usual?

**Comment by xiaq** [comment]
> > > I still feel this should be the default behavior when doing `eq $e1 $e2` as including the stack trace in the equality test is never useful, and as the discussion in this issue shows, is a confusing and a source of bugs.
> > 
> > 
> > It was confusing because printing the exception object didn't indicate that it contains the stack trace.
> 
> So that would leave "never useful" and "source of bugs" on the table, which I'm inclined to agree with. What are your thoughts on the matter? What would be wrong with `eq` comparing anything but the stack traces and `is` behaving as usual?

The important bit here is consistency. `eq` is a structural equality comparison function, and should only output true when the two values are actually structurally equal. If two exceptions have different stack traces, they are _not_ structurally equal. The stack trace component wasn't visible before and is still not really accessible yet, but it is actually there and will be made accessible.

When designing a language, you can bend rules to make certain use cases work nicer, but this kind of micro-optimizations usually end up making the language worse as a whole.

**Comment by dunsany** [comment]
What about putting this optimization behind a pragma?

**Comment by xiaq** [comment]
A pragma for how `eq` works on a specific type of values seems to be overkill.

I'm putting "the behavior of `eq` for comparing exception values" in the "things you need to learn" folder. When the `stack-trace` field is properly exposed, I doubt this will be a point of confusion for many people.

**Comment by krader1961** [comment]
> It was confusing because printing the exception object didn't indicate that it contains the stack trace.

That is only part of the reason for the confusion. The fact is that you have to, today, always write `eq $e1[reason] $e2[reason]` and `eq $e1 $e2` is **never useful**. Having Elvish treat the two formulations the same is backward compatible and makes writing correct Elvish code easier. 

> The important bit here is consistency. eq is a structural equality comparison function, and should only output true when the two values are actually structurally equal. If two exceptions have different stack traces, they are not structurally equal. 

Your second statement is true but I disagree with the first statement and thus the rationale for the current behavior. Can anyone provide an example where including the stack trace in a structural equality comparison of two exception objects is useful? Or, to put it another way, my proposal is implemented would make it difficult to perform a useful exception comparison where you want the stack trace to be included in the comparison? This seems like another case where pragmatism is more important than purity.
