### ISSUE TITLE
special-case two paths, /dev/tty and /dev/null, on Windows

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1633]
There was a recent IM discussion pointing out the challenge of writing an Elvish program that needs to use the UNIX paths */dev/tty* and */dev/null* on Windows. On Windows the equivalent are *con* and *nul* (or *//./con* and *//./nul* if using UNC names). It's a PITA to deal with this in a portable manner so it was suggested that it would be helpful if Elvish implicitly converted the UNIX device names to their Windows equivalent. Alternatively, have builtin vars that expand to the appropriate string for each platform; e.g., `DevNul` and `DevTty`. As a long time UNIX programmer I don't like that option but include it for discussion since it is explicit and avoids introducing behavior that might surprise a Windows programmer.

**Comment by krader1961** [comment]
> Wouldn't $path:dev-tty and $path:dev-null (and maybe $path:con and $path:nul) be appropriate places for this?

Agreed, assuming we want to go the variable route. And having slept on the matter I'm now leaning towards variables rather than magically special-casing the /dev pathnames since doing so is likely to be hard to document in a discoverable fashion. Not to mention it feels wrong to privilege the UNIX device names and not the Windows equivalents.

**Comment by xiaq** [comment]
Yes, variables are the way to go.
