### ISSUE TITLE
Way to stop history mode and start command mode without clearing line.

### ISSUE THREAD

**Issue by aca** [elves/elvish#1636]
I wanted to close history navigation and start command(vi) mode to edit command in the history. 

Up -> ESC

But it clears the line. So I tried this but it doesn't work properly.

```
set edit:history:binding["Ctrl-["] =  { edit:command:start }
```

<img width="246" alt="image" src="https://user-images.githubusercontent.com/50316549/210494570-b64a2afb-9617-4a36-a744-69d4857eaf50.png">

And this doesn't work as edit:close-mode clears the line.
```
set edit:history:binding["Ctrl-["] =  { edit:close-mode; edit:command:start }
```

I am searching for some api to preserve current line in history mode. 
Or let me know if anyone knows the trick. I'm not sure some new api should be introduced for this.

**Comment by xiaq** [comment]
This is a gap in the API. There should be a new function `edit:history:accept` for this.
