### ISSUE TITLE
Completion for md-to-clip tool

### ISSUE THREAD

**Issue by EmilySeville7cfg** [elves/elvish#1676]
Hi! As a project author, I am requesting elvish completion based on [Bash completion](https://github.com/command-line-interface-pages/v2-tooling/tree/main/md-to-clip#completions-pencil) for my CLI tool. What it does: basically, it converts TlDr pages to Command Line Interface Pages. The difference between them, that the last ones have [more expressive syntax](https://github.com/command-line-interface-pages/syntax/blob/main/type-specific/cli.md).

[Here](https://command-line-interface-pages.github.io/site.github.io/about/) is a project site.

**Comment by xiaq** [comment]
Hi! Elvish is quite some distance away from shipping completion scripts for external commands, and when it does, it's likely going to ship completion scripts for some very commonly used ones.

If you'd like to provide your users with a better experience, my suggestion is to ship an Elvish completion script with your project itself.

Elvish's completion system is still subject to change though and I expect it will become easier to write completion scripts in future, but it's not a priority at the moment.

**Comment by xiaq** [comment]
This won't be actionable for Elvish for a while (if ever), so I'll close this for now.
