### ISSUE TITLE
Native Windows port

### ISSUE THREAD

**Issue by Bigous** [elves/elvish#168]
Hi, is there any plan to support windows?

**Comment by xiaq** [comment]
Windows support would be nice to have, but it's not a priority. With the coming Linux subsystem in Windows 10 we might as well be able to run the Linux binary directly; it's also more likely to stablelize faster than elvish, so I recommend you to just wait. :)

**Comment by be5invis** [comment]
However most Windows users need a **native** port, which means

 * Seamless interop with all existing .exes
 * Supports Unicode via wide APIs
 * Some code to deal with backslashes?

**Comment by xiaq** [comment]
Elvish seems to work on WSL just fine, but a native Windows port will be even nicer.

The first difficulty I encountered is that Windows does not have a `select` syscall, which is used by `edit/async-reader.go`.

**Comment by huiyiqun** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740141(v=vs.85).aspx

How about this?

**Comment by xiaq** [comment]
@huiyiqun This is part of winsocks and only works on sockets:

> The select function determines the status of one or more **sockets**, waiting if necessary, to perform synchronous I/O.

**Comment by be5invis** [comment]
@xiaq Switch to libuv (

**Comment by xiaq** [comment]
@be5invis i do not want to introduce another C dependency. It would be great to know how libuv implements its event loop in Windows and learn from it, though.

**Comment by xiaq** [comment]
Hmm, I/O polling is done with [I/O Completion Ports](https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365198%28v=vs.85%29.aspx) on Windows.

**Comment by GoLangsam** [comment]
I'd highly appreciate a native Win Version as well. And I'd like to use Your language (only) in a project.
Thus, I need to ask: Is the language (less shell!) intended to be and remain(!) usable on M$-Win?
My second question: "Is there a plan to separate the language more strictly from 'rest'" is probably stupid, and may not need a new issue?

**Comment by Chilledheart** [comment]
Below is my progress on elvish's [windows support](https://github.com/Chilledheart/elvish/commits/win32):
- [x] use WaitForMultipleObjects under windows
- [x] mask Umask under windows
- [ ] call ReadConsoleInput to clean up mouse events
- [ ] termios layer cleanup for windows

Beside a `select` syscall, windows terminal behaves differently from unix's. It is not supported by termios package, you can refer to microsoft's document https://docs.microsoft.com/en-us/windows/console/using-the-console

**Comment by Chilledheart** [comment]
I just tried the program below using IOCP and it didn't work with "invalid handle" runtime errors.
It is a shame that IOCP can't handle with windows console. Just let you know that.

```
#include <conio.h>
#include <iostream>
#include <windows.h>
#include <string>

static std::string GetErrorStr(int error) {
  char err[4096] = {};
  FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM, NULL, error,
                MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), err, sizeof(err) - 1,
                NULL);
  return err;
}

int main() {
  std::string inStr;
  DWORD fdwMode, fdwOldMode;
  HANDLE hStdIn = GetStdHandle(STD_INPUT_HANDLE);
  FlushConsoleInputBuffer(hStdIn);
  auto port = CreateIoCompletionPort(hStdIn, NULL, NULL, 1);
  if (port == INVALID_HANDLE_VALUE) {
    std::cerr << "CreateIoCompletionPort(): " << GetErrorStr(GetLastError()) << std::endl;
    return -1;
  }

  while (true) {
    DWORD bytes;
    ULONG_PTR completion_key;
    LPOVERLAPPED overlapped;
    if (GetQueuedCompletionStatus(port, &bytes, &completion_key, &overlapped, INFINITE)) {
      if (_kbhit()) {
        std::cerr << "kb event" << std::endl;
        int i = _getch();
      } else {
        // clear events
        INPUT_RECORD r[512];
        DWORD read;
        ReadConsoleInput(hStdIn, r, 512, &read);
        std::cerr << "mouse event" << std::endl;
      }
    } else {
      std::cerr << "GetQueuedCompletionStatus(): " << GetErrorStr(GetLastError()) << std::endl;
    }
  }
}
```

**Comment by stealthybox** [comment]
I wonder if it would run well under MSYS /w mintty?
Don't have a machine to test this anymore.

**Comment by be5invis** [comment]
@Chilledheart 
Console is a very weird thing. Like, it talks to the video adapter DIRECTLY, so in theory you can draw text outside the console window.

**Comment by be5invis** [comment]
@xiaq 
Do we need an alternative syntax that changes escape character from `\` to something else (like `` ` ``)? The scripts for alternative syntax should use `.elw` extension rather than `.elv`.

**Comment by xiaq** [comment]
Latest status:

Elvish builds and runs on Windows since 55d7b6f944ea9d1109c15621379691f9806ecf49. However,

* The daemon does not work yet since it uses Unix sockets. This can be fixed by falling back to a localhost-only TCP socket (or Windows's equivalency of Unix sockets, if any) on failure to create an Unix socket.

* The line editor does not work yet since it depends on `select` for reading console inputs. Windows's `select` is implemented in userland and only works on sockets. The fix is to use `WaitMultipleObjects`, which supports waiting for console inputs. Contrary to what I believed earlier, it is not necessary to use async I/O. In fact, `select` on Unix does not require the use of async I/O either; dependency on async I/O has been dropeed since 49282286a2ecaf83c9e5cfe8ab18cb46507d75fd.

  As a side note, Windows's `ReadConsoleInput` API provides direct access to console events, which will make for a much simpler and more reliable event reader for the line editor.

**Comment by Chilledheart** [comment]
Well Done, Qi!

**Comment by xiaq** [comment]
Closing this as there is basic support for Windows now. For further work, see the "Windows support" column in the [backlog](https://github.com/elves/elvish/projects/4)
