### ISSUE TITLE
Clojure already has pipelines, FYI

### ISSUE THREAD

**Issue by roryokane** [elves/elvish#17]
Clojure actually does have a way to avoid the reverse-order problem with Lisps that you lament in the README. Here is another way of writing your example Clojure code from [the end of the README](https://github.com/xiaq/elvish#appendix-a):

```clojure
(require ['clojure.string :refer '(upper-case)])
(def strs '("aha" "LOLaha" "hahaLOL" "hum?"))
(def lols (->> strs
               (filter #(re-find #"LOL" %))
               (map upper-case)
               sort))
```

As you can see, the functions are written in the order they are applied, by using the [`->>` macro](http://grimoire.arrdem.com/1.6.0/clojure.core/DASH_GT_GT/) (similar to the [`->` "thread" macro](http://grimoire.arrdem.com/1.6.0/clojure.core/DASH_GT/)). I don't know enough about Clojure to say whether use of that macro is idiomatic or not, but Clojure does support it. You should note it as an alternative in your README.

Since fixing the problems with Lisps' pipelining seems to be one of the goals of your shell, you should consider Clojure's approach as an option.

**Comment by xiaq** [comment]
Due credit is given to the `->` and `->>` constructs in the latest version of README.
