### ISSUE TITLE
Execute command line on Windows and dll in the same path

### ISSUE THREAD

**Issue by darcy-shen** [elves/elvish#1708]
Elvish Vesion: 1.19.2
OS: Windows 11

I think it is a elvish bug: https://github.com/xmake-io/xmake/issues/3942

Here is the invoke chain:
+ C:\Qt\Tools\mingw810_64\bin\windres.exe
   + C:\Qt\Tools\mingw810_64\bin\gcc
      + C:/Qt/Tools/mingw810_64/bin/../libexec/gcc/x86_64-w64-mingw32/8.1.0/cc1.exe

I found that using elvish, cc1.exe can not find `C:/Qt/Tools/mingw810_64/bin/libwinpthread-1.dll`

It might be feature but not a bug???

**Comment by krader1961** [comment]
> Elvish Vesion: 1.19.2

There is no such Elvish version.

I read the other issue you linked to. I cannot see how this, or the other issue, has anything to do with the Elvish shell.

**Comment by darcy-shen** [comment]
> I read the other issue you linked to. I cannot see how this, or the other issue, has anything to do with the Elvish shell.

Yes, not a elvish issue. Just ignore it.
