### ISSUE TITLE
Lambda variable highlighted as red (nonexistent)

### ISSUE THREAD

**Issue by hexchain** [elves/elvish#172]
![1459836637](https://cloud.githubusercontent.com/assets/529520/14272734/354c0284-fb38-11e5-80ff-75ae22784ed1.png)

**Comment by xiaq** [comment]
It is no longer colored as red but entirely uncolored now. On the other hand, variables get a purple coloring when it is not used as the command. Interesting.

**Comment by xiaq** [comment]
The reason for the aforementioned phenomena is caused by `edit.writer` not joining styles correctly, which has been fixed in 69dca19b68757ac092af38deccdf1cfe2b8e4660. Now they are red again.
