### ISSUE TITLE
New built function: filter

### ISSUE THREAD

**Issue by da-tubi** [elves/elvish#1721]
How about add a new built-in `filter`:
```
fn filter {|pred @rest|
  each {|x|
    if ($pred $x) {
      put $x
    }
  } $@rest
}
```

**Comment by hanche** [comment]
If so, I would like an option `&not` to invert the sense of the test. And perhaps even an option `&out` (defaulting to `$put~`) to specify an output function.

Here is my current filter function:

```
fn filter {|pred~ @items &not=$false &out=$put~|
  var ck~ = $pred~
  if $not { set ck~ = {|item| not (pred $item)} }
  each {|item| if (ck $item) { $out $item }} $@items
}
```

**Comment by da-tubi** [comment]
Here is the scala code snippet of filter and filterNot:
```
scala> Seq(1, 2, 3).filter(x => x % 2 == 0)
res0: Seq[Int] = List(2)

scala> Seq(1, 2, 3).filterNot(x => x % 2 == 0)
res2: Seq[Int] = List(1, 3)
```

**Comment by wizhi** [comment]
@hanche 

> I would like an option &not to invert the sense of the test.

I think you're better off using composable functions instead:

```elvish
fn fnot {|f| put {|@args| not ($f $@args) }}
fn even {|n| == (% $n 2) 0 }

range 5 | filter (fnot $even~)
▶ (num 1)
▶ (num 3)
```

Even better, [define a `comp` function](https://github.com/wizhi/dot-elvish/blob/791dc9ceb7f86b184d419b995ed26f70d6ba0f1a/lib/fn.elv#L13):

```elvish
fn even {|n| == (% $n 2) 0 }

range 5 | filter (fn:comp $not~ $even~)
▶ (num 1)
▶ (num 3)
```

> And perhaps even an option &out (defaulting to $put~) to specify an output function.

I think this breaks the pipeline nature of the shell. Again, you can compose things so nicely with pipes:

```elvish
fn even {|n| == (% $n 2) 0 }
fn exclaim {|s| put $s! }

range 5 | filter (fn:comp $not~ $even~) | each $exclaim~
▶ 1!
▶ 3!
```

**Comment by krader1961** [comment]
I have had a `filter` command in my Elvish config for a long time (see https://github.com/krader1961/elvish-lib/):

```
# Filters a sequence of items and outputs those for whom the function outputs
# $true.
fn filter {|&out=$false func~ @inputs|
    if $out {
        each {|item| if (not (func $item)) { put $item } } $@inputs
    } else {
        each {|item| if (func $item) { put $item } } $@inputs
    }
}
```

This arguably should be a builtin but only if doing so improves the performance.

**Comment by crinklywrappr** [comment]
@da-tubi https://github.com/crinklywrappr/rivendell
