### ISSUE TITLE
new rc location not being read

### ISSUE THREAD

**Issue by ThinkSalat** [elves/elvish#1727]
according to documentation [here](https://elv.sh/ref/command.html#rc-file), the rc.elv file should be located in `%AppData%\elvish\rc.elv`. On windows, this goes to  `~\AppData\Roaming\elvish`.  however it is not reading from this rc.elv. When I place the same rc.elv in the legacy folder, `~\.elvish\rc.elv`, it does read from the rc.elv file

**Comment by krader1961** [comment]
`elvish --version`? Also, if the legacy path exists it is used even if the AppData path exists unless you're running the latest version of Elvish. So make sure only one of those files exists. And if you're running a sufficiently new version of Elvish then running `put $runtime:effective-rc-path $runtime:rc-path` can be helpful.

**Comment by ThinkSalat** [comment]
Huh. I think something is wrong with my install... I have it in program files. I downloaded the exe from [here](https://dl.elv.sh/windows-amd64/elvish-HEAD.zip). 
![image](https://github.com/elves/elvish/assets/31082405/43c57504-6189-4637-8b1e-4d2b729257a0)


Same thing happens whenever I run ls, mkdir, etc. I followed everything [here](https://elv.sh/get/), then tried to install starship

this issue comes up trying to enter the `put` command above as well:

![image](https://github.com/elves/elvish/assets/31082405/bf4fcd8d-aed5-4631-947f-a836d46a1df9)

**Comment by krader1961** [comment]
Only the [`builtin`](https://elv.sh/ref/builtin.html) module is imported automatically. You have to explicitly import all other modules. I put this at the top of my *rc.elv*:

```
# Standard elvish modules we always want to be readily available.
use builtin
use epm
use file
use flag
use math
use path
use platform
use re
use readline-binding
use runtime
use store
use str

# Make my modules available.
use interactive
use github.com/krader1961/elvish-lib/util
```

The most likely reason the `elvish` binary isn't found is because you are modifying `E:PATH` (or `paths`) in your *rc.elv*. Programs like `ls` are not built into Elvish. They are external commands you'll need to install and put the appropriate directory in `E:PATH`.

**Comment by ThinkSalat** [comment]
Thanks for your help in the matrix Kurt. Closing this as resolved.

The issue: I had XDG_CONFIG_HOME set to a nonexistent directory, and I also didn't have the elvish install directory in my path.

**Comment by mijdavis2** [comment]
For anyone else coming here with issues, the new config path is actually `~/.config/elvish/rc.elv`
