### ISSUE TITLE
completion problem with soft link to directory

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#173]
```
~> cd soft-link-to-dir<tab>
```
will results in
```
~> cd soft-link-to-dir<space inserted here>
```
instead of
```
~> cd soft-link-to-dir/
```

**Comment by xiaq** [comment]
The filename completer uses `ioutil.ReadDir`, which in turns uses `os.Lstat` to stat a file, which reports symlinks to directories as files. Working on a fix.

**Comment by xiaq** [comment]
Hmm, treating symlinks to directories as directories has a minor downside: when trying to remove such a symlink `link-to-dir` by typing `rm link-to<Tab>` will complete to `rm link-to-dir/` which is unwanted. `fish` has this behavior.

`zsh` has a more complex behavior. When completing a directory name, the trailing `/` is appended tentatively: if you press Tab again, it stays, but if you do anything else, it disappears. This sophisticated behavior solves this problem, however I am not sure whether the complexity is worthwhile.
