### ISSUE TITLE
end of history results in `Unbound: Down`

### ISSUE THREAD

**Issue by terlar** [elves/elvish#175]
I am not sure if this is intentional or not, but I got a bit confused when I held down the down arrow key and ended up getting spammed with `Unbound: Down`.

I would suggest either staying silent or perhaps keeping the notification to one line and also have the output more useful.

**Comment by xiaq** [comment]
`Unbound: Down` means that the down key is not bound to any function. The best wording I came up with :) can you suggest something better?

You can silence this message with `le:binding[insert][Down]={ }`, i.e. binding Down in insert mode to an empty function.

And no, I don't want to limit the error output to one line. The general idea is that there may be multiple errors that happen consecutively, and display only the latest one loses information. For instance, imaging that multiple keys are sent very rapidly (perhaps via some keyboard automation tool), none of which is bound. Telling the user that all are not bound is more useful.

**Comment by terlar** [comment]
I see so the history is using a different mode and insert mode has the binding for `Up` which enters history mode? At this point you have the binding for `Down` but as soon as you reach the end of history you get thrown back into the insert mode and then the key `Down` is unbound again.

When you look at it like this it makes sense and is not that confusing. I was just confused because I was browsing the history where `Down` is bound and then suddenly `Down` was unbound. I didn't realize there were different modes with different bindings.

I also agree that you shouldn't limit to the last error.

**Comment by xiaq** [comment]
@terlar Yes that is the case.

But on second thought, I think that the scenario is quite common, so I bound Down in the default mode to a tiny function that just shows "End of history". I hope there will be less confusion for newcomers.
