### ISSUE TITLE
`kill-left-alnum-word` and `kill-alnum-word-left`

### ISSUE THREAD

**Issue by balthild** [elves/elvish#1768]
In the document, there are [`edit:kill-alnum-word-left`](https://elv.sh/ref/edit.html#edit:kill-alnum-word-left) and [`edit:kill-alnum-word-right`](https://elv.sh/ref/edit.html#edit:kill-alnum-word-right). However, they are actually `kill-left-alnum-word` and `kill-right-alnum-word`.

https://github.com/elves/elvish/blob/7b7462f02c1139d63135ddc294359414aac7fa18/pkg/edit/buffer_builtins.go#L54-L55

![图片](https://github.com/elves/elvish/assets/2662758/364bb92c-2eec-4112-887e-6db7f1bf030b)

**Comment by xiaq** [comment]
Thanks for reporting!
