### ISSUE TITLE
Mapping `$edit:close-mode~` has no effect

### ISSUE THREAD

**Issue by plaukiu** [elves/elvish#1798]
As I understand, looking at [readline-binding.elv](https://github.com/elves/elvish/blob/1aeb2f6e98fd45ef2ab853a24b9b27feae5c36e9/pkg/mods/readline-binding/readline-binding.elv#L1), `$edit:close-mode~` should close all non-insert modes back to insert-mode. (and [$edit:completion:close~](https://elv.sh/ref/edit.html#edit:completion:close) has been removed, right?)

I am trying to remap `C-q` to do the same thing. I try 
```
set edit:global-binding[C-q] = $edit:close-mode~
set edit:global-binding[Ctrl-Q] = $edit:close-mode~
set edit:completion:binding[C-q] = $edit:close-mode~
set edit:listing:binding[C-q] = $edit:close-mode~
```
and others, but none of them have any effect: while `C-g` continues to close modes, `C-q` does nothing.

Am I doing something wrong?

**Comment by xiaq** [comment]
I'll close this because it's a terminal issue - in the meantime I've added some notes to https://elv.sh/ref/edit.html#format-of-keys that some keys may not be available due to limitations of the terminal.

**Comment by xiaq** [comment]
I've also removed the doc for edit:completion:close.

**Comment by plaukiu** [comment]
thank you! for your prompt responses and actions :))

**Comment by plaukiu** [comment]
But it's weird that `C-q` are received properly by other applications! Is it possible that elvish does not disable its IXON flag of its termios when it establishes a connection with the terminal?

**Comment by xiaq** [comment]
> But it's weird that `C-q` are received properly by other applications! Is it possible that elvish does not disable its IXON flag of its termios when it establishes a connection with the terminal?

Yes - these are all the termios manipulation Elvish does:

https://github.com/elves/elvish/blob/a03125e10e84c115ed0c63ebcc5fdcb5526f00d8/pkg/cli/term/setup_unix.go#L24-L36

I haven't really dug deep enough into termios stuff to know whether it's safe for Elvish to always disable IXON. I guess you can always call `stty -ixon` yourself - are there precedents from other shells or terminal programs to disable IXON?

**Comment by plaukiu** [comment]
> > But it's weird that `C-q` are received properly by other applications! Is it possible that elvish does not disable its IXON flag of its termios when it establishes a connection with the terminal?
> 
> Yes - these are all the termios manipulation Elvish does:
> 
> https://github.com/elves/elvish/blob/a03125e10e84c115ed0c63ebcc5fdcb5526f00d8/pkg/cli/term/setup_unix.go#L24-L36
> 
> I haven't really dug deep enough into termios stuff to know whether it's safe for Elvish to always disable IXON. I guess you can always call `stty -ixon` yourself - are there precedents from other shells or terminal programs to disable IXON?

yes – fish disables IXON and IXOFF, zsh disables it if the system has termios and termio

**Comment by xiaq** [comment]
> yes. [fish](https://github.com/fish-shell/fish-shell/blob/4e816212a1c5fecc2e9e7079ad9299d51b3416fe/src/reader.rs#L783) disables IXON and IXOFF by default, but provides [a way](https://github.com/fish-shell/fish-shell/pull/7708) to enable it. [zsh](https://github.com/zsh-users/zsh/blob/a66e92918568881af110a3e2e3018b317c054e4a/Src/Zle/zle_main.c#L240) enables IXON by default, but provides an [option](https://zsh.sourceforge.io/Doc/Release/Options.html) (see FLOW_CONTROL) to disable it.
> 
> Fish is valued for its better defaults over zsh. I think keymaps should take precedence over old features – most people won't know it's there, but those who do should know exactly what they're missing. I don't think this specialised piece of knowledge should be required by default.

Nice, I filed https://github.com/elves/elvish/issues/1803.

The user would still need to know quirks like Ctrl-I being identical to Tab, but at least we get two keys back.

**Comment by plaukiu** [comment]
> The user would still need to know quirks like Ctrl-I being identical to Tab
Yess, but they won't need to learn about the historical curiosities of flow control!

And when Kitty keyboard protocol is implemented, even Ctrl-I will go away.

**Comment by xiaq** [comment]
> > The user would still need to know quirks like Ctrl-I being identical to Tab
> 
> Yess, but they won't need to learn about the historical curiosities of flow control! And when Kitty keyboard protocol is implemented, even Ctrl-I will go away.

If they use a terminal that supports the kitty protocol... which none of the more mainstream ones support yet :-/

In any case it's a small incremental improvement, but Elvish is just a small piece of the puzzle.
