### ISSUE TITLE
Programmable listing modes

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#180]
Basically everything that involves "finding something from a list and operate on it" can benefit from a listing mode:
- process listing
- systemd service listing

**Comment by huiyiqun** [comment]
Similar to [fzf](https://github.com/junegunn/fzf)

**Comment by mqudsi** [comment]
fwiw, fzf is also written in go.

Software like neovim supports pluggable list viewers/selectors that the user can swap (fzf, denite, unite, etc). Could be an interesting paradigm if everything is just an interface and elvish provides a basic one that can be swapped out for something else.

**Comment by xiaq** [comment]
There is now `edit:listing:start-custom`.
