### ISSUE TITLE
Some keybindings do not work well in tmux

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#181]
For example:
Alt+{Up,Down,Up,Down} results in:

```
Unbound: Ctrl-Alt-[
Unbound: Ctrl-Alt-[
Unbound: Ctrl-Alt-[
Unbound: Ctrl-Alt-[
~/go/src/github.com/elves/elvish> [A[B[A[B                                                                                                huiyiqun@edge
```

And Ctrl+{Left,Right} is parsed as {Left,Right}

**Comment by xiaq** [comment]
What is your terminal emulator and the value of `$TERM` outside tmux?

**Comment by tw4452852** [comment]
This is because of [this](https://unix.stackexchange.com/a/73697).

**Comment by xiaq** [comment]
Ah, of course Ctrl-Alt-[ is a sign of double ESC.
