### ISSUE TITLE
Scoping of the right hand side of a var assignment

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1829]
### What happened, and what did you expect to happen?

What happens:

```
⬥ var a = x
⬥ var a = [$a $a] ##
⬥ put $a
⮕ [$nil $nil]
```

Expected result should be `[x x]`.

Clearly, the problem is that the right hand side of the assignment (marked `##` in the above code) is *within* the scope of the variable being declared.

I think the correct behaviour (for some value of “correct”  is to first evaluate the right hand side of the assignment, then create the new variable(s) and perform the assignment.

Others may disagree, and some may argue that this is a feature request rather than a bug. But if so, it is at least a documentation bug, since the exact behaviour is not documented.

### Output of "elvish -version"

0.21.0-dev.0.20240724150116-9597a25e366b-dirty

### Code of Conduct

- [X] I agree to follow Elvish's [Code of Conduct](https://src.elv.sh/CODE_OF_CONDUCT.md).

**Comment by hanche** [comment]
This appears to have been introduced with [commit 9597a25e ](https://github.com/elves/elvish/commit/9597a25e366be33374c2c8cbacc1e554bd1968ea) where `with` was introduced.

**Comment by xiaq** [comment]
The original behavior is the intended one and was broken accidentally. A regression test should prevent this from happening in future!
