### ISSUE TITLE
There are no sample scripts

### ISSUE THREAD

**Issue by ilyash** [elves/elvish#185]
Please consider adding sample (demo) scripts written in `elvish`. This will help newcomers to feel the language.

**Comment by xiaq** [comment]
Hi @ilyash, that is a very good suggestion.

For now there are some small snippets of elvish code in the README as well as the [draft language guide](https://elvish.io/_draft/doc/language.html) (keep this URL a secret, it is a draft :). I will do a bigger demo some time.

**Comment by xiaq** [comment]
The website now has a cookbook and a language reference with some examples. Admittedly they are not many, but I think we can call this issue fixed.

**Comment by techtonik** [comment]
Cookbook: https://elvish.io/learn/cookbook.html
Source: https://github.com/elves/elvish.io/blob/master/src/learn/cookbook.md
