### ISSUE TITLE
Flag Commands Cause Panic When Given $nil Arguments.

### ISSUE THREAD

**Issue by 4ffy** [elves/elvish#1850]
### What happened, and what did you expect to happen?

The various functions in the `flag` module cause a Go panic via nil dereference if passed a `$nil` value as any of their arguments. I would expect these to throw an exception, rather than panicking.

**Examples:**

```elvish
flag:call $nil $nil
flag:parse $nil []
flag:parse-getopt $args $nil
```

**Example Stacktrace:**
[log.txt](https://github.com/user-attachments/files/17481630/log.txt)

### Output of "elvish -version"

0.22.0-dev.0.20241021163419-8527641024a2

### Code of Conduct

- [x] I agree to follow Elvish's [Code of Conduct](https://src.elv.sh/CODE_OF_CONDUCT.md).

**Comment by 4ffy** [comment]
This issue was reported again in #1869 and fixed.

**Comment by xiaq** [comment]
Thanks for reporting! Left too many issues untriaged and still slowly going thru things...
