### ISSUE TITLE
checksum not same for windows build

### ISSUE THREAD

**Issue by qianlongzt** [elves/elvish#1865]
### What happened, and what did you expect to happen?

~> curl https://cdg.dl.elv.sh/windows-amd64/elvish-v0.21.0.zip.sha256sum
9361f9b7e0ebce444f4e9e59e87f67f83aa4468a6ca3457c951a52b6530894aa  elvish-v0.21.0.zip
~> curl https://hkg.dl.elv.sh/windows-amd64/elvish-v0.21.0.zip.sha256sum
c6665a9ca057370ace04471b291493f15428ed60eb27766ab642caf50ce8cf5b  elvish-v0.21.0.zip

### Output of "elvish -version"

0.21.0+official

### Code of Conduct

- [X] I agree to follow Elvish's [Code of Conduct](https://src.elv.sh/CODE_OF_CONDUCT.md).

https://github.com/ScoopInstaller/Main/blob/master/bucket/elvish.json

**Comment by xiaq** [comment]
Hmm this is kind of puzzling - the HEAD builds do have the same checksums.

**Comment by xiaq** [comment]
Just did the very hacky thing of copying the files in cdg.elv.sh to hkg.elv.sh.

I've added a note in my release checklist to check if the divergence happens again with the next release. Thanks for reporting!
