### ISSUE TITLE
Support pageUp and pageDown in completion mode

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#191]

**Comment by xiaq** [comment]
This is quite complex, since the widths of columns are variable.

**Comment by xiaq** [comment]
A more important question is: what do you expect PageUp and PageDown to do in a horizontally scrolling list? Should they scroll to the page to the right and left respectively? Or should they scroll a half page up and down?

**Comment by xiaq** [comment]
After revisiting this issue I feel it doesn't make sense for the completion mode, which scrolls horizontally, to support PageUp/PageDown.

It is also not very useful typically. If you want to skip an entire horizontal page, pressing Right several times is usually sufficient.
