### ISSUE TITLE
Allow persistent right prompt

### ISSUE THREAD

**Issue by theblazehen** [elves/elvish#198]
I like having say a clock (to see how long commands execute for) and exit status in my right prompt.

Also, would it be possibly to implement a way for the rprompt to be updated before a command is executed?

**Comment by xiaq** [comment]
Reasonable. Perhaps controlling this behavior through a boolean variable $le:persistent-rprompt will make sense?

**Comment by theblazehen** [comment]
Yeah, that sounds like a good idea.
