### ISSUE TITLE
Using color in the prompt?

### ISSUE THREAD

**Issue by theblazehen** [elves/elvish#199]
I might just be missing something, but I tried

```
fn textcolor_black { tput setaf 0 }
fn textcolor_red { tput setaf 1 }
fn textcolor_green { tput setaf 2 }
fn textcolor_yellow { tput setaf 3 }
fn textcolor_blue { tput setaf 4 }
fn textcolor_magenta { tput setaf 5 }
fn textcolor_cyan { tput setaf 6 }
fn textcolor_white { tput setaf 7 }
fn textcolor_reset { tput sgr0 }

fn makemyprompt { textcolor_magenta;print `whoami`;textcolor_reset;print '@';textcolor_yellow;print `hostname`;textcolor_reset;print ': ';textcolor_blue;print `pwd`;textcolor_reset;echo }
```

Then did `le:prompt={ makemyprompt }`, which didn't work (Didn't change colors, just output the control codes in text, eg `[35m`. Same thing happens with le:prompt={ put `makemyprompt` }

**Comment by xiaq** [comment]
It is indeed desirable to support colors and other styles in prompts.

The reason you are seeing the control text (without the ESC) is that the line editor ignores unprintable characters in the prompt. This allows us to have full control over the layout -- we can be sure that the user cannot move the cursor, and we can compute the width of the prompts.

We can whitelist SGR sequences (`ESC '[' number 'm'`) to fix this. But I would also like to expose the `styled` struct (https://github.com/elves/elvish/blob/master/edit/styled.go) to elvishscript as a structured way of ouputting styled text.

**Comment by theblazehen** [comment]
Found a workaround: `le:prompt={ tput setaf 2 >/dev/tty; echo hi }`

**Comment by xiaq** [comment]
Prompts with colors can now be built using the new `le:styled` builtin. For instance, if you want the current directory in green followed by "❱" in yellow as the prompt, use:

```
le:prompt={ le:styled (tilde-abbr $pwd) 32; le:styled '❱ ' 33 }
```
