### ISSUE TITLE
Add a framework for supporting something similar to zsh-dwim

### ISSUE THREAD

**Issue by theblazehen** [elves/elvish#200]
https://github.com/oknowton/zsh-dwim

I quite like the concept, would be neat to have that integrated into the shell and then have various completions as plugins.

(Great job on the shell btw!)

**Comment by xiaq** [comment]
I imagine that by making it possible to do the following in elvishscript, such a feature will be possible:

* Access the command-line history
* Obtain the current command
* Set the current command

Then the implementation looks like

```
cmd=(get-current-command)
if == $cmd ""; then
    cmd=(get-last-command)
fi
set-current-command (dwim $cmd)
```

Where `dwim` is a command that does the actual transformation.

**Comment by xiaq** [comment]
The needed functionalities have now been implemented. The functionality of `zsh-dwim` can be implemented as follows:

```sh
fn elvish-dwim {
  cmd=$le:current-command
  if == $cmd ""; then
    cmd=$le:history[-1]
  fi
  le:current-command=(dwim $cmd)
}
# Ctrl-U is not a great choice, but we are following zsh-dwim anyway
le:binding[insert][Ctrl-U]=$&elvish-dwim
```

Unfortunately AFAICS it is not easy to use zsh-dwim as a standalone command, so you will have to implement `dwim` yourself.
