### ISSUE TITLE
Alow disabling of the `<interact>:1:1: eval error: /bin/false exited with 1` feature

### ISSUE THREAD

**Issue by theblazehen** [elves/elvish#201]

**Comment by xiaq** [comment]
Non-zero exit values of external commands are treated like exceptions in elvish, and what you see is an exception traceback.

**Comment by theblazehen** [comment]
Yeah, is it possible to catch the exception perhaps?

**Comment by xiaq** [comment]
After catching the exception, maybe you will want to... show a traceback to tell the user where things went wrong? :)

In forms with a single command, the context information is redundant. But if you consider commands with command substitutions (e.g. `a (b)`), pipelines (`a | b`) or multiple commands (`a; b; c`) then it is essential to know which command threw an exception.
