### ISSUE TITLE
Allow the user to check the exit status of the previous command. `$?` in other shells

### ISSUE THREAD

**Issue by theblazehen** [elves/elvish#202]

**Comment by xiaq** [comment]
Non-zero exit statuses are exceptions; use `try/except`. The following

```
try
    e:false
except e
    echo $e
tried
```

outputs `?(error '4-11: false exited with 1')`. Unfortunately the error value `$e` is not very usable at this moment -- you cannot retrieve the exit value inside it, for instance.

**Comment by theblazehen** [comment]
Ty. Some regex would work I think.

I like having the exit status in my prompt. (If you haven't noticed, I'm really picky about my prompt.. Do you have a bountysource by any chance?)

**Comment by xiaq** [comment]
Tracking in #208.
