### ISSUE TITLE
Consider using Go 1.6+'s vendor directory

### ISSUE THREAD

**Issue by zmwangx** [elves/elvish#209]
Using the vendor directory makes offline and reproducible builds easy. Speaking as one of the maintainers of the [Homebrew package manager](https://github.com/Homebrew/brew), we especially encourage its use. We'd really appreciate it if you could adopt the vendor system at some point. Thanks.

P.S. `elvish` was added to Homebrew recently:

- https://github.com/Homebrew/homebrew-core/pull/4724;
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/elvish.rb)

**Comment by xiaq** [comment]
This will be done before the next preview release (0.4).

**Comment by zmwangx** [comment]
👍

**Comment by xiaq** [comment]
Fixed by e6648ffd921cec91bcd10d4fcbd67a290675fb25. I have also tagged 0.4.

**Comment by zmwangx** [comment]
Thank you!
