### ISSUE TITLE
Write a proper introduction

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#219]

**Comment by krader1961** [comment]
Is this still relevant? Should the issue be closed? It seems to me the current web/HTML docs at https://elv.sh/ (or self hosted via `cd website; make gen`) are good enough with regards to introducing a new user to Elvish. The current docs can obviously be improved upon but they appear to meet the minimum threshold implied by this issue.

**Comment by xiaq** [comment]
The closest thing Elvish now has to a beginner's introduction is the ["fundamentals" doc](https://elv.sh/learn/fundamentals.html) but I am not happy about its current state:

* It should be expanded to cover more fundamental features. I like how [fish's tutorial](http://fishshell.com/docs/current/tutorial.html) covers both UI and language features and it seems to be a good model to follow.

* It could use some tips comparing Elvish features to other shells and other programming languages to cater to users with different backgrounds.

* It could probably use an introductory example that is more motivating than the classical "hello world".

Right now Elvish tend to attract people who are already literate in both programming and UNIX, who have no problem heading directly to the reference section. But eventually Elvish will start seeing users who don't have such strong backgrounds, and we will need a better beginner's introduction.

**Comment by xiaq** [comment]
There's now a *Beginner's Guide to Elvish* series on https://elv.sh/learn/.
