### ISSUE TITLE
Case insensitive completion

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#228]

**Comment by xiaq** [comment]
To use a case-insensitive prefix matcher, do

```sh
edit:-matcher[''] = [a]{ edit:match-prefix &ignore-case=$true $@a }
```

There is also "smart case" a la Vim -- case insensitive when the pattern is lower case, case sensitive otherwise:

```sh
edit:-matcher[''] = [a]{ edit:match-prefix &smart-case=$true $@a }
```
