### ISSUE TITLE
elvish bomb

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#229]
move fast and break...

I have following file:
```
~> cat .elvish/env.elv
GOPATH=$env:HOME/go
PATH=$env:PATH:$env:HOME/bin
```

If I type:
```
~> $env:PATH
```

then it will explode and all memory will be exhausted.

No additional testing any more. I'm tired of rebooting.

I think, it's because of the `PATH=$env:PATH`.

**Comment by xiaq** [comment]
This is because the implementation of `use` first loads the file and then creates the namespace. In `env.elv`, the use of `env:` itself automatically `use`s `env` recursively.

We should change the implementation of `use`.
