### ISSUE TITLE
<interact>:1:3: eval error: arity mismatch

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#233]
```
~ $ a=`/bin/ls` 
<interact>:1:3: eval error: arity mismatch
```

So what's the right way to capture the output of `ls`

**Comment by huiyiqun** [comment]
`a=[(ls)]` instead

**Comment by zhsj** [comment]
I feel `slurp` is better.... But same behavior like bash/zsh is much better....

**Comment by huiyiqun** [comment]
In case you need a string instead of a list.
