### ISSUE TITLE
package manager for elvish

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#239]
We need a solution to share useful elvish scripts and keep them up-to-date.

**Comment by xiaq** [comment]
Let us make `epm`, elvish package manager. The design is open for discussion.

# API

* `epm:install a:b:c url` installs `url` as module `a:b:c`.

 - What should the syntax of `url` look like? We can start with support for GitHub, but it should be extensible to other kinds of sources

* `epm:update a:b:c` updates module `a:b:c`.

 - Should we simply do `git -C ~/.elvish/a/b/c pull`, or keep record of where the module was originally installed from?

* `epm:update-all` updates all modules.

 - Should we attempt to update those modules **not** installed using `epm`?

# Usage

I can think of two ways to add a new module `a:b:c` to your configuration, neither of which is perfect:

1. Use `epm:install a:b:c url` to install, and after the command completes, add `use a:b:c` to `~/.elvish/rc.elv`.

 - When copying the dotfile to another machine, one has to repeat the `epm:install` calls 😢 

2. Put `epm:install a:b:c url; use a:b:c` in `~/.elvish/rc.elv`. The next time elvish starts, the modules will be installed.

 - We need to make `epm:install` 1) concurrency-safe 2) do nothing when `a:b:c` exists, which is no big deal.

 - Elvish is blocked before the installation completes 😢

**Comment by xiaq** [comment]
The `epm` module has been implemented and documented in https://elvish.io/ref/epm.html.
