### ISSUE TITLE
unpack sliced list

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#254]
`$@list` unpack the `$list` while `$list[1:2]` slice it. However, we could not unpack sliced list directly like:

```
~> put $@a[1:2]
<interact>:1:9: eval error: index out of range
put $@a[1:2]
        ^


```

it's difficult to do something like:

```
~> put [$@a[:2] $@a[3:]]
```

**Comment by xiaq** [comment]
This has to do with the syntax. `$a[1:2]` is `{$@a}[1:2]`, which splices `$a` and applies slicing on each element. For instance:

```
a=[lorem ipsum]
put $@[0:3] # lor ips
```

**Comment by xiaq** [comment]
I want to add a new builtin called `explode`, but it is taken by [PIL](http://www.pythonware.com/products/pil/). :-/

Let's just change `unpack` to unpack its argument instead of input. The old `unpack` is now `each unpack`.
