### ISSUE TITLE
Elvish does not handle winch correctly

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#257]
I narrowed the window and then broaden it. we have following:

![screenshot_2016-10-11_21-40-34](https://cloud.githubusercontent.com/assets/3468160/19272511/6ddf1c32-8ffb-11e6-8824-9ee1b2ec0013.png)

**Comment by huiyiqun** [comment]
We have elvish in tmux in zsh

**Comment by huiyiqun** [comment]
in termite

**Comment by xiaq** [comment]
Can you still reproduce this issue?

**Comment by xiaq** [comment]
I am going to assume this has been fixed :-|
