### ISSUE TITLE
Strings in if statements incorrectly passed to strconv.ParseFloat?

### ISSUE THREAD

**Issue by vendion** [elves/elvish#260]
I'm not sure if a recent update broke the way if statements worked in elvish but in my _rc.elv_ I have the following to load certain scripts depending on the current OS:

```
os=(uname -s)
if == $os 'Darwin'; then
...
fi
```

When I launch a new elvish session it seems it is trying to parse the string as a float value

```
Exception: strconv.ParseFloat: parsing "Darwin": invalid syntax
Traceback:
  [interactive], line 12:
    if == $os 'Darwin'; then
~ ▶
```

**Comment by xiaq** [comment]
The `==` builtin was changed to work on numbers. To compare strings, use `==s`.

I maintain a list of incompatible changes between 0.4 and the upcoming 0.5 pre-release version: https://gist.github.com/xiaq/5dc9bc15b4b3b39e5468fb80c9873fc5

**Comment by xiaq** [comment]
BTW, you can also use `is` for comparing strings, which looks nicer than `==s`.

**Comment by vendion** [comment]
Would that look like `if is $os 'Darwin'; then` if so I think I would prefer that.
