### ISSUE TITLE
API for modifying history

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#262]
So that we could import histories from other shells.

**Comment by zhsj** [comment]
And then we can implement completer with history in pure elvish lang.

**Comment by huiyiqun** [comment]
I found a maybe useful function here.

https://github.com/elves/elvish/blob/3f987e286736cfb6d26085459ce7b45b24eb4afc/edit/history.go

**Comment by huiyiqun** [comment]
However, `history` is a concept only available in `line editor` currently, I'm not sure how should I expose this concept in `eval` gracefully. Maybe a new separate package?

@xiaq

**Comment by huiyiqun** [comment]
@zhsj you could use the `history` builtin

**Comment by huiyiqun** [comment]
There is already `store` package.

**Comment by huiyiqun** [comment]
We could use `store/cmd.go` directly. I will try to fix #263 first.

**Comment by xiaq** [comment]
The variable `$le:history` allows reading the history, so what lacks is a API for modifying history. I have changed the title of the issue.

**Comment by krader1961** [comment]
See also issue #1205 where I pointed out that `dir-history` should not be in the `builtin:` namespace and manipulating the interactive history should be possible independent of whether the shell is interactive.

**Comment by xiaq** [comment]
This is now supported by `store:add-cmd` \o/
