### ISSUE TITLE
The history builtin may fail with "table is locked"

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#263]
Run `history` repeatly, you may get following problem:

```
~> history
Exception: database table is locked: cmd
Traceback:
  [interactive], line 1:
    history
```

if you pipe the output to `count`, the probability the problem happens becomes higher.

**Comment by huiyiqun** [comment]
@zhsj Use this instead for editor mode

```
~> $le:history 233
▶ 'ls -la'
~> each { put $@ } $le:history
▶ 'ls -la'
```

and maybe `history` builtin for script? @xiaq 

```
~> elvish a.elv
Exception: variable $le:history not found
Traceback:
  [interactive], line 1:
    each { put $@ } $le:history
Exception: elvish exited with 1
Traceback:
  [interactive], line 1:
    elvish a.elv
~> cat a.elv
each { put $@ } $le:history

```

**Comment by huiyiqun** [comment]
However, the builtin `history` is still dangerous for it will fail whenever the table is locked.

**Comment by xiaq** [comment]
See: https://github.com/mattn/go-sqlite3/issues/274

PS. Since this bug might indicate that we are using `sqlite` in a wrong way, I am not accepting the PR to remove `history` until this bug is fixed.

**Comment by xiaq** [comment]
Also, with `history | each { }`, this happens virtually every time on my machine.
