### ISSUE TITLE
Some symbols in fontawesome are not displayed in prompt

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#270]
I have [these icons](https://github.com/huiyiqun/my-elvish/blob/5731ba1de5dc784cca112fa47696ff7847e75f1b/git.elv#L3) in my prompt, but they are not displayed.

![screenshot_2016-10-13_06-45-45](https://cloud.githubusercontent.com/assets/3468160/19330380/af2073ce-9110-11e6-8a3f-2c40c10d285d.png)

As you can see, my terminal is able to display them correctly.

**Comment by xiaq** [comment]
Likely they have been determined to be unprintable and filtered from the prompt.
