### ISSUE TITLE
Wrong width in prompt

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#271]
This icon has a width 2 but occupies only half width in prompt.

![screenshot_2016-10-13_06-53-03](https://cloud.githubusercontent.com/assets/3468160/19330570/c992a5a0-9111-11e6-82fa-2b9a62b1a7ac.png)

**Comment by xiaq** [comment]
Seems that it falls within the "emoji" range of b240fb39f18c8ff5f21238af7ed26089f1828437.

**Comment by huiyiqun** [comment]
@xiaq 

![screenshot_2016-10-10_21-13-43](https://cloud.githubusercontent.com/assets/3468160/19346205/c81eda22-9107-11e6-97af-3330283c585b.png)

still buggy.

**Comment by xiaq** [comment]
Can you paste the symbol in the issue?

**Comment by huiyiqun** [comment]
There should be a space between > and the cursor. What‘s more, the `e` at the end of `rprompt` is out of the terminal.

**Comment by huiyiqun** [comment]
~/.elvish on master ◦ / ~>                                              huiyiqun@edge

**Comment by huiyiqun** [comment]
![screenshot_2016-10-13_18-49-41](https://cloud.githubusercontent.com/assets/3468160/19346461/08ab4214-9109-11e6-8935-be341c20f591.png)

**Comment by xiaq** [comment]
If you run `echo x ◦ xx`, how does ◦ occupy 1 column (like `x`) or two (like `xx`)?

**Comment by xiaq** [comment]
I mean `put x ◦ xx`.

**Comment by huiyiqun** [comment]
This character `◦` just ocuppy two space in my terminal.

**Comment by huiyiqun** [comment]
![screenshot_2016-10-13_18-55-27](https://cloud.githubusercontent.com/assets/3468160/19346569/ab4dc050-9109-11e6-95b4-8532c142e283.png)

**Comment by xiaq** [comment]
Then it is weird that it didn't use to work, because before the "fix" wcswidth would return 2 for the symbol. Hmm.

**Comment by xiaq** [comment]
What about `put x ◦x xx`? How many columns does ◦ occupy then?

**Comment by huiyiqun** [comment]
Before fix I run elvish in PC of my lab while currently in my laptop.

**Comment by xiaq** [comment]
Confirmed by reporter to be terminal's bug.
