### ISSUE TITLE
exception raised even when it's wrapped with try

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#275]
```
~/go/src/github.com/elves/elvish on master ◦ / ~> each { try fail 'WTF'; tried }  [1 2 3]

Exception: WTF
Traceback:
  [interactive], line 1:
    each { try fail 'WTF'; tried }  [1 2 3]
  [interactive], line 1:
    each { try fail 'WTF'; tried }  [1 2 3]
```

**Comment by huiyiqun** [comment]
![screenshot_2016-10-13_20-03-41](https://cloud.githubusercontent.com/assets/3468160/19348367/3286ffba-9113-11e6-995c-aff70f270446.png)

**Comment by xiaq** [comment]
Exceptions are only caught when `except` is present. See https://github.com/elves/elvish/wiki/Language-Specification#try
