### ISSUE TITLE
gpg/dirmngr not working

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#278]
I need someone to verify. But it happens on my laptop.

1. gpg/dirmngr works in konsole with zsh as the default shell.
2. gpg/dirmngr works in elvish which is launched in zsh.
3. gpg/dirmngr doesn't  work in konsole with elvish as the default shell.

The problem is:
When I try `gpg --recv-keys 7dfbb2f2`, it's just stuck.
I try wireshark to capture the network package and I find there's no traffic sent.

**Comment by zhsj** [comment]
The problem maybe is dirmngr side....

**Comment by xiaq** [comment]
Even if it is dirmngr's bug, it is worth investigating the difference between the behavior elvish and zsh when launching dirmngr that is causing the bug to manifest itself.

**Comment by xiaq** [comment]
@zhsj can you ensure that you are on HEAD?

**Comment by zhsj** [comment]
@xiaq yeah, HEAD. Since it's a random bug, I have reproduced the bug on zsh too...

**Comment by xiaq** [comment]
Ah, ok.
