### ISSUE TITLE
nav mode: fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#283]
When access proc file like pagemap.

**Comment by xiaq** [comment]
Not fixed by a80e6d15faf4221e5063dcd4858481e8beb7d886?

**Comment by zhsj** [comment]
@xiaq No, proc file size return by stat is always zero.

**Comment by zhsj** [comment]
@xiaq But it would be nice if nav mode doesn't filter out all proc files. I find nav mode with preview is very useful when check a process's information.
