### ISSUE TITLE
Support for zsh like $commands variable

### ISSUE THREAD

**Issue by vendion** [elves/elvish#291]
I went searching through the issue queue to see if this was already suggested, or if it's already implemented in Elvish.

ZSH has an array called `$commands` that is auto populated with a list of executable files within a user's `PATH`.  The contents of this array is cached to speed up access to it at the cost of a slightly longer startup time for the shell.  With this array things like checking if a command exists can be done slightly cleaner than using `which` within an if statement.

ZSH:
```
if [[ -n "${commands[perlbrew]}" ]] ; then
  ...
fi
```

Common ways to do this is BASH include writing if statements with one of the following:
```
which foo >/dev/null
command -v foo >/dev/null 2>&1
type foo >/dev/null 2>&1
hash foo 2>/dev/null
```

End of the day it comes down to a stylistic choice than anything, but I think Elvish could take an approach similar to ZSH's `$commands` array without any huge hit in startup performance.

**Comment by xiaq** [comment]
This has been implemented using a pair of builtin commands instead of variables. Since result of external command resolution can change from time to time (e.g. user can put new executables in /bin anytime), I think this is more appropriate.
