### ISSUE TITLE
Support WSL

### ISSUE THREAD

**Issue by wbsdty331** [elves/elvish#293]
Windows 10 14965 Insider(OS : Ubuntu 16.04 LTS)

I tried Linux Version `.tar.gz`,. but It doesn't work.

**Comment by xiaq** [comment]
Is there any error message?

**Comment by xiaq** [comment]
The [version 0.5 binary](https://dl.elvish.io/elvish-0.5-linux.tar.gz) works on build 14395 (which is the latest stable build I get on my laptop).

**Comment by wbsdty331** [comment]
@xiaq It works good.
Thanks!
