### ISSUE TITLE
Ctrl-\ kill elvish itself

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#297]
```
~> sleep 100<Enter><Ctrl-\>
```

Then the terminal tab is closed.

**Comment by zhsj** [comment]
@huiyiqun I think it is by design...

**Comment by huiyiqun** [comment]
I guess it's a misfeature.

**Comment by xiaq** [comment]
It's a bug. Ctrl-\ sent while external commands are running should not kill elvish; those sent when elvish editor is active should.

**Comment by xiaq** [comment]
This issue is caused by a lack of job control (#410) and the handling of SIGQUIT (#441). They are now tracked in their own issues.
