### ISSUE TITLE
Find a suitable semantics for compounding complex data structures

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#299]
Right now, only strings can be compounded. Compounding (say) a list with a string results in an error:

```sh
echo [a b c]foo # erroneous
```

Perhaps we can find some actual use for such a terse syntax.

**Comment by Artoria2e5** [comment]
Perhaps make it something like a brace expansion?

**Comment by xiaq** [comment]
@Artoria2e5 Not sure what you intend -- can you tell me, say, what `[a b c]foo` should evaluate to?

**Comment by Artoria2e5** [comment]
Hmm, `[afoo bfoo cfoo]`?

**Comment by xiaq** [comment]
I don't know, but that doesn't sound like a common operation to me :-|

**Comment by vendion** [comment]
I'm not sure if this is what @Artoria2e5 was referring to, pretty sure it is, https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html

In BASH and ZSH, it comes in handy for working with multiple files with same basename but different extensions or prefixes, etc.

**Comment by xiaq** [comment]
@vendion thanks for the pointer, but elvish already has brace expansion.

**Comment by vendion** [comment]
@xiaq Yeah that is why I added the part of not being sure if it would be useful for other data types, as well as my uncertainty of if other shells do as well.  I guess I could have misunderstood your previous post.

**Comment by xiaq** [comment]
A use case has been found when a list is followed by a wildcard pattern: #1047.

But when wildcard is not involved, no good use has been found yet, so I'll continue to forbid expressions like `[a b c]foo` and close this issue.
