### ISSUE TITLE
Not autocompleting nested dirs.

### ISSUE THREAD

**Issue by noisypixy** [elves/elvish#30]
Pressing "tab" doesn't complete nested dirs. I'm lazy, and it would be fine to save some keystrokes xD.

![30](https://cloud.githubusercontent.com/assets/6207198/3859723/f34e33d8-1f1b-11e4-8b5e-84cc7d738dc0.png)

**Comment by xiaq** [comment]
Fixed by commit f52e1760b098c3ac5eff8e9b29e095a6a88827ec.
