### ISSUE TITLE
Add a startup file for non-interactive sessions

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#316]
Right now rc.elv is only executed when elvish is started in interactive mode. When commands are specified via `-c` or in a script, there is no startup file. Perhaps we should have one.

**Comment by lifranc** [comment]
It would be nice to use elvish as login shell. Right now it isn't possible, especially on a non-standard system, like nixOS, since there is no startup configuration.
Perhaps this should be called 'basic feature' instead of 'enhancement', since elvish is not a proper shell without it.

**Comment by krader1961** [comment]
I don't understand @ghost's comment but do agree that there should be a "startup file" for non-interactive invocations of `elvish`. I was slightly surprised to recently learn that *~/.elvish/rc.elv* is only sourced by interactive shells when I attempted to run an elvish script via crontab.

My preference would be to introduce a mechanism for determining if the shell is interactive or not. Something like fish's `status is-interactive` command. That would allow people to predicate a particular initialization on whether or not the shell is interactive. Alternatively, introduce a new startup file that is always sourced; and before *~/.elvish/rc.elv* for interactive shells. But please do not mimic legacy mechanisms such as *~/.login*, *~/.profile*, and `$BASH_ENV` (or the ksh `-E` option).

**Comment by xiaq** [comment]
Revisting this, I now believe that there shouldn't be a startup file for non-interactive sessions.

Presumably the intention of any such startup file is to alter the Elvish environment in some a way that can be useful to all the scripts in a user's system. However:

* Elvish doesn't have configuration options like bash's `setopt` that can affect how scripts are executed, so there are very few useful things such a startup file can do in the first place;

* This startup file can still do things like changing environment variables, which can be useful, but doing that means the user's scripts now depend on this startup file, and is now less portable to other people's systems.

In lieu of a startup file for non-interactive sessions, it's better if the user just puts the common "startup" code in a module, and `use` that module from their scripts.

I may have missed some genuine use cases for a startup file for non-interactive sessions though. If there is a very compelling use case that can't be solved by another mechanism, this issue can be re-opened.

**Comment by krader1961** [comment]
For the record the only thing I would have used this for is setting env vars. I long ago created a *~/.elvish/lib/env.elv* module that I `use` from *rc.elv* and non-interactive scripts to ensure I've got a consistent environment for all my Elvish shells. So from my perspective I personally no longer see any need for this feature.
