### ISSUE TITLE
"invalid escape sequence" when trying to escape a dot

### ISSUE THREAD

**Issue by muesli** [elves/elvish#317]
I'm trying to run:

    git grep "foo\.bar"

which is a valid escape sequence, since I want to match an actual dot (as opposed to any character as parsed by the grep pattern), but results in elvish complaining:

parser error: 14-15: invalid escape sequence

**Comment by xiaq** [comment]
What you want to do here is to pass the backslash to `grep`; use `'foo\.bar'`.

Double quotes support C-like escape sequences in elvish, and `\.` is not a valid escape sequence for double quotes.

**Comment by xiaq** [comment]
Spec added: https://github.com/elves/elvish/wiki/Language-Specification#string-literals, closing.
