### ISSUE TITLE
[question] why arity?

### ISSUE THREAD

**Issue by aeosynth** [elves/elvish#323]
to show a date in my prompt, i can set `le:rprompt = date`, but if i want a formatted date, i can't simply extend this with the format string:

```
le:rprompt = date '+%a %d %R'
Exception: arity mismatch
Traceback:
  [interactive], line 1:
    le:rprompt = date '+%a %d %R'
```

i have to create a function and 'stutter':

```
fn rprompt { date '+%a %d %R' }
le:rprompt = rprompt
```

why is arity a useful concept?

**Comment by xiaq** [comment]
Use le:rprompt = { date ... }

Arity mismatch in this case means you cannot assign two values to one variable.

**Comment by aeosynth** [comment]
ah, thanks for clarifying
