### ISSUE TITLE
kill-path-component

### ISSUE THREAD

**Issue by aeosynth** [elves/elvish#325]
another nice feature from fish is the `backward-kill-path-component` function, bound to `^W`, which kills everything left of the cursor, to the next `/` or whitespace. or maybe i should implement it in my own config? or maybe it's not needed if i use the navigation mode.

are you interested in taking more features from fish? i was mostly happy with it as my default shell.

**Comment by xiaq** [comment]
Does Ctrl-Left (or Alt-B) and Ctrl-Right (or Alt-F) work in the same way in fish?

**Comment by aeosynth** [comment]
fish treats those sequences similarly to bash, similar to vim `b` and `w`

**Comment by xiaq** [comment]
See #333.
