### ISSUE TITLE
Script path as a builtin variable (a la `__file__` in python, `__dirname` in nodejs)

### ISSUE THREAD

**Issue by summivox** [elves/elvish#327]
Origin of the problem: http://stackoverflow.com/questions/6659689/referring-to-a-file-relative-to-executing-script

After ranting to @xiaq he said I should

> file a feature request and hope it gets adopted in 20 years

**Comment by xiaq** [comment]
Documentation: https://elvish.io/ref/builtin.html#src

**Comment by summivox** [comment]
20 years => 1 year

👍

**Comment by xiaq** [comment]
Clarification: The "it" in my original comment referred to Elvish, not this bug :)
