### ISSUE TITLE
anaconda python causes 'arity mismatch' in Elvish Shell, when activating an environment.

### ISSUE THREAD

**Issue by PowerSnail** [elves/elvish#329]
Versions:

- Bash on Windows
- Elvish Shell v. 0.7
- conda 4.3.13

Step to reproduce:

- Install latest Elvish Shell using `curl`.
- Install latest anaconda as explained on its website
- create an environment, e.g. `conda create --name myenv`
- try to activate `myenv`: `source activate myenv`

Compare the outcome:

Shell | outcome
--- | ---
Elvish running on Bash on Windows | ![image](https://cloud.githubusercontent.com/assets/7428673/23285596/3b7683b0-fa00-11e6-8e37-d8de2b501b92.png)
Bash on Windows without Elvish|![image](https://cloud.githubusercontent.com/assets/7428673/23285580/1bd596d6-fa00-11e6-8639-d8d5d8fbf6de.png)

Thank you!

**Comment by huiyiqun** [comment]
The `activate` script of anaconda is written for posix shell or bash shell.

But elvish is not posix.

**Comment by xiaq** [comment]
The `source` command in elvish only takes one argument, and that is causing an arity mismatch here.

But even if it does, elvish cannot source POSIX shell scripts. There is #205 but it won't happen very soon :(.
