### ISSUE TITLE
partial completion

### ISSUE THREAD

**Issue by aeosynth** [elves/elvish#332]
in bash/fish, pressing `Tab` completes filenames to the longest common prefix, with a second `Tab` offering a completion menu (bash menu is not interactive). elvish only has full completion; i would like partial completion as well.

**Comment by xiaq** [comment]
It does, try:

```sh
~> touch foobar1 foobar2
~> echo foo<Tab> # completes to foobar
```

If you can't, there is a bug, and please tell me how to reproduce it.

**Comment by aeosynth** [comment]
hm, it does work. i think i was confused because it would immediately open the completion menu, instead of waiting for a second tab:

```
> touch abb acc
> echo a<Tab> # name is immediately completed fully
```

bash/fish require the second tab. closing.
