### ISSUE TITLE
add readline keybindings

### ISSUE THREAD

**Issue by aeosynth** [elves/elvish#339]
elvish adds some initial friction by not supporting common readline keybindings, eg ^H for backspace, ^A/^E for home/end, etc.

for a list of keybindings, see:

https://en.wikipedia.org/wiki/GNU_Readline#Emacs_keyboard_shortcuts
https://cnswww.cns.cwru.edu/php/chet/readline/readline.html#SEC13

**Comment by xiaq** [comment]
Add `use embedded:readline-binding` to your rc file to use.

**Comment by scateu** [comment]
burst into tears.

**Comment by aeosynth** [comment]
nice. i'd prefer it default, as this is mainly for initial friction, but i'll close.

**Comment by orivej** [comment]
To save some time for those looking for `Unbound: Ctrl-H`, the current expression is `use readline-binding`.
