### ISSUE TITLE
Possible to suppress job control messages?

### ISSUE THREAD

**Issue by vendion** [elves/elvish#343]
Is it possible to suppress job control messages using Elvish?  For an example of what I mean I'm trying to setup [wal](https://github.com/dylanaraps/wal) to automatically set the color scheme for new terminal windows to match the others.  The directions in the readme says that [for bash and zsh use (wal -r &)](https://github.com/dylanaraps/wal#applying-the-theme-to-new-terminals) in the correct configuration file, but this syntax doesn't do the same thing under Elvish.

Using the syntax from Wal's readme I get the following:
```
Exception: head of command must be 1 value; got 0
Traceback:
  /home/vendion/.elvish/rc.elv, line 22:
      (wal -r &)
  /home/vendion/.elvish/rc.elv, line 21-23:
    if (!=s (which wal) '') {
      (wal -r &)
    }
/home/vendion/bin/wal: line 257: printf: write err
job wal -r & finished, errors = wal exited with 1
~>    
```

Not using the `()` in my _rc.elv_ file wal does correctly set the color scheme but I also see the job control output in my terminal:
```
job wal -r & finished
~ ❱   
```

In my _rc.elv_ I have the command wrapped in a if statement to check if wal is present in my `$PATH` as I share my configs on multiple machines.

**Comment by xiaq** [comment]
Feature request accepted; parentheses in Elvish is for output capture, not subshells like in other shells.

**Comment by xiaq** [comment]
It is now possible to suppress the message sent when a bg job finishes without error by setting [$notify-bg-job-success](https://elv.sh/ref/builtin.html#notify-bg-job-success) to `$false`.
