### ISSUE TITLE
Elvish won't compile

### ISSUE THREAD

**Issue by thorn0906** [elves/elvish#344]
--- FAIL: TestNewStore (0.00s)
       store_test.go:33: NewStore() -> (*, failed to initialize shared variable table: unable to open database file), want (*, <nil>)

This happens whenever I try to build Elvish. Could be a problem with my computer... Any ideas?

**Comment by xiaq** [comment]
This is an error in the test case. You don't need the tests to pass to build Elvish, just use `go get`.
