### ISSUE TITLE
Raw mode requires two presses of ^V

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#350]
Raw mode should be triggered by just one ^V.

**Comment by xiaq** [comment]
Fixed!

**Comment by zzamboni** [comment]
```
[~]─> elvish -buildinfo
Version: v0.13-rc4-7-g732da65
Go version: go1.13.5
Reproducible build: true
```

I'm not sure what raw mode is for (I had never used it), but for me, it still requires two presses of Ctrl-v to have the "RAW" indicator appear.
