### ISSUE TITLE
Introduce an API for restoring editor state after executing a command

### ISSUE THREAD

**Issue by aeosynth** [elves/elvish#351]
I'd like the nav mode kept open after a command, so I can repeat the command on multiple filenames sequentially.

**Comment by xiaq** [comment]
I like this feature request.

Aside from the obvious solution of adding an `$le:persistent-navigation` option, I wonder whether this feature can be somehow generalized to be more useful.

**Comment by xiaq** [comment]
#535 is now the preferred the approach to solve this problem, closing this as a duplicate.
