### ISSUE TITLE
In web backend, run commands with pty IO, not pipe

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#356]

**Comment by dansenpir** [comment]
@xiaq Privado

**Comment by xiaq** [comment]
Closing this as the web frontend is not being worked on and may never be worked on again.

**Comment by krader1961** [comment]
> Closing this as the web frontend is not being worked on and may never be worked on again.

@xiaq, In light of that comment, and the desire to improve [test coverage](https://github.com/elves/elvish/milestone/8) for the 0.15 release shouldn't the existing web frontend code be disabled by default via `// +build` comments and/or otherwise be excluded from test coverage metrics?
