### ISSUE TITLE
Asynchronous syntax highlighting

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#357]
Part of syntax highlighting involves filesystem access, and can be slow if e.g. the user is on a network drive. In that scenario the entire editor will be blocked.

We can make the highlighter asynchronous, and if highlighting is not available when the next keystroke comes or after (e.g.) 20ms (whichever happens first), we render the command unhighlighted, and re-render when highlighting becomes available.

**Comment by xiaq** [comment]
https://github.com/ain/libsnailio is a library for slowing down IOs on macOS. I will use that to uncover more issues on slow file systems.

**Comment by dansenpir** [comment]
@xiaq Não fiz isso, pois nunca enviam arquivos no formato .py. Quando querem revisar algum código ou algo assim, mandam o link do pastebin.com ou do Git.

Essa medida é para barrar possíveis envios de apostilas piratas. 

Mas, pelo visto está se tornando um problema, então irei ajustar o bot.

**Comment by xiaq** [comment]
The interface for the highlighter is as follows:

```go
type LateUpdate struct {
    Buffer string
    From, To int
    Style string
}

type Highlighter interface {
    Get(buffer string) (styled.Text, []error)
    LateUpdates() (<- chan LateUpdate)
}
```

The Get method is called to get highlighted buffer, and parse and compilation errors. This step doesn't involve any I/O access - in particular, the highlighted buffer will *not* highlight external commands.

Highlights that involve I/O are delivered on the LateUpdates channel. Each LateUpdate identifies which buffer it is for, which range should be highlighted, and in what style (as a `styled` transformer).

**Comment by xiaq** [comment]
Actually, this interface is simpler:

```go
type Highlighter interface {
    Get(buffer string) (styled.Text, []error, <-chan styled.Text)
}
```

Late updates are simply delivered on a channel returned from Get. Since the highlighter itself has all the information, it can return the complete, updated text instead of justing telling the caller which part has been updated. Since this method now only has one method, it might as well be changed into a function:

```go
type Highlighter func(buffer string) (styled.Text, []error, <-chan styled.Text)
```

**Comment by xiaq** [comment]
Implemented in the `newedit` package, closing proactively.
