### ISSUE TITLE
Could not start daemon.

### ISSUE THREAD

**Issue by kybin** [elves/elvish#378]
I run this on my laptop. (Manjaro lastest)

And I saw this.

warning: cannot start daemon: cannot find elvish: not found
cannot connect to daemon after 1s: dial unix /tmp/elvish-1000/sock: connect: no such file or directory

**Comment by zhsj** [comment]
@kybin Where did you put the elvish binary? Is it in your PATH, eg /usr/bin or /usr/local/bin

**Comment by kybin** [comment]
I ran it with `./elvish` in Download folder.
I moved it inside of $PATH and it works fine.

Thank you @zhsj !

**Comment by tjikini** [comment]
Same for NixOS :(
elvish is inside $PATH, but things is complicated in NixOS, I guess.
First "bad" commit (9ac0c60)[https://github.com/elves/elvish/commit/9ac0c600ebc9c38023e27d7c9214ef4ace9d90ef]

**Comment by xiaq** [comment]
@tjikini That commit does not change the behavior of the daemon, so it seems to be a weird first bad commit. Also, can you open a new bug? This one is caused by Elvish not being in PATH and I doubt NixOS has a different story.

**Comment by tjikini** [comment]
Sorry.
@xiaq nevermind, installation via `nix-rebuild` works fine
