### ISSUE TITLE
Elvish crashed on key combination

### ISSUE THREAD

**Issue by fahrenq** [elves/elvish#386]
Just installed elvish from [aur](https://aur.archlinux.org/packages/elvish/).
Crashed when pressed `ctrl + back slash` (220 key code).
Log: https://pastebin.com/AkJhYExf

**Comment by xiaq** [comment]
Ctrl-\ sends SIGQUIT. Traditionally it doesn't crash shells, but you will find out that it also crashes `cat`, `sleep`, etc. :)

Change of the behaviour is now tracked in #411.
