### ISSUE TITLE
Piping a large range into a command locks up the shell

### ISSUE THREAD

**Issue by occivink** [elves/elvish#389]
Reproducer: `range 50 | echo`. Does not occur for "small" values, I suppose the cutoff is system-dependent.
This is probably a nonsensical command to run, but in any case it shouldn't lock up the shell.

**Comment by xiaq** [comment]
This could be fixed by draining the input channel at the end of each command, however this should be done carefully. For instance, the following should continue to work:

```sh
range 50 | {
  echo foo
  each [x]{ echo $x }
}
```
