### ISSUE TITLE
cannot be indexed for setting

### ISSUE THREAD

**Issue by serussell** [elves/elvish#392]
Having trouble with lists.

```
~> kind-of $paths
▶ list
~> paths[0] = "/usr/local/sbin"
~> a = [1 2 3]
~> kind-of $a
▶ list
~> a[0] = 1
Exception: cannot be indexed for setting (value is [1 2 3], type list)
Traceback:
  [interactive], line 1:
    a[0] = 1
```
Are lists immutable, except for some magic lists?

**Comment by xiaq** [comment]
This is a known regression documented in the [release notes](https://elvish.io/blog/0.9-release-notes.html). However, I will leave this bug open until it is fixed.
