### ISSUE TITLE
Support editing command line with external editor

### ISSUE THREAD

**Issue by alexherbo2** [elves/elvish#393]
That could be useful when commands grow in complexity to be able to use an external editor.

That could be done by passing the command-line contents plus the cursor position to the usual editor and flushing the command-line buffer on quitting with the new contents.

Command-line buffer should not be updated if editor quits with error though.

# Prototypes

## Default

``` elvish
edit:command:edit
```

Launch the usual editor.

The following command will be executed:

``` elvish
$E:EDITOR <file> +<line>:<column>
```

### Usage

``` elvish
edit:binding[insert][Alt-i] = edit:command:edit
```

## String

``` elvish
edit:command:edit <editor>
```

Launch given editor.

The following command will be executed:

``` elvish
<editor> <file> +<line>:<column>
```

### Usage

``` elvish
edit:binding[insert][Alt-i] = {
  edit:command:edit $E:EDITOR
}
```

## Lambda

``` elvish
edit:command:edit <lambda>
```

Launch given editor, using lambda return value.

The following options are passed:
- `file`
- `line`
- `column`

### Usage

``` elvish
edit:binding[insert][Alt-i] = {
  edit:command:edit {
    put $E:EDITOR $opts[file] +$opts[line]:$opts[column]
  }
}
```

**Comment by xiaq** [comment]
This is now covered by the more general #535, closing as duplicate.
