### ISSUE TITLE
Add command abbreviation support

### ISSUE THREAD

**Issue by alexherbo2** [elves/elvish#394]
They could nicely replace aliases as shortcuts.

Aliases are well suited to pass default parameters or hijack a command, for example `ls` to [exa][].

But they are limited when we use them as shortcuts: if we change the shortcut to something else, it’s not valid in history anymore.

Abbreviations would work nicely on that.

[exa]: https://the.exa.website

**Comment by krader1961** [comment]
It seems to me this has been addressed in as much as Elvish now supports REPL abbreviations; albeit that support is not documented and the current abbreviation support is not optimal. See issue #947. Nonetheless it seems to me, in light of that issue, and the fact that abbreviations are now supported, this issue should be closed.

**Comment by krader1961** [comment]
@xiaq, AFAICT this issue was (mostly) resolved by your implementation of interactive abbreviations in commit 4bb34ab0b. Which I'm documenting in my work in progress change to resolve #947. Is there some reason to believe this is still a distinct, unresolved, issue?

**Comment by krader1961** [comment]
@xiaq, This should be closed since it is resolved AFAICT.
