### ISSUE TITLE
Typo on home page - "Control structures in Elvish has an intuitive C-like syntax."

### ISSUE THREAD

**Issue by shlomif** [elves/elvish#400]
The "has" in that sentence should be "have". Thanks!

**Comment by xiaq** [comment]
Fixed, thanks!

BTW, the website has its own repo https://github.com/elves/elvish.io please file future reports there!

**Comment by shlomif** [comment]
On Sat, 08 Jul 2017 11:46:55 +0000 (UTC)
Qi Xiao <notifications@github.com> wrote:

> Fixed, thanks!

Thanks and you are welcome.

> 
> BTW, the website has its own repo https://github.com/elves/elvish.io please
> file future reports there!
> 

Thanks for the info.


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Let’s talk about restores instead of backups - http://is.gd/WatQqu

The most exciting phrase to hear in science, the one that heralds new
discoveries, is not “Eureka!” (I found it!) but “That's funny…”.
— https://en.wikiquote.org/wiki/Isaac_Asimov [Attributed]

Please reply to list if it's a mailing list post - http://shlom.in/reply .
