### ISSUE TITLE
Iterating over maps

### ISSUE THREAD

**Issue by silvasur** [elves/elvish#413]
If I'm not overlooking something, it is currently not possible to iterate over the items of a map. This makes it basically impossible to process some JSON data structures out there.

My suggestion would be to add a function that returns the keys of a map, so one can iterate over them (and as a consequence can also access the values for the given keys).

I implemented a version of this function (named `keys`) at my fork: silvasur/elvish@bcf959c0d15ade60ea39d2370db9ccd0aa550856

Here's an example of using it:

```
my_map = [&a=foo &b=bar &c=baz]
keys $my_map | each [k]{ echo "key: "$k", value: "$my_map[$k] }
```
Will print:
```
key: a, value: foo
key: b, value: bar
key: c, value: baz
```

If you think this is a useful addition, please let me know, and I'll do a proper pull request and add documentation / tests for the new function.

**Comment by xiaq** [comment]
@silvasur you are right that we currently lack a way to iterating keys, and thanks for the issue and the implementation, I am open for a PR.

BTW, I peeked the code -- please use the `IterateKeyer` interface instead of `Map`.
