### ISSUE TITLE
[question] Overwriting default last command keybinding

### ISSUE THREAD

**Issue by vendion** [elves/elvish#420]
I see that with Elvish 0.9 the default keybinding to trigger the last command/bang mode from `Alt-,` to `Alt-1` while this may be fine in a general case `Alt-N` is used in my window manager to switch between tags. Due to this I would like to revert this back to the old keybinding in my configs since `Alt-,` didn't conflict with any other keybindings.

Looking at the output of `pprint $edit:binding` I see the data structure for lastcmd but I'm not sure what I need to change.
```
~ ❱ edit:binding[lastcmd][default]=alt-,
~ ❱ edit:binding[lastcmd][default]=$edit:lastcmd:&alt-,
Exception: variable $edit:lastcmd:&alt- not found
Traceback:
  [interactive], line 1:
    edit:binding[lastcmd][default]=$edit:lastcmd:&alt-,
~ ❱ edit:binding[lastcmd][default]=$edit:lastcmd:alt-,
Exception: variable $edit:lastcmd:alt- not found
Traceback:
  [interactive], line 1:
    edit:binding[lastcmd][default]=$edit:lastcmd:alt-,
~ ❱ edit:binding[lastcmd][default]=edit:lastcmd:alt-,
~ ❱ edit:lastcmd
Exception: search edit:lastcmd: not found
Traceback:
  [interactive], line 1:
    edit:lastcmd
~ ❱ edit:binding[lastcmd][default]=alt-,
~ ❱ alt-,
Exception: search alt-,: not found
Traceback:
  [interactive], line 1:
    alt-,
~ ❱ edit:binding[lastcmd][default]=$edit:lastcmd:alt-,
Exception: variable $edit:lastcmd:alt- not found
Traceback:
  [interactive], line 1:
    edit:binding[lastcmd][default]=$edit:lastcmd:alt-,
~ ❱ edit:binding[lastcmd][default]=edit:lastcmd:alt-,
~ ❱ edit:lastcmd:alt-,
Exception: search edit:lastcmd:alt-,: not found
Traceback:
  [interactive], line 1:
    edit:lastcmd:alt-,
~ ❱ edit:binding[lastcmd][alt-,]=edit:lastcmd:alt-default
~ ❱ edit:lastcmd:alt-default
Exception: editor inactive
Traceback:
  [interactive], line 1:
    edit:lastcmd:alt-default
```

**Comment by xiaq** [comment]
Sorry for breaking your workflow. The key for starting the lastcmd mode lives in the binding table for the **insert** mode, not **lastcmd** mode. This seems to be something people run into frequently, I will document this.

Use the following:

```sh
edit:binding[insert][Alt-,] = { edit:lastcmd:start }
```

The key for *accepting* the entire line cannot yet be changed though (now tracked in #421), but binding `Alt-,` to accept the highlighted candidate (which, initially, is the entire line) is a workaround:

```sh
edit:binding[lastcmd][Alt-,] = { edit:listing:accept }
```

I will leave the issue open until documentation is in place.

**Comment by vendion** [comment]
Ah thank you, I did not think to look in the insert table, did seem a bit counter intuitive to me at the time but does make sense when you think about it as you are in insert mode when you press the keys after all. 🤦‍♂️

**Comment by xiaq** [comment]
This has been [documented](https://elvish.io/ref/edit.html#bindings-to-start-modes).
