### ISSUE TITLE
Build is unsuccessful when Cgo is disabled

### ISSUE THREAD

**Issue by xchenan** [elves/elvish#425]
Package mattn/go-sqlite3 includes codes in Cgo. Hence when Cgo is disabled, elvish cannot be built successfully. Some projects (u-root https://github.com/u-root/u-root, for instance) requires codes in pure Go and the codes in C is an block on the way. 

To benefit the people who would like to apply elvish to the scenario that requires pure Go, I suggest that the codes which use sqlite3 for command history will be compiled only when Cgo is enabled. People that do not meet such case are still free to use sqlite3 so they will not be affected at all.

Beside, for a more thorough tests, cases when CGO_ENABLED=0 shall be added to travis, IMHO.

I am fixing this right now. So if you do not have objections I will go ahead and open a PR for it.

**Comment by xiaq** [comment]
The current plan is to replace sqlite with a pure go database.

It’s fine for me if you want to make Elvish buildable without cgo right now, as long as you don’t mind doing extra work that won’t be necessary in the near future.

The cleanest way to avoid depending on cgo, AFAICT, is to use a dummy implementation of daemon/service when cgo is not enabled; this requires minimal change in the code.

**Comment by rminnich** [comment]
I'm a bit concerned about this daemon. Dropping unix domain sockets in /tmp seems like a possible problem if someone wants to DDOS it. Also, management of many different such sockets also strikes me as a problem. 

I wonder if we could talk about the problems the daemon is intended to solve and maybe look at other approaches.

Thanks!

**Comment by xiaq** [comment]
@rminnich I am not sure what DDoS possibilities you have in mind, but Elvish ensures that the directory in which the socket lives [has a proper permission](https://github.com/elves/elvish/blob/e40a400795487ed16d9bc8f2abb58fec8d21c403/main.go#L250). Also, There is only one socket per daemon.

We used to access the database from different processes, which limit the choice of databases to virtually just SQLite. Using the daemon for mediating access to the database allows us to use any database implementation and eliminate the SQLite dependency (and hence the cgo dependency).

Tmux also uses this approach of daemon and client communicating through a Unix socket, and complaints are very rare. The robustness of the Elvish daemon should be improved, but if it works for tmux, it can work for Elvish.

**Comment by xiaq** [comment]
Fixed in #428.
