### ISSUE TITLE
`alias` command to allow dynamic alias generation

### ISSUE THREAD

**Issue by dmix** [elves/elvish#442]
I have a bunch of ZSH files generating aliases using associative arrays, for ex:

`~/zsh/aliases/git.zsh`
```zsh
typeset -A gitcmds

gitcmds=(
    gs    "status"
    gc    "commit"
    gb    "checkout -b"
    gpl   "pull --rebase origin"
    gpo   "push origin"
    gundo "reset --soft HEAD~1"
)

for k in "${(@k)gitcmds}"; do
    alias $k="git $gitcmds[$k]"
done
```

Then, for example, I can use `$ gs` in terminal and it runs `git status`.

I haven't been able to figure out how to port this to Elven. For ex, I tried this:

`~/.elvish/rc.elv`
```
gitCmds=[
    &gs=    "status"
    &gcl=   "clone"
    &gc=    "commit"
    &gb=    "checkout -b"
    &gpl=   "pull --rebase origin"
    &gpo=   "push origin"
    &gundo= "reset --soft HEAD~1"
]

keys $gitCmds | each [k]{
    fn "$k"{ git $gitCmds[$k] $@ }  # <-  scoped locally
}
```

BUT the fn is scoped inside the closure. So I can't call any of the `gs`/`gl`/etc functions globally.

Any ideas on how to do this? 

Maybe a builtin `alias/2` function is needed which makes it globally accessible. For example:

```
aliases = [
    [gs         "git status"]
    [gl         "git log"]
    [gc         "git commit"]
    [gcl        "git clone"]
    [gundo      "git reset --soft HEAD~1"]
]

keys $aliases | each [a]{
    alias $a[0] $a[1]  # <-- scoped globally
}
```

This would make me switch to Elvish and possibly contribute code.

The lack of assoc arrays in Fish is why I haven't switched to that shell from zsh either. I spent way too much time making these to abandon them all. I was pretty excited to try out Elvish when I saw how powerful it was.

**Comment by dmix** [comment]
I managed to hack together a simple alternative version within the constraints of the language which calls a short function name.

https://gist.github.com/dmix/41350b4833e8625a6130115bf0bf92ac

The interface looks like this:

```
git-aliases = [
    &prefix= "g"
    &name= "git"
    &aliases="
        s     git status
        l     git log
        c     git commit
        cl    git clone
        undo  git reset --soft HEAD~1
    "
]

fn g [@cmd]{ 
    aliases $git-aliases $cmd 
}
```

Which can then be used like this:
```
$ g s
> git status

$ g undo
>  git reset --soft HEAD~1
```

And pressing `g` alone would print out a list of available aliases.

I used a multi-line string + some regex to parse the list of aliases but a list of lists would work as well with little effort:

```
git-aliases = [
    &prefix= "g"
    &name= "git"
    &aliases=[
        [s               git status]
        [l                git log]
        [c               git commit]
        [cl              git clone]
        [undo         undo  git reset --soft HEAD~1
    ]
]
```
Obviously this is non-ideal vs full aliases, as each prefixed alias would need a 1-3 letter function defined (g, mx, elx)... but it gave me a chance to play with the language.

**Comment by myfreeweb** [comment]
If you only get "g s" you might as well use Git's aliases functionality…

**Comment by dmix** [comment]
@myfreeweb I only used `git` as an example everyone knows

a) I have about ~20 arrays of aliases for different apps, unix utilities, macOS/archlinux/debian, programming tools, etc, etc

b)  I want a uniform place for all of my aliases, , so gitconfig doesn't make sense here.

@xiaq I updated the first comment with an example interface for an `alias/2` implementation. Is this something planned for the future?

**Comment by zzamboni** [comment]
In case anyone finds this interesting: I have implemented an `alias` library which can be used to maintain command aliases easily. You can find it here: https://github.com/zzamboni/vcsh_elvish/blob/master/.elvish/lib/alias.elv

**Comment by krader1961** [comment]
@zzamboni, I like your alias module. It's a pretty good Elvish equivalent of the fish `alias` command. I don't like cluttering my *rc.elv* with all the personal wrappers I have and your solution means I can put them in other files without having to explicitly source each file.

Looking at your code the only thing I noticed is a minor nit in the implementation of the `list` function. The `.*` in the sed pattern should be removed since the grep guarantees the pound-sign is anchored at the start of the line. Removing that avoids unnecessary backtracking:

```
_ = ?(grep '^#alias:def ' $dir/*.elv | sed 's/^.*#//')
```

**Comment by zzamboni** [comment]
@krader1961 thanks for the comment. My original code was exactly like you suggest, but the `.*` becomes necessary when you have more than one alias, because then the output from `grep` includes the filename, like this:
```
[~]─> grep '^#alias:def ' ~/.elvish/aliases/*.elv
/Users/taazadi1/.elvish/aliases/ls.elv:#alias:def ls e:ls --color=auto
/Users/taazadi1/.elvish/aliases/more.elv:#alias:def more less
/Users/taazadi1/.elvish/aliases/v.elv:#alias:def v vagrant
```
I should've probably implemented this using a loop to make it cleaner, but honestly I was lazy, and I don't think in this particular case the extra regex will cause any perceivable performance impact - I guess I could be wrong if you have thousands of aliases ;)

**Comment by krader1961** [comment]
> ... the .* becomes necessary when you have more than one alias, because then the output from grep includes the filename,...

True, @zzamboni, I forgot to mention that you also need to add the `-h` option to the grep to suppress the file names.

**Comment by zzamboni** [comment]
Good point - fixed. Thanks!

**Comment by xiaq** [comment]
Alias definition can be implemented after #613.

One key difference (which I think is a good thing) is that it is not possible to implement an `alias` function that modifies the "interactive namespace" (the namespace under which the interactive session runs) directly - the user must explicitly enable any definitions by assigning to `-exports-` in `rc.elv`. Using the example in OP:

```elvish
git-cmds=[
  &gs=    "status"
  &gcl=   "clone"
  &gc=    "commit"
  &gb=    "checkout -b"
  &gpl=   "pull --rebase origin"
  &gpo=   "push origin"
  &gundo= "reset --soft HEAD~1"
]
# must be in rc.elv!

-exports- = [&]
keys $git-cmds | each [k]{
  -exports-[$k"~"] = [a]{ git (explode $git-cmds[$k]) $@a }
}
```

An alias library is still possible: but in addition to providing a function that lets you define aliases, it also needs to have a function to generate the content of `-exports-`. A hypothetical `alias` module can work like this:

```elvish
alias:def gs git status
alias:def gcl git clone
# ... other alias:def calls
-exports- = (alias:export)
```

**Comment by xiaq** [comment]
Closing because #613 (now fixed!) now enables you to dynamically define aliases.

**Comment by zzamboni** [comment]
I have updated https://github.com/zzamboni/elvish-modules/blob/master/alias.org to work with the new implementation of `-exports-`.

**Comment by dmix** [comment]
@xiaq thanks, works great
