### ISSUE TITLE
Put all builtins modules under "core:"

### ISSUE THREAD

**Issue by alexherbo2** [elves/elvish#451]

**Comment by xiaq** [comment]
Builtins implemented in Go will remain in the `builtin:` namespace. The `core:` namespace will be used for important functions and variables implemented in Elvish.

**Comment by zzamboni** [comment]
I'm not sure if I agree with this - having different namespaces depending on how things are implemented exposes some internals to the user, and requires the user to remember where something is. Top-level bundled namespaces such as `re:`, `edit:` or `epm:` separate functions by their functionality, which makes much more sense from the user's point of view. But how would the user remember what's in `builtin:` vs `core:`?

**Comment by xiaq** [comment]
The core: namespace will be pre-imported like builtin:. It should be a technical detail you don't need to worry most of the time.

**Comment by zzamboni** [comment]
OK, fair enough 😄
