### ISSUE TITLE
Add low-level module constructs

### ISSUE THREAD

**Issue by alexherbo2** [elves/elvish#452]

**Comment by xiaq** [comment]
A possible interface:

```
module $mod $block
```

Where `$mod` is a string literal, and `$block` is a lambda literal. This will create a namespace called `$mod` and evaluate `$block` in it.

**Comment by xiaq** [comment]
The new [eval](https://elv.sh/ref/builtin.html#eval) command fills a similar role to the originally proposed `module` command. There is another low-level module commands worth defining, see #1113.
