### ISSUE TITLE
Command line not expanded before history search

### ISSUE THREAD

**Issue by mqudsi** [elves/elvish#471]
Since elvish expands variables when completing (e.g. `~/foo<TAB>` replaces `~` with the full path), the history is less likely to match verbatim what is at the prompt.

For example, if you have a path that you only autocomplete to, `~/foo/bar` and you want to edit this path again, typing in `nvim ~/foo/<TAB>` then selecting `bar` records a history entry `nvim /full/path/to/foo/bar`. Afterwards, typing in `nvim ~<UP>` results in a "no history matches" because the tilde is not expanded before matching against history.

**Comment by xiaq** [comment]
The fact that tab completion expands ~ should be considered a bug: #474

**Comment by xiaq** [comment]
Closing this as the underlying issue is #474.
