### ISSUE TITLE
Segfault when expanding non-existent key in $edit:binding

### ISSUE THREAD

**Issue by joatca** [elves/elvish#475]
Was trying to enter `put $edit:binding[insert][Alt-1]` but made a typo and did `put $edit:binding[insert][Alt-2]` instead and got a segfault:

    ~> put $edit:binding[insert][Alt-2]
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7cea00]
    
    goroutine 425 [running]:
    github.com/elves/elvish/eval.(*Evaler).Eval.func1(0xc420349860, 0xc4203498c0)
    	/home/fm/go/src/github.com/elves/elvish/eval/eval.go:177 +0x80
    created by github.com/elves/elvish/eval.(*Evaler).Eval
    	/home/fm/go/src/github.com/elves/elvish/eval/eval.go:180 +0xe0

Using whatever version comes from `go get github.com/elves/elvish`

**Comment by xiaq** [comment]
`$edit:binding` has been gone from HEAD. Have you tried `go get -u github.com/elves/elvish`?

**Comment by joatca** [comment]
That fixed it! No segfault:

    fraser@smout:~$ go get -u github.com/elves/elvish
    fraser@smout:~$ go/bin/elvish 
    ~> put $edit:binding[insert][Alt-2]
    Exception: variable $edit:binding not found
    Traceback:
      [interactive], line 1:
        put $edit:binding[insert][Alt-2]

**Comment by xiaq** [comment]
By the way, $edit:binding[insert] is now $edit:insert:binding. See https://github.com/elves/elvish/wiki/Draft-release-notes-for-0.10 for recent changes.
