### ISSUE TITLE
Typing/pasting & into elvish returns parse error - unexpected rune

### ISSUE THREAD

**Issue by amarsahinovic** [elves/elvish#479]
I tried adding [Sublime Text 3 Pacman repository](https://www.sublimetext.com/docs/3/linux_repositories.html#pacman) and I encountered the following issue:

First, after pasting into the terminal:
~~~
~> curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg           
parse error: 60-61 in [interactive]: unexpected rune
~~~

After pressing enter:
~~~
~> curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
Parse error: unexpected rune
  [interactive], line 1:
    curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
~>
~~~

Also, if I try to type & character into terminal, I get this:
~~~
~> &                                                                               
parse error: 0-1 in [interactive]: unexpected rune
~~~

Pacman elvish info:
~~~
~> pacman -Qi elvish
Name            : elvish
Version         : 0.9-2
Description     : A friendly and expressive Unix shell.
Architecture    : x86_64
URL             : https://github.com/elves/elvish
Licenses        : custom:2-clause BSD
Groups          : None
Provides        : elvish
Depends On      : glibc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 8.19 MiB
Packager        : Unknown Packager
Build Date      : Wed 06 Sep 2017 02:03:10 AM CEST
Install Date    : Wed 06 Sep 2017 02:03:18 AM CEST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
~~~

**Comment by muesli** [comment]
`&&` doesn't exist in elvish. Use a semicolon instead.

**Comment by amarsahinovic** [comment]
@muesli Thanks, didn't know that! But I still find it strange that it shows the error after pressing & (I understand why it should fail after pressing the enter key). Perhaps it could use a more helpful error message for people coming to elvish?

**Comment by muesli** [comment]
It shows me that parse error while I type that out. Is it not doing that for you?

**Comment by zzamboni** [comment]
@amarsahinovic Elvish does on-the-fly parsing, which is why it flags errors as you type. As you continue typing and correct the syntax, the error will disappear.

Elvish is very powerful, but it's different enough from other shells that it's worth your time to read through some of the documentation when you start. I would recommend the "[Some Unique Semantics](https://elvish.io/learn/unique-semantics.html)" page, which assumes you know other shells already. From there you can move to some of the other tutorials and reference documentation.

**Comment by amarsahinovic** [comment]
@muesli Yeah, I thought it was weird, but after @zzamboni explanation that elvish parses as I type, it makes sense (although I still think better error message could be shown, "unexpected rune" means nothing to me in this context as I have never heard of it before, and I can't find anything about it on the page @zzamboni linked for example)

@zzamboni Thanks for the info.

I think I'll close the issue, thanks everyone!
