### ISSUE TITLE
Run prompts asynchronously

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#482]
Sometimes prompts can take a long time and will block the UI. In that case, Elvish can render the prompt as a placeholder (say "?") and update it when the function completes.

**Comment by zzamboni** [comment]
This would be very nice, with a couple of considerations:
- Don't use "?" - better cache the previous value and use that
- Run asynchronously but not overlapping - otherwise we have a potential explosion of simultaneous number of prompt commands running at the same time.

**Comment by therealpxc** [comment]
Are there any shells that currently do this right? This would be a pretty nice feature and hugely increase the perceived 'performance' of Elvish for people who use VCS prompts.

**Comment by xiaq** [comment]
Good news, this has landed in master. To see it in action, try this:

```sh
edit:prompt = { echo 'slow prompt'; sleep 1 }
edit:-prompts-max-wait = 0.05
```

Read dd2d36a6d346372593163718e9465503d307fc47 for a detailed explanation and caveat.

**Comment by zzamboni** [comment]
@xiaq this is great! I have vastly simplified my [chain theme](https://github.com/zzamboni/vcsh_elvish/blob/master/.elvish/lib/theme/chain.org) implementation thanks to this new feature.
