### ISSUE TITLE
Support for tilix (VTE)

### ISSUE THREAD

**Issue by doppioandante** [elves/elvish#489]
Hello, when using terminals based on recent versions of VTE, the shell should synchronize with vte respect to the current path. This is so that VTE knows the current path in case a new terminal or split is needed.

I've somewhat adapted the bash/zsh script that is usually shipped with vte, and I got this:
```
# vte terminal support
E:HOSTNAME = (re:replace "\\..*" "" (hostname))

fn __vte_osc7 []{
  printf "\033]7;file://%s%s\007" $E:HOSTNAME $pwd
}

edit:before-readline = [
    {
        printf "\033]0;%s@%s:%s\007%s" $E:USER E:HOSTNAME $pwd (__vte_osc7)
    }
]
```
The way it works is by writing some metadata that VTE can read.
This kind of works, but changing directory using the Location prompt doesn't work.
This is only a minor annoyance but I was wondering whether adding other hooks could make sense?

Fish has an interesting approach to this, as it allows variables to be watched from what I can understand: relevant code here
https://github.com/fish-shell/fish-shell/pull/973/files#diff-78513777ead43586268a4b2eca20088eR219

**Comment by xiaq** [comment]
This is a dup of #493.
