### ISSUE TITLE
cd hooks

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#493]
Add two hooks, `$before-cd` and `$after-cd`, that are triggered before and after changing directory.

**Comment by zzamboni** [comment]
Yes please! 👍

**Comment by krader1961** [comment]
FWIW, I can only find one reference to execution hooks in the elves/elvish.io project *src/ref/edit.md* file. This mechanism definitely needs more documentation. In particular the `before-location`, `after-location`, `before-history`, `after-history`, `before-lastcmd`, and `after-lastcmd` hooks are not documented. Too, the concept of hooks needs to be documented outside of the mention in the [edit module](https://elvish.io/ref/edit.html).

**Comment by dmix** [comment]
@xiaq Any documentation on how to use this?

I'm building a close of https://github.com/rupa/z for Elvish (and any other shell) in Rust: https://github.com/dmix/portal and I need a way to detect directory changes with `cd`.

In ZSH I was able to get it to work with

```
autoload -U add-zsh-hook
add-zsh-hook -Uz chpwd (){ 
    portal db track $pwd
}
```
I tried:

```
edit:after-cd = [{ echo 'just changed dir' }]
```

But I got this error:

`new variables can only be created in local scope`

Am I missing something?

**Comment by SolitudeSF** [comment]
its `after-chdir = [[_]{ put 'just changed dir' }]`
tracking directory is not a job of editor.

**Comment by zzamboni** [comment]
@dmix The `before/after-chdir` hooks are documented here: https://elv.sh/ref/builtin.html#$after-chdir

The error you got was caused by you trying to create a new variable inside the `edit:` module (which is not allowed), but additionally your hook function was missing one argument, which is automatically passed as the path of the new directory.

**Comment by dmix** [comment]
@zzamboni @SolitudeSF thanks guys, I need to relearn Elvish it seems!
