### ISSUE TITLE
Changed login shell to Elvish, gnome-terminal won't start.

### ISSUE THREAD

**Issue by haarts** [elves/elvish#498]
I've taken the plunge and changed my login shell to elvish with `chsh`. However, upon reboot, I no longer can open a terminal window (`ctrl-alt-t` in Gnome, Ubuntu 17.04.). Briefly I see this error message: `warning: cannot start daemon: cannot find elvish: not found`

I've installed elvish by `go get github.com/elves/elvish`. It installed the elvish binary in `/home/me/prj/go/bin/elivsh`. I've added that path to `/etc/shells` and then changed my shell with `chsh`.

Running `elvish` works.

The SHA which is checked out is f84e406bb8740ac06b5bfd9839a809e5f6a8d713.

I'm missing some silly PATH stuff no doubt. But I'm scratching my head.

**Comment by xiaq** [comment]
Hmm, this seems like a similar problem to #496, but Elvish should still be able to start itself instead of quitting abnormally. Are there more outputs, potentially a panic message? If GNOME terminal has an option for not closing the terminal window when the command quits, can you try turning that on and see if there are more outputs?

**Comment by haarts** [comment]
Unfortunately I can not find such an option and the logs don't help either.
I've read the linked issue and this must be the same. When I'm able I'll dig further. I'm now monitoring #496 too.

**Comment by zzamboni** [comment]
@haarts Indeed this is related to #496. The workaround for now is to specify the `-bin` option when you run Elvish, like this (in your case): `/home/me/prj/go/bin/elvish -bin /home/me/prj/go/bin/elvish`.

My other recommendation would be to avoid changing your login shell. What I do is instead I configure my terminal (I use Terminal.app on macOS, but I would hope gnome-terminal has something similar) to run Elvish upon starting a new shell. That way, if elvish fails for some reason, your terminal will still open but with bash.

Another benefit of leaving your login shell untouched is that it prevents breakage from programs which assume your login shell is a POSIX-compliant one and execute external commands using POSIX syntax. I first encountered this with some Emacs package when I was using fish.

Of course this only works if you mainly use the shell from your terminal program, and not through ssh or some other mechanism.

**Comment by haarts** [comment]
That's some solid advice @zzamboni. Thanks a lot. My `gnome-terminal` does indeed have such a function. 
I'm closing this issue.
