### ISSUE TITLE
RFC: (Syntactic sugar) Allow space to separate namespace and function

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#501]
(I'm just throwing this out for comments - I'm not sure how easy this would be, or even if it's a good idea)

It occurred to me that it might be nice to allow, as syntactic sugar, to separate the module and function name with a space instead of a colon. This would allow invoking module functions using the familiar `command subcommand` structure.

This way, instead of typing [`alias:new` or `alias:list`](https://github.com/zzamboni/vcsh_elvish/blob/master/.elvish/lib/alias.elv), one could type `alias new` or `alias list`.

I'm aware this could muddle the command resolution rules and make it unnecessarily complicated, so I'm not fully adamant on the idea - but I think it would be a cool and easy way to define new modules whose functionality can be accessed in a familiar and easy way.

**Comment by xiaq** [comment]
I agree to your points. As neat as it is, I can think of a few more downsides:

1. This syntax only applies to functions, not ordinary variables.

1. This creates two equivalent ways to access functions in modules. The only difference between `mod:func` and `mod func` is stylistic.

1. Names of modules and commands can now collide. That makes it harder to name your modules.

**Comment by zzamboni** [comment]
Yes, probably not worth the trouble. Closing this.
