### ISSUE TITLE
Bad matcher cause completion to hang

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#503]
Minimal example:

1. Do `edit:-matcher[''] = { bad command }`
2. In a directory with sufficiently many files, do `echo `<Tab>

The editor hangs.

**Comment by tw4452852** [comment]
I think we could close this issue now.

**Comment by xiaq** [comment]
FWIW, if you wrote "fix #503" or "fixes #503" this issue will be auto-closed: https://help.github.com/articles/closing-issues-using-keywords/
