### ISSUE TITLE
`del` command needs to be documented

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#504]
Someone recently asked on Gitter how to unset an environment variable. Turns out there is an undocumented `del` command to do that; e.g., `del E:VARNAME`. You can also specify the local namespace (scope) but it doesn't allow deleting values in other namespaces.. This issue is to remind someone to document it.

**Comment by krader1961** [comment]
Okay, @xiaq, but a suggestion if I may? Consider changing the description of the [elvish.io](https://github.com/elves/elvish.io) project page from

> Source code for https://elvish.io.

to something like

> Documentation for Elvish and the source for the https://elvish.io web site.

The Fish shell project also has a separate project for its web site but all the documentation is in the shell source project. I just assumed (without looking) the same was true of this project.

**Comment by xiaq** [comment]
This is now documented in https://elvish.io/ref/language.html#deleting-variable-or-element-del
