### ISSUE TITLE
Document variable and function identifier syntax

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#505]
I can't find any place in the documentation where the rules governing valid identifiers (i.e., variable and function names) is documented. Empirical testing suggests that something like this text (from the fish-shell docs) would be appropriate:

> A variable name can not be empty and can contain only letters, digits, and underscores. It may begin and end with any of those characters.

**Comment by xiaq** [comment]
Thanks for reporting. Please file future reports against documentations in https://github.com/elves/elvish.io/issues (this one can remain here).

**Comment by xiaq** [comment]
Now documented in https://elvish.io/ref/language.html#string and https://elvish.io/ref/language.html#variable.
