### ISSUE TITLE
Clarify `try { } except [varname] { }` documentation and fix implementation

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#506]
A user recently asked for help on Gitter with handling the exceptions thrown when an external command exits with a non-zero status. Among other mistakes they made they were doing the equivalent of this: `try { false } except 2 { do_something }`. Note the `except 2`. The person was expecting that to only execute the exception block if the exit status was two. They didn't realize the `2` is actually a var name to which the value of the exception is assigned. However, even that doesn't work:

```
~/go/src/github.com/elves/elvish> try { false } except 2 { put $2 }
Exception: variable $2 not found
Traceback:
  [interactive], line 1:
    try { false } except 2 { put $2 }
  [interactive], line 1:
    try { false } except 2 { put $2 }
```

But if you change the var name to a letter it does work:

```
~/go/src/github.com/elves/elvish> try { false } except x { put $x }
▶ ?(fail 'false exited with 1')
```

It also looks like there is an implementation bug since you can create a var named `2`:

```
~/go/src/github.com/elves/elvish> 2 = abc
~/go/src/github.com/elves/elvish> put $2
▶ abc
```

So it seems like `except 2 { put $2 }` should be legal and work.

**Comment by xiaq** [comment]
Thanks for reporting. Please file future reports against documentations in https://github.com/elves/elvish.io/issues (this one can remain here).

**Comment by xiaq** [comment]
This has been clarified in the current edition of https://elvish.io/ref/language.html#exception-control-try. The bug of not being to use `$2` has also been fixed. Thanks for reporting!
