### ISSUE TITLE
Support Bash aliases?

### ISSUE THREAD

**Issue by xtuc** [elves/elvish#510]
This is an open question. Would you be open to adding the support for Bash aliases?

My use case: I have tons of them and would like to import them easily.

**Comment by xiaq** [comment]
This is a dup of #442.

**Comment by zzamboni** [comment]
@xtuc this is pretty easy to implement as a function. Using my own [alias](https://github.com/zzamboni/vcsh_elvish/blob/master/.elvish/lib/alias.elv) module as a base, the following function allows you to use the bash alias syntax:

```
fn alias [@args]{
  line = $@args
  name cmd = (splits '=' $line)
  alias:def $name $cmd
}
```

For example:

```
> bash -l 
$ alias
alias bd='. bd -s'
alias cd='prompt_cd builtin'
alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
alias git='hub'
alias more='less'
alias v='vagrant'
$ alias > ~/tmp/bash-aliases
$ logout
-source /Users/taazadi1/tmp/bash-aliases
Defining alias bd
Defining alias cd
Defining alias fixopenwith
Defining alias git
Defining alias more
Defining alias v
```
