### ISSUE TITLE
Asynchronous prompt erases Elvish error messages whenever it updates the prompt

### ISSUE THREAD

**Issue by therealpxc** [elves/elvish#512]
When an async prompt is enabled using, e.g., the configuration lines [here](https://github.com/elves/elvish/issues/482#issuecomment-343710502), if there is an error on the line being typed at the prompt, it will only show in between updates of the async prompt. When it adds the character indicating that it is waiting, as well as when it updates the prompt, the messages disappear. This effectively means that those handy error messages only flash on the screen for a moment.

**Comment by xiaq** [comment]
This bug is no longer present in the rewritten editor.
