### ISSUE TITLE
Allow customization of stale prompt marker

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#513]
For prompt theme purposes, it would be nice to allow customizing the stale-prompt marker from the default (https://github.com/elves/elvish/commit/dd2d36a6d346372593163718e9465503d307fc47#diff-b50c0ed36c6482d1373be5e2a68bf0daR165).

Maybe a new variable `$-prompt-stale-marker` or something like that? Ideally it should be possible to assign either a string or an `edit:styled` object to it.

**Comment by zzamboni** [comment]
As I've been using this feature, I've found it immensely helpful, but the flickering on/off of the stale marker a bit distracting (for example, when I'm in a large git repo, so that the git parts of my prompt almost always take longer than the threshold). I was thinking it might be better to allow specifying a function that gets passed the current prompt and returns the new one. The default behavior could be to add the character marker like today, but it could also change the color of the prompt, return the prompt unchanged, etc.

**Comment by xiaq** [comment]
Yes, the appearance of stale prompt should be customizable. But what if the user wants a marker before the prompt? What if the user wants to apply a style (e.g. reverse video) to the prompt?

I have another approach in mind: allow the user to assign a function to `$edit:-stale-prompt-transform` that transforms the prompt. The function can take the prompt as argument (or input?) and its output becomes the stale prompt.

**Comment by zzamboni** [comment]
Yes, this is exactly what I thought after using the feature for a while. See my previous comment :)

**Comment by xiaq** [comment]
While thinking about this, I had the idea that a transformer that inverses the current prompt will be a good one: but that is tricky to implement, since `edit:styled` values are not nestable. I gave a shot to a new, high-level redesign and the result is #320.

**Comment by zzamboni** [comment]
@xiaq did you mean #520?

**Comment by xiaq** [comment]
@zzamboni Right, I meant #520. I'm glad that you like it!

**Comment by xiaq** [comment]
Fixed in #624 thanks to @dcu!
