### ISSUE TITLE
Support fallback matcher in completion

### ISSUE THREAD

**Issue by xofyarg** [elves/elvish#516]
The sequence in current strategy is, find a completer based on the context then select a matcher according to the completer's name. If the matcher failed to find any candidate, we are out of luck. It would be good to have a fallback matcher for a single completer, or a list of completer for same context. The completion will continue until one of the matcher/completer in the same context find a candidate.

One of the use cases is filename completion. Say we have a directory with files having the same prefix, people only need to type the unique part before completion with a "match-subseq" as fallback matcher:

```
foo/
- bar.1
- bar.2
- bar.3
- baz
```

Current approaches are:
1. complete then use filter
2. set argument completer to use subseq matcher, which works in this case, but often bring other confusions since it's not that "deterministic" than prefix match.

**Comment by xiaq** [comment]
```
edit:-matcher[argument] = [seed]{
    inputs = [(all)]
    prefix-results = [(put $@inputs | edit:match-prefix $seed)]
    if (or $@prefix-results) {
        put $@prefix-results
    } else {
        put $@inputs | edit:match-subseq $seed
    }
}
```

(You need to update to HEAD as I uncovered and fixed a bug with matcher when testing this code.)

**Comment by xiaq** [comment]
The matcher is now available as a module: https://github.com/xiaq/edit.elv/blob/master/smart-matcher.elv. (BTW I realized that there should also be a standard substring matcher and added it.)
