### ISSUE TITLE
Converting dir history to JSON doesn't work

### ISSUE THREAD

**Issue by notramo** [elves/elvish#526]
`dir-history | to-json` gives strange result.
`edit:command-history | to-json` is OK.

**Comment by zzamboni** [comment]
I can confirm this. The problem seems to happen only when the data comes from dir-history. For example:
```
> dir-history | take 1
▶ [&path=/Users/taazadi1/.emacs.d &score=366.2701]
> dir-history | take 1 | to-json
{"Descriptor":{},"Fields":["/Users/taazadi1/.emacs.d","371.1423"]}
```

But if manually `put` the same data, it works fine:

```
> put [&path=/Users/taazadi1/.emacs.d &score=366.2701] | to-json
{"path":"/Users/taazadi1/.emacs.d","score":"366.2701"}
```

**Comment by notramo** [comment]
Yes, it only happens with `dir-history`, and this also works:
```
dir-history | each [i]{ put [ &path=$i[path] &score=$i[score] ] |to-json }
```

**Comment by xiaq** [comment]
Yeah, this is because the output of `dir-history` aren't really maps but "map-like" values.
