### ISSUE TITLE
undefined: os.Unsetenv

### ISSUE THREAD

**Issue by rapha8l** [elves/elvish#53]
Hi, 

On two new machines running debian jessie, I get

>go get github.com/xiaq/elvish    
> # github.com/elves/elvish/eval
> go/bin/src/github.com/elves/elvish/eval/builtin_special.go:281: undefined: os.Unsetenv

Thanks

Raphael

**Comment by cryptix** [comment]
Hmm.. not sure when it was introducet but `Unsetenv()` is part of the golang standardt [os](http://golang.org/pkg/os/) package.

What version of go do you have installed? (`go version`)

**Comment by xiaq** [comment]
We require golang>=1.4, while Jessie ships with 1.3.
