### ISSUE TITLE
On Mac OS X, tab completion triggers "resource temporarily unavailable"

### ISSUE THREAD

**Issue by max107** [elves/elvish#54]
```bash
[max:~]$ elvish

~> cd projects

~/projects> ls Test                                                                              max@maxs-mbp
Completing Test
Test1                Test2           Test3
Editor error: write /dev/stdin: resource temporarily unavailable
My pid is 5341
~/projects>
```

**Comment by xiaq** [comment]
Please report the setup of your terminal and construct a minimal example that can reproduce this issue.

**Comment by max107** [comment]
Mac 10.9, iTerm2, go version go1.4.2 darwin/amd64. Minimal example you can see in first post.

**Comment by max107** [comment]
@xiaq how i can debug this problem to get more information?

**Comment by xiaq** [comment]
@max107 Unfortunately I am pretty clueless about this problem and properly debugging it likely requires you to modify the source code. A thing we can do is to find out whether this is iTerm2-specific. Can you try to reproduce the bug with another terminal?

**Comment by max107** [comment]
@xiaq default mac os terminal - problem exists

**Comment by xiaq** [comment]
I have reproduced this issue on FreeBSD. Looking into it.
