### ISSUE TITLE
Limit number of lines in LOCATION mode

### ISSUE THREAD

**Issue by notramo** [elves/elvish#545]
If someone has a lot of paths in the directory history, entering LOCATION mode wipes the content of the terminal away, and the directory names fills the whole terminal.
Because listing views can be scrolled, I think, the number of lines could be reduced.

**Comment by xiaq** [comment]
The customization point is $edit:max-height, documented [here](https://elvish.io/ref/edit.html#editmax-height).

**Comment by notramo** [comment]
Cool! Thanks!
