### ISSUE TITLE
Can't use backspace at the prompt

### ISSUE THREAD

**Issue by vendion** [elves/elvish#55]
When typing at the prompt I am unable to delete characters using the backspace key, attempting to do so results in a ```Unbound: Ctrl-H``` error.  If I move the cursor over the character and press delete though that works as expected.

**Comment by xiaq** [comment]
The default key binding handles `^?` but not `^H` as backspace. Either configure your terminal to send `^?` on backspace, or wait for customizable key bindings to land...

**Comment by vendion** [comment]
This was via a ```TTY``` session so I'm not sure if altering what gets sent on backspace like that would be easy or wise.

**Comment by ke7ofi** [comment]
Isn’t `^H` standard? If so, why is the current binding `^?`?

**Comment by xiaq** [comment]
I have added `^H` to the default key binding to do the same thing as ASCII `DEL`.

There are a lot of emulator particularities when it comes to function keys. I will deal with them systematically some time in future.
