### ISSUE TITLE
Delete from command history

### ISSUE THREAD

**Issue by notramo** [elves/elvish#554]
To keep the history clean, deleting items can be useful.
Deleting from history is more difficult than with `bash` or `zsh`, because these shells use plain text history files, while `elvish` uses a database.
The command should delete items based on their id.

**Comment by notramo** [comment]
What about exposing it as an array?

**Comment by kidosatori** [comment]
Voting this up as well. I abuse history, `^R` and ~~hashtags~~ comments to quickly and unambiguously find the commands I use most frequently. For example, this is how I connect to IRC:

```
ssh -t example.com 'tmux a -t weechat || tmux new -s weechat'  #irc
```

(Note the trailing comment. I just press `^R` and type `#irc`)

Being able to delete old history entries would allow me to cleanup these "tags" when I update or deprecate them.

**Comment by href** [comment]
I'd like to add that it would be nice if the history mode had a shortcut to delete selected entries. For my use case that would be enough. I just need to remove a command here or there, and what better way than to delete it right where it can be found.

**Comment by krader1961** [comment]
In addition to being able to delete history entries it would be nice if there was a `history` command for showing and manipulating command history. That is, something that wraps `edit:command-history` but is human friendly. Something analogous to the fish [history](http://fishshell.com/docs/current/cmds/history.html) command.

**Comment by xiaq** [comment]
Now supported by `store:del-cmd`: https://elv.sh/ref/store.html#storedel-cmd
