### ISSUE TITLE
Delete from directory history

### ISSUE THREAD

**Issue by notramo** [elves/elvish#555]
Elvish should support deleting from directory history.

**Comment by jiegec** [comment]
Additionally, We can scan through the history and prune the directories that no longer exist.

**Comment by notramo** [comment]
@jiegec, I currently have a simple [script](https://gist.github.com/notramo/9c4d579d4faf54ca5c31661fae54891a) for hiding old, and nonexistent directories using `edit:loc-hidden`,  and my config runs it at startup. But testing dirs that are deleted a long time ago slightly slows down my shell's startup.

**Comment by notramo** [comment]
What about exposing the dir history as a map (`[ &~/code=15 &~/docs=30 ]`), then users can use `del` or `dissoc`. Also, this would make the dir history more flexible, because users can change weight of a directory, or change path (e.g. after a directory `mv`).
