### ISSUE TITLE
Make executable names in environment variables callable

### ISSUE THREAD

**Issue by notramo** [elves/elvish#557]
Environment variables are quite different from Elvish variables, because they only can store strings.
This works:
```
editor = (external kak)
$editor .elvish/rc.elv
```
But this don't:
```
$E:EDITOR = (external kak)
$E:EDITOR rc.elv
# And when other programs search for the `EDITOR` variable, they say something similar to this: 
exec: "<external kak>": executable file not found in $PATH
```

**Comment by xiaq** [comment]
The example is a good one; `var = (external kak); $var ...` should always behave like `(external kak) ...`. I have taken another approach to resolve this though: Assigning environment variables to non-string values is now forbidden.

You can call the editor in `$E:EDITOR` by constructing an external command on the fly: `(external $E:EDITOR) rc.elv`; if you use this a lot, you can simply make a function

```elvish
fn editor [@args]{ (external $E:EDITOR) $@args }
```

**Comment by notramo** [comment]
`(external $E:EDITOR) rc.elv` works, and is a good solution.
Forbidding non-string variable assignment to environment variables is also cool.

**Comment by chengxuncc** [comment]
How about `external $E:EDITOR rc.elv`
