### ISSUE TITLE
On Mac OS X, entering navigation mode triggers "resource temporarily unavailable"

### ISSUE THREAD

**Issue by dbbbit** [elves/elvish#56]
![2015-05-20 8 39 57](https://cloud.githubusercontent.com/assets/8575796/7716970/143fbc66-fecc-11e4-95c5-fa0a57770d8d.png)

**Comment by xiaq** [comment]
Please describe how to reproduce this bug.

**Comment by dbbbit** [comment]
最早是在 $HOME 目录下按 `^N`, 就会出现这个报错。
后来发现只要是文件／目录数量比较大的目录中进入导航模式都会报错。
~/tmp/t1> tree
.
├── t1
├── t10
├── t2
├── t3
├── t4
├── t5
├── t6
├── t7
├── t8
└── t9

11 directories, 0 files

这个时候 ^N 工作良好，但是再增加一个目录就挂。 

~> uname -a                                                                     
Darwin Airbus.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

不论 ITerm 或者 mac 自带终端都有这个问题。

**Comment by xiaq** [comment]
@dbbbit  Is this bug is present in HEAD?

**Comment by xiaq** [comment]
I have reproduced this issue on FreeBSD. Looking into it.

**Comment by xiaq** [comment]
Fixed by ac605a1dee18824335231691f4f1353115325180.
