### ISSUE TITLE
Support introspecting closures

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#560]
Current design is to expose the source code via a `code` attribute:

```
~> f = { echo lorem }
~> echo $f[code]
{ echo lorem }
```

**Comment by zzamboni** [comment]
The attribute is fine, but maybe it would be more consistent to do this through the existing `src` function? E.g. `src $f`

**Comment by xiaq** [comment]
Yes, that will also be useful, but it's a slightly different thing: the `src` returns information about the **entire** source code. Consider this:

```
echo a; f = { put (src)[code] }
```

This will output `echo a; f = { put (src)[code] }`, not just the definition for `f`.

So we need to have both. As an alternative to your proposal, I'm also considering adding another `src` attribute.

**Comment by zzamboni** [comment]
Awesome!
