### ISSUE TITLE
Inconsistencies when using a period in a namespace name

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#561]
It seems that periods are in general allowed in namespace names, except when assigning variables. Assume for example:

```
[~/.elvish]─> epm:install github.com/zzamboni/theme.elv
```

Then the following works:

```
[~/.elvish]─> use github.com/zzamboni/theme.elv/chain
[~/.elvish]─> chain:setup
[~/.elvish]─> echo $chain:prompt_pwd_dir_length
1
[~/.elvish]─> chain:prompt_pwd_dir_length = 2
[~/.elvish]─> echo $chain:prompt_pwd_dir_length
2
```

If `theme.elv` is left in the namespace, then function calls work, but no variable references or assignments:

```
[~/.elvish]─> use github.com/zzamboni/theme.elv:chain
[~/.elvish]─> theme.elv:chain:setup
[~/.elvish]─> echo $theme.elv:chain:prompt_pwd_dir_length
Compilation error: variable $theme not found
[tty], line 1: echo $theme.elv:chain:prompt_pwd_dir_length
[~/.elvish]─> theme.elv:chain:prompt_pwd_dir_length = 2
Parse error: bad assignment LHS
, line 1: theme.elv:chain:prompt_pwd_dir_length = 2
```

Is there an established rule here? I think if periods are allowed in the namespace at all, then they should work consistently, otherwise they should be disallowed.

**Comment by xiaq** [comment]
Right, We need to check that namespaces introduced with `use` are valid variable names.

Moreover, there is a similar situation with `fn`:

```
fn a.b { }
a.b # works
put $a.b~ # doesn't
```
