### ISSUE TITLE
Something is wrong in the reference:The Language,13.2 Arguments and Options

### ISSUE THREAD

**Issue by RevolverOcelotA** [elves/elvish#574]
The example in [The language,13.2 Arguments and Options](https://elvish.io/ref/language.html#arguments-and-options):
`splits &sep=: /home:/root`

The explaination in [The Builtin Module,Splits](https://elvish.io/ref/builtin.html#splits):
splits
    `splits $sep $string`

Looks like the latter is the correct one.

**Comment by notramo** [comment]
But the former would be better.

**Comment by xiaq** [comment]
Thanks, it has been fixed.

@notramo It used to be the case that the separator was an option instead an argument. However, Elvish's options must be optional and need to have a default value. There isn't a good default value for the separator, so I made it an argument instead.
