### ISSUE TITLE
Crash moving cursor when editor is higher than edit:max-height

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#578]
If `edit:max-height` is set and the line is longer than that number of lines, moving the cursor to the beginning of the line causes a crash with the backtrace below.

How to reproduce:
- Set `edit:max-height = 2`
- Type any command, until it extends beyond 2 lines (the editor scrolls and the first line disappears)
- Press `Ctrl-A` (if you are using `readline-bindings`) to move to the beginning of the line. It can also be triggered moving back a word at a time.
- Crash

Here is the stack trace I get: https://gist.github.com/zzamboni/00de788acca1fbc31466f87633b910a2

**Comment by xiaq** [comment]
Aha, good catch. I tried to handle cases where the terminal is very small, but had no evidence that it was also correctly handled; the situation is rare enough that it never caused me any problem in practice. `edit:max-height` is a great way to surface such problems.

Also, it can be more convenient for others to read the issue if you paste stacktraces somewhere else (e.g. as a gist) and link to it.

**Comment by zzamboni** [comment]
Moved stack trace to a gist - sorry about that!
