### ISSUE TITLE
OSX: Running commands with sudo fails

### ISSUE THREAD

**Issue by vendion** [elves/elvish#58]
Running OSX running commands with `sudo` fails.

Under ZSH
```
~> sudo echo true
Password:
true
```

Under elvish
```
~> sudo echo true
Status: external command not found
~> echo true
true
~> which sudo
/usr/bin/sudo
```

Using sudo works as expected on FreeBSD 10.2 and Arch Linux though.

**Comment by xiaq** [comment]
Most likely this is because `sudo` lives somewhere not in the default `$PATH` and you didn't `export` your modified version of `$PATH`.

**Comment by vendion** [comment]
From the second example, using evish the `which` command reports that `sudo` is `/usr/bin/sudo`, and of course ZSH reports the same.  Which I can confirm that `/usr/bin` is in my path as I would have bigger problems than just with `sudo`.

Here is what is in my path under both shells:

ZSH
```
/Users/vendion/perl5/perlbrew/bin:/Users/vendion/perl5/perlbrew/perls/perl-5.22.0/bin:/Users/vendion/perl5/bin:/usr/local/heroku/bin:/usr/local/go/bin:/Users/vendion/bin:/Users/vendion/gocode/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/vendion/.fzf/bin:/Users/vendion/.composer/vendor/bin
```

Elvish
```
/Users/vendion/perl5/perlbrew/bin:/Users/vendion/perl5/perlbrew/perls/perl-5.22.0/bin:/Users/vendion/perl5/bin:/usr/local/heroku/bin:/usr/local/go/bin:/Users/vendion/bin:/Users/vendion/gocode/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/vendion/.fzf/bin:/Users/vendion/.composer/vendor/bin
```

My PATH under both shells is identical, and both include `/usr/bin`

**Comment by xiaq** [comment]
@vendion that's interesting. Can you build the latest commit (`go get -u github.com/elves/elvish`) and tell me what `put-all $paths` in elvish outputs?

**Comment by xiaq** [comment]
Also the output of ``stat `which sudo` ``. Or `stat (which sudo | from-lines)` in elvish if you don't mind the currently cumbersome syntax.

**Comment by xiaq** [comment]
You can actually just use `stat (which sudo)` in elvish now :)

**Comment by vendion** [comment]
Okay I updated Elvish to commit `0a30f08`

The results of `put-all $paths` is:
```
▶ /Users/vendion/perl5/perlbrew/bin
▶ /Users/vendion/perl5/perlbrew/perls/perl-5.22.0/bin
▶ /Users/vendion/perl5/bin
▶ /usr/local/heroku/bin
▶ /usr/local/go/bin
▶ /Users/vendion/bin
▶ /Users/vendion/gocode/bin
▶ /usr/local/bin
▶ /usr/local/sbin
▶ /usr/local/opt/ruby/bin
▶ /usr/bin
▶ /bin
▶ /usr/sbin
▶ /opt/X11/bin
▶ /Users/vendion/.fzf/bin
▶ /Users/vendion/.composer/vendor/bin
```

Elvish didn't like the ``stat `which sudo``` syntax but did the `stat (which sudo | from-lines)` and `stat (which sudo)` just fine.  Here is the result of both:

```
16777220 116067484 -r-s--x--x 1 root wheel 0 168448 "Jan 26 14:35:49 2016" "Dec  3 01:34:09 2015" "Dec 24 17:47:17 2015" "Dec  3 01:34:09 2015" 4096 176 0x80020 /usr/bin/sudo
```

**Comment by vendion** [comment]
Cleaner version of the stat command doing `stat -x (which sudo)`

```
~> stat -x (which sudo)
  File: "/usr/bin/sudo"
  Size: 168448       FileType: Regular File
  Mode: (4511/-r-s--x--x)         Uid: (    0/    root)  Gid: (    0/   wheel)
Device: 1,4   Inode: 116067484    Links: 1
Access: Tue Jan 26 14:35:49 2016
Modify: Thu Dec  3 01:34:09 2015
Change: Thu Dec 24 17:47:17 2015
```

**Comment by xiaq** [comment]
@vendion There is nothing funny, which only made it more puzzling.

Is there any problem with other external commands in `/usr/bin`, in particular programs with setuid, like `su` and `ping`?

**Comment by vendion** [comment]
Tested with `su` and `ping` command and they seem to work just fine, although for OSX ping is `/sbin/ping` and does not have setuid and both commands work just fine.

Comparing the mode for `sudo` and `su` I see something a bit confusing to me.  The `sudo` command mode is `4511` which means that group and other does have execute permissions but do not have read permissions, while the mode for `su` is `4755` which means that group and others have both read and execute permissions.  Not sure why different shells would have different behaviors it it was a permission problem though.

**Comment by xiaq** [comment]
@vendion I believed this should be fixed now. The code used to `open` the executable for reading. Now it just uses `stat`. I don't remember why I did this, most likely an oversight.

**Comment by vendion** [comment]
Confirmed that change does make it work.
