### ISSUE TITLE
Python Virtual Environments

### ISSUE THREAD

**Issue by iwoloschin** [elves/elvish#582]
I've been playing around with different shells lately and Elvish is pretty interesting, but I'm also currently doing a lot of Python development, and I'd like to have virtual environment support.  Python's virtualenv sets environment variables, and is therefore shell specific.  I imagine it'd be possible to write an 'activate.elv' to match the supplied bash/csh/fish activate scripts, but before I try I wanted to see if anyone has tried this already?

**Comment by xofyarg** [comment]
I happen to have the same issue, and wrote a simple script several hours ago, but you might want to check epm first.

```
PREFIX = $E:HOME/.venv                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                              
fn deactivate {                                                                                                                                                                                                                                               
    if (not-eq $E:_OLD_VIRTUAL_PATH "") {                                                                                                                                                                                                                     
        E:PATH = $E:_OLD_VIRTUAL_PATH                                                                                                                                                                                                                         
        del E:_OLD_VIRTUAL_PATH                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                              
    if (not-eq $E:_OLD_VIRTUAL_PYTHONHOME "") {                                                                                                                                                                                                               
        E:PYTHONHOME = $E:_OLD_VIRTUAL_PYTHONHOME                                                                                                                                                                                                             
        del E:_OLD_VIRTUAL_PYTHONHOME                                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                              
    if (not-eq $E:VIRTUAL_ENV "") {                                                                                                                                                                                                                           
        del E:VIRTUAL_ENV                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                                         
}

fn activate [pe]{
    E:VIRTUAL_ENV = $PREFIX/$pe

    E:_OLD_VIRTUAL_PATH = $E:PATH
    E:PATH = $E:VIRTUAL_ENV/bin:$E:PATH

    if (not-eq $E:PYTHONHOME "") {
        E:_OLD_VIRTUAL_PYTHONHOME = $E:PYTHONHOME
        del E:PYTHONHOME
    }
}

edit:arg-completer[pyvenv:activate] = [@args]{
    e:ls $PREFIX
}
```

**Comment by zzamboni** [comment]
Not an Elvish-specific answer, but you might be interested in looking into [Nix](https://nixos.org/nix/) - one of its abilities is to give you separate environments with different packages or versions installed. You can find a lot of information just by searching for "nix python development", but here are a few that look useful:
- https://ariya.io/2016/06/isolated-development-environment-using-nix
- https://github.com/datakurre/setup.nix
- https://gist.github.com/CMCDragonkai/dcc1b538352624ea690d695ee1ff1528

I use Nix but I'm not a python developer, so I have not personally tested the above.

Ob. Elvish: I have a [nix](https://github.com/zzamboni/elvish-modules/blob/master/nix.org) module in my [elvish-modules](https://github.com/zzamboni/elvish-modules) package, which you can use to set up your Nix environment in Elvish.

**Comment by iwoloschin** [comment]
@zzamboni, thanks, that's interesting, but I think trying to use Nix is probably overkill for my purposes at this time.  I'm already relying on pip/virtualenv to deploy my projects and other users are likely not using Elvish or Nix, so I'd rather keep things as simple as possible.  Definitely something to keep in mind for future projects though!

The above functions work pretty well when copied into rc.elv, but it's kind of odd to see them there.  I've tried creating a package, but that led to things like "python:activate virtualenv" which is kind of odd to type out.  Is there anyway a package installed with epm can promote functions to the global namespace?

**Comment by zzamboni** [comment]
@iwoloschin not yet, although @xiaq has mentioned some ideas for getting this to work. What I do for now is load the module and then set up a wrapper function that simply calls the module, something like this (from [my config](https://github.com/zzamboni/dot-elvish/blob/master/rc.org#directory-and-command-navigation-and-history):
```
use github.com/zzamboni/elvish-modules/dir
fn cd [@dir]{ dir:cd $@dir }
fn cdb [@dir]{ dir:cdb $@dir }
```
Probably not the prettiest, but it has the advantage of making it explicit where the functions are coming from.

You could also use my [alias module](https://github.com/zzamboni/elvish-modules/blob/master/alias.org) for this (I should probably convert the above to aliases!). For example:
```
use github.com/zzamboni/elvish-modules/alias
alias:new activate python:activate
```
Note that `alias:new` creates a persistent alias, so you don't necessarily have to define them in your config file (you can do it interactively), the defined functions get stored under your `~/.elvish/aliases/`.

**Comment by iwoloschin** [comment]
That's not a bad idea, maybe I'll give that a shot, it's a little more work than setting up an individual package, but not unreasonable to do so.  If that works well I'll probably close this issue and do a PR to the awesome-elvish stuff to point out any new packages.  Thanks!

**Comment by zzamboni** [comment]
You are welcome! It will be awesome if you contribute some new packages.

(BTW I am thinking of making aliases not get saved by default, see https://github.com/zzamboni/elvish-modules/issues/1).

**Comment by iwoloschin** [comment]
@zzamboni, so I got things working with aliases, but a couple of questions.

1) I think the alias definitions *must* be in rc.elv, is that correct?  I can't define the aliases in my module itself, correct?
2) The alias breaks the edit:arg-completer variable, right now I have it set as `python:activate`, but if I declare it as an alias now it should just be `activate`.  For now I've just put the following line in and it seems to work:
```
edit:arg-completer[activate] = $edit:arg-completer[python:activate]
```
Is there a better way to handle this with aliases?

**Comment by xiaq** [comment]
I am working on a [POSIX shell](https://github.com/xiaq/posixsh) which is quite close to parsing the `activate` script.

**Comment by iwoloschin** [comment]
Ok, wound up bundling this all up into a package and I've also made a PR for awesome-elvish so that hopefully the next person to ask for this finds it before opening up an issue.  Closing this as complete.

https://github.com/iwoloschin/elvish-packages/blob/master/python.elv

**Comment by iwoloschin** [comment]
@xiaq, just saw your comment now, that'd be awesome for this and many other things too!

**Comment by zzamboni** [comment]
@iwoloschin I had never tried defining aliases from within a module, but I just tested and it works - the alias is defined in the top namespace and not within the module namespace. I guess `-source` (which is used to define the alias functions) operates outside of the current module namespace.

I am not sure whether it's a good idea to allow a module to define top-level functions automatically, as it reduces the transparency of the module's behavior. Also, what if a user of your module already has some other command called `activate` and thus wants to wrap `python:activate` with a different name?

About the completion: I guess `alias:new` could check whether a completer already exists for the command being aliased, and copy it to the completer for the alias, but I'm not sure if it might have unintended consequences. I'll think about it. Do you think this would be useful behavior?

**Comment by iwoloschin** [comment]
@zzamboni probably a bad idea to implicitly update the completer as an alias could change the command to make the original completion no longer valid (for instance, look at the `git` command, each of it's subcommands have unique completions).  I think the only time it makes sense is if you're just trying to promote a function to the global namespace, which arguably shouldn't be an alias anyways :).

I played around with `-source` as well, and that happily imports everything into the global namespace, but I'm unclear on how much I can, or should, rely on the `-source` command to do stuff like that, as it seems contrary to Elvish design principles.  If `-source` is allowable the better solution might be to just drop an activate.elv file into each virtual environment (do a PR to the virtual environment codebase itself) and be explicitly like every other shell.

**Comment by rdw20170120** [comment]
I need to be able to activate a Python virtual environment.  I want to switch to Elvish as the shell for my monorepo-based project.  I have already abandoned Bash, Fish, and Xonsh for this.  But the lack of a `source` command or similar in Elvish seems to be a showstopper.  It appears that I cannot use Elvish, even though I like its syntax and philosophy best.  Am I missing something?  MUST Elvish be configured in `rc.elv`, or not at all?  I need to be able to configure the current shell using a script that resides in my project source repository.

**Comment by href** [comment]
There's more knowledgeable people that are better equipped to give you a useful answer, but you probably could just store your project-specific code in a module in each project (say `project.elv`) and import it:

```elvish
$ echo 'fn foo { echo bar }' > project.elv
$ use ./project
$ project:foo
bar
```

The only thing to keep in mind: Modules are cached by their absolute path and re-importing won't change anything. It's probably useful to read the docs about modules to learn more: https://elv.sh/ref/language.html#modules

**Comment by rdw20170120** [comment]
@href, thank you for your suggestion.

I very much need ALL my code to reside in my source repository, and I MUST NOT pollute the user's personal account configuration.  These are design constraints of my solution.  However, my Elvish code would be far too much to put in just one file.  While attempting to use Fish over the last few months, I already wrote literally dozens and dozens of source files spread across many directories.  My legacy implementation in Bash likewise has about a dozen files filled with function definitions.

The Fish approach is manageable at least in part because it has the `fish_function_path` upon which I can include the relevant directories containing my source.  I wish that Elvish had something similar.  I think that I can make `use` work, except for the restriction that modules have to either live in `~/.config/elvish/lib` or they must be referenced with relative paths (very labor-intensive and fragile).

What made this particularly difficult is that the language reference (to which you linked above) tells us almost nothing about modules.  It mentions a "module spec", but never defines it.  I looked through numerous sample scripts, only to find that modules can be referenced within GitHub, or in the default location, or with a relative path, but the syntax and semantics are very muddy (to an outsider like me) among them.

May I please say that modules are an absolutely crucial part of any significant use of Elvish, and yet they have very light treatment in the documentation and lack real-world examples.

**Comment by rdw20170120** [comment]
@krader1961 has rightly suggested that [I open a new issue for my various questions](https://github.com/elves/elvish/issues/1401).
