### ISSUE TITLE
Allow empty array slice at the end of an array

### ISSUE THREAD

**Issue by hanche** [elves/elvish#586]
The title together with this example may be sufficient to explain the issue:

    x = [a b c]
    put $x[3:]

Currently, this throws an exception (index out of range). I think it should produce an empty list instead. Ditto for the equivalent `$x[3:3]`, but `$x[4:]` should still be disallowed.

An obvious workaround involves the use of `builtin:drop` instead of a slice: `[(drop 3 $x)]`.

**Comment by xiaq** [comment]
Good point; I imagine this is more useful when the low index is generated programmatically to drop the first `$n` elements.

FYI, this behavior is also [allowed by Go](https://golang.org/ref/spec#Slice_expressions).

**Comment by xiaq** [comment]
Fixed in 24d1eac385765d451fdcaa91577b980dc5d909af; the commit message was unfortunately not accurate.
