### ISSUE TITLE
Feature proposal: allow options when loading modules

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#599]
It would be nice to have a way to pass data when loading a module with the `use` command. To keep in line with existing conventions, it could be passed as options, for example:
```
use &foo=bar &baz=boo module
```
I think the best way to handle this would be to set `module:foo=bar` and `module:baz=boo` before executing the module code. This would be a good way to set default values for module variables which can be used at load time.

Alternatively, the options could be stored in a special map that can be accessed by the module.

**Comment by hanche** [comment]
A better alternative may be to provide a way to preconfigure a module before it is loaded. There may be many users of the module, and you may not know which one will use it first, causing it to be loaded. It seems wrong to burden all potential users of the module to know how it should be configured. (I have no good suggestion for a mechanism.)

**Comment by zzamboni** [comment]
@hanche do you mean multiple modules/functions using the same module from within the same Elvish session, and trying to configure it it conflicting ways? I think this could be a problem, but it's no different than the current mechanism of assigning values to module variables. I just did a quick test and, despite the lexical scoping, it seems that if two modules load the same module, the variables in the loaded module are shared, and changes on one side are visible from the other - @xiaq care to comment about this?

**Comment by hanche** [comment]
@zzamboni What you describe is what I expected. However, assigning to a module variable is at least very explicit, and has the same effect always. But it is disconcerting to not know whether the options you give to the `use` call will be honoured or not – depending on whether the module was already loaded or not. I think the potential for confusion is less with my suggestion.

**Comment by xiaq** [comment]
I am not in favor of the proposal. If `use` supports arbitrary options and reinterprets them as variable assignments, we are making it impossible for the `use` command itself to accept any options in future.

I believe that declaring a `setup` function (or `init`, although I slightly prefer `setup`) in the module and calling it on the use site is good enough.

**Comment by zzamboni** [comment]
Fair enough :)
