### ISSUE TITLE
Redirecting input of value-consuming functions to a file makes it not return

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#600]
```
~> cat in.txt
abc
123
lorem
456
~> each [line]{ echo $line } < in.txt
abc
123
lorem
456
("each" does not return)
```

**Comment by scurest** [comment]
Same thing for `count`.

It appears to get blocked forever waiting for the channel band of its input port, which is a `BlackholeChan`.

https://github.com/elves/elvish/blob/7969c6650fd917d981034610ffa1749c16bf5db7/eval/compile_op.go#L525-L528

Maybe the channel should depend on what kind of redir it is (`ClosedChan` for read redirs?).

**Comment by xiaq** [comment]
Aha. That is very correct.

**Comment by scurest** [comment]
This will crash on

    put A > a.txt

now because elvish writes to a closed channel ;) I think the channel needs to be picked based on what kind of redir it is: `ClosedChan` for reads, `BlackholeChan` for writes and appends(?), ??? for read-writes.

**Comment by ShalokShalom** [comment]
This can be corrected in the documentation: https://elv.sh/learn/effective-elvish.html#mixing-bytes-and-values

![Screenshot_20210328_235324](https://user-images.githubusercontent.com/6344099/112769357-ddd4dc00-9020-11eb-9e9a-904d470e56b0.png)
