### ISSUE TITLE
Don't record empty commands in history

### ISSUE THREAD

**Issue by hanche** [elves/elvish#603]
Sometimes, my twitchy fingers enter an empty commands. Then, when I just want to run the previous command, I hit up-arrow return and inadvertenly run the empty command again, which is annoying. So I think the history mechanism should discard empty commands.

**Comment by notramo** [comment]
I worked around this with readline bindings:
```elvish
fn is_readline_empty { 
  # Readline buffer contains only whitespace.
  re:match '^\s*$' $edit:current-command 
} 

edit:insert:binding[Enter]   = { 
  if (is_readline_empty) { 
    # If I hit Enter with an empty readline, it launches fzf with command history
    edit:current-command = ' fuzzy_history_search'
    edit:smart-enter 
    # But you can do other things, e.g. ignore the keypress, or delete the unneeded whitespace from readline buffer
  } else {
    # If readline buffer contains non-whitespace character, accept the command. 
    edit:smart-enter 
  } 
} 
```
Also, there is #554 opened, when it will be implemented, you can automate (e.g. with `edit:before-readline` deletion of these items.
