### ISSUE TITLE
Unterminated single-quoted strings do not emit errors or properly slice

### ISSUE THREAD

**Issue by wu4** [elves/elvish#61]
Observe:

	~> put `working string`
	▶ `working string`

That works. However, if you don't end the string:

	~> put `cut-off string
	▶ `cut-off strin`

Compare with double-quoted strings, which error on the same input:

	~> put "cut-off string
	<tty 5>:1:5: parsing error: invalid syntax
	put "cut-off string
	    ^

That's not where it ends. It gets worse:

	~> put `
	panic: runtime error: slice bounds out of range [recovered]
	    panic: runtime error: slice bounds out of range

	elvish/errutil.Catch(0xc82005fbb8)
	    elvish/errutil/exception.go:23 +0xe0
	elvish/parse.unquote(0x5, 0x4, 0xc82000b5c4, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0)
	    elvish/parse/parse.go:335 +0x153
	elvish/parse.(*Parser).primary(0xc82005fbe0, 0xc8201da5e0)
	    elvish/parse/parse.go:385 +0x247

	...

**Comment by xiaq** [comment]
Seems the parser has some holes... Will look into it.

**Comment by xiaq** [comment]
This is fixed by the new parser. Also, the syntax for single-quoted strings now use `'` instead of `` ` `` .
