### ISSUE TITLE
Support dynamic generation of the interactive namespace in rc.elv

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#613]
Right now `rc.elv` runs in the same namespace as the namespace the interactive session runs in (the "interactive namespace"). That makes it difficult to do some things like generating aliases, before namespaces in Elvish are very much static. This is how we can address that:

If `rc.elv` contains a special variable called, say `$-exports-`, its content is poured into the interactive namespace after `rc.elv` finishes running. For example if `rc.elv` contains:

```elvish
-exports- = [&]
range 10 | each [x]{ -exports-[$x] = $x }
```

Then in the interactive session you have variables `$0` through `$9`.

The names defined in `$-exports-` are brought into the interactive namespace in addition to the `rc.elv` namespace itself, with the latter taking precedence in case of a conflict. For instance if `rc.elv` contains

```elvish
x = foo
y = bar
-exports- = [&x=foo2 z=lorem]
```

Then in the interactive namespace, you have x=foo, y=bar and z=lorem.

**Comment by zzamboni** [comment]
I have updated https://github.com/zzamboni/elvish-modules/blob/master/alias.org to work with this new implementation of `-exports-`.
