### ISSUE TITLE
Octal numbers with `0o`

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#614]

**Comment by krader1961** [comment]
This appears to be resolved by virtue of enhancements by the [Go 1.13 language runtime](https://www.infoworld.com/article/3408740/golang-113-adds-number-literal-prefixes.html):

```
[~]─> float64 0o17
▶ (float64 15)
[~]─> == 0o17 (float64 0o17)
▶ $true
[~]─> == 15 (float64 0o17)
▶ $true
[~]─> == 0b1111 (float64 0o17)
▶ $true
[~]─> == 0b11110 (float64 0o17)
▶ $false
[~]─> == 0b1111 (float64 15)
▶ $true
[~]─> == 0b1111 0o17
▶ $true
```

Obviously this has potential problems given the use of the Go `float64` type for numeric values. Nonetheless, despite the above concerns, it seems like documenting support for `0o` and `Ob` number prefixes should be sufficient to close this issue.
