### ISSUE TITLE
Sourced files cannot access module-level variables

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#621]
A file `-source`'d from within a function can access function variables (including arguments) but not module variables.

```
[~/.elvish]─> cat lib/test.elv 
modvar = a

fn test [arg]{
  echo "echo arg=$arg" > /tmp/sourced0.elv
  -source /tmp/sourced0.elv
  fnvar = b
  echo "echo fnvar=$fnvar" > /tmp/sourced1.elv
  -source /tmp/sourced1.elv
  echo "echo modvar=$modvar" > /tmp/sourced2.elv
  -source /tmp/sourced2.elv
}
[~/.elvish]─> use test
[~/.elvish]─> test:test argval
arg=argval
fnvar=b
Exception: Compilation error: variable $modvar not found
/tmp/sourced2.elv, line 1: echo modvar=$modvar
Traceback:
  /Users/taazadi1/.elvish/lib/test.elv, line 10:
      -source /tmp/sourced2.elv
  [tty], line 1:
    test:test argval
```

**Comment by krader1961** [comment]
Since the experimental `-source` command has been removed this would seem to no longer be an issue. :smile:

**Comment by krader1961** [comment]
My previous comment should have said the `-source` command was deprecated by commit ff7c5005 rather than removed. Nonetheless, it seems like this is now a non-issue.

Of course replacing the `-source` command with `eval` causes all three uses to fail to compile. Since you can't use `eval`'s `&ns` option to refer to the namespace being constructed by `use test` there is no way for any of the equivalent eval statements (e.g., `eval (slurp /tmp/sourced0.elv)`) to work.

**Comment by zzamboni** [comment]
@rdw20170120 as has been mentioned in other issues where you commented, Elvish has all the necessary mechanisms for doing this:

- Querying ([`has-env`](https://elv.sh/ref/builtin.html#has-env), [`get-env`](https://elv.sh/ref/builtin.html#get-env)) and manipulating ([`set-env`](https://elv.sh/ref/builtin.html#set-env), [`unset-env`](https://elv.sh/ref/builtin.html#unset-env)) environment variables.
- Dynamically adding functions to the interactive environment: [`edit:add-var`](https://elv.sh/ref/edit.html#editadd-var).
- [Hooks](https://elv.sh/ref/edit.html#hooks) which you can set in the interactive environment to check and trigger actions based on certain conditions (e.g. upon entering a given directory). Note: [`direnv`](https://direnv.net/) helps with this, and already has Elvish support.

**Comment by rdw20170120** [comment]
@zzamboni, thank you for your comments!  This is perhaps the most important insight that I have received, despite all the documentation and issues that I have read here.  I think that Elvish desperately needs real-world tutorials that incorporate crucial bits of information like this.  In my research, I did find proposals and discussion of functionality like `has-env`, but I found nothing that seemed to document and demonstrate its actual use in the Elvish language.

By the way, allow me please to say that I have looked through your published Elvish code, and I found that to be the secret to solving my most basic issues late last night.  You are a gentleman and a scholar, Sir!  Bravo!

**Comment by rdw20170120** [comment]
Yes, @zzamboni, I am working on joining the community as you suggest.  I have installed Weechat, but now I have to figure out all the steps to get it working...  :)  Meanwhile, questions were burning!

**Comment by rdw20170120** [comment]
@krader1961 has rightly suggested that [I open a new issue for my various questions](https://github.com/elves/elvish/issues/1401).

**Comment by krader1961** [comment]
@zzamboni and @xiaq: It seems to me this should be closed since the `source` command has been removed. In as much as the problem described in the original comment still exists it should probably be reframed in a new issue in terms of the current Elvish capabilities.
