### ISSUE TITLE
epm:upgrade crashes if something in libs is not a git repo

### ISSUE THREAD

**Issue by dcu** [elves/elvish#626]
should be handled gracefully

**Comment by zzamboni** [comment]
Can you give more details? I have directories under `~/.elvish/lib` which are not git repos and it works fine.

**Comment by dcu** [comment]
my dir looks like `github.com/dcu/something` but it's not a git repo yet

**Comment by zzamboni** [comment]
Got it - I had never seen the error because my `~/.elvish` is a git repo in itself, so any subdirectories which are not are considered as part of the top-level repo and I never see an error. I'm working on a fix.

**Comment by zzamboni** [comment]
@dcu I've submitted #628 which fixed this problem. While it gets merged, you can grab the fixed `epm.elv` from https://gist.github.com/zzamboni/8d9fbdc4f8aad9e4ae181752b1f6964c and put it by hand in `~/.elvish/lib/` to use it instead of the bundled module.
