### ISSUE TITLE
Pressing ctrl n 2 times crashes the shell

### ISSUE THREAD

**Issue by dcu** [elves/elvish#627]
```runtime error: invalid memory address or nil pointer dereference```

**Comment by xiaq** [comment]
Good catch.

**Comment by Gwimm** [comment]
It's still happening.

**Comment by elihunter173** [comment]
Can confirm as v0.12

**Comment by chengxuncc** [comment]
won't fix?

**Comment by SolitudeSF** [comment]
its already fixed in `cliedit` branch.

**Comment by xiaq** [comment]
Fixed.
