### ISSUE TITLE
String interpolation with commands

### ISSUE THREAD

**Issue by renannprado** [elves/elvish#632]
I couldn't find the documentation on how to do the equivalent to `echo "test $(lsb_release -cs)"` from bash in elvish. 

edit: sorry I already found in https://elvish.io/learn/fundamentals.html
though I believe that such examples should be in https://elvish.io/ref/language.html#string as well.

**Comment by xiaq** [comment]
Thanks for the feedback. This is documented in the [section](https://elvish.io/ref/language.html#compound-expression-and-braced-lists) on compound expressions, and the section on double-quoted string now links to it.
