### ISSUE TITLE
take hangs on redirected stdin

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#634]
```
> cat file
foo
bar
```
The following works as expected:
```
> cat file | take 1
▶ foo
```
But the following hangs - I have to close the terminal:
```
> take 1 < file
▶ foo
^D
^C
^X
```

`drop` suffers from the same problem.

**Comment by zzamboni** [comment]
Maybe related to #600?

**Comment by xiaq** [comment]
I gave #600 the correct title and am closing this as a duplicate.
