### ISSUE TITLE
Wrong syntax highlighting on double-colon builtins

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#639]
Not sure how long this has happened, but I just realized that some builtins are being highlighted as non-existing command (it runs OK). It seems to apply to functions which have two colons in their name:
![image](https://user-images.githubusercontent.com/32876/37505613-0f3e6a54-28e6-11e8-91d4-0db5b33c04f7.png)

**Comment by xiaq** [comment]
Fixed!
