### ISSUE TITLE
edit:abbr[] with regex

### ISSUE THREAD

**Issue by notramo** [elves/elvish#646]
If it would work with regular expressions instead of strings, it would be more flexible.
For example, a temporary workaround for #605 can be this:
(it changes the `~` only at the start of the line to the full path of the home directory)
```elvish
edit:abbr['^~'] = '/home/username/'
```

**Comment by krader1961** [comment]
I recommend rejecting this proposal for several reasons. Starting with the computational cost. The proposal is also not compatible with the editor (e.g., emacs or vim) abbreviation model that this feature is intended to mimic. Finally, the ambiguity of allowing arbitrary regexps means the behavior will be confusing. What would this do:

```
edit:abbr['x.*y'] = 'you are dead'
```

Presumably it would replace everything between the `x` and `y` chars, inclusive. I fail to see how that is useful.

**Comment by krader1961** [comment]
FWIW, The work I'm doing to change the behavior of abbreviations, in the context of issue #947, might address this request without the cost of evaluating a bunch of regex every time a character is typed.

**Comment by xiaq** [comment]
Revisiting this, I also feel this should be rejected (also given that #605 has now been fixed). Closing.
