### ISSUE TITLE
Unable to accept and (re)start completion in one binding command

### ISSUE THREAD

**Issue by notramo** [elves/elvish#647]
Example use case:  
I have designed a custom keybinding schema for path completion that is more efficient and faster than the current, or `bash`/`fish`/`zsh`.  
This requires restarting the completion mode from the same function that calls `edit:completion:accept`. This is currently not possible. So this code only accepts the candidate when executed in one chunk:
```elvish
edit:completion:accept; edit:completion:start
```

**Comment by xiaq** [comment]
I actually used to have a similar keybinding at one time. Interesting that it no longer works.

**Comment by xiaq** [comment]
This now works in HEAD again. Try the following:

```elvish
edit:completion:binding[Ctrl-X] = { edit:completion:accept; edit:completion:start }
```

And then do `ls ./`, Tab, select a directory with at least one file in it, press Ctrl-X. This will accept the directory and continue to complete filenames in it.
