### ISSUE TITLE
RFC: allow before-cd to modify target directory

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#653]
I started playing with cd hooks, and I can tell it will simplify a lot the code for my [dir](https://github.com/zzamboni/elvish-modules/blob/master/dir.org) module.

I was thinking it might be nice if `before-chdir` hooks had the possibility of modifying the target directory. This would make it trivial to implement things like `cd -` support, directory aliases, etc., without having to write wrappers for the `cd` command. The semantics could be discussed, but something like this could work: if any of the `before-chdir` hooks return any values, use the last returned value as the new target directory, otherwise use the original argument.

What do you think?

**Comment by xiaq** [comment]
No. These hooks are global, meaning that if you are able to modify the directory in a `before-chdir` hook you can impact how `cd` behaves in every module. It can break code like:

```elvish
cd $dir # what if $dir is "-"?
```

Use a wrapper for `cd`. Wrappers are functions, and functions are lexically scoped. You will not change the behavior of `cd` for everyone else.

**Comment by zzamboni** [comment]
Fair enough, and good reasoning.
