### ISSUE TITLE
'each' with multiple arguments

### ISSUE THREAD

**Issue by notramo** [elves/elvish#660]
The `each` builtin command should accept multiple arguments.
```elvish
cat words.txt| each [i j k]{ put $i" "$j" "$k }

**Comment by xiaq** [comment]
You are looking for [eawk](https://elvish.io/ref/builtin.html#eawk).

Conflating `each` and `eawk` is problematic as they behave differently with unary functions. When `eawk` gets a unary function, it does field splitting and makes sure that there is only one field, while `each` only accepts unary functions and does not field splitting.

It is also not clear how `eawk` should behave when given value inputs.

So overall, what you are looking for is `eawk` and it is different thing from `each`; there is no reason for merging these two things.
