### ISSUE TITLE
Problem with array slicing syntax

### ISSUE THREAD

**Issue by notramo** [elves/elvish#669]
Can't use variable names as the starting index of the slice when using a slice of a list. The shell interprets it as if it would be a namespace:
```elvish
i = 2
put [ a b c d e ][$i:5]
```
It should output `▶ [c d e]`, but it gives a compilation error that variable `5` is not found in the `$i` namespace.
What do you think about using `..` (used in many languages e.g. Ruby, Crystal, Perl6) instead of `:` for slices?

**Comment by zzamboni** [comment]
You can wrap the variable in curly braces, like this:

```
put [ a b c d e ][{$i}:5]
▶ [c d e]
```

**Comment by notramo** [comment]
@zzamboni Another solution is `[ a b c d e ][(put $i):5]`. But both are ugly and harder to read.

**Comment by xiaq** [comment]
Aha. Good point. Let's use `..`.

**Comment by xiaq** [comment]
Planning to address this before 0.15.

**Comment by krader1961** [comment]
If someone were to tackle this is the intent is to support `:` and `..` with `:` marked as deprecated in the documentation?

**Comment by xiaq** [comment]
Yes, and use of `:` for slices should emit a warning.
