### ISSUE TITLE
Candidate list filtering

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#67]
When doing tab completion, fish allows you to press Space to filter the candidate list. Elvish should also support this, but I don't like the choice of Space. I also prefer subsequence matching over substring matching (which is used by fish).

**Comment by bpinto** [comment]
Have you considered using [fzf](https://github.com/junegunn/fzf)?

As it's also written in Go, I can imagine lots of places where we could use it, for instance, instead of implementing a ranger-like navigation.

**Comment by xiaq** [comment]
@bpinto Thank you for the pointer! fzf looks very cool. Give me some time to play with it and think about whether and how it can be integrated.
