### ISSUE TITLE
Navigation mode?

### ISSUE THREAD

**Issue by techtonik** [elves/elvish#670]
This page https://elvish.io/ref/philosophy.html references `ranger` navigation mode, but.. I can't find about it. Ctrl+N in `ranger` just creates new tab.

**Comment by SolitudeSF** [comment]
press `ctrl+n` in shell

> For instance, the “navigation mode”, summoned by Ctrl-N, **mimics** Ranger

**Comment by techtonik** [comment]
I don't have access to `elvish` right now. I just wanted to know what is this Ctrl-N by reading docs.

**Comment by zzamboni** [comment]
You can see a more detailed description of Navigation Mode here: https://elvish.io/learn/cookbook.html - search for the paragraph that starts with "Press Ctrl-N".
