### ISSUE TITLE
Start filtering immediately after entering completion mode

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#678]
Right now, if you type something when in completion mode, the behavior is to accept the current selection and insert the character you typed. If you use ^F to start filtering (indicated by the cursor being next to the modeline), the behavior changes to filtering the candidates.

Starting in the filter mode is likely more useful.

**Comment by zzamboni** [comment]
This is doable by binding Tab to both start completion mode and filter mode. I do exactly this, you can see the code here: https://github.com/zzamboni/dot-elvish/blob/master/rc.elv#L53

**Comment by zzamboni** [comment]
@xiaq duh, i hasn't realized it was you who posted this (replied from my email), thought it was someone asking how to do it :) Sorry about that
