### ISSUE TITLE
Command ID inconsistency

### ISSUE THREAD

**Issue by notramo** [elves/elvish#679]
I have read the commit message in 89bc1e5.
The id given by `edit:command-history` isn't correct.

```elvish
store:del-cmd 0
story:del-cmd 0
```
Does this code work and remove the first 2 commands from history?

**Comment by xiaq** [comment]
No; the IDs are known to inconsistent.

**Comment by xiaq** [comment]
The IDs are now consistent.

Note that the sequence number of commands start at 1, and they do not change after deleting commands; so `store:del-cmd 1` will delete the first command, and it will leave a hole; the command history will now start at 2.
