### ISSUE TITLE
Suppress "finished" message from a backgrounded job

### ISSUE THREAD

**Issue by iwoloschin** [elves/elvish#683]
Is there any way to suppress the `job ... finished` message after a backgrounded job completes?

**Comment by xiaq** [comment]
Here is some guidance for whoever is interested in implementing this feature :)

The code that writes the message is here:
 https://github.com/elves/elvish/blob/c5ccdcdab4f7f9503615bef81c961f3484873088/eval/compile_op.go#L137-L147

To control the behavior you will want to add a new field to the `Evaler` type, and add a builtin variable for controlling the behavior. Adding a builtin variable is as simple as:

https://github.com/elves/elvish/blob/c5ccdcdab4f7f9503615bef81c961f3484873088/eval/eval.go#L88

You can find the definition of `Evaler` in that same file.
