### ISSUE TITLE
eawk hangs when run from a regular file

### ISSUE THREAD

**Issue by hanche** [elves/elvish#690]
This is adapted from an example given in the documentation (⬥ is my prompt):

    ⬥ cat foo
     lorem ipsum
       1 2
    ⬥ cat foo | eawk [_ a b]{ put $a }
    ▶ lorem
    ▶ 1
    ⬥ eawk [_ a b]{ put $a } < foo
    ▶ lorem
    ▶ 1
    ^C

When run with input from a regular file, `eawk` hangs and must be killed.

This happens with 0.11 and HEAD on macOS, and 0.11 on linux (I haven't tried HEAD on linux).

**Comment by notramo** [comment]
Also happens with HEAD on Linux.

**Comment by xiaq** [comment]
This is a dup of #600.
