### ISSUE TITLE
Add documentation about making Elvish the login shell

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#694]
Citing https://github.com/elves/elvish.io/issues/9

@marcdel:

> It wasn't obvious to me how to change my default shell to elvish. It might be helpful to have this information in the docs somewhere. I'd be happy to submit a PR, but I'm not sure where the best place for this would be.

> For reference, what worked for me was: `echo $(which elvish) | sudo tee -a /etc/shells && chsh -s $(which elvish)`.

@zzamboni:

> @marcdel the instructions should be split in two steps: add the new shell to /etc/shells (which should be done only once), and then use chsh to change the shell of any users.

**Comment by xiaq** [comment]
My comment: I am not quite sure about the consequences of making Elvish the login shell. I personally have refrained from doing so, so we want to suggest an alternative - making Elvish the default command of the terminal emulator or `tmux`. We can still have instructions on how to make Elvish the login shell, with "dangers ahead" attached though.

**Comment by zzamboni** [comment]
Fully agree - I also don't make Elvish my login shell, but the default
command in Terminal.app.

**Comment by iwoloschin** [comment]
I've found that having elvish exec'd from ~/.bashrc works well, just put this as the last line in ~/.bashrc:

```bash
[ -x /usr/bin/elvish ] && SHELL=/usr/bin/elvish exec /usr/bin/elvish
```

This is suggested by a number of Linux distributions for use with fish, I think I originally copied it from the Arch wiki.

**Comment by kwshi** [comment]
By the way, I have elvish set directly as my default login shell.  I've been going for almost a month now, and there aren't any big issues (yet).

There's still the issue with having no `rc.elv` equivalent for non-interactive sessions (#718), and so my `$E:PATH` is a little bit off for some things.  It has not been unbearable.

**Comment by tunnel49** [comment]
Thanks @iwoloschin I modified this slightly in case I actually need to start bash from elvish some times.
> ```shell
> [ -x /usr/bin/elvish ] && shopt -q login_shell && SHELL=/usr/bin/elvish exec /usr/bin/elvish
> ```

**Comment by krader1961** [comment]
FWIW, This issue has been, more or less, addressed by changes that resulted in https://elv.sh/get/#using-elvish-as-your-default-shell. However, I would argue that is the wrong place to put that information. That information should probably be moved to the FAQ. With links from the https://elv.sh/get/  https://elv.sh/ref/command.html pages to that FAQ entry.
