### ISSUE TITLE
Collaboration with Oh project?

### ISSUE THREAD

**Issue by notramo** [elves/elvish#713]
The [`oh`](https://github.com/michaelmacinnis/oh) shell is another modern shell written in Go, which also has very good ideas.
Both projects (`elvish` and `oh`) has similar (but not the same) ideas and aims, and are lacking developers.
What do you think about merging the ideas from one shell to the other, and developing it together with @michaelmacinnis?
(I also opened an issue in the `oh` repo: https://github.com/michaelmacinnis/oh/issues/29)

**Comment by SolitudeSF** [comment]
how would that collaboration look like? both shells seem very different in the language features.

**Comment by xiaq** [comment]
Thanks @notramo.

As discussed in https://github.com/michaelmacinnis/oh/issues/29, although we don't see the efforts on Oh and Elvish merging any time soon, we are not ruling out collaborations. I did try to sell Elvish's upcoming line editor as a basis for building Oh's line editor, not sure how that will go :)
