### ISSUE TITLE
nested if commands need an explicit ^D to execute

### ISSUE THREAD

**Issue by frantic1048** [elves/elvish#714]
I'm writing shortcuts for my git command. And I encountered a strange behavior of elvish.

Code sample:

```elvish
fn g [@args]{
  if (eq (count $args) 0) { e:git status -s; return }

  op @rest = $@args
  if (eq $op 'b') {
    if (eq (count $@rest) 0) {
      e:git for-each-ref --sort=committerdate 'refs/heads/' --format="%(HEAD) %(refname:short)"
    } else {
      e:git branch $@rest
    }
    return
  }
}
```

Expected Behavior:

- `g`<kbd>ENTER</kbd>: executes `e:git status -s`
- `g b --help`<kbd>ENTER</kbd>: executes `e:git branch --help`
- `g b`<kbd>ENTER</kbd>: executes ` e:git for-each-ref --sort=committerdate 'refs ...`
- `g b | rg fixabc`<kbd>ENTER</kbd>: executes `e:git for-each-ref --sort=committerdate 'refs ... | rg fixabc`

Actual Behavior:

- `g`<kbd>ENTER</kbd>: executes `e:git status -s`
- `g b --help`<kbd>ENTER</kbd>: executes `e:git branch --help`
- `g b`<kbd>ENTER</kbd><kbd>^D</kbd>: executes ` e:git for-each-ref --sort=committerdate 'refs ...`
- `g b | rg fixabc`<kbd>ENTER</kbd><kbd>^D</kbd>: executes `e:git for-each-ref --sort=committerdate 'refs ... | rg fixabc`

Difference: the last two commands need an extra <kbd>^D</kbd> to execute.

Is this behavior a feature? How can I avoid the <kbd>^D</kbd> to directly execute my `g b` command after pressing <kbd>ENTER</kbd> ?

**Comment by xiaq** [comment]
Use `count $rest` instead of `count $@rest`.

The `count` command takes either 0 or 1 arguments. In the former case, it waits for user input.

**Comment by frantic1048** [comment]
Thanks a lot, I did not notice the `@`...
