### ISSUE TITLE
rc.elv not run for non-interactive scripts?

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#718]
My window manager (`bspwm`) has an autostart script (`bspwmrc`) that is written in any shell language of my choosing.  I have chosen to write it in elvish.  In my `rc.elv`, I have configured `$E:PATH` and so on to include custom path directories; yet these changes are not reflected in the `bspwmrc` script running in Elvish.

This leads me to believe that `rc.elv` is not executed for "raw" scripts, i.e. ones launched through `#!/bin/elvish`.  With a little bit of fiddling, I find that this is indeed the case; non-interactive elvish scripts indeed do not execute `rc.elv`.

Is this actually desirable behavior?  Several of my scripts rely on the `$E:PATH` configured in my `rc.elv`.  I understand there are some advantages to restricting `rc.elv` to interactive sessions; perhaps we could consider having another script, such as `profile.elv` or something like that, that is always run at the start of any script?

**Comment by krader1961** [comment]
FWIW, I am not a fan of the legacy POSIX shells like ksh, bash, zsh with regard to their myriad of per user startup scripts; e.g., *~/.login*, *~/.profile*, *~/.kshrc*, etcetera. I prefer the [`fish` shell](http://fishshell.com/) approach of having a single per user startup script: *~/.config/fish/config.sh*. If you need to predicate some initializations on being interactive or not you explicitly do so via `if status is-interactive`.  My vote is for a similar mechanism in Elvish.

The problem you ran into, @kwshi, has been noted by others. I could swear I've seen more than one issue mentioning this the only one I can readily find is #316. Probably the other discussions of this problem have been on Gitter. This is really a duplicate of #316.

**Comment by kwshi** [comment]
Oops.  I'll close this so it can be tracked on #316.
