### ISSUE TITLE
Make most readline-bindings default behavior?

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#720]
This is a suggestion, not a bug.

So I've noticed two things about the `readline-binding` module.

1. There are several redundant overlaps in the `readline-binding.elv` and the `binding.elv` source.  A few example are `Alt-f` and `Alt-b`, which, in both files, map to the same thing (`move-dot-left-word`, `move-dot-right-word`, respectively).
2. Several of the non-redundant bindings in `readline-binding.elv`, such as `Ctrl-a` and `Ctrl-e`, are in fact unused in the default `binding.elv` source.

Considering that (1) we are already willingly adopting some readline-like behavior as the default, and (2) that some other good, common readline-like behavior can also be used as the default without disrupting existing behavior, why not incorporate as much of `readline-binding.elv` into `binding.elv` as we can, keeping only the conflicting bindings in `readline-binding.elv`.

I think this would be desirable as it would offer some more-sane defaults to newcomers well-accustomed to said bindings (e.g. `Ctrl-a`, `Ctrl-e`), and also because it would not disrupt the status-quo experience (since these unused bindings are, after all, unused anyway).  Plus, it would be a nice way to consolidate and clean-up the keybinding code a little bit and get rid of some redundancies, and some unnecessary ambiguity down the road.

**Comment by xiaq** [comment]
Probably not; I would like to reserve some keys for future features.

The default binding has the property that no functionality is bound to two different keys. For instance, move-dot-sol is already bound to Home, so binding ^A to that is not necessary. The readline binding, as I understand it, tries to accommodate setups where function keys are not usable (keyboards lacking function keys or terminals not supporting them). I don't think that is still common today. Dedicating four Ctrl- keys to cursor movements used to be necessary but I find that a waste of precious key binding space when the vast majority of users have access to arrow keys.

Some keys in the default binding, notably ^L and ^N, already conflicts with readline bindings, so readline users would likely already be surprised.

**Comment by kwshi** [comment]
That's fair.

It seems, though, that the default binding does bind `Alt-f` and `Ctrl-Left` both to `move-dot-left-word`, so the uniqueness property doesn't seem to exactly hold.  Perhaps at some point it's worth revisiting the default bindings, purely for the sake of organization?  Also, then, there is still the fact that `readline-binding` performs some redundant bindings on top the default bindings, and the question of whether one should actually do anything about them.

**Comment by xiaq** [comment]
The exception of `Alt-f` and `Alt-b` is actually kind of... disingenuous. It is there because macOS's Terminal.app maps Alt-Left to Alt-b and Alt-Right to Alt-f (and does not support Ctrl-Left and Ctrl-Right).

I am actually not sure as to how to handle this well. Maybe they should just be removed and it's not Elvish's problem that Terminal.app is broken.

**Comment by xiaq** [comment]
I filed #729 for this.
