### ISSUE TITLE
vi-style insertion

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#728]
Currently, the default readline bindings add emacs-like keybindings to insertion mode, *a la* bash.

Bash readline also allows configuration to make the insertion vi-like, with something like `set -o vi` in the readline config.  (https://www.gnu.org/software/bash/manual/html_node/Readline-vi-Mode.html)

Perhaps we would like that in elvish at some point and allow it to be enabled somehow via the init script?

**Comment by kwshi** [comment]
Oh, okay.  Never mind me.

**Comment by xiaq** [comment]
You don't need to run `binding:install` (it is called by default when the editor is loaded), the last line is sufficient.

The command mode is actually quite incomplete. In particular, it doesn't support any two-letter commands like `dw`.

**Comment by mmlb** [comment]
Is there a way to integrate https://github.com/ardagnir/athame here? Its frustrating to have `vi` bindings when I'd say most people use `vim` and more powerful actions are the norm.
