### ISSUE TITLE
Fix race conditions found with "test -race" and use it in CI

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#73]
Elvish is not thread safe yet.

**Comment by xiaq** [comment]
Making the evaluator thread-safe enables a very cool feature: we can load the rc file **asynchronously**.

**Comment by xiaq** [comment]
Redefined this issue to be specifically about auditng with `go test -race`. The overall topic is now tracked in a Project.

**Comment by xiaq** [comment]
Running this reveals a lot of data races in `pkg/cli` and `pkg/edit`, and surprisingly, no race condition in `pkg/eval`.

**Comment by krader1961** [comment]
I just ran the tests with race detection enabled on my macOS server and observed twelve (12) race failures. It seems to me that resolving this issue should be a high priority. Races are inherently problematic. The best outcome is the program terminates when the race occurs but it is just as likely that the results will be incorrect.

**Comment by krader1961** [comment]
> Making the evaluator thread-safe enables a very cool feature: we can load the rc file asynchronously.

I'm curious what that comment implies. Why would being able to load the *~/.elvish/rc.elv* asynchronously be useful? Once control has been handed to the interactive REPL environment or the script being run don't both of those environments require that evaluation of the *rc.elv* file be completed? What does it mean for that initialization to be done asynchronously?

Having said that I think resolving this issue should be a high priority. Arguably a blocking issue for a 0.14 release.

**Comment by xiaq** [comment]
Agree that this should be high priority.

Re sourcing rc.elv asynchronously, it can be useful if rc.elv contains commands that take time to execute. It's perhaps not a good approach, but the way how it works should be straightforward - just treat rc.elv as if code running with `&`.

**Comment by xiaq** [comment]
All race conditions found with `go test -race` have been fixed, and TravisCI is running test with `-race` on both Linux and macOS.

**Comment by krader1961** [comment]
I can confirm that on my macOS server, where I was seeing 12 race failures, I'm now seeing zero. That is fantastic and the most significant improvement I've seen in the past few months. This greatly improves my confidence that I won't observe random incorrect results, or crashes, from non-trivial elvish scripts.
