### ISSUE TITLE
Recognize Shift-Alt-arrow and Cmd-Alt-arrow on iTerm2

### ISSUE THREAD

**Issue by hanche** [elves/elvish#734]
If I hit `Shift-Alt-Up`, I get this error:

    error when reading terminal: bad CSI: "\x1b[1;10A"

similar error messages appear with the other arrow keys (with the final A replaced by B, C or D).

Something similar happens with `Command-Alt` arrow combinations (with 10 replaced by 9).

This is in iTerm2 on a Mac. I assume the resulting codes are more or less standard ones. It would be good if they were added to elvish's repertoire of recognized byte sequences, so we can bind to these keystrokes.

**Comment by hanche** [comment]
In Terminal, it seems that Alt-Shift-Up sends the same code as Alt-Up without the shift (same for the other arrows).

Could you find out what codes are sent in Hyper? Just run `od -t ax1` and press the four key combos, then end with return and Ctrl-D.

**Comment by xiaq** [comment]
Hmm. These are CSI-style escape sequences, and ABCD are the typical codes for arrow keys in such sequences:

https://github.com/elves/elvish/blob/e33828aa0f298d0acf41f5da2eb512c00aab81ff/edit/tty/reader_unix.go#L345-L371

The problem is that neither 10 nor 11 is a standard xterm-style modifier code, only 0-8 are considered valid now:

https://github.com/elves/elvish/blob/e33828aa0f298d0acf41f5da2eb512c00aab81ff/edit/tty/reader_unix.go#L472-L494

Looks like an iTerm2 invention to me. Extending the `xtermModify` should fix the problem but I wonder how widely used those codes (10 and 11) are and whether we will run into conflict in future.

**Comment by hanche** [comment]
Looks like they should have used code 4. I'll see if I can talk iTerm into doing so; but now dinner is ready.

**Comment by xiaq** [comment]
c.f. https://www.xfree86.org/4.8.0/ctlseqs.html#PC-Style%20Function%20Keys

Yes, iTerm should use code 4. But for Command-modified keys, they still have to invent some new code.

Indepent of whether iTerm is doing the correct thing, we should be able to accodomate it if no other terminal emulator uses modifier code 10 or 11.

@hanche bon appetit :)

**Comment by hanche** [comment]
It is fairly straightforward, if a bit tedious, to teach iTerm2 different escape sequences for all sorts of keystrokes with modifiers. I might ask the developer about his rationale for the current choice, however.

**Comment by xiaq** [comment]
@iwoloschin Can you confirm that you get `\x1b[1;11X` with Cmd-Alt-Arrow? Both @hanche and I are getting`\x1b[1;9X`. Maybe I should just read iTerm2's source code...

**Comment by xiaq** [comment]
@hanche iTerm2 supports customizing the sequences function keys translate to. Open Preferences, in the "Profiles" page, there is a "Keys" tab. Can you check whether the keys concerned in this issue are there?

**Comment by xiaq** [comment]
I found the code:

https://github.com/gnachman/iTerm2/blob/d8da925a3c614f0d895c2b600ef068082c0fdc2c/sources/VT100Output.m#L605-L624

**Comment by krader1961** [comment]
For me using current iTerm2 with no magic bindings [alt-cmd-right-arrow]:

```
fish_key_reader                                                      21.8  h
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.348 ms)  hex:   5B  char: [
(  0.314 ms)  hex:   31  char: 1
(  0.292 ms)  hex:   3B  char: ;
(  0.305 ms)  hex:   39  char: 9
(  0.437 ms)  hex:   43  char: C
bind \e\[1\;9C 'do something' 
```

The other variants (left, down, up) produce the same output differing only in the final letter as you would expect.

**However**, note that the [cmd] modifier has no effect.

**Comment by xiaq** [comment]
The commit that introduced these modifier codes was https://github.com/gnachman/iTerm2/commit/1779398165497a9b1c335b3188ea10d66c82de6a

**Comment by hanche** [comment]
No, the shift-meta-arrow keys weren't mentioned anywhere in my preferences. I have since added them to the global “Keys” setting in iTerm2, though.

Interesting to note that the source has `altModifierValues`, doing what might be expected, and `metaModifierValues`, doing what we observed. Perhaps it is influenced by the settings of Left/Right ⎇ Key in the Profiles tab. I have the left one set to Esc+ and the right one set to Normal, so I can have access to the full character set allowed by my keyboard, yet use the left one as a meta key. Or alt key? I am a bit confused about the difference.

**Comment by hanche** [comment]
(Whoops, hadn't read the previous two comments from @xiaq when I wrote the above.)

**Comment by xiaq** [comment]
Aha, this is not an iTerm2 invention: https://github.com/joejulian/xterm/blob/defc6dd5684a12dc8e56cb6973ef973e7a32caa3/input.c#L357-L375

**Comment by hanche** [comment]
That explains a lot. So xterm considers Alt and Meta to be different modifiers; then that makes sense.

**Comment by xiaq** [comment]
We now have an interesting question: should we simply coalesce Alt and Meta and continue to maintain a distinction?

**Comment by xiaq** [comment]
Let's start with conflating Alt and Meta. If a valid use case of distinguishing Alt and Meta arises we will change that.
