### ISSUE TITLE
Support accessing previous command outputs? (a la IPython)

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#735]
That would be a nice language feature to have, I think.  It could look something like `_` for the previous output and `_n` for the nth output, or maybe `-` and `-n` if we think that's nicer, or maybe we could have it as a builtin function, which wouldn't *quite* be as convenient but would still be nice to have.

**Comment by xiaq** [comment]
Keeping the output of all commands -- or even just the last command -- means we will consume a possibly unbound amount of memory. This is not a cost we want to incur on everyone.

Redirecting the output is also not easy: to make terminal-oriented commands (like `vi`) continue to work, you need to redirect the output to a pseudo-terminal and pass through inputs and outputs.

**Comment by xiaq** [comment]
Instead of having this as a language feature, I am more interested in having this as an editor feature. We can have a "notebook mode" (think Jupyter notebook) where the output of all commands are recorded. You can reference results from previous commands, and also save the entire session.

**Comment by notramo** [comment]
Will the backend pty of the web inteface be owned by the shell?

**Comment by xiaq** [comment]
@notramo I am not sure what you mean. This issue is not quite related to the web interface, the feature can work in the terminal.

**Comment by krader1961** [comment]
My feelings are that this feature should only be available via the web UI; if available at all. Which itself should be divorced from a normal elvish process. See issue #375 where the cost of always enabling the web UI is quite expensive. We definitely should not compound that cost by capturing arbitrary command output in, possibly long lived, interactive Elvish shells.

**Comment by xiaq** [comment]
Revisiting this, doing this will require quite a bit of pseudo-terminal machinery to be built into Elvish, and that is not something I want to put in the scope of Elvish right now. Closing.
