### ISSUE TITLE
Document `$fn-name~` syntax for referencing function variables?

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#739]
Title is self-descriptive.  When a function is declared via `fn fn-name`, it is implicitly accessible as the variable `$fn-name~`:

```
~> fn whatever { }
~> put $whatever~
▶ <closure 0xc4200c0c80>
```

Skimming through the language reference, I did not find documentation on this feature.  I only found this from skimming through the builtin `eval` Elvish codebase, and from code written by other people.  I think this would be nice to include in the language documentation.

On a related note, I do wonder: why is it we chose to define `$fn-name~` implicitly instead of simply `$fn-name`?

**Comment by zzamboni** [comment]
You are quite right - I never noticed this is not explicitly documented. This should probably be documented in the [Function definition](https://elv.sh/ref/language.html#function-definition-fn) section of the docs.

As for the naming - @xiaq can probably clarify better, but I think variables whose names end with `~` are interpreted specially, in the sense that they can be called as functions. While `~` can be used in variable names, if it appears at the end it seems that Elvish checks its value to make sure it's a lambda (although the error could probably be improved):

``
[~]─> foo~bar = hi
[~]─> put $foo~bar
▶ hi
[~]─> foo~ = hi
Exception: multiple errors: need !!<nil>, got string; need !!<nil>, got string
[tty], line 1: foo~ = hi
[~]─> foo~ = { put hi }
[~]─> foo
▶ hi
```
