### ISSUE TITLE
Allow explosion operator (@) on maps

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#743]
This would be analogous to Python's `**kwargs` sort of operator, and JS's "object rest spread" operator.  This is desirable for, say, merging two dictionaries, or for passing arguments blindly to wrapped functions in a higher-order function--example:

```Python
def wrap(fn):
  def wrapped(*args, **kwargs):
    return fn(*args, **kwargs)
```

```elvish
fn wrap [f~]{
  fn wrapped[@args, @@kwargs] { # syntax, maybe?
    f $@args $@@kwargs
  }
}
```

**Comment by xiaq** [comment]
Dup with #584.
