### ISSUE TITLE
Output shows raw ANSI sequences on Windows < 10

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#753]
We now rely on the support for ANSI output sequences on Windows, which was only added in Windows 10. We should use Windows's native console output API instead.

**Comment by SitiSchu** [comment]
Since Windows 7 is deprecated now I guess this isn't needed anymore ?

**Comment by krader1961** [comment]
I noticed you documented in commit cd1576a63 that only Windows 10 is officially supported. Does that mean this issue should be closed? Or, if not, changed from a bug to an enhancement as something we don't expect to work but would like to work if the cost of doing so was reasonable?

**Comment by xiaq** [comment]
Yes this issue can be closed now. Yay \o/
