### ISSUE TITLE
Support JSON output in -compileonly

### ISSUE THREAD

**Issue by notramo** [elves/elvish#760]
It is complicated to parse the output of the `-compileonly` flag if there are compilation errors.
I want to implement syntax checking into the Kakoune plugin: https://gitlab.com/notramo/elvish.kak
It would be better if this flag could support the `-json` flag.
It should also be able to output physical line and column number.

**Comment by xiaq** [comment]
Letting `-json -compileonly` write JSON is a brilliant idea.

LSP has a [Diagnostic](https://microsoft.github.io/language-server-protocol/specification#diagnostic) format, we should use it.
