### ISSUE TITLE
Bad output with $num-bg-jobs

### ISSUE THREAD

**Issue by iwoloschin** [elves/elvish#763]
The $num-bg-jobs variable no longer works as expected:
```
~> put $num-bg-jobs
▶ <unknown 0>
```
The number of background jobs does go up and down properly, but the "<unknown>" text breaks some tools/themes that expect just a number.  I believe it may be related to this commit https://github.com/elves/elvish/commit/fc420bad4fdc9079aab5dc7ca9d7f3f6d762045f?

**Comment by xiaq** [comment]
Thanks for reporting, I forgot about it :)
