### ISSUE TITLE
Suspending causes control to return to the parent shell on macOS

### ISSUE THREAD

**Issue by ntchambers** [elves/elvish#770]
Running macOS High Sierra with iTerm2, suspending a program with ctrl + z returns control back to the parent shell instead of elvish. I have a recording available [here](https://asciinema.org/a/1QYC7HLr3oJO1l3EWt5ArJyJB). I only recorded elvish-HEAD in the video, but elvish-12 does the same.

**Comment by SolitudeSF** [comment]
elvish doesn't have suspend functionality. so its handled by outer shell.

**Comment by ntchambers** [comment]
Ah I see. Thanks!
