### ISSUE TITLE
Expand string to call parameters

### ISSUE THREAD

**Issue by xiamaz** [elves/elvish#780]
In bash it is possible to use a string to represent separate arguments, such as:

```
foo $(echo "aaa bbb")  # Interpreted as two arguments
foo "aaa bbb" # Interpreted as one argument
```

Is there a way to enforce the first behavior in elvish? If a call returns a space delimited string, it is not directly interpreted as multiple args.

**Comment by SolitudeSF** [comment]
use list of strings, or manually split a string

**Comment by xiamaz** [comment]
Okay, thank you very much for the reply. This solves my issue!
