### ISSUE TITLE
"Capture only value stream" mode

### ISSUE THREAD

**Issue by zzamboni** [elves/elvish#784]
It would be nice to have a way to specify that an output capture `( ... )` should only capture the byte/value output from the command. For example, if I want to produce some debugging output from within a captured command, at the moment the only way to do it is to redirect the output to `/dev/tty`:
```
[~]─> foo = [(echo "hi"; put "bye")]
[~]─> put $foo
▶ [hi bye]
[~]─> foo = [(echo "hi" >/dev/tty; put "bye")]
hi
[~]─> put $foo
▶ [bye]
```
This is not ideal, as the byte output might still want to be captured by another enclosing command.

One idea: a new type of capture character, e.g. `< ... >` could signify "capture only values".

```
> foo = [<echo "hi"; put "bye">]
hi
> put $foo
▶ [bye]
```

Maybe related to #247

**Comment by xiaq** [comment]
The functionality does not need to be implemented by a new syntax, a new "only values" command would suffice. It discards byte inputs to it but passes value inputs through. You can just add it to the end of a pipeline to only preserve bytes. For examples:

```
{ echo bytes; put value } | only values
```

However, for the use case of writing debug information, it is better to output it to stderr using >&2.

**Comment by zzamboni** [comment]
Good points both of them. "only values" should ideally be complemented by "only bytes". Also, good point about `>&2` in this particular case, but the general use case I think is still valid.

**Comment by zzamboni** [comment]
Very cool - thanks!
