### ISSUE TITLE
Parsing command-line arguments, e.g. argparse

### ISSUE THREAD

**Issue by jtmoulia** [elves/elvish#795]
### Question

Is there an easy way to parse command-line flags from elvish? I have access to the args from `$args`, but I'd like a way to define positional args and long/short option flags and keyword args.

    my-script.elv positonal-arg --long-flag -f --long-option value1 -o value2

### Use-Case

My use-case is that when I'm writing an elvish script as an executable meant to be called from the command-line I'd like to be able to define an CLI for that script. Elvish's function signatures are expressive, but I can't use things like optional keyword arguments from other languages (...right?).

### Existing Implementations:

  - python [argparse](https://docs.python.org/3/library/argparse.html)
  - fish [argparse](https://fishshell.com/docs/current/commands.html#argparse)
  - go [flag](https://golang.org/pkg/flag/)

Elvish has [getopt.go](https://github.com/elves/elvish/blob/master/getopt/getopt.go) but I think that's for internal usage (?)

Btw, I'm super impressed by elvish -- trying to make it my daily shell.

**Comment by xiaq** [comment]
The getopt package is used to implement [edit:complete-getopt](
https://elv.sh/ref/edit.html#edit:complete-getopt), although it's possible to make it also usable for parsing arguments too.

While the full functionality getopt is useful - especially if you are writing a wrapper script for another program, I feel that it is too flexible and complex, and something more opinionated should be preferred to parse arguments to most scripts, which can be modeled after Go's [flag](
https://godoc.org/flag) library. So Elvish should actually have two libraries for parsing command arguments:

* A `getopt` library, for writing wrapper scripts of another program

* A `flag` library, for everything else.

**Comment by krader1961** [comment]
If you do implement a `getopt` like command it should not be modeled after the POSIX command of the same name as that is a horrible, error prone, API. When I wrote the fish [argparse](https://fishshell.com/docs/current/commands.html#argparse) I deliberately designed it to have a fish script friendly API while providing almost all the functionality of the libc `getopt_long()` function.

**Comment by seh** [comment]
Has anything materialized on the flag parsing front?

**Comment by xiaq** [comment]
Fixed in 5bf688cf4d6d487fb9122948e1775b9aaa194bb1 🎉
