### ISSUE TITLE
Command output uses unsupported sequences on Windows

### ISSUE THREAD

**Issue by capnspacehook** [elves/elvish#798]
I know that in the README it states that Windows support is experimental, but I'd thought I'd post this issue here as it doesn't seem like a hard problem to fix.

Colors work great on elvish on Windows, but whenever an exception is thrown, for example when a program is called that is outside of the PATH, the output of the exception thrown is weird: 

```
Exception: [31;1mexec: "ls": executable file not found in %PATH%[m
[tty], line 1: [1;4mls[m
```

Edit: it appears this happens not only on exceptions. I ran an example command from the Elvish website, `put lorem ipsum | count`, expecting the output to be: `2`. But instead this was my output: `▶ 27h[?2004l`. Even though the arrow shows up here on Github, it doesn't in Powershell or Command Prompt.

**Comment by xiaq** [comment]
Finally took some time to fix this after I had spent several days developing on a Windows box :)

Enjoy the Elvish experience on Windows!

**Comment by Xjs** [comment]
Something similar to this is still occuring for me on Windows using https://github.com/elves/elvish/commit/92cb80d89a6a4050033936dd8cce68a2debc811f . I used https://github.com/Xjs/elvish/commit/28fa32e00c7de50322e354b1f2327b2f1e8f4906 as a workaround for some time now, but that broke input in unbuffered programs. Any ideas on how to fix it?

Output:

```
Exception: ←[31;1mgit exited with 141←[m
[tty 7], line 1: ←[1;4mgit log←[m
```

Screenshot:

![image](https://user-images.githubusercontent.com/58270/81066074-d8d4de80-8edc-11ea-97e9-f7b4a00d08a8.png)

Screenshot with my fix:

![image](https://user-images.githubusercontent.com/58270/81066197-0883e680-8edd-11ea-8d45-09df27f707ba.png)
