### ISSUE TITLE
Make it possible for editor bindings to access the terminal

### ISSUE THREAD

**Issue by babariviere** [elves/elvish#808]
I am currently to write a binding to edit current command in an editor (for very large command like curl)

My current issue is that editor that use libraries like ncurses starts to block and/or fail to write to stdout and also cannot read from stdin.

Here is a snippet of my function + my binding:

```
fn edit-cmd [editor]{
    file = (mktemp)
    echo $edit:current-command > $file
    $editor $file
    edit:current-command = (cat $file)
}

edit:insert:binding[Alt-e] = { edit-cmd (external nano) }
```

If you could give me any hints on what needs to be changed, I would fix this issue by myself 

PS: forgive me for the title, I couldn't explain this issue clearly in just one phrase

**Comment by xiaq** [comment]
What you are requesting here is to allow commands in *bindings* to have access to the terminal.

This is harder than it sounds, as the Elvish editor needs to assume that only it has access to the terminal; as such it redirects the IO in the bindings so that they don't mess up the terminal.

**Comment by notramo** [comment]
#535

**Comment by xiaq** [comment]
Closing as a duplicate.
