### ISSUE TITLE
Add a new value $nil

### ISSUE THREAD

**Issue by hanche** [elves/elvish#810]
Since json documents can contain `null` values, elvish ought to have a corresponding value so that `from-json` and `to-json` won't lose information. Currently, `from-json` converts `null` to an empty string, while `to-json` represents an empty string as an empty string.

I suggest naming the special value `$nil`, though `$null` is another possibility. It should probably be falsy. And `is` and `eq` should be able to detect whether something is `$nil` as opposed to `$false`.

**Comment by xiaq** [comment]
Yeah, let's do that. It can also serve as a good initial value for variables when Elvish starts requiring explicit declaration of variables.

**Comment by xiaq** [comment]
Fixed in f6bdd0e079dfe79185ee2642e6995e404972191e.
