### ISSUE TITLE
(edit:command-history -1)[cmd] no longer evaluates to the command text

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#821]
There has been an unintended break in API compatibility.

**Comment by zzamboni** [comment]
@xiaq this seems to be fixed in master now - modulo the fact that `edit:command-history` no longer takes an argument, so the commands need to be extracted through indexing, which is fine but should be documented:
```
> put [(edit:command-history)][-1][cmd]
▶ 'put [(edit:command-history)][-1][cmd]'
```

**Comment by xiaq** [comment]
This is now documented in https://elv.sh/ref/edit.html#editcommand-history.
