### ISSUE TITLE
Blocks IO after using ncmpc

### ISSUE THREAD

**Issue by greenfork** [elves/elvish#822]
After I use [ncmpc](https://github.com/MusicPlayerDaemon/ncmpc) (music daemon for [mpd](https://github.com/MusicPlayerDaemon/MPD)) it launches curses client, I quit it and the IO is blocked, e.g. `cat` says

```
/usr/bin/cat: -: Resource temporarily unavailable
Exception: cat exited with 1
[tty], line 1: cat
```

I also tried using another curses based app `cfdisk`. If I use it after the session where I used `ncmpc` it has no effect. But if I use it before `ncmpc` then no problem occurs even after I use `ncmpc`.

I also tried `nudoku`, sudoku game on curses. Which produces no problem by itself but has no effect on `ncmpc`.

OS: VoidLinux
elvish: HEAD
ncmpc:
```
ncmpc version: 0.34
build options: multibyte wide locale iconv nls colors getmouse artist-screen help-screen search-screen song-screen key-screen outputs-screen
```

**Comment by xiaq** [comment]
I don't have a Linux box to debug this right now, but

* Does calling `reset` fix the problem?
* What is output of `stty` before and after running `ncmpc`?

**Comment by greenfork** [comment]
`stty` before and after outputs same string:
```
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
```

`reset` does not fix the problem.

**Comment by hanche** [comment]
I think this is likely related, perhaps even the very same same issue, as #588.

**Comment by xiaq** [comment]
I have a Linux box to debug this now. I suspect that `ncmpc` uses nonblocking IO itself and is not putting the terminal back in blocking mode correctly.

**Comment by hanche** [comment]
That's my guess too. But as I said in a comment on my old issue referenced above, elvish ought to be able to recover from this. That probably means explicitly putting the terminal back in blocking mode at some appropriate point, such as after a command has been run.
