### ISSUE TITLE
Writing an external program that puts to the value channel

### ISSUE THREAD

**Issue by singpolyma** [elves/elvish#823]
Probably the easiest thing here would be an `eval` command or similar that could be used like `from-json` on programs that emit elvish syntax, but it could also be possible to execute programs with an already-open FD just like the stdin/stdout/stderr FDs that when written to would be treated automatically as elvish data.

**Comment by zzamboni** [comment]
Not exactly what you are asking, but you can pass bytes from other commands into the value channel using [slurp](https://elv.sh/ref/builtin.html#slurp). However, `slurp` converts its whole input into a single string, so you need to split it or parse it as needed:
```
> echo yes | slurp
▶ "yes\n"
> splits "\n" ({ echo yes; echo no } | slurp)
▶ yes
▶ no
▶ ''
```

**Comment by xiaq** [comment]
The grammar of Elvish data literals is not intended to be a serialization format (well, not yet). Programs can just emit JSON, which is much more universal than Elvish data syntax.

**Comment by xiaq** [comment]
Closing this - please clarify if I misunderstood you.
