### ISSUE TITLE
Indexing a map with values returned by range builtin produces a float64 error

### ISSUE THREAD

**Issue by codyopel** [elves/elvish#826]
```
local:l = [ &0=a ]
local:i = (range 1)
echo $i
echo $l[$i]
```

`Exception: no such key: (float64 0)`

**Comment by xiaq** [comment]
This is because `range` emits float64 numbers while `0` is a string.

Use `$l[(to-string $i)]`, or build the map with float64 numbers as keys: `l = [&(float64 0)=a]`.

**Comment by codyopel** [comment]
@xiaq 
It is probably worth adding a note to the docs with an example for using range to produce a list of integers because this is a common use case and range returning float64 is probably unintuitive for most users.  Previously range returned whatever type was passed in I believe before the float64 changes or it was just always a string.

e.g.
```
(range 16 | [a]{to-string $a})
```
