### ISSUE TITLE
Printing prompt string for test purpose

### ISSUE THREAD

**Issue by edouard-lopez** [elves/elvish#827]
**related:** https://stackoverflow.com/q/56228984/802365

---

Hello,
I'm on a prompt implementation and would like to test I correctly support `elvish`. I already do that for other shells by invoking their prompt variable/method, e.g.

#### `bash`

    bash -ci 'echo $PS1'

#### `fish` 

	fish -c 'fish_prompt'

How can I print te prompt content in Elvish?

**Comment by krader1961** [comment]
As I wrote on Gitter those two examples are not equivalent. The bash example displays the definition of the primary prompt. The fish example displays the output of the prompt function. If you want the definition of the function you need to do `fish -c 'type fish_prompt'`. So you need to clarify which of those two behaviors you want.

**Comment by edouard-lopez** [comment]
@krader1961, I'm interested by the output, as a per-user point-of-view, not the definition. Below are the commands I run and the output they give:

### Fish
```
❯ docker run \
  --name run-pure-on-fish \
  --rm \
  --interactive \
  --tty \
  --volume=(pwd):/home/pure/.pure/ \
  pure-on-fish:integration-test  fish -c 'fish_prompt'
```

#### Output
```
/home/pure/.pure integration-test*
❯
```

### Bash
```
❯ set shell bash; docker run \
  --name run-pure-on-$shell \
  --rm \
  --interactive \
  --tty \
  --volume=(pwd):/home/pure/.pure/ \
  pure-on-bash:integration-test bash -ci 'echo $PS1'
```

#### Output
```
/home/pure/.pure integration-test* ❯
```

**Comment by krader1961** [comment]
@edouard-lopez I think I see the reason why you are confused by my question. In POSIX shells the `PS1` var is a string with meta chars (e.g., escape sequences). If you just echo it you get the raw string . That is, the definition of the prompt. But if that raw string does not contain any meta chars then it is a literal string that undergoes no transformation when used as a prompt. Which means that echoing it produces the same output you would see when it is used to display the prompt.

For example, on my system the default bash prompt is defined thusly:

```
$ bash -ic 'echo "$PS1"'
\s-\v\$
```

Which renders as `bash-5.0$ `. To see the rendered version you need to do this:

$ bash -ic 'echo "${PS1@P}"'
bash-5.0$
```

So, as I said earlier, your two examples are not equivalent. But your response shows that you are interested in the rendered form rather than the definition of the prompt.

**Comment by edouard-lopez** [comment]
Thanks @krader1961 
I define [`$PS1` dynamically](https://github.com/edouard-lopez/pure/blob/d5c633716ff4962a89ecda31a226a22a9649ba16/config/prompt.bash#L3), that's the purpose of my prompt project:

    export PS1=$(python3 $PURE_EXECUTABLE_PATH/pure/prompt.py --last-command-status $?)

Could you elaborate on the syntax `${PS1@P}`? 
* What is it call? 
* ~Is it bash `4.0` compatible?~ yes

N.B.: The unicode char `❯` (U+276F) is expected.

**Comment by krader1961** [comment]
The `@` operator performs parameter transformation. See the section of the bash man page that begins with `${parameter@operator}`. This is a feature unique to bash. In ksh you have to use `eval echo $PS1`. No idea what the zsh equivalent is.
