### ISSUE TITLE
problems piping to kind-of

### ISSUE THREAD

**Issue by doubleagent** [elves/elvish#828]
I'm new to elvish, so it's entirely possible this issue is addressed in some way I haven't encountered yet.  Going through https://elv.sh/learn/unique-semantics.html and thought it would be interesting to see what `kind-of` had to say about json stuff and ran into this.

![image](https://user-images.githubusercontent.com/56522/58108279-27e11100-7bb1-11e9-8f93-f44edf48c43f.png)

Capturing output eg `kind-of (...)` works fine, but I'm surprised piping doesn't work.

**Comment by doubleagent** [comment]
capturing output works fine, though.

**Comment by krader1961** [comment]
The [documentation](https://elv.sh/ref/builtin.html#kind-of) does not even imply that `kind-of` reads from stdin or the value stream. The broken pipe failure is a natural consequence of that fact. See issue #736 where this behavior was discussed in the context of the `pprint` builtin.

**Comment by notramo** [comment]
@doubleagent There is a workaround for your code:
```elvish
put [lorem ipsum foo bar]| to-json| kind-of (all)
```
`all` captures the value input, and puts it on the value output.

**Comment by doubleagent** [comment]
Thanks guys!
