### ISSUE TITLE
elvish fn appears to distort output of bat

### ISSUE THREAD

**Issue by doubleagent** [elves/elvish#829]
I have `cat` 'aliased' to `bat` (https://github.com/sharkdp/bat) in my `rc.elv`, and I wanted to see if that was causing any delay (spoiler: it isn't).  I did notice, however, that running the alias caused the output to be distorted.  If I run without the alias everything looks fine.

![image](https://user-images.githubusercontent.com/56522/58110181-a8554100-7bb4-11e9-9c12-76008a52e735.png)

I ran this in two different terminal emulators (xterm & kitty) and saw the same thing.

**Comment by SolitudeSF** [comment]
where is the distortion?

**Comment by doubleagent** [comment]
Alright.  I don't understand why `cat f` runs `bat`, but `time cat f` runs `cat`

**Comment by xiaq** [comment]
The `time` command is an external one, so it does not respect Elvish functions. This will make the problem more obvious:

```
~> fn f { echo f }
~> f
f
~> time f
# shows something like "f not found"
```

**Comment by doubleagent** [comment]
Ah, okay - thanks for taking the time to explain!  :-)

**Comment by doubleagent** [comment]
Still reading through the docs, so my apologies if this has a documented answer.  I wonder if there's anything like lisp macros in elvish, which would run a substitution like this during the compilation phase?

**Comment by zzamboni** [comment]
Not that I know, but what use case did you have in mind?  Keep in mind that Elvish has a `-time` builtin which you can use to time any Elvish function, and which would correctly interpret functions:
```
[~]─> fn f { echo foo }
[~]─> time f
f: No such file or directory
        0.00 real         0.00 user         0.00 sys
Exception: time exited with 127
[tty], line 1: time f
[~]─> -time { f }
foo
56.471µs
```

**Comment by doubleagent** [comment]
There's nothing specifically that I'm trying to do besides learn.  :-)

**Comment by zzamboni** [comment]
Always happy to help - and thanks for the link to `bat`! I didn't know about it, might start using it :)

**Comment by doubleagent** [comment]
Came across this at the end of Effective Elvish (https://elv.sh/learn/effective-elvish.html)

![image](https://user-images.githubusercontent.com/56522/58213006-4e3ca480-7cb6-11e9-8374-b197f62341f2.png)

So it appears you are correct.
