### ISSUE TITLE
Elvish ignores SHLVL

### ISSUE THREAD

**Issue by crinklywrappr** [elves/elvish#834]
SHLVL is often used to track 'how many shells deep you are'.

![image](https://user-images.githubusercontent.com/56522/59163833-8cfe9700-8acb-11e9-8ef2-3d3ef8a17ae6.png)

**Comment by krader1961** [comment]
Support for env var `SHLVL` should be implemented. Even though I despise the POSIX shell standard this feature is useful and does not otherwise imply support for that flawed standard.

**Comment by xiaq** [comment]
SHLVL doesn't seem to be documented by POSIX, just a de-facto standard. It's easy enough to implement.
