### ISSUE TITLE
How to terminate find/exec command

### ISSUE THREAD

**Issue by ktm5j** [elves/elvish#837]
Hey folks.  I've been falling in love with elvish lately, but I've hit a snag.  Can someone tell me how I can run `find .. -exec ..` properly in elvish?  Typically you terminate the `-exec` arg with an escaped semicolon: `\;` 

What I would normally do in bash: `find . -inum 933545 -exec rm {} \;`

This is what I'm experiencing with elvish:

```
[/z/W/D/Fabric]─> find . -inum 933545 -exec rm {} \;
parse error: 32-33 in [interactive]: unexpected rune '\\'
parse error: 32-33 in [interactive]: unexpected rune '\\'
```

I've tried various arrangements with quotes, etc. but I can't seem to make it work.  Thanks in advance!

**Comment by SolitudeSF** [comment]
`find . -inum 933545 -exec rm '{}' ';'`

**Comment by ktm5j** [comment]
Awesome! Thanks for the quick response, much appreciated

**Comment by SolitudeSF** [comment]
you could also opt for elvish builtin `exec` like `find . -inum 933545 | each [x]{ rm $x }`

**Comment by ktm5j** [comment]
Oh that's good to know, thanks for the advice
