### ISSUE TITLE
Calling scripts with ~ expansion gives error

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#841]
Suppose the following:

A script is located at `"~/test.elv"`, where `"~"` expands to `"/home/me"`.  I can run the script by calling `/home/me/test.elv`, or by running `./test.elv` from the home directory.  However, if I directly run `~/test.elv`, I get the error
```
Exception: head of command must be callable; got string
```

If it makes a difference, I'm running a slightly old version (v0.12) on macOS; I tried but could not figure out how to install a later version via Homebrew, possibly because I am on a company network.  If this has been resolved since then and fixed in a later version, feel free to close.

**Comment by SolitudeSF** [comment]
its still present on master. probably related #605

**Comment by xiaq** [comment]
Indeed, and both will be fixed if #764 is fixed.

**Comment by xiaq** [comment]
Fixed as #764 was fixed.
