### ISSUE TITLE
Support |&  and >& from csh

### ISSUE THREAD

**Issue by johnwcowan** [elves/elvish#847]
The idea here is to support `|&` as alternative to `|` when constructing pipelines.  This means that not only is stdout redirected to the pipe, but stderr is too.  Similarly, `>&` means that not only is stdout directed to the named file, but stderr too.  These are by far the most common cases of fd-specific redirection.

This is considerably more robust than the Posix shell `2>&1`, where it is easy to reverse the `2` and `1`, and (in the case of file redirection) to place the `2>&1` on the left of the `>` redirection instead of on the right of it.  

There is a minor incompatibility that `>&1` means something different from its meaning in Posix shells, but I think that is worth keeping: you can always write `2>&1` instead.

**Comment by xiaq** [comment]
The `|&` and `>&` syntaxes are both just mashing two things together; while the POSIX syntax of `2>&1` can be combined, orthogonally, with pipes or other redirections to achieve the same effect. It is also a generic syntax and is not limited to stdout or stderr.

I'd say that the POSIX syntax is better: it is orthogonal, general and conceptually simpler, even if it looks a bit clunky. See #859 for a proposal on how to make it more readable.
