### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by dcu** [elves/elvish#852]
Copy and paste:

```
edit:completion:arg-completer[go] = [cmd, args]{
    arg=$args[(- (count $args) 1)]
    put $arg*
}
```
then `go <tab>`

I'm using the master version

**Comment by xiaq** [comment]
The underlying crash has been fixed, but note that there are some problems with your example code:

* Elvish does not use comma to separate arguments
* You need to use `@args` to get all remaining arguments

So the correct code should be:

```
edit:completion:arg-completer[go] = [cmd @args]{
    arg=$args[(- (count $args) 1)]
    put $arg*
}
```

Also, you could just use `$args[-1]` to access the last element. So you can write:

```
edit:completion:arg-completer[go] = [cmd @args]{ put $args[-1]* }
```

Finally, in a **completer** you don't do filtering; the filtering is handled in a separate pass; see https://elv.sh/ref/edit.html#argument-completer. Maybe I should rename "completer" to "generator" to make this clearer.
