### ISSUE TITLE
Ulimit has no effect

### ISSUE THREAD

**Issue by href** [elves/elvish#856]
Setting the  ulimit in elvish has no effect:

```shell
$ ulimit -n
> 256
ulimit -n 1024
ulimit -n
> 256
```

The following command works around the issue:
```shell
sh -c "ulimit -n 1024; exec elvish"
```

Observed on macOS 10.14.5.

**Comment by xiaq** [comment]
`ulimit` has to be implemented as a builtin, and Elvish does not support that yet.

**Comment by xiaq** [comment]
Duplicate of #307.
