### ISSUE TITLE
Support named FD in redirections

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#859]
Elvish supports the POSIX syntax for FD redirections, like `echo 1>&2`. This means "redirect stdout (fd 1) to stderr (fd 2)". Since `echo` writes to FD 1, the whole command will write to FD 2 as a result.

The syntax is succinct, but not very readable. One way to improve it is to support using names instead of FD numbers. For instance, the former can be written as `echo stdout>&stderr`.

Note: neither the `1` nor the `stdout` before `>` is actually needed in the examples, because stdout is the default source of output redirections, but they are spelled out for the purpose of examples.

**Comment by jiujieti** [comment]
I will try to work on this one
