### ISSUE TITLE
`/` allows division by zero

### ISSUE THREAD

**Issue by 0x005c** [elves/elvish#865]
Is this an intended behaviour?

**Comment by SolitudeSF** [comment]
IEEE 754 defines that division by zero should return infinity.

**Comment by 0x005c** [comment]
But some languages such as Ruby throws an error which tells division by zero.

**Comment by SolitudeSF** [comment]
yes, that means ruby doesnt comply to this standard and elvish does.

**Comment by xiaq** [comment]
It is an intended behavior.

Almost all languages support division by 0 in floating point arithmetic, including Ruby:

```
~> irb
irb(main):001:0> 1.0/0.0
=> Infinity
```

The special thing about Elvish is that it always use floating point arithmetic, like JavaScript.
