### ISSUE TITLE
Using `each` with interactive commands

### ISSUE THREAD

**Issue by vendion** [elves/elvish#870]
Is it possible to use an interactive command within an `each` loop, like using [beets](http://beets.io/) and using `each` to pass in a list of files in a loop similar to a `for` or `foreach` loop in other shells?

Example:
```elvish
each [x]{ beet import -m $x } [(ls)]
```

When I tried it did at least one loop and errored out due to stdin stream being closed

```
[/u/h/v/M/U/Unknown_Album]─> each [x]{ beet import -m $x } [(ls)]

/usr/home/vendion/Music/Unknown_Artist/Unknown_Album/06-Track_6.ogg (1 items)
Finding tags for album "Junya Nakano, Masashi Hamauzu & Nobuo Uematsu - Final Fantasy X: Original Soundtrack".
Candidates:
1. 仲野順也, 浜渦正志 & 植松伸夫 - Final Fantasy X: Original Soundtrack (15.2%) (missing tracks, artist) (4xDigital Media, 2004, XW, SQUARE ENIX)
2. 植松伸夫, 仲野順也 & 浜渦正志 - Final Fantasy X: Uematsu's Best Selection (13.5%) (missing tracks, id, mediums, ...) (CD, 2001, US, TOKYOPOP Soundtrax, TPCD 0211-2)
3. 仲野順也, 浜渦正志 & 植松伸夫 - Final Fantasy X: Original Soundtrack (13.4%) (missing tracks, id, artist, ...) (2xCD, 2002, KR, Squaresoft, SRCD-3657)
4. 浜渦正志 - Final Fantasy XIII: Original Soundtrack PLUS (12.6%) (missing tracks, id, mediums, ...) (CD, 2010, JP, SQUARE ENIX, SQEX-10192)
5. 仲野順也, 浜渦正志 & 植松伸夫 - Final Fantasy X: Original Soundtrack (7.7%) (missing tracks, id, artist, ...) (4xCD, 2001)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort? error: stdin stream ended while input required
Exception: beet exited with 1
Traceback:
  [tty], line 1:
    each [x]{ beet import -m $x } [(ls)]
  [tty], line 1:
    each [x]{ beet import -m $x } [(ls)]
```

or is `each` the wrong command to use in this case.

**Comment by zzamboni** [comment]
I think indeed `each` disconnects stdin (probably because `each` itself can receive the list through stdin), but you can manually redirect the input of the command, like this:
```
each [x]{ beet import -m $x < /dev/tty } [(ls)]
```

**Comment by vendion** [comment]
Yeap redirecting `stdin` inside the lamda like you suggested works.

I guess the question is now is that is this working as intended (if so the documentation for `each` might need updating or a note regarding this added somewhere) or is this a bug? Personally working in other shells I would expect `stdin` to still be available within the loop.

**Comment by xiaq** [comment]
I think `each` should not close stdin when arguments are supplied on the command line.

**Comment by xiaq** [comment]
This is now fixed, thanks for reporting.
