### ISSUE TITLE
Official Matrix support room

### ISSUE THREAD

**Issue by notramo** [elves/elvish#871]
Matrix aims to be a successor of IRC.
https://matrix.org/

**Comment by notramo** [comment]
Matterbridge inserts the nick of the sender into the message. This is ugly.
I wonder if Matrix could be used to bridge with a more native-like experience.
There is already a bridged Gitter room. #gitter_elves=2Felvish:matrix.org
The Gitter users are represented like native users (even profile pictures are supported) with the difference that **(Gitter)** is appended to their names. Freenode users are bridged similarly, with puppet users.

**Comment by SitiSchu** [comment]
For Telegram there is https://t2bot.io/telegram/ (can be self hosted) it uses puppet accounts aswell on the matrix side.

**Comment by xiaq** [comment]
I gave Matrix a try. Initially I tried to use Matrix's bridges to replace Matterbridge, but the experience was less than ideal for several reasons:

* The official Gitter integration is quite nonstable and drops messages
* The Telegram bridge https://t2bot.io/telegram/ seems to be problematic either; I couldn't set up bridging with `!tg bridge <id>`
* The format that the IRC bridge uses for reply is quoting the message being replied in `<...>` at the **beginning**; this seems to be not customizable, and worse than Matterbridge's format of quoting in `(re: ...)` at the **end**.

So I will just opt to treating Matrix as yet another IM bridged by Matterbridge. I have already created a room [#elvish:matrix.org](https://matrix.to/#/#elvish:matrix.org) and I'll configure Matterbridge to bridge it with the other rooms, and document it.

**Comment by xiaq** [comment]
Re Matrix providing a more native experience: the native experience is only available for Matrix and IRC users, because the flexibility of the Matrix protocol allows the bridge to create "puppet" accounts to mirror IRC/Gitter/Telegram on the Matrix side. Not exactly sure how the IRC side is implemented, but at least the IRC protocol makes it pretty easy to send messages under arbitrary nicknames, thus achieving an effect similar with puppeting.

For people using other IMs, especially Telegram and Gitter where most active users are on, messages from other IMs will still be sent by a bot run by the bridge.

Granted, some bridges have specific support for linking accounts in different IMs, so that they can send the message from the linked accounts, but that works against the idea of "using whichever IM you want" and come with security risks.

**Comment by notramo** [comment]
@xiaq The t2bot.io Telegram bridge has a notice:
> If your user ID ends with :matrix.org then you will encounter some problems using t2bot.io - please register for an account elsewhere or run your own homeserver. [Learn more](https://t2bot.io/docs/2020-matrix-org-lag/)

You have an account on matrix.org, maybe this was the problem.
The matrix.org IRC bridge and the matrix.org Gitter bridge also has performance issues.
Best solution would be running a custom Gitter bridge, plumbing the Matrix room to IRC, and invoking the Telegram bot. This way, Matrix and IRC users would have a protocol-native experience, and Gitter and Telegram experience would be nearly the same as now.

**Comment by xiaq** [comment]
@notramo Ha, one would assume that matrix.org runs a decent Matrix server :) good to know that there are better choices though. Running my own server also sounds like a feasible choice.

My biggest problem now is the quoting format - it seems really non-ideal and not customizable. If it's easy to change them I'd consider switching :)

**Comment by notramo** [comment]
@xiaq I opened an issue at the IRC bridge repo.
Currently the solution I see mostly is that some IRC channel admins ask the Matrix users to not use the reply feature, but mention the user they are replying to.
I took a look at the conversation. Most of the traffic is from Gitter and Telegram, and only a very small amount of traffic comes from IRC (about 10-15%). Also, replies are very rare, so asking users not to use this function wouldn't bring too much change.
Also, if guest joins would be allowed in the Matrix room, then users could join the chat without registering on any homeserver (just like IRC). (Maybe some users use IRC only because it doesn't force them to register. In this case, they could use Matrix as well.)
Also, there are interesting IRC servers which use Matrix as backend. Maybe you should check them out.
https://github.com/matrix-org/matrix-ircd
https://github.com/nilsding/AgentSmith
