### ISSUE TITLE
Inconsistent return for -compileonly -json

### ISSUE THREAD

**Issue by sblundy** [elves/elvish#873]
If the input has a compilation error, a missing variable for instance, `elvish -compileonly -json` outputs JSON objects with information about the error's location in separate fields. But when it's a parse error, the objects only have the message field.

Example:

**val-missing.elv**
```
if $x {
	echo 'yes'
}
```

**bracket-missing.elv**
```
if $true {
	echo 'yes'

```

```bash
$ elvish -compileonly -json val-missing.elv
[{"fileName":"/val-missing.elv","start":3,"end":5,"message":"variable $x not found"}]
Exception: elvish exited with 2
[tty], line 1: elvish -compileonly -json val-missing.elv
$ elvish -compileonly -json bracket-missing.elv
[{"message":"parse error: 23-23 in bracket-missing.elv: should be '}'"}]
Exception: ./elvish exited with 2
[tty], line 1: elvish -compileonly -json bracket-missing.elv
```

The first has `fileName`, `start`, `end`, and `message` fields. The second just has `message`

**Comment by xiaq** [comment]
Fixed.
