### ISSUE TITLE
Redirection symbol <> usage

### ISSUE THREAD

**Issue by chengxuncc** [elves/elvish#876]
What does symbol `<>` used for? 
```
~> echo hello world! <> file
~> cat file
hello world!
~> echo 123 <> file
~> cat file
123
o world!
~>
```
I didn't find it useful anywhere.

**Comment by xiaq** [comment]
It is there mostly for completeness. There aren't many commands that do read and write on a standard FD, but that doesn't mean that you can't write such a command.

POSIX shell has it: https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html (search for `<>`).
