### ISSUE TITLE
Tilde expansion removes terminating slash in path name

### ISSUE THREAD

**Issue by hanche** [elves/elvish#878]
Consider this:

    ⬥ put ~/tmp/
    ▶ /Users/hanche/tmp

Note that the terminating slash is missing. As a result of this,

    ⬥ fossil clone {ssh://somwehere/some/path/ ~/fossil/}bar.fossil

(real example, munged names) did clone a fossil repository into `fossilbar.fossil` in my home directory. That was not what I intended!

**Comment by xiaq** [comment]
Fixed, thanks for reporting!
