### ISSUE TITLE
Suggestion Image preview in navigator

### ISSUE THREAD

**Issue by epikur-io** [elves/elvish#879]
Hey I really like elvish and I use it as my private shell every day.
I would suggest a feature. It it would be very nice if elvish would allow the user to define a program for a image preview inside the elvish navigator.
It could be implemented using `github.com/eliukblau/pixterm` which has quite nice 256 color preview of images inside terminals and allow the user via rv.elv config file to enable/disable the navigator image preview.

**Comment by xiaq** [comment]
Thanks for the suggestion. There is already a tracking issue for this, #380, so I will close this one.
