### ISSUE TITLE
Make sure that all panics are recovered

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#88]
Right now, `main.go` has a global panic guard that drops you to `/bin/sh`.

Ideally, most calls in `main.go` should be panic-guarded. For instance, access to nil pointers can happen when the input is incomplete and the editor tries to compile an incomplete AST. These panics should be guarded in future.

**Comment by xiaq** [comment]
I will leave this unfixed for a while on purpose, since during developments panics will drive me to fix bugs more promptly. And we don't have comprehensive logging facilities yet.

**Comment by krader1961** [comment]
@xiaq,Is this still an unresolved issue? AFAICT I have never seen an elvish panic that does not result in a rescue shell. And looking at the source code it looks like it is making a good faith attempt to deal with all Go panics. ITSM that you have resolved this issue.

**Comment by xiaq** [comment]
Yes this can be closed.
