### ISSUE TITLE
Issue labels

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#886]
This document details the labels used in this issue tracker

## Type labels

The following labels identify the type of the issue and are mutually exclusive:

* `bug`
* `cleanup`
* `note`
* `question`

Feature requests do not have a specific label, they are the default.

## Additional labels

* `blocks 1.0`: issue must be resolved before 1.0 is released.
* `maybe`: there is not yet enough evidence to determine if the issue is a good idea. Eventually, either the issue turns out to be a good idea (and has this label this removed), or the issue turns out to be a bad idea (and gets closed).

**Comment by xiaq** [comment]
So I've given up on the effort of categorizing Elvish issues using the "Project/Component/Area" system - it's impossible for me to keep everything in mind, and the benefits they provide are doubtful. I am removing them, and updating the original comment of this issue.

**Comment by krader1961** [comment]
My opinion is that for an open source project at this stage of its evolution there shouldn't be much more than a "bug" label to make it easy to identify bugs that need to be resolved and possibly a "question" label.

A "question" label is useful in a couple of ways. First, a "question" type issue should have the highest priority. Higher than an issue with a "bug" label. Second, as people continue using the issue tracker for reporting bugs, desired enhancements, questions, and other issue types people can filter on "label==question" to get a sense for what sorts of problems people are experiencing using the project.

Labels other than the above two tend to very subjective in my experience and are hard to justify for a project at this stage of its life-cycle.

**Comment by xiaq** [comment]
Since the labels are now simple enough and hopefully self explanatory, I'll close and unpin this.
