### ISSUE TITLE
Nondeterminism when incrementing a variable concurrently

### ISSUE THREAD

**Issue by andychu** [elves/elvish#888]
I did a little more testing based on the lobsters discussion: https://lobste.rs/s/hj3np3/mvdan_sh_posix_shell_go

If I run `f | f` with the function f below (using the elvish-HEAD binary), sometimes the variable is incremented by one, and sometimes it's incremented by 2.

My suspicion is that this is a race condition.  If that's the case I think it would be undefined behavior in Go, and would be flagged by Go's race detector (though I didn't try).

```
~/install> fn f { echo ---;  a = (+ $a 1) }


~/install> echo $a
22
~/install> 
~/install> f|f
---
~/install> echo $a
23
~/install> f|f
---
~/install> echo $a
25
~/install> f|f
---
~/install> echo $a
26
~/install> f|f
---
~/install> echo $a
27
~/install> f|f
---
~/install> echo $a
29
```

**Comment by xiaq** [comment]
It is a race condition, but the underlying variable is mutex-guarded:

https://github.com/elves/elvish/blob/bd70489b242981ce6fe1ef1b0b8f52a44da74695/pkg/eval/vars/ptr.go#L40-L52

Go's race condition detector is only supposed to catch race conditions that can cause memory corruption, so it won't catch this one.

Elvish doesn't have a good story for memory sharing yet. A GIL is not a good solution; most of the interpreter state is actually concurrency-safe anyway. I would like to develop a set of synchronization primitives later.

**Comment by andychu** [comment]
BTW I also get this behavior for lists and maps:

```
~/install> fn chlist { echo ---; mylist[0] = x }
~/install> mylist = []
~/install> chlist
---
Exception: variable $mylist does not exist, compiler bug
Traceback:
  [tty], line 1:
    fn chlist { echo ---; mylist[0] = x }
  [tty], line 1:
    chlist
~/install> 
```

**Comment by xiaq** [comment]
That's because Elvish's variables require declaration before use. This is fine:

```elvish-transcript
~> mylist = [a]
~> fn chlist { echo ---; mylist[0] = x }
~> chlist
---
```

Still, Elvish should have caught that when `chlist` is not defined during the compilation phase. I have filed #889 for this.

**Comment by krader1961** [comment]
Expanding on @xiaq's answer: The race is in the expansion of `$a` and the assignment to `a`. The statement `a = (+ $a 1)` can expand `$a` in both go routines before the assignment that the other thread makes can be seen. Which causes both go routines to increment and assign the same value. The use of a mutex when accessing or modifying the var, in isolation, is insufficient. Concurrent modification of global vars is inherently problematic (i.e., race prone) without using an explicit mutex for using that global var.

**Comment by xiaq** [comment]
See #1003 for a proposed atomic mutation primitive.
