### ISSUE TITLE
Clear builtin (CTRL + L)

### ISSUE THREAD

**Issue by bpinto** [elves/elvish#89]
I have been trying to bind `CTRL + L` to the clear builtin but I haven't found a way to do it. Could you guide me?

**Comment by xiaq** [comment]
`clear` is not a builtin. After I implement the support for binding elvish functions to keys, you should be able to use the following:

```
bind Ctrl-L { clear }
```

Note that the space after `{` is significant.

**Comment by xiaq** [comment]
It is now possible to use `bind Ctrl-L { clear > /dev/tty }`. The redirection is necessary since when binding a function to a key, elvish redirects the output of the function to an internal pipe so that it won't mess up with the terminal.

However, due to a bug (#95), this will do more than what you want - it will erase the elvish prompt. Maybe `clear` deserves an implementation as a builtin of the editor...

**Comment by bpinto** [comment]
Has commit https://github.com/elves/elvish/commit/e49d44c0909fb98154dff7455c32bd0c7fca201a "broken" support for this as a bind has to be a builtin?

**Comment by xiaq** [comment]
No, but a later commit removed the `bind` builtin and let you manipulate the binding table in a more direct way. Use `le:binding[insert][Ctrl-L]={ clear > /dev/tty }`.

**Comment by bpinto** [comment]
I was planning on opening a PR with something like this:

```
diff --git a/edit/bind.go b/edit/bind.go
index 19954ae..79473ae 100644
--- a/edit/bind.go
+++ b/edit/bind.go
@@ -24,6 +24,7 @@ var defaultBindings = map[bufferMode]map[Key]string{
 		Key{Home, 0}:     "move-dot-sol",
 		Key{End, 0}:      "move-dot-eol",
 		// Killing.
+		Key{'L', Ctrl}:    "clear",
 		Key{'U', Ctrl}:    "kill-line-left",
 		Key{'K', Ctrl}:    "kill-line-right",
 		Key{'W', Ctrl}:    "kill-word-left",
diff --git a/edit/builtins.go b/edit/builtins.go
index f2401c7..f584617 100644
--- a/edit/builtins.go
+++ b/edit/builtins.go
@@ -48,6 +48,7 @@ var builtins = []Builtin{
 	// Command and insert mode
 	{"start-insert", startInsert},
 	{"start-command", startCommand},
+	{"clear", clear},
 	{"kill-line-left", killLineLeft},
 	{"kill-line-right", killLineRight},
 	{"kill-word-left", killWordLeft},
@@ -131,6 +132,10 @@ func startCommand(ed *Editor) {
 	ed.mode = modeCommand
 }
 
+func clear(ed *Editor) {
+	ed.clear()
+}
+
 func killLineLeft(ed *Editor) {
 	sol := strutil.FindLastSOL(ed.line[:ed.dot])
 	ed.line = ed.line[:sol] + ed.line[ed.dot:]
```

But editor does not have a `clear` method. Suggestion?
I ran that command directly on the shell and the binding worked, just would like to propose it to be a default binding.

**Comment by xiaq** [comment]
There are already a few builtins that I feel should be done in pure elvish, and I don't want to introduce another one. `le:binding[insert][Ctrl-L]={ clear > /dev/tty }` is good enough. You can put it in your rc file.

I don't use `^L` personally, and I wonder how many people do, so I am not making this a default binding yet. I am also considering making `^L` trigger the yet-to-be-implemented autojump mode (see last comment in #27), akin to how `^L` selects the location bar in browsers.

**Comment by xiaq** [comment]
In case you don't know, the rc file is `~/.elvish/rc.elv`.

**Comment by jamesalbert** [comment]
Is any way to map something like Alt-left/right arrow keys? I'm noticing (for me) it's picking up Alt-left_arrow_key as Alt-b which is fine, but is there a way I could tell it to perform an Esc+b like I would for iterm?

**Comment by xiaq** [comment]
@jamesalbert This is an issue not related to your question. Please don't post here. You can discuss such questions in one of IM channels.

**Comment by jamesalbert** [comment]
@xiaq my apologies, but I asked a keybinding question in a convo that was discussing keybindings.
