### ISSUE TITLE
edit:move-dot-left-small-word moves too far

### ISSUE THREAD

**Issue by hanche** [elves/elvish#899]
The builtin `edit:move-dot-left-small-word` acts just like its big brother `edit:move-dot-left-word`.

Note that the corresponding `edit:move-dot-right-small-word` works as advertised.

**Comment by xiaq** [comment]
Ah, it's just a typo in the code:

https://github.com/elves/elvish/blob/41985123d3c3103619a6afc849ae58c4d95e1099/pkg/edit/builtins.go#L187

**Comment by hanche** [comment]
It appears that we can close this, as it was rediscovered in #911 and fixed in d623dafd35.
