### ISSUE TITLE
HOW TO READ USER INPUT

### ISSUE THREAD

**Issue by enty8080** [elves/elvish#900]
Sorry for trouble... How to read user input in Elvish like in python input() or bash read to the variable?

**Comment by zzamboni** [comment]
If you are using a recent build from master (or a nightly), you can use the `read-upto` function. For example, to read a line of input:
```
resp = (read-upto "\n")
```
In older versions of Elvish, you need to use an external command, for example:
```
resp = (head -n1)
```

**Comment by enty8080** [comment]
Thank you very much!

**Comment by enty8080** [comment]
And how to read user input with the specific prompt message like in python:
    p = input('message> ')

**Comment by zzamboni** [comment]
You can use the `print` function to print a prompt without a newline at the end:
```
print "Enter your input: "
resp = (read-upto "\n")
echo You entered: $resp
```

**Comment by zzamboni** [comment]
Note that `read-upto` returns also the final character, so the returned value includes a newline at the end. To return only the string, trim away the last character:
```
print "Enter your input: "
resp = (read-upto "\n")[:-1]
echo You entered: $resp
```
