### ISSUE TITLE
How to read user input with message?

### ISSUE THREAD

**Issue by enty8080** [elves/elvish#901]
And how to read user input with the specific prompt message like in python:
    p = input('message> ')

**Comment by zzamboni** [comment]
You can use the `print` function to print a prompt without a newline at the
end.

**Comment by enty8080** [comment]
Something like this?

```
print "message> "
p = (read-upto "\n")
```

**Comment by zzamboni** [comment]
Yes. Note that `read-upto` returns also the final character, so the returned value includes a newline at the end. To return only the string, trim away the last character:
```
print "Enter your input: "
resp = (read-upto "\n")[:-1]
echo You entered: $resp
```

**Comment by enty8080** [comment]
Thank you!
