### ISSUE TITLE
Scope confusion with if and while

### ISSUE THREAD

**Issue by hanche** [elves/elvish#905]
Example (⬥ is my prompt):

```
⬥ if (x = $true; put $x) { echo $x }
Exception: variable $x not found
Traceback:
  [tty], line 1:
    if (x = $true; put $x) { echo $x }
  [tty], line 1:
    if (x = $true; put $x) { echo $x }
⬥ put $x
▶ $true

```

As can be seen, `$x` does exist *after* running the `if`. It should be in scope within the `if` body, for sure?

Of course,

```
⬥ x= if (x = $true; put $x) { echo $x }
```
works as expected, and is better code as it does not pollute the local namespace. But stil, I consider this a bug.

The same thing happens with `while`. In fact, that is how I discovered the bug  – with a more complicated expression in place of `$true`, of course.

**Comment by krader1961** [comment]
This appears to be closely related to, if not exactly the same thing as, issue #532.

This issue raises an interesting question. Should temporary assignments even be legal when there is no associated command?

**Comment by xiaq** [comment]
It seems that this now works as intended:

```
~> if (var x = $true; put $x) { put $x }
▶ $true
```

**Comment by krader1961** [comment]
> It seems that this now works as intended

It still seems broken in that `x` is not scoped to the `if` and leaks into the enclosing scope:

```
0.000151 elvish> put $x
compilation error: 4-6 in [tty]: variable $x not found
compilation error: variable $x not found
[tty 2], line 1: put $x
0.000056 elvish> if (var x = $true; put $x) { put $x }
▶ $true
0.000264 elvish> put $x
▶ $true
```

That's not how the Go equivalent behaves. Of course Elvish isn't restricted to behaving like Go in this regard but it seems to me like it should.

**Comment by hanche** [comment]
This has little to do with `if` as such. The point is that parenthesised code runs in the surrounding scope, a fact that I utilised once in my (now obsolete) trick to optionally load os-specific modules.

The scoping rule for parenthesised code seems to be by design, not by accident (though I am not sure I've heard that stated explicitly).

**Comment by xiaq** [comment]
Yes, only lambdas introduce new scopes.

**Comment by krader1961** [comment]
Yes, but a [parenthesized output capture](https://elv.sh/ref/language.html#output-capture) expression evaluated as an `if` conditional runs in the context of the `if` and side effects, such as defining a new var, should arguably be limited to the scope of the `if`. If the current behavior isn't changed the documentation needs to make this behavior clearer.

**Comment by hanche** [comment]
You may indeed argue that `if`, `while`, and `for` should all introduce their own scopes. The resulting behaviour might be somewhat less surprising, but on the other hand, introducing a special scoping rule for these commands complicates the language and makes it less consistent, or so it seems to me. So I think the current behaviour is OK, with the _possible_ exception of the loop variable of a `for` loop.

Documentation is a different matter, and it definitely could use some improvement. Maybe make that a separate issue, seeing as this one has been closed? Hmm, I think I'll just go ahead and open one.
