### ISSUE TITLE
Expanding maps

### ISSUE THREAD

**Issue by hanche** [elves/elvish#908]
In analogy with the `$@list` notation for expanding a list, use `$@@map` for expanding a map.

This only makes sense in a few contexts:

```
> map1 = [&a=1 &b=2]
> map2 = [&c=3 $@@map] # equivalent to map2 = [&c=3 &a=1 &b=2]
> fun $@@map1 # equivalent to fun &a=1 &b=2
```
Additionally, the @@ notation could be used in the argument list of a function definition:

```
fn fun [&a=$nil @@kw]{ … }
fun &a=1 &b=2 &c=3
# in the body of fun, a=1 and kw=[&b=2 &c=3]
```

These ideas are, of course, shamelessly stolen from python's `**`. Probably one to be put on the back burner for now, but might it be consider for some future enhancement?

**Comment by xiaq** [comment]
Dup with #584. Regarding the syntax, my preference is still `$%map`, in analogy with Perl's hash sigil.

**Comment by hanche** [comment]
Aha! I tried my best to search for it, but never found the dup. Maybe it comes down to a different choice of words. Agreed that `$%map` is better, so long as you don't mind using up another character for special syntax.
