### ISSUE TITLE
Failed to (first) start when out of space

### ISSUE THREAD

**Issue by ant5** [elves/elvish#909]
I gave a try to elvish as my new shell but there was no space left on my home volume. Elvish has failed to start with the following error:

```
/: write failed, filesystem is full
warning: cannot create data directory ~/.elvish

(0x91ca00,0xdef020)

, 0x30, 0x999fc0)
        pkg/cli/histutil/store.go:54 +0x26
github.com/elves/elvish/pkg/cli/histutil.initStores(...)
        pkg/cli/histutil/fuser.go:31
github.com/elves/elvish/pkg/cli/histutil.NewFuser(0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/cli/histutil/fuser.go:23 +0x39
github.com/elves/elvish/pkg/edit.NewEditor(0xa8c4e0, 0xc0000840a0, 0xc00010c000, 0x0, 0x0, 0xc00006a358)
        pkg/edit/editor.go:29 +0xd0
github.com/elves/elvish/pkg/program/shell.interact(0xc000010018, 0xc000010020, 0xc000010028, 0xc00010c000, 0xc000029340, 0x11, 0xc00010c000)
        pkg/program/shell/interact.go:25 +0xa7
github.com/elves/elvish/pkg/program/shell.(*Shell).Main(0xc000102200, 0xc000010018, 0xc000010020, 0xc000010028, 0xc0000201b0, 0x0, 0x0, 0x0)
        pkg/program/shell/shell.go:54 +0x320
github.com/elves/elvish/pkg/program.Main(0xc0000201b0, 0x1, 0x1, 0x0)
        pkg/program/program.go:119 +0x1f4
main.main()
        main.go:14 +0x45

goroutine 6 [syscall]:
os/signal.signal_recv(0xc000040787)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/elves/elvish/pkg/eval.init.13.func1()
        pkg/eval/port.go:49 +0x53
created by github.com/elves/elvish/pkg/eval.init.13
        pkg/eval/port.go:48 +0x49

goroutine 10 [runnable]:
github.com/elves/elvish/pkg/program/shell.handleSignals.func1(0xc00006a1e0, 0xc000010028)
        pkg/program/shell/shell.go:75
created by github.com/elves/elvish/pkg/program/shell.handleSignals
        pkg/program/shell/shell.go:75 +0x8a
```

**Comment by krader1961** [comment]
@ant5 What behavior would you prefer? Should elvish simply ignore that it can't create the files to save its state? What do other shells such as `bash`, `ksh` and `zsh` do in the situation you reported for `elvish`?

**Comment by ant5** [comment]
I just was scared that some unpredictable things can prevent me to login to a system.   I had not any thoughts about shell reliability before this case.  Now I think that reliability for the shell mean  only the one thing:  be able to start in every (may be bad) circumstances and allow user to execute a commands. 

May be, the bad circumstances may be considered in design and elvish will have Plan B to drop all feature for startup ability.

**Comment by krader1961** [comment]
@ant5 I don't fully understand your previous comment since you and I seem to have different primary languages. However, I agree that an `elvish` interactive shell should continue to run even if it cannot open, or write to, its history file. Elvish should display an appropriate diagnostic and continue to process interactive commands.

**Comment by ant5** [comment]
> since you and I seem to have different primary languages

My poor english had never been noticed in such subtle manner.  :thumbsup:

> elvish interactive shell should continue to run even if it cannot...

It will be great cause to switch to elvish as a default shell.

**Comment by krader1961** [comment]
See also issue #126 and #596. Using a text based history mechanism would make it much easier to deal with this scenario. It also makes it much easier for humans to examine the command history file.

**Comment by xiaq** [comment]
Elvish should definitely fail gracefully when the disk is full. Tagging this as a bug and aiming to fix it before the next release.
