### ISSUE TITLE
How to switch off external commands?

### ISSUE THREAD

**Issue by enty8080** [elves/elvish#910]
How to switch off all external commands and use just builtin commands?

**Comment by SolitudeSF** [comment]
`E:PATH = ''`

**Comment by krader1961** [comment]
@enty8080 As discussed on Gitter, if all you want to do is see what can be done in elvish without relying on any external commands (e.g., grep, ls, seq) all you have to do, as @SolitudeSF and others have already said, is execute `E:PATH = ''` before doing anything else. Doesn't that answer your question? If not, can you provide more information about what you're trying to do?

**Comment by enty8080** [comment]
I am trying to switch off all external commands as default without using rc.elv and E:PATH = ''. I mean I want to edit code of elvish so that it can not execute external commands as default.

**Comment by zzamboni** [comment]
@enty8080 but why? I'm afraid this might be a case of the [XY problem](http://xyproblem.info/) - you have stated repeatedly what you want to do, but not why. What is the problem you are trying to solve? What's the enveloping use case for your question?

The ability to execute external commands is a fundamental part of any shell, so I doubt this will ever become part of the shell itself. Emptying the PATH as suggested achieves the same effect (at least superficially, since you can still type full paths to the commands), but this seems not to satisfy your need. So what is it that you are trying to achieve?

**Comment by enty8080** [comment]
I already said that I want to disable the execution of external commands and use only the elvish programming language

**Comment by SitiSchu** [comment]
Then what's the issue with simply clearing out E:PATH? that effectively disables external commands unless typed with their full path which you can't do by accident. If you just want to use elvish and nothing else clear out your PATH and don't use anything with its full path and you're good to go.

**Comment by krader1961** [comment]
@enty8080 What you are asking is known as "an exercise for the student." Note that there is no need to modify your *~/.elvish/rc.elv* file. In fact, a simpler, safer way to do this is a trivial wrapper script:

```sh
#!/bin/sh
export PATH=''
exec elvish "$@"
```

If you absolutely feel you need to modify the elvish source I'll give a hint: Try using `os.Setenv()` in `NewEvaler()`.

**Comment by enty8080** [comment]
NewEvaler() in runtime.go?

**Comment by krader1961** [comment]
> NewEvaler() in eval.go?

Yes, that is the only `NewEvaler()` function in the source.

**Comment by enty8080** [comment]
@krader1961, I don't know how to use `os.Setenv` 😥 Can you write an example of setting `PATH=''`?

**Comment by krader1961** [comment]
@enty8080 Try searching for existing uses of `os.Setenv()` in the elvish source. See also the Go documentation: https://golang.org/pkg/os/. If you can't figure it out with those hints then you shouldn't be trying to modify the source. And you still haven't explained why simply setting `PATH` using something like the wrapper script I gave you isn't an acceptable solution.

**Comment by krader1961** [comment]
@enty8080 Can this be closed?

**Comment by enty8080** [comment]
Yes

**Comment by xiaq** [comment]
I am not sure what the original motivation for this issue was, but a lexically-scoped variant of this feature can be quite useful. See #978.
