### ISSUE TITLE
Need to type Ctrl-V twice (macOS)

### ISSUE THREAD

**Issue by hanche** [elves/elvish#917]
On macOS, I need to type Ctrl-V (bound to `edit:insert-raw`) twice to get the desired effect. If I wish to insert a literal Ctrl-V, I need to type it _four_ times.

I only have to run `edit:insert-raw` once in the minibuffer, however.

**Comment by krader1961** [comment]
This also happens on FreeBSD but not my Linux VMs. On WSL (windows subsystem for linux) it has a different bug. Typing one [ctrl-v] starts raw mode but it doesn't actually emit the raw char. For example, [ctrl-v][ctrl-v] results in a literal `V` being inserted.

**Comment by krader1961** [comment]
The bug is due to how the termios iexten flag affects input on Linux versus BSD. On Linux it is ignored if canonical mode is disabled. On BSD it still affects some input if iexten is true and canonical is false.
