### ISSUE TITLE
Support CRLF ("\r\n") as a valid line separator in scripts

### ISSUE THREAD

**Issue by SitiSchu** [elves/elvish#918]
Supporting CRLF (`\r\n`) line endings would fix issues with modules installed using `epm` not working on windows due to git's `autocrlf` setting.

**Comment by SitiSchu** [comment]
I changed the title to be more generic since things like `curl -I` return output containg CRLF so when capturing the output and trying to put it into a list the list items will have `\r` in them

**Comment by krader1961** [comment]
Does this proposal apply only to elvish scripts? Or does it also apply to the implicit line splitting done by the `(...)` output capture and the implicit splitting done by many commands such as this example:

```
~> echo "abc\ndef" | each $str:to-upper~
▶ ABC
▶ DEF
```

How would this affect `read-upto`? Should this only be done on platforms (e.g., MS Windows) where CRLF line endings are native or also on UNIX like platforms?

**Comment by krader1961** [comment]
Regarding how this would interact with `read-upto` see #907 which discusses introducing a dedicated `read-line` function.

**Comment by SitiSchu** [comment]
It was only for scripts before but then I changed it to apply it to the implicit splitting too (since headers in http use CRLF)

**Comment by xiaq** [comment]
I changed the title back to supporting CRLF in elvish scripts - I don't see the harm in supporting this.

Supporting CRLF in the implicit splitting of output capture is a different feature and is tracked separately in #970.

**Comment by xiaq** [comment]
Related and interesting: Go supports using `\r\n` as line endings in sources, but strips raw `\r` from multi-line string literals.

The thinking seems to be that converting the line endings of a source file shouldn't change it from the Go compiler's perspective. This is a useful property, but I am not sure Go's approach is a good way to implement it, so I'll default to *not* adopting the stripping behavior.
