### ISSUE TITLE
Cannot install latest version with "go get" in module mode

### ISSUE THREAD

**Issue by rythmkraze** [elves/elvish#926]
Installing elvish using `env GO111MODULE=on go get github.com/elves/elvish` is failing as follows. 
```
go: downloading github.com/elves/elvish v0.10.1
go: github.com/elves/elvish upgrade => v0.10.1
go: finding module for package github.com/boltdb/bolt
go: finding module for package github.com/xiaq/persistent/vector
go: finding module for package github.com/xiaq/persistent/hashmap
go: finding module for package github.com/mattn/go-isatty
go: finding module for package golang.org/x/sys/unix
go: finding module for package github.com/xiaq/persistent/hash
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/boltdb/bolt v1.3.1
go: downloading github.com/xiaq/persistent v0.0.0-20190312105637-a1d9ac4077fc
go: downloading golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
go: found github.com/boltdb/bolt in github.com/boltdb/bolt v1.3.1
go: found github.com/xiaq/persistent/hash in github.com/xiaq/persistent v0.0.0-20190312105637-a1d9ac4077fc
go: found github.com/mattn/go-isatty in github.com/mattn/go-isatty v0.0.12
go: found golang.org/x/sys/unix in golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
# github.com/elves/elvish/eval
/home/rkanchan/go/pkg/mod/github.com/elves/elvish@v0.10.1/eval/closure.go:91:19: undefined: hashmap.Empty
/home/rkanchan/go/pkg/mod/github.com/elves/elvish@v0.10.1/eval/compile_value.go:509:8: undefined: hashmap.Empty
/home/rkanchan/go/pkg/mod/github.com/elves/elvish@v0.10.1/eval/list.go:105:16: l.inner.Nth undefined (type vector.Vector has no field or method Nth)
/home/rkanchan/go/pkg/mod/github.com/elves/elvish@v0.10.1/eval/list.go:113:21: l.inner.AssocN undefined (type vector.Vector has no field or method AssocN)
/home/rkanchan/go/pkg/mod/github.com/elves/elvish@v0.10.1/eval/map.go:13:8: undefined: hashmap.HashMap
/home/rkanchan/go/pkg/mod/github.com/elves/elvish@v0.10.1/eval/map.go:23:19: undefined: hashmap.HashMap
/home/rkanchan/go/pkg/mod/github.com/elves/elvish@v0.10.1/eval/map.go:29:11: undefined: hashmap.Empty
```

**Comment by krader1961** [comment]
Works for me. You didn't tell us your `go version` or platform (e.g., `uname -a` output). Note that this project currently requires a relatively recent Go release; specifically >= 1.13. So if you're using an older version of Go, which seems likely given your use of `GO111MODULE=on`, that is likely the issue.

**Comment by krader1961** [comment]
Note that I can reproduce similar errors on my ancient Ubuntu 16.04 32-bit VM for which the most recent Go version is 1.6.2:

```
$ env GO111MODULE=on go get github.com/elves/elvish                                                                                                                           0 ms
# github.com/elves/elvish/program/daemon
go/src/github.com/elves/elvish/program/daemon/daemon.go:48: undefined: os.Executable
# github.com/elves/elvish/parse
go/src/github.com/elves/elvish/parse/error.go:33: undefined: strings.Builder
go/src/github.com/elves/elvish/parse/error.go:54: undefined: strings.Builder
go/src/github.com/elves/elvish/parse/error.go:72: undefined: strings.Builder
```

**Comment by rythmkraze** [comment]
Im using `go1.14` on `Ubuntu 18.04.3 LTS`

**Comment by krader1961** [comment]
Note that elvish v0.10.1 is quite old; dating back to 2017-09-18. The state of the elvish code at that time did have a *eval/closure.go* file which did import `"github.com/xiaq/persistent/hashmap"`. But the current code does not have that file. That file is now named *pkg/eval/closure.go*. So the question is why your environment, @rythmkraze, is trying to install an ancient version of the elvish project.

**Comment by rythmkraze** [comment]
Go Modules appears to be unable to detect the newer releases as seen at https://pkg.go.dev/github.com/elves/elvish?tab=versions

The only version it detects is `v0.10.1 – Sep 18, 2017`

**Comment by rythmkraze** [comment]
I think its because all the release tags except for `v0.10.1` are not [semver](https://semver.org/) compatible. All the other release tags are missing the PATCH version.

**Comment by xiaq** [comment]
Interesting, I had no idea that Go modules require a PATCH version!

I'll retrospectively tag all the v0.x version as v0.x.0.

**Comment by xiaq** [comment]
Done. Note that this does not reproduce now because v0.13.1 is the latest release, but when v0.14.0 is released you will be able to go-get it.

https://pkg.go.dev/github.com/elves/elvish?tab=versions should also start showing all the historical versions soon.

Thanks for reporting, @rythmkraze.
