### ISSUE TITLE
elvish does not correctly handles ASCII control escape sequences in the prompt

### ISSUE THREAD

**Issue by KsRyY** [elves/elvish#929]
I wanted to use [Starship](https://github.com/starship/starship), a cross-shell prompt with elvish. I've tried something similar to this:
```
edit:rprompt = (constantly "") # wipe the rprompt to prevent problems
edit:prompt = { starship prompt } # `starship prompt` is the command that will print output a prompt
```
and the output is a disaster, like this:
```
^[[1;36m~^[[0m
^[[1;32mλ^[[0m
```
It should be like this (with the color of course):
```
~ 
λ
```
I don't know why, but I believe that elvish does not correctly unescape these control sequences included in the prompt, which causes this problem.

**Comment by SolitudeSF** [comment]
duplicate #814

**Comment by KsRyY** [comment]
@SolitudeSF OK.

**Comment by zzamboni** [comment]
@KsRyY FYI - #814 is closed now, so the following now works:
```
edit:prompt = { starship prompt }
```
