### ISSUE TITLE
Support showing stack trace for exceptions in editor binding and prompt

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#945]
Today if an editor binding or prompt throws an exception, Elvish only shows the error message and hides the full stack trace. It should be possible to show the full stack trace.

This can be implemented by supporting a flag `$edit:show-exception-stack-trace`, and show the stack trace when it is true.

**Comment by zzamboni** [comment]
A gentle ping on this - I'm still puzzled by an error I see sometimes, and which I have been unable to trace:
```
prompt function error: arity mismatch: arguments here must be 0 values, but is 1 value
```

**Comment by xiaq** [comment]
@zzamboni Rest assured that it's being prioritized - it's part of the 0.14 milestone :)

I am considering a different way to implement this:

* Add a list variable `$edit:exceptions` to save exceptions.
* Whenever an exception happens in one of the editor callbacks, print out the index where the exception is saved (e.g. `exception saved in $edit:exceptions[3]`)
* Add a builtin to print the full exception stack trace, e.g. `show-exc $edit:exceptions[3]`.

It also makes sense to add a `exc` module for exceptions utilities, so the `show-exc` command can be `exc:show` instead.
