### ISSUE TITLE
Suppor referring to variables with meta characters in their names

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#946]
We have builtin functions with meta characters in their names, such as `!=`. It is not possible to refer to their corresponding variables (`$!=~` is not valid).

To fix that, we can support *quoted variable names*. The `$` sign can be followed by a quoted string, and the string specifies the variable names. For example, the variable for `!=` can be written as `$"!=~"` or `$'!=~'.` Note that since this works on the primary node level, the variable name must be given inside a single string: `$'!='~` refers to a variable called `!=`, then concatenated with `~`.

This won't break any existing code since the character sequence `$"` and `$'` are invalid syntax now.

Moreover, the LHS of assignments should also support variable names with meta characters.

This feature is actually very similar to *quoted symbols* found in most Lisps (such as [Racket](https://docs.racket-lang.org/guide/symbols.html)).

**Comment by krader1961** [comment]
This has been resolved by commit 80e944bee2bc832ba30d9d007ff78e8cc9158a1d and therefore can be closed.
