### ISSUE TITLE
Document $edit:abbr

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#947]
The CLI abbreviation expansion feature isn't documented. You can create abbreviations via statements such as `edit:abbr['l '] = 'less '` or `edit:abbr[gcp] = 'git cherry-pick -x'`. Abbreviations are sometimes preferable to a function of the same name for several reasons:

1) You might want to modify the expanded text before executing it.

1) You want the expanded text to appear in the command history.

1) You want a visual reminder of what will be executed by typing a cryptic shortcut like `gcm`.

1) You only want the shortcut to be available at an interactive prompt, not as a function that can be used in elvish scripts, to avoid potential problems.

The existing behavior isn't optimal, IMHO, but let's start by documenting it so people are aware it exists and know how to use it.

**Comment by krader1961** [comment]
Note that what Elvish calls "abbreviations" are known as "aliases" in Bash. With several caveats such as bash, optionally, enabling expansion in non-interactive contexts (see `shopt expand_aliases`).

**Comment by zzamboni** [comment]
@krader1961 I don't agree that abbreviations and bash aliases are equivalent, since abbreviations expand automatically regardless of where they are typed in the command line, not only in the command position. The [alias](https://github.com/zzamboni/elvish-modules/blob/master/alias.org) module implements a wrapper to provide a "traditional alias" functionality, which simply defines functions behind the scenes.

**Comment by krader1961** [comment]
@zzamboni, Yes and no. Bash aliases are not functions. They result in a simple text substitution. They also allow expansion after the command position if the alias expansion ends in a space. When people switch from bash to fish they see that fish has an `alias` command and assume it implements the same behavior as the bash feature of the same name. Which results in confusion when they realize it isn't the same thing. Back when I used, and contributed to, fish it seemed like 98% of the time that a confused user opened an issue on this topic they were told to use an abbreviation instead.

My biggest complaint about the elvish abbreviation mechanism is that it isn't limited to expansion in the command position; at least by default.

**Comment by xiaq** [comment]
> My biggest complaint about the elvish abbreviation mechanism is that it isn't limited to expansion in the command position; at least by default.

Well, because abbreviations are *not* modeled after aliases, they are modeled after abbreviations in word processing software :)

**Comment by krader1961** [comment]
> Well, because abbreviations are not modeled after aliases, they are modeled after abbreviations in word processing software :)

Understood. But most users will expect the alias/abbr to only be substituted in the "command" position. Consider something like `edit:abbr['l '] = 'less '`. The Intent is to make it possible to type `l /some/file` and have that translated to 'less /some/file`without the second `l` expanded to `less`.

**Comment by zzamboni** [comment]
@krader1961 you keep mentioning alias/abbr as if they are equivalent, but I think they are two fundamentally different mechanisms in Elvish. What in other shells is known as "aliases" are in Elvish simply functions, and are implemented as such by modules like [alias](https://github.com/zzamboni/elvish-modules/blob/master/alias.org). Whether such an "easy function definition" mechanism should be built into Elvish is a separate question, I think.

But the abbreviation mechanism is mean to provide a simple "text expansion" mechanism. I agree you can "abuse" it to implement alias-like function mappings, but even with the space, the potential for mistaken expansion remains.

I agree the abbr mechanism needs to be properly documented, but we should not try to make it into an alias functionality, as this will only cause confusion.

**Comment by krader1961** [comment]
@zzamboni I think there is some confusion because in elvish (and fish) an "alias" is a simple function. But in POSIX shells like bash an alias is not a function -- it is a simple substitution of the alias with an arbitrary string which can include shell meta-chars (e.g., "|"). But limited to the "command" position in a statement.

Elvish definitely should not, ever, implement something like the horrible hack that is the POSIX "alias" command. Functions and text abbreviations are sufficient and much cleaner. My point is that it should be **possible** to limit abbreviation expansion to the "command" position in a statement. If I want an abbreviation such as `l` => `less` I shouldn't have to resort to a function. The whole point is that I want `less` to appear in my command history regardless whether I use the abbreviation or type the full command name. Similarly, with something like `gcp` => `git cherry-pick -x` I want the expansion to appear on the command line so I can backspace over the `-x` if it isn't appropriate. If I make `gcp` a function I can't do that.

**Comment by krader1961** [comment]
Consider the following fish abbreviation definitions that I've been using for several years:

```
abbr -a -g -- gc 'git commit'
abbr -a -g -- gca 'git commit --amend'
```

This works because the expansion only occurs when the user types a space, `|`, or presses [enter]. But the Elvish abbreviation model means that the `gca` abbreviation cannot be used. At least not without including a space in the abbreviation definition. But that means you can't simply type `gc` or `gca` followed by [enter]. I'm sure there are good uses of the current Elvish behavior so I'm not proposing making that behavior impossible to use.

Note that Vim abbreviations are only expanded when the abbreviation is followed by punctuation such as a space or comma. As well as pressing [esc] to exit insert mode or pressing [enter]. That is arguably a superior model to the one used by fish. In fish I can type `gc|` and my `gc` abbreviation will be expanded. But typing `gc,` does not expand my abbreviation. I would argue it should expand when the comma is typed if we're going to use the "modeled after abbreviations in word processing software" definition.

**Comment by krader1961** [comment]
Consider another example. I have a fish abbreviation that converts `-` => `cd -`. I've never had a problem using that in fish because abbreviations are only expanded in the command position in that shell. That is yet another example for why supporting, if not making abbreviation expansion only occur in the "command position" by default, is useful.

**Comment by xiaq** [comment]
@krader1961

It has been my design intention to let abbreviations expands anywhere. I have the following in my rc.elv:

```
edit:abbr = [
  &'>!'= '> /dev/null'
  &'||'= '| less'
  &//ul= '/usr/local'
]
```

None of them is a command alias; I depend on the fact that they expand everywhere.

Command aliases are best implemented by defining a function, as @zzamboni pointed out.

I can see a possible argument in favor of using an abbreviation-like mechanism for aliases though: you may want to *type* `gc` but get `git commit` in the *history*, to make it easier to (for example) search for all git commands. I'm open to such a feature request if that's what you need.

Overall, it's counter-productive to insist that an Elvish feature must be a 1:1 replacement for a feature in another shell - Elvish has its own way of combining features, and let's focus on discussing how something should work with other parts of Elvish, rather than how it works elsewhere :)

**Comment by krader1961** [comment]
@xiaq, I did not mean to imply that Elvish should behave exactly like a different shell. For example, the fish project has seen many requests to allow abbreviation expansion in other than the command position. My point was that fish's behavior at the time I stopped tracking its releases (just prior to fish 3.0) appeared to satisfy the expectations of the vast majority its users; including myself.

I think the Elvish abbreviation implementation would address my concerns if it only did the expansion when a non-word character was typed. That would be consistent with how abbreviations in Emacs and Vim work. That would probably also make it unnecessary to implement an option that limits the expansion to the "command position" of a statement. Which would be considerably simpler to implement and document.

**Comment by krader1961** [comment]
> you may want to type gc but get git commit in the history, to make it easier to (for example) search for all git commands.

Yes, precisely. If I use the abbreviation, or type the expansion, I want to be able to search for the expansion in the history regardless whether or not I initially typed the abbreviation. Not to mention seeing the expansion on the command line so that it is quite obvious what will be run. Also, so that I can modify the expansion. Such as removing the `-x` token from the expansion of my `gcp` => `git cherrypick -x` abbreviation. In this case I want the `-x` option to be visible to remind me that cherry-picking a change should normally include the commit ID of the change in the current branch.
