### ISSUE TITLE
option parsing is too lenient

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#958]
While responding to feedback on PR #937 I changed the `math:is-inf` command to accept a `&sign` option. I was surprised by two things:

1) I could pass invalid values to the option. In this instance the option should only allow integers (or perhaps float64). Passing an invalid number caused the value to be silently ignored and the default was used instead.

1) I could specify invalid options. This is true for other builtins that accept options; e.g., `echo &sep=: &argle=bargle abc def` silently ignores the unexpected `&argle` option.

**Comment by xiaq** [comment]
Sounds like something worth spending some time to fix before next release.
