### ISSUE TITLE
Make it possible to turn off implicit external command resolution on a per-scope basis

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#978]
When writing modules and scripts, it can be useful to turn off implicit external command resolution. This has two benefits:

* Make it very easy to see which external commands a script or module depends on;

* Make it possible for Elvish to statically check the existence of commands, improving the safety of the script or module.

This will need to be implemented as a special command that applies the restriction in the current **lexical scope** (files are also lexical scopes). It is conceptually comparable to JavaScript's [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) or Perl's [strict pragma](https://perldoc.perl.org/strict.html).

An example: Assuming that the special command is `strict`, and there is no function named `ls` the following will trigger a compilation error:

```sh
# In a file, or any lexical scope
strict
ls # triggers compilation error
e:ls # ok
```

Inspired by #910.

**Comment by krader1961** [comment]
> Make it possible for Elvish to statically check the existence of commands, improving the safety of the script or module.

This seem impossible given the dynamic nature of external command resolution based on the value of `$E:PATH` when the command is run. AFAICT the goal of this issue is impossible for a command shell. At least not unless you're going to restrict changes to `$E:PATH` after the Elvish program is compiled. Alternatively, require that any external command references be resolved at compilation time, thus immune to any subsequent changes to `$E:PATH` as the program runs. A solution that seems worse than the problem it tries to solve.

**Comment by xiaq** [comment]
The static checking happens not during the compilation of Elvish, but during the compilation of Elvish scripts.

Dynamic PATH is a problem, but the majority of scripts are not going to manipulate it.

**Comment by xiaq** [comment]
Yes, this will require the paths of external commands to be resolved during compilation. This is not a bad thing for the majority of modules and scripts.

**Comment by krader1961** [comment]
> The static checking happens not during the compilation of Elvish, but during the compilation of Elvish scripts.

When I wrote "Elvish program" I meant a script written in the Elvish language, not the "elvish" binary.

> Dynamic PATH is a problem, but the majority of scripts are not going to manipulate it.

Yes, but the behavior when PATH is modified still needs to be defined; even if it's just "changing PATH will not affect the resolution of any external command invoked by the script."

**Comment by xiaq** [comment]
After some consideration, I'll adopt the following syntax for this pragma:

```
option cnf = off # unresolved commands are compile-time errors
option cnf = external # unresolved commands are external commands (default)
```

The same syntax can be used to support command-not-found hooks (#272).

The `option` special command can be extended to accept other per-scope language options. I don't have anything else in mind though.

A script can declare its external command dependencies explicitly like this:

```
option cnf = off
var ls~ = (external ls)
var cat~ = (external cat)
# use of other undeclared commands triggers compile-time errors
```

**Comment by hanche** [comment]
Just curious, but why `cnf`? It makes me think “configuration”, but that makes no sense for this option.

**Comment by xiaq** [comment]
Suggestion for other names welcome, especially ones shorter than `fallback-resolver` :)
