### ISSUE TITLE
There's no way to print the message inside the exception

### ISSUE THREAD

**Issue by tfga** [elves/elvish#986]
Somewhere in my code I throw this exception:
```
fail 'No connected devices'
```
I'd like to catch this somewhere else and print the message to the user. But I couldn't find a way to do it.
```sh
$ e = ?(fail 'No connected devices')

$ echo (to-string $e)
?(fail 'No connected devices')

$ echo $e[cause]
<unknown No connected devices>
```

How can I print just the message?

**Comment by xiaq** [comment]
Thanks for raising this, please see #208 which tracks a comprehensive introspection API for exceptions.
