### ISSUE TITLE
Test failures 

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#997]
I sometimes see the following test failure of *pkg/edit/prompt_test.go* on some of my virtual machines:

```
ok      github.com/elves/elvish/pkg/diag        0.028s
--- FAIL: TestPromptStaleThreshold (0.23s)
    prompt_test.go:72: Wanted buffer not shown
    prompt_test.go:72: Want: Width = 50, Dot = (0, 5)
        ┌──────────────────────────────────────────────────┐
        │???> $                                            │
        └──────────────────────────────────────────────────┘
    prompt_test.go:72: Last buffer: Width = 50, Dot = (0, 5)
        ┌──────────────────────────────────────────────────┐
        │???> $                                            │
        └──────────────────────────────────────────────────┘
FAIL
FAIL    github.com/elves/elvish/pkg/edit        4.331s
ok      github.com/elves/elvish/pkg/edit/complete       0.043s
```

Immediately rerunning the unit test succeeds. It looks like the `edit:prompt-stale-threshold = 0.05` in `TestPromptStaleThreshold()` in *pkg/edit/prompt_test.go* causes flakey behavior because it depends on the performance of the platform on which the unit test is running.

**Comment by xiaq** [comment]
I changed the hardcoded value to a value scaled by `ELVISH_TEST_TIME_SCALE` (which was just [documented](https://github.com/elves/elvish/blob/master/CONTRIBUTING.md#elvish_test_time_scale)). You should set this environment variable to a value greater than 1 when running in VMs.

Are you seeing this particular fail disproportionately more often other tests? If so, we can also bump the base value for the times.

**Comment by krader1961** [comment]
> I changed the hardcoded value to a value scaled by ELVISH_TEST_TIME_SCALE...

Fantastic. I'll modify the test runner script I wrote to run the tests in parallel on all my VMs to use that env var and report back soon with the results. When I was running fish unit tests on the same systems I had tweak a similar knob by a small amount to minimize false positive failures.

> Are you seeing this particular fail disproportionately more often other tests?

Yes. While I sometimes see other tests fail intermittently this particular test is flakey more frequently than any other test. I'll take a look at whether tweaking its timeout independent of setting `ELVISH_TEST_TIME_SCALE` reduces the flakiness.

**Comment by krader1961** [comment]
Setting `ELVISH_TEST_TIME_SCALE=2` still results in noticeable flakiness on a couple of my VMs, while five seems to eliminate the problem. Thx.
